Added feedstock for kubelogin
conda-forge/staged-recipes pull request #12558
Opened 2020-09-04 02:12 UTC by krisevans

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

2020-09-04 02:12 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/kubelogin```) and found it was in an excellent condition.

2020-09-04 03:02 UTC, dhirschfeld commented
```
'kubelogin' is not recognized as an internal or external command,
operable program or batch file
```
`conda-build` packages up artefacts under `%PREFIX%`. I think what's happening here is that `make` is putting the binary elsewhere so it's not being packaged.

I think we may need to ignore the build script and just call the `go` compiler directly.

We can use another `go` recipe as a template:
https://github.com/conda-forge/terraform-provider-azurerm-feedstock/blob/master/recipe/meta.yaml

It looks like CF sets some variables which can be used:
https://github.com/conda-forge/terraform-provider-azurerm-feedstock/blob/723dd977cac2779e7fadabb5d0c3d4e988c5b1b1/.ci_support/win_64_.yaml#L5-L16

...and something like the below should (hopefully) work:
```yaml
build:
  number: 0
  script:
    - go build -v -o {{ target_gobin }}{{ name }}{{ target_goexe }}
```

2020-09-04 03:54 UTC, dhirschfeld commented
It looked like it worked *but* the version information is missing:
```
(%PREFIX%) %SRC_DIR%>kubelogin --version 
kubelogin version 
git hash: 
Go version: 
Build time:
```
...which, I think, is because we're not setting the [`LDFLAGS`](https://github.com/Azure/kubelogin/blob/1ee0da905a5b9ce9dceacff7e914b3c3c1e198ea/Makefile#L20-L22):
```
LDFLAGS    := -X main.version=$(VERSION) \
    -X main.goVersion=$(shell go version | cut -d " " -f 3) \
	-X main.buildTime=$(BUILD_TIME)

<snip>
go build -o $(BIN) -ldflags "$(LDFLAGS)"
```

2020-09-04 04:59 UTC, dhirschfeld commented
The version can be pulled from the `PKG_VERSION` env var
```
%SRC_DIR%>set "PKG_VERSION=0.0.5" 
```

...but the others might be more difficult.
```
> conda list '^go$' --json | jq .[0].version
"1.13.15"
```

2020-09-04 06:53 UTC, dhirschfeld commented
Looks good!
```
(%PREFIX%) %SRC_DIR%>kubelogin --version 
kubelogin version 
git hash: 0.0.5
Go version: go1.13.15
Build time: 2020-09-04T06:26:33Z
```

2020-09-04 07:03 UTC, dhirschfeld approved these changes
:shipit:

2020-09-06 08:32 UTC, dhirschfeld commented
From [gitter](https://gitter.im/conda-forge/conda-forge.github.io?at=5f549c62ec534f584fe742be) it seems we may have to try and find *all* of the required licenses.
https://github.com/conda-forge/conda-forge.github.io/issues/1052

...at least for `go` it seems there's a tool to help with this:
https://github.com/google/go-licenses#complying-with-license-terms

2020-09-06 10:01 UTC, dhirschfeld commented
Might be something to crib from the [`argo` PR](https://github.com/conda-forge/staged-recipes/pull/11799)
https://github.com/hadim/staged-recipes/blob/d6d00d1415856f8c0d45d8dc6605b83afc16edef/recipes/argo/build_library_licenses.sh

2020-09-07 02:27 UTC, dhirschfeld commented on recipes/kubelogin/build_library_licenses.sh
> +$GOBIN/bin/go-licenses save $KUBELOGIN_PATH --save_path=$LIBRARY_LICENCES_PATH
```suggestion
$GOBIN/go-licenses save $KUBELOGIN_PATH --save_path=$LIBRARY_LICENCES_PATH
```
One too many bins!
```
<snip>placehold_p/bin/bin/go-licenses
```

2020-09-07 04:50 UTC, dhirschfeld commented
*All* the licenses output by `go-licenses` tool are now packaged in the `recipe/library_licenses` folder:

![image](https://user-images.githubusercontent.com/881019/92349295-fb8c3380-f118-11ea-99e4-aedd1524f294.png)


ping @chrisburr - is this good to merge?

2020-09-08 17:29 UTC, scopatz commented on recipes/kubelogin/build_library_licenses.sh
> +git clone https://github.com/Azure/kubelogin.git
Please use the sources section in the meta.yaml to get the source code

2020-09-08 17:29 UTC, scopatz commented on recipes/kubelogin/meta.yaml
> +    - posix  # [win]
This seems to have bash dependence as well

2020-09-08 17:30 UTC, scopatz requested changes
Use sources

2020-09-08 21:25 UTC, dhirschfeld commented on recipes/kubelogin/build_library_licenses.sh
> +rm -fr $TEMP_DIR
```suggestion
rm -fr $LIBRARY_LICENCES_PATH
pushd %SRC_DIR%
$GOBIN/go-licenses save $KUBELOGIN_PATH --save_path=$LIBRARY_LICENCES_PATH
popd
```

2020-09-08 21:29 UTC, dhirschfeld commented
@scopatz - is there a better place to save the licenses? The *actual* license is in a `info/license` folder alongside the `info/recipe` folder but I don't know how we could access that folder from the build to e.g. add `thirdparty` subfolder?

2020-09-08 23:33 UTC, dhirschfeld commented
The `posix` package includes `m2-base` which includes `m2-bash`:
```
posix 1.0.0 2
-------------
file name   : posix-1.0.0-2.tar.bz2
name        : posix
version     : 1.0.0
build       : 2
build number: 2
size        : 2 KB
subdir      : win-64
url         : https://repo.anaconda.com/pkgs/msys2/win-64/posix-1.0.0-2.tar.bz2
md5         : 83ce222b94ccaf79838a6ffa5a1cd6bc
dependencies:
  - m2-base
  - m2-diffutils
  - m2-make
  - m2-tar
  - m2-unzip
  - m2-zip
  - msys2-conda-epoch >=20160418
```

2020-09-09 03:14 UTC, dhirschfeld commented on recipes/kubelogin/build_library_licenses.sh
> +popd
```suggestion
export THIRDPARTY_LICENCES_PATH="$RECIPE_DIR/thirdparty_licenses/"

rm -fr $THIRDPARTY_LICENCES_PATH
go get -v github.com/google/go-licenses
$GOBIN/go-licenses save $SRC_DIR --save_path=$THIRDPARTY_LICENCES_PATH
```

2020-09-09 03:46 UTC, dhirschfeld approved these changes
LGTM

2020-09-09 18:26 UTC, scopatz commented
> but I don't know how we could access that folder from the build to e.g. add thirdparty subfolder?

Yeah, you'd have to install it into share or something

2020-09-09 18:27 UTC, scopatz commented on recipes/kubelogin/meta.yaml
> +    - posix  # [win]
This still needs a bash dep

2020-09-09 18:27 UTC, scopatz commented on recipes/kubelogin/meta.yaml
> +    - posix  # [win]
At least on posix

2020-09-16 02:47 UTC, chrisburr commented
> is there a better place to save the licenses? The _actual_ license is in a `info/license` folder alongside the `info/recipe` folder but I don't know how we could access that folder from the build to e.g. add `thirdparty` subfolder?

You could concatenate them together and the specify `license_file: ALL_LICENSES` in the `meta.yaml`.

```bash
cp "${SRC_DIR}/LICENSE" ALL_LICENSES
for fn in thirdparty_licenses/*; do
    echo "${fn}
    cat "${fn}"
done >> ALL_LICENSES
```

Alternatively, the `license_file:` field does accept a list so the files could be included individually, but I don't think it supports globbing to more easily include them all:

```yaml
  license_file:
    - LICENSE
    - thirdparty_licenses/*
```

2020-09-16 03:59 UTC, dhirschfeld commented
Since the licenses are defined in named subfolders you would have to recursively concatenate all the licenses whilst also attributing the source (defined by the folder hierarchy).

Given that, I'm inclined to leave it as-is if that's not a problem? Whilst it might not be ideal, I believe it meets the license *requirements* and I think the right way to solve this would be adding globbing as a feature.

2020-09-16 09:08 UTC, dhirschfeld commented
If someone is about who could kick the CI I think this PR will pass now that `go-licenses` is available.

2020-09-16 09:28 UTC, chrisburr commented
@conda-forge-admin, please restart ci

> Given that, I'm inclined to leave it as-is if that's not a problem?

Are all of the files finding they way into the package? It looks like they're just being copied to the recipe directory which is then deleted when the CI job finishes though I might be missing something.

2020-09-16 11:13 UTC, dhirschfeld commented
> *It looks like they're just being copied to the recipe directory*

`conda` packages everything in the recipe directory into the `info/recipe` folder in the tarball so all the licenses make it into the `bz2` package:

![image](https://user-images.githubusercontent.com/881019/93329546-af4f9a80-f860-11ea-8760-a92786553a62.png)

☝️ from the `go-licenses` recipe which uses itself to package its own licenses!

I remember, in the early days of `conda`, putting my recipe in the root of my project source and eventually finding the entire source tree in the final package! 😆

2020-09-16 11:33 UTC, dhirschfeld commented
@conda-forge-admin, please restart ci

2020-09-16 12:45 UTC, dhirschfeld commented
When using the packaged `go-licenses` binary it fails with the below error:
```
login
+ go-licenses save C:/Miniconda/conda-bld/kubelogin_1600256405799/work '--save_path=D:\a\1\s\recipes\kubelogin/thirdparty_licenses/'
Error: cannot register licenses from archive: open D:\bld\go-licenses_1600240623892\work\gopath\pkg\mod\github.com\google\licenseclassifier@v0.0.0-20190926221455-842c0d70d702\licenses\licenses.db: The system cannot find the path specified.
Usage:
  licenses save <package> [flags]

Flags:
      --force              Delete the destination directory if it already exists.
  -h, --help               help for save
      --save_path string   Directory into which files should be saved that are required by license terms

Global Flags:
      --alsologtostderr                  log to standard error as well as files
      --confidence_threshold float       Minimum confidence required in order to positively identify a license. (default 0.9)
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --logtostderr                      log to standard error instead of files
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          log level for V logs
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

F0916 11:43:49.397416    4972 main.go:43] cannot register licenses from archive: open D:\bld\go-licenses_1600240623892\work\gopath\pkg\mod\github.com\google\licenseclassifier@v0.0.0-20190926221455-842c0d70d702\licenses\licenses.db: The system cannot find the path specified.
```

I've not been able to find out why or fix the problem :/

2020-09-16 12:48 UTC, dhirschfeld commented
I reverted to the last good commit over in #12674. Could that one please be merged and this one closed?

It might take a `go` expert to figure out why the packaged binary doesn't work.

2020-09-16 12:55 UTC, closed without merging