Added xcube-sh and xcube-cci
conda-forge/staged-recipes pull request #12823
Opened 2020-10-06 09:08 UTC by dzelge

This PR will add the xcube plugins xcube-sh and xcube-cci to conda-forge

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

2020-10-06 09:08 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/xcube-cci```, ```recipes/xcube-sh```) and found some lint.

Here's what I've got...


For **recipes/xcube-cci**:

 * The recipe must have some tests.
 * The requirements section contained an unexpected subsection name. imports is not a valid subsection name.
 * ``requirements: run: aiohttp >= 3.6`` should not contain a space between relational operator and the version, i.e. ``aiohttp >=3.6``
 * ``requirements: run: nest-asyncio >= 1.3`` should not contain a space between relational operator and the version, i.e. ``nest-asyncio >=1.3``
 * ``requirements: run: lxml >= 4.5`` should not contain a space between relational operator and the version, i.e. ``lxml >=4.5``
 * ``requirements: run: pydap >= 3.2`` should not contain a space between relational operator and the version, i.e. ``pydap >=3.2``

For **recipes/xcube-sh**:

 * The recipe must have some tests.
 * The requirements section contained an unexpected subsection name. imports is not a valid subsection name.

2020-10-06 09:13 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/xcube-cci```, ```recipes/xcube-sh```) and found some lint.

Here's what I've got...


For **recipes/xcube-cci**:

 * ``requirements: run: aiohttp >= 3.6`` should not contain a space between relational operator and the version, i.e. ``aiohttp >=3.6``
 * ``requirements: run: nest-asyncio >= 1.3`` should not contain a space between relational operator and the version, i.e. ``nest-asyncio >=1.3``
 * ``requirements: run: lxml >= 4.5`` should not contain a space between relational operator and the version, i.e. ``lxml >=4.5``
 * ``requirements: run: pydap >= 3.2`` should not contain a space between relational operator and the version, i.e. ``pydap >=3.2``

2020-10-06 09:14 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/xcube-cci```, ```recipes/xcube-sh```) and found it was in an excellent condition.

2020-10-06 11:02 UTC, pont-us requested changes

2020-10-06 11:02 UTC, pont-us commented on recipes/xcube-sh/meta.yaml
> +  run:
There are some differences here with the dependencies list in environment.yml (e.g. here psycopg2 is missing).

2020-10-06 12:02 UTC, dzelge commented
I agree to be a reviewer (dzelge)

2020-10-06 12:49 UTC, pont-us commented
I agree to be a reviewer (pont-us)

2020-10-06 14:17 UTC, scopatz commented on recipes/xcube-cci/meta.yaml
> +    - pip
Is this? It isn't usually needed

2020-10-06 14:18 UTC, scopatz commented
@pont-us are you willing to be a maintainer?

2020-10-06 14:25 UTC, pont-us commented
@scopatz Yes, I am.

2020-10-07 14:37 UTC, dzelge commented
@conda-forge/staged-recipes

Can you please merge or comment?

Thanx heaps

2020-10-07 15:03 UTC, merged