adding pantab and tableauhyperapi recipes
conda-forge/staged-recipes pull request #12846
Opened 2020-10-07 18:36 UTC by lphexter

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

2020-10-07 18:37 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pantab```, ```recipes/tableauhyperapi```) and found some lint.

Here's what I've got...


For **recipes/pantab**:

 * The recipe could do with some maintainers listed in the `extra/recipe-maintainers` section.
 * There are 1 too many lines.  There should be one empty line at the end of the file.
 * ``requirements: run: pycparser >= 2.20`` should not contain a space between relational operator and the version, i.e. ``pycparser >=2.20``
 * ``requirements: run: cffi >= 1.14.2`` should not contain a space between relational operator and the version, i.e. ``cffi >=1.14.2``

For **recipes/pantab**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

For **recipes/tableauhyperapi**:

 * The recipe could do with some maintainers listed in the `extra/recipe-maintainers` section.
 * The recipe `license` should not include the word "License".
 * There are 1 too many lines.  There should be one empty line at the end of the file.

For **recipes/tableauhyperapi**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2020-10-07 18:40 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pantab```, ```recipes/tableauhyperapi```) and found some lint.

Here's what I've got...


For **recipes/pantab**:

 * Recipe maintainer "lhexter" does not exist

For **recipes/tableauhyperapi**:

 * The recipe `license` should not include the word "License".
 * Recipe maintainer "lhexter" does not exist

For **recipes/tableauhyperapi**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2020-10-07 18:41 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I was trying to look for recipes to lint for you, but couldn't find any.
Please ping the 'conda-forge/core' team (using the @ notation in a comment) if you believe this is a bug.

2020-10-07 18:48 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pantab```, ```recipes/tableauhyperapi```) and found some lint.

Here's what I've got...


For **recipes/tableauhyperapi**:

 * The recipe `license` should not include the word "License".

For **recipes/tableauhyperapi**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2020-10-08 13:43 UTC, synapticarbors requested changes
I am not sure if we can support either of these packages. `pantab` depends on `tablueauhyperapi` and that appears to be a proprietary package with no published source distribution (wheels on pypi only) and a proprietary license, which I'm not sure if conda-forge is willing to accept. 

> 1.1	Grant of License. Subject to all of the terms and conditions of this Agreement, Tableau grants you a non-transferable, non-sublicensable (except as expressly authorized herein), non-exclusive license to (a) use the Software for your own purposes and (b) reproduce and distribute the Software in binary code form only, provided that: (i) you distribute the Software complete and unmodified and only bundled as part of, your Programs (as so bundled, the "Program Package"), (ii) the Programs add significant value to the Software, (iii) you do not distribute additional software intended to replace any component(s) of the Software, (iv) you do not remove or alter any proprietary legends or notices contained in the Software, (v) you do not decompile, disassemble or otherwise attempt to reverse engineer the Software (except to the extent applicable law prohibits such restrictions), (vi) you do not modify or create a derivative work of the Software (except that bundling and distributing as expressly authorized hereunder is permitted), (vii) you do not make any representations, guarantees or warranties of any type with respect to the specifications, features, capabilities or otherwise concerning the Software or on behalf of Tableau, (viii) you only distribute the Software subject to a license agreement that protects Tableau's interests consistent with the terms contained in this Agreement, and (ix) you agree to defend and indemnify Tableau and its licensors from and against any damages, costs, liabilities, settlement amounts and/or expenses (including attorneys' fees) incurred in connection with any claim, lawsuit or action by any third party that arises or results from the use or distribution of any and all Programs and/or Software. "Programs" means one or more software programs which you have independently developed.
> 
> 1.2	Submission to Tableau. Prior to first distribution of the Software to any third party, you shall notify Tableau of the name of your Programs and the applicable Program Package by email to hyperapilicensing@tableau.com. Previously such notifications were sent to licensing@tableausoftware.com. Please note that we will provide limited, and potentially untimely, monitoring for such notifications. You agree that if you elect to distribute the Program Package, Tableau may publicly disclose you as a licensee of the Software and identify your Programs and Program Package. Furthermore, if Tableau reasonably determines that review of your Program Package is necessary for Agreement compliance verification purposes, you will, within ten (10) days of request by Tableau, at no charge, provide Tableau with one (1) fully enabled copy of the Program Package for use by Tableau solely for such purposes.
> 

@conda-forge/staged-recipes -- any thoughts on this?

2020-10-08 13:43 UTC, synapticarbors commented on recipes/example/meta.yaml
>      - pip
please do not modify this file. This is the example

2020-10-08 13:43 UTC, synapticarbors commented on recipes/pantab/LICENSE.txt
> +BSD 3-Clause License
The license file is in the source distribution so you should remove this manually packaged one.

2020-10-08 13:43 UTC, synapticarbors commented on recipes/pantab/meta.yaml
> +test:
Please add an import test:

https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#python-imports

```yaml
test:
   import:
      - pantab
...
```

2020-10-08 13:43 UTC, synapticarbors commented on recipes/tableauhyperapi/meta.yaml
> +  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-py3-none-manylinux2014_x86_64.whl
conda-forge does not build from `.whl` files. You need a source distribution. See general comment

2020-10-08 13:43 UTC, synapticarbors commented on recipes/tableauhyperapi/meta.yaml
> +test:
You need an import test as above.

2020-10-08 20:54 UTC, lphexter commented
@synapticarbors yes, I wasn't sure either - if you all have thoughts on whether or not it's possible to add this that'd be great! @conda-forge/staged-recipes

2020-10-09 07:42 UTC, xhochy commented
Clause `1.2` sounds like a thing that is hard to achieve, I would say these terms make it unhostable as part of conda-forge.

2021-04-07 08:50 UTC, closed without merging