Add a recipe for ckan-editor-utils
conda-forge/staged-recipes pull request #12904
Opened 2020-10-16 00:19 UTC by ericmccowan

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

2020-10-16 00:19 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/ckan-editor-utils```) and found it was in an excellent condition.

2020-10-16 01:20 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/ckan-editor-utils```) and found some lint.

Here's what I've got...


For **recipes/ckan-editor-utils**:

 * Please do not delete the example recipe found in `recipes/example/meta.yaml`.

2020-10-16 01:24 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/ckan-editor-utils```) and found it was in an excellent condition.

2020-10-18 14:35 UTC, saraedum requested changes
Looks good, though you don't need the pins on Python.

2020-10-18 14:35 UTC, saraedum commented on recipes/ckan-editor-utils/meta.yaml
> +    - python >=3.6,<4.0
```suggestion
    - python
```

2020-10-18 14:35 UTC, saraedum commented on recipes/ckan-editor-utils/meta.yaml
> +    - python >=3.6,<4.0
```suggestion
    - python
```

2020-10-18 14:35 UTC, saraedum commented on recipes/ckan-editor-utils/meta.yaml
> +    - poetry >=1.1.3
```suggestion
    - poetry >=1.1.3,<2
```

2020-10-18 14:35 UTC, saraedum commented on recipes/ckan-editor-utils/meta.yaml
> +  summary: Utilities for editing CKAN using its API.
```suggestion
  summary: Utilities for editing CKAN, the Comprehensive Knowledge Archive Network
```

Just a suggestion. I had no idea what CKAN was and I find it nice to see acronyms expanded when I go to feedstocks without having to google them.

2020-10-18 14:46 UTC, ericmccowan commented
Thank you for the suggestions, those have all been committed now.

2020-11-17 09:27 UTC, dopplershift approved these changes

2020-11-17 09:28 UTC, merged