add ndd
conda-forge/staged-recipes pull request #12935
Opened 2020-10-19 21:20 UTC by simomarsili

Hi, this is a python/fortran repo.

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

2020-10-19 21:21 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/ndd```) and found some lint.

Here's what I've got...


For **recipes/ndd**:

 * Failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint .` from the recipe directory.

2020-10-19 21:36 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/ndd```) and found it was in an excellent condition.

2020-10-28 10:37 UTC, simomarsili commented
ready for review

2020-11-17 09:23 UTC, dopplershift requested changes

2020-11-17 09:23 UTC, dopplershift commented on recipes/ndd/meta.yaml
> +    - numpy >=1.13
You should only need numpy in `host`

2020-11-17 09:23 UTC, dopplershift commented on recipes/ndd/meta.yaml
> +  number: 3
Build number should be 0 to start.

2020-11-19 21:05 UTC, simomarsili commented on recipes/ndd/meta.yaml
> +    - numpy >=1.13
Thanks!

2020-11-19 22:45 UTC, dopplershift approved these changes

2020-11-19 22:45 UTC, merged