Add fortran-binary Python package
conda-forge/staged-recipes pull request #13318
Opened 2020-11-24 18:06 UTC by robertodr

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [X] Source is from official source
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
- [ ] When in trouble be please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2020-11-24 18:06 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/fortran-binary```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/fortran-binary**:

 * noarch: python recipes are recommended to have a lower bound on the python version. This recommendation will become a requirement in the future.
 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2020-11-24 18:07 UTC, robertodr commented
@vahtras do you agree to be maintainer of this package?

2020-11-24 18:09 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/fortran-binary```) and found it was in an excellent condition.

2020-11-24 21:00 UTC, dopplershift reviewed
Pending maintainer confirmation.

2021-01-08 14:00 UTC, vahtras commented
> Pending maintainer confirmation.

I confirm (if his is the way to do it...)

2021-01-08 14:38 UTC, robertodr commented
@conda-forge/help-python this is ready to go

2021-01-15 11:01 UTC, robertodr commented
@conda-forge/help-python @dopplershift anything else I should do to move this forward?

2021-01-22 19:38 UTC, dopplershift approved these changes

2021-01-22 19:40 UTC, dopplershift requested changes

2021-01-22 19:40 UTC, dopplershift commented on recipes/fortran-binary/meta.yaml
> +{% set sha256 = "be613276fb3141b81933c508990b8fa5e71f1df04a7423567d2aa78a16267241" %}
Can you actually undo the templating of the sha and build? It's not usually done any more like that and can make things more difficult for the auto-update bot.

2021-01-26 20:44 UTC, dopplershift approved these changes

2021-01-26 20:44 UTC, merged