Added pushover feedstock
conda-forge/staged-recipes pull request #13334
Opened 2020-11-26 06:46 UTC by krisevans

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2020-11-26 06:46 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/python-pushover```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/python-pushover**:

 * noarch: python recipes are recommended to have a lower bound on the python version. This recommendation will become a requirement in the future.
 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2020-11-26 23:33 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/python-pushover```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/python-pushover**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2020-11-27 02:42 UTC, synapticarbors requested changes

2020-11-27 02:42 UTC, synapticarbors commented on recipes/python-pushover/LICENSE
> +                    GNU GENERAL PUBLIC LICENSE
You should remove this file since the license file is already in the source distribution

2020-11-27 02:42 UTC, synapticarbors commented on recipes/python-pushover/meta.yaml
> +  script: "{{ PYTHON }} -m pip install . -vv"
It looks like this has a python entry point. You should add it:

https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#python-entry-points

and then add a test under `commands`:

https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#test-commands

2020-11-27 02:42 UTC, synapticarbors commented on recipes/python-pushover/meta.yaml
> +  license: GPLv3
`license: GPL-3.0-or-later`

2020-11-27 03:34 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/python-pushover```) and found it was in an excellent condition.

2020-11-27 03:51 UTC, synapticarbors approved these changes

2020-11-27 03:51 UTC, synapticarbors commented
I'm happy to merge this once the listed co-maintainer agrees to be listed.

2020-11-27 03:58 UTC, dhirschfeld commented
@synapticarbors - I'm happy to be a maintainer for this recipe!

2020-11-27 03:58 UTC, merged