add sklearn2pmml
conda-forge/staged-recipes pull request #13339
Opened 2020-11-26 13:26 UTC by FernandezMathieu

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2020-11-26 13:26 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/sklearn2pmml```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/sklearn2pmml**:

 * noarch: python recipes are recommended to have a lower bound on the python version. This recommendation will become a requirement in the future.
 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2020-11-26 13:27 UTC, FernandezMathieu commented
Requirements `sklearn-pandas` [in a PR.](https://github.com/conda-forge/staged-recipes/pull/13335)

2020-11-26 13:32 UTC, FernandezMathieu commented
@conda-forge-linter

2020-11-30 15:16 UTC, FernandezMathieu commented
@conda-forge-linter restart ci

2020-11-30 15:36 UTC, FernandezMathieu commented
@conda-forge-linter restart ci

2020-11-30 16:11 UTC, FernandezMathieu commented
@conda-forge-linter restart ci

2020-12-01 04:05 UTC, dopplershift requested changes
Just a couple minor things.

2020-12-01 04:05 UTC, dopplershift commented on recipes/sklearn2pmml/meta.yaml
> +  license: GPL-3.0
The license looks like it's actually AGPL-3.0

2020-12-01 04:05 UTC, dopplershift commented on recipes/sklearn2pmml/meta.yaml
> +    - python
Should also be `python >=2.7`

2020-12-01 07:51 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/sklearn2pmml```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/sklearn2pmml**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2020-12-01 09:34 UTC, dopplershift commented on recipes/sklearn2pmml/meta.yaml
> +  license: AGPL-3.0
Apologies, looks like that actually should have been `AGPL-3.0-only`

2020-12-02 07:35 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/sklearn2pmml```) and found it was in an excellent condition.

2020-12-02 23:26 UTC, dopplershift approved these changes

2020-12-02 23:26 UTC, merged