Adding pyModeS
conda-forge/staged-recipes pull request #13582
Opened 2021-01-01 23:11 UTC by xoolive

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [n/a] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there => please post a comment @junzis 
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-01-01 23:11 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyModeS```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/pyModeS**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2021-01-01 23:13 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyModeS```) and found it was in an excellent condition.

2021-01-02 20:06 UTC, junzis commented
Hi @conda-forge-linter and @xoolive, yes, I will be the maintainer.

2021-01-02 22:36 UTC, xoolive commented
@conda-forge/help-python This is ready for review

2021-01-04 17:23 UTC, mariusvniekerk requested changes

2021-01-04 17:23 UTC, mariusvniekerk commented on recipes/pyModeS/meta.yaml
> +  noarch: python
noarch packages can't have compiled portions

2021-01-04 20:26 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyModeS```) and found some lint.

Here's what I've got...


For **recipes/pyModeS**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2021-01-04 20:32 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyModeS```) and found it was in an excellent condition.

2021-01-05 01:02 UTC, dopplershift approved these changes

2021-01-05 01:02 UTC, merged