Adding bibmanager package
conda-forge/staged-recipes pull request #13726
Opened 2021-01-19 16:23 UTC by pcubillos

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-01-19 16:23 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/bibmanager```) and found some lint.

Here's what I've got...


For **recipes/bibmanager**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.

For **recipes/bibmanager**:

 * noarch: python recipes are recommended to have a lower bound on the python version. This recommendation will become a requirement in the future.

2021-01-20 14:49 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/bibmanager```) and found it was in an excellent condition.

2021-01-22 19:45 UTC, dopplershift requested changes

2021-01-22 19:45 UTC, dopplershift commented on recipes/bibmanager/meta.yaml
> +  skip: True  # [py<36]
You should be able to make this `noarch: python` instead of using skip.

2021-01-22 19:45 UTC, dopplershift commented on recipes/bibmanager/meta.yaml
> +    - python
Make this then `python >=3.6`.

2021-01-22 19:45 UTC, dopplershift commented on recipes/bibmanager/meta.yaml
> +    - python
And here too.

2021-01-25 07:32 UTC, pcubillos commented
OK, I think I resolved all the requests. Thank you very much Ryan for reviewing this PR.

2021-01-26 20:36 UTC, dopplershift approved these changes

2021-01-26 20:36 UTC, merged