Add recipe for nc2zarr
conda-forge/staged-recipes pull request #13739
Opened 2021-01-20 10:11 UTC by pont-us

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml"
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [x] Source is from official source
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-01-20 10:11 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/nc2zarr```) and found it was in an excellent condition.

2021-01-20 10:18 UTC, bcdev commented
I am willing to be listed as a maintainer.

2021-01-20 10:22 UTC, forman commented
I am willing to be listed as a maintainer.

2021-01-20 10:24 UTC, AliceBalfanz commented
I am willing to be listed as a maintainer.

2021-01-20 10:26 UTC, TonioF commented
I am willing to be listed as a maintainer.

2021-01-20 10:33 UTC, dzelge commented
I am willing to be listed as a maintainer.

2021-01-20 10:47 UTC, pont-us commented
I am willing to be listed as a maintainer.

2021-01-20 11:53 UTC, pont-us commented
@conda-forge/help-python ready for review :).

2021-01-22 09:57 UTC, merged

2021-01-22 09:58 UTC, kmuehlbauer requested changes

2021-01-22 09:58 UTC, kmuehlbauer commented on recipes/nc2zarr/meta.yaml
> +  home: https://github.com/simplejson/simplejson
Please add the correct link here.

2021-01-22 09:58 UTC, kmuehlbauer commented on recipes/nc2zarr/meta.yaml
> +  doc_url: https://github.com/simplejson/simplejson/README.md
Here another two lines to fix

2021-01-22 09:59 UTC, kmuehlbauer commented
@pont-us Please add the changes to the metadata in the feedstock, when it is created.

2021-01-22 10:24 UTC, pont-us commented
> @pont-us Please add the changes to the metadata in the feedstock, when it is created.

Thank you, will do!