Add libimagequant and pngquant
conda-forge/staged-recipes pull request #14036
Opened 2021-02-21 17:35 UTC by izahn

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-02-21 17:36 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/libimagequant```, ```recipes/pngquant```) and found some lint.

Here's what I've got...


For **recipes/libimagequant**:

 * The recipe must have some tests.

2021-02-21 17:51 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/libimagequant```, ```recipes/pngquant```) and found it was in an excellent condition.

2021-02-21 20:13 UTC, izahn commented
I think this is ready for review!

2021-02-23 02:37 UTC, izahn commented
@conda-forge/help-c-cpp it would be awesome if you can take a look at this. It is the last set of dependencies for ocrmypdf!

Thanks for all your time and efforts!

2021-02-23 06:47 UTC, xhochy requested changes
`libimagequant` should have a `run_exports` specifying its ABI compatability: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#export-runtime-requirements

2021-02-23 06:47 UTC, xhochy commented on recipes/libimagequant/meta.yaml
> +    - bash -c "[ -f $PREFIX/lib/libimagequant.0.dylib ]"  # [osx]
```suggestion
    - test -f $PREFIX/lib/libimagequant.so  # [linux]
    - test -f $PREFIX/lib/libimagequant.0.dylib  # [osx]
```

2021-02-23 06:47 UTC, xhochy commented on recipes/libimagequant/meta.yaml
> +  license_family: GPL2
We set that automatically when the license is SPDX compatible.
```suggestion
```

2021-02-23 06:47 UTC, xhochy commented on recipes/libimagequant/meta.yaml
> +    - lib/
That shouldn't be needed.

2021-02-23 06:47 UTC, xhochy commented on recipes/pngquant/meta.yaml
> +    - lib/
```suggestion
  rpaths:
    - lib/
```

as above. If really needed, please add a comment why.

2021-02-23 06:47 UTC, xhochy commented on recipes/pngquant/meta.yaml
> +  license_family: GPL2
```suggestion
```

2021-02-23 06:47 UTC, xhochy commented on recipes/pngquant/meta.yaml
> +    - libpng
Don't these libraries all have `run_exports`? Then you could omit them here.

2021-02-23 13:03 UTC, xhochy approved these changes

2021-02-23 13:04 UTC, merged