Add ibis-omniscidb recipe
conda-forge/staged-recipes pull request #14114
Opened 2021-02-26 23:03 UTC by xmnlab

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-02-26 23:03 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/ibis-omniscidb```) and found some lint.

Here's what I've got...


For **recipes/ibis-omniscidb**:

 * Non noarch packages should have python requirement without any version constraints.

2021-02-26 23:08 UTC, xmnlab commented
ibis-omniscidb license was already included to the repository(https://github.com/omnisci/ibis-omniscidb/blob/master/LICENSE.txt), and it would be available for the next version.

2021-02-26 23:11 UTC, xmnlab commented
The current version of ibis-framework (1.4) has still support for omniscidb (just for python 3.7), but this support will be dropped in the next version (2.0).

This recipe, for now, will support just python 3.8 and python 3.9

2021-02-26 23:12 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/ibis-omniscidb```) and found it was in an excellent condition.

2021-02-27 00:23 UTC, beckermr requested changes

2021-02-27 00:23 UTC, beckermr commented on recipes/ibis-omniscidb/meta.yaml
> +    - python
You need a min version here too.

2021-02-27 13:33 UTC, xmnlab commented on recipes/ibis-omniscidb/meta.yaml
> +    - python
done! thank you so much for the review.

2021-02-27 14:39 UTC, beckermr approved these changes

2021-02-27 14:40 UTC, merged

2021-03-01 13:09 UTC, xmnlab commented
thank you so much @beckermr