Ibm db sa feedstock
conda-forge/staged-recipes pull request #14340
Opened 2021-03-22 13:14 UTC by amukherjee28

Checklist
- [ ] Adding support for ibm_db_sa package into conda-forge channel
- [ ] License file is packaged (see [here](https://github.com/amukherjee28/staged-recipes/blob/master/LICENSE.txt)).
- [ ] Source is from official source. https://pypi.org/project/ibm-db-sa/
- [ ] Build number is 1.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://github.com/ibmdb/python-ibmdb) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://github.com/ibmdb/python-ibmdb/blob/master/README.md) before pinging a team.

2021-03-22 13:15 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I was trying to look for recipes to lint for you, but couldn't find any.
Please ping the 'conda-forge/core' team (using the @ notation in a comment) if you believe this is a bug.

2021-03-23 13:01 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/ibm_db_sa```) and found some lint.

Here's what I've got...


For **recipes/ibm_db_sa**:

 * The recipe must have some tests.
 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [14, 15, 16]
 * Recipe maintainer "arnab mukherjee" does not exist

2021-03-24 06:08 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/ibm_db_sa```) and found it was in an excellent condition.

2021-03-25 08:13 UTC, amukherjee28 commented
@conda-forge-admin Do all the automated task need to pass for the pull request to be accepted and feedstock creation?
I see that the linux_64 is failing for glibc check thats the only issue with the pull request now.

2021-03-25 10:40 UTC, amukherjee28 commented
@conda-forge-admin the linux_64 build fails because of pre - defined installation of glibc version 2.12 and the expectation is to have 2.17
The same things works fine in linux_64_centos7 where the glibc version is 2.17

2021-03-25 10:43 UTC, amukherjee28 commented
@conda-forge/core the linux_64 build fails because of pre - defined installation of glibc version 2.12 and the expectation is to have 2.17
The same things works fine in linux_64_centos7 where the glibc version is 2.17

2021-03-26 07:45 UTC, amukherjee28 commented
@conda-forge-admin @conda-forge/core can this be merged and a feedstock be created.

Thanks.

2021-03-30 15:04 UTC, xhochy requested changes

2021-03-30 15:04 UTC, xhochy commented on recipes/ibm_db_sa/meta.yaml
> +    - sqlalchemy  1.3.23
Why this this pinned so hard?

2021-03-30 15:04 UTC, xhochy commented on recipes/ibm_db_sa/meta.yaml
> +  summary: Python Alchemy driver for DB2 (LUW, zOS, i5) and IDS
Should read `SQLAlchemy`

2021-03-30 15:04 UTC, xhochy commented on recipes/ibm_db_sa/conda_build_config.yaml
> +  - cos7                                  # [linux64]
This is not needed, you can add the following to `conda-forge.yml` on the feedstock:

```
os_version:
  linux_64: cos7
```

2021-03-30 15:04 UTC, xhochy commented on recipes/ibm_db_sa/meta.yaml
> +    - {{ compiler('cxx') }}
The packages doesn't seem to contain any compiled code so you probably don't need a compiler.

2021-03-30 15:04 UTC, xhochy commented on recipes/ibm_db_sa/meta.yaml
> +  number: 1
Should be ß

2021-03-30 15:04 UTC, xhochy commented on LICENSE.txt
> +Apache License
Don't change the licence of the staged-recipes repository.

2021-04-29 19:30 UTC, amukherjee28 commented on LICENSE.txt
> +Apache License
@xhochy I have addressed all your comments in a separate pull request 

https://github.com/conda-forge/staged-recipes/pull/14418

Can you please review the pull request.

Thanks

2021-09-07 06:19 UTC, closed without merging