adds pymde
conda-forge/staged-recipes pull request #14383
Opened 2021-03-25 02:29 UTC by mfansler

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-03-25 02:29 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pymde```) and found it was in an excellent condition.

2021-03-25 03:10 UTC, mfansler commented
The `torchvision` dependency does not have a **win-64** build available.

2021-03-25 03:38 UTC, mfansler commented
@conda-forge/help-python please review; all expected builds appear to work.

The **win_64** check fails due to lack of `torchvision` build. Please let me know if I should include a skip because of that.

Modified from a `grayskull` recipe.

2021-03-25 14:34 UTC, akshayka commented
I'm writing to state that I approve being included as a maintainer.

@mfansler, thanks so much for putting this together. I have a couple questions/comments.

**First question.**
Is it possible to get away with not specifying the NumPy version explicitly, during the build step? For example, in this other recipe, it is noted that conda-forge inserts the oldest numpy per platform/runtime.

https://github.com/conda-forge/cvxpy-feedstock/blob/master/recipe/meta.yaml#L68-L69

Later the same recipe uses a `pin_compatible` primitive: https://github.com/conda-forge/cvxpy-feedstock/blob/master/recipe/meta.yaml#L73

The only reason I ask is because not having to specify the NumPy version would make maintaining this recipe easier, I think. (I'm trying to simplify this on the official PyMDE CI, as well, but there I am not using conda.)

**Second question.**
Would it make sense to run the unit tests in the recipe? Something like

```
test:
  requires:
    - pytest
  source_files:
    - pymde/
  imports:
    - pymde
  commands:
    - pytest pymde/ -v
 ```

Thanks once again!

2021-03-25 15:23 UTC, mfansler commented
@akshayka yes, those both are great ideas that should be doable. For now, I'd propose we see if this gets approved as is, then we can make those changes afterward on the feedstock repo (where we can add those as Issues to address). Does that sound good?

2021-03-26 15:51 UTC, mfansler commented
@conda-forge/help-python please review.

2021-03-30 23:45 UTC, dopplershift requested changes
Looks good. Just a couple minor changes.

2021-03-30 23:45 UTC, dopplershift commented on recipes/pymde/LICENSE
> +                                 Apache License
If you bump to `0.1.5`, you can remove the license file since it's now included in the PyPI tarball.

2021-03-30 23:45 UTC, dopplershift commented on recipes/pymde/meta.yaml
> +  script: {{ PYTHON }} -m pip install . -vv
Since this is a compiled package, please add `skip: true  # [win]` to skip the build on Windows due to the missing dependency.

2021-03-31 02:14 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pymde```) and found some lint.

Here's what I've got...


For **recipes/pymde**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [15]

2021-03-31 02:15 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pymde```) and found it was in an excellent condition.

2021-03-31 02:47 UTC, mfansler commented
@dopplershift thanks for the review! I've incorporated your suggestions and verified the LICENSE from the PyPI packaged is correctly bundled.

2021-03-31 19:28 UTC, merged