Adding puppies package for astrophyics research
conda-forge/staged-recipes pull request #14397
Opened 2021-03-26 10:49 UTC by pcubillos

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-03-26 10:49 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/puppies```) and found it was in an excellent condition.

2021-06-12 04:43 UTC, mwcraig requested changes
@pcubillos -- this just needs a couple minor changes to merge. Thanks for opening the PR!

2021-06-12 04:43 UTC, mwcraig commented on recipes/puppies/meta.yaml
> +    - numpy >=1.8.1
You can safely drop this restriction -- conda-forge hasn't support a numpy that old in a long, long time (maybe ever).

2021-06-12 04:43 UTC, mwcraig commented on recipes/puppies/meta.yaml
> +    - puppies
Please add this too:

```suggestion
    - puppies
  commands:
     - pip check  
  requires:    
    - pip
```

2022-03-18 19:58 UTC, carterbox approved these changes
FYI, the default channel of your GitHub repo doesn't contain any code (which is a bit strange), all the code is in the aprilis channel.

Also, for future reference, conda-forge offers prerelease channels if you're into releasing non-finalized code. However, in this case, I don't think that's your intention.

2022-03-18 19:58 UTC, merged

2022-03-18 20:03 UTC, pcubillos commented
Thanks @carterbox !
Yes, I'll merge into main as soon as I'm happy with a first final release.