Adding meld: modeling employing limited data
conda-forge/staged-recipes pull request #14409
Opened 2021-03-27 02:44 UTC by jlmaccal

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-03-27 02:44 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/meld```) and found some lint.

Here's what I've got...


For **recipes/meld**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [13]

2021-03-27 04:37 UTC, jlmaccal commented
@conda-forge-admin, please ping team

I'm new to conda-forge and could use some help.

I'm trying to setup a matrix build using `conda_build_config.yaml`, but this doesn't seem to be re-rendering any of the scripts in `.ci-support`, so the build fails.

2021-03-27 04:37 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/staged-recipes and so here I am doing that.

2021-03-27 23:40 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/meld```) and found it was in an excellent condition.

2021-03-28 19:19 UTC, jlmaccal commented
@conda-forge-admin, please ping team

This should be ready for review.

2021-03-28 19:19 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/staged-recipes and so here I am doing that.

2021-03-29 16:26 UTC, isuruf commented on recipes/meld/build.sh
> +CMAKE_FLAGS="  -DCMAKE_INSTALL_PREFIX=${PREFIX}"
```suggestion
CMAKE_FLAGS="${CMAKE_ARGS}  -DCMAKE_INSTALL_PREFIX=${PREFIX}"
```

2021-03-29 16:35 UTC, isuruf requested changes
You need to package the text https://github.com/maccallumlab/meld/blob/3f2893e6728a8eac172de7f5ce37cf1c6d99d22a/plugin/platforms/cuda/src/CudaMeldKernelSources.cpp.in#L1-L25

2021-03-29 16:49 UTC, jlmaccal commented
> You need to package the text https://github.com/maccallumlab/meld/blob/3f2893e6728a8eac172de7f5ce37cf1c6d99d22a/plugin/platforms/cuda/src/CudaMeldKernelSources.cpp.in#L1-L25

I have update the license upstream here:
[meld/COPYING at master · maccallumlab/meld](https://github.com/maccallumlab/meld/blob/master/COPYING)

Do I need to produce a new source tarball and update this PR?

2021-03-29 16:51 UTC, isuruf commented
That's the best approach. You could also copy that file into the recipe directory and not release a new source tarball.

2021-03-29 16:55 UTC, jlmaccal commented
OK, done!

2021-03-29 18:48 UTC, merged