aurorafusion recipe
conda-forge/staged-recipes pull request #14463
Opened 2021-04-05 20:31 UTC by fsciortino

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

Conda-forge recipe for `aurorafusion`. The code is mostly Python3 but also includes some Fortran90 and Julia. The Julia component is not expected to be built upon installation, but the fortran part is. 

Mention @smithsp

2021-04-05 20:31 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes```) and found some lint.

Here's what I've got...


For **recipes**:

 * There are too few lines.  There should be one empty line at the end of the file.
 * Please do not delete the example recipe found in `recipes/example/meta.yaml`.

2021-04-05 20:33 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/aurorafusion```) and found some lint.

Here's what I've got...


For **recipes/aurorafusion**:

 * There are too few lines.  There should be one empty line at the end of the file.

2021-04-05 20:33 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/aurorafusion```) and found it was in an excellent condition.

2021-04-05 23:28 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/aurorafusion```) and found some lint.

Here's what I've got...


For **recipes/aurorafusion**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2021-04-07 16:58 UTC, smithsp commented
@fsciortino You should probably go through the checklist in the header comment of this PR and check off all parts that are done.

2021-04-07 17:00 UTC, smithsp commented
Also @fsciortino I do not think that the build https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=299903&view=logs&jobId=6f142865-96c3-535c-b7ea-873d86b887bd&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823 failed due to the python version requirement of `omfit_classes`.

2021-04-07 17:28 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/aurorafusion```) and found it was in an excellent condition.

2021-04-28 21:15 UTC, fsciortino commented
It took a while, but the recipe is finally passing all tests. Thanks @smithsp for your help!

@conda-forge-admin, please ping team

2021-04-28 21:16 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/staged-recipes and so here I am doing that.

2021-04-29 19:22 UTC, dopplershift requested changes

2021-04-29 20:39 UTC, dopplershift approved these changes

2021-04-29 20:39 UTC, merged