Add pyflashtext
conda-forge/staged-recipes pull request #14492
Opened 2021-04-07 22:08 UTC by francbartoli

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-04-07 22:08 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyflashtext```) and found some lint.

Here's what I've got...


For **recipes/pyflashtext**:

 * There are too few lines.  There should be one empty line at the end of the file.

2021-04-07 22:52 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyflashtext```) and found it was in an excellent condition.

2021-04-08 14:29 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyflashtext```) and found some lint.

Here's what I've got...


For **recipes/pyflashtext**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2021-04-08 14:47 UTC, synapticarbors requested changes

2021-04-08 14:47 UTC, synapticarbors commented on recipes/pyflashtext/meta.yaml
> +    - python
As according to the linter, change `python` to `python >=3.5` both under `host` and `run`.

2021-04-08 14:47 UTC, synapticarbors commented on recipes/pyflashtext/meta.yaml
> +  script: python -m pip install --no-deps --ignore-installed .
Change to `script: "{{ PYTHON }} -m pip install . -vv"` as shown in the `example/meta.yaml`.

2021-04-08 14:51 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyflashtext```) and found it was in an excellent condition.

2021-04-08 14:56 UTC, francbartoli commented
Thanks @synapticarbors for the review! That should be fixed now

2021-04-08 14:59 UTC, synapticarbors approved these changes

2021-04-08 15:04 UTC, merged