Add xmovie
conda-forge/staged-recipes pull request #14543
Opened 2021-04-13 13:55 UTC by jbusecke

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-04-13 13:55 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/xmovie```) and found some lint.

Here's what I've got...


For **recipes/xmovie**:

 * Feedstock with the same name exists in conda-forge.

2021-04-13 14:01 UTC, jbusecke commented
Dear @conda-forge/help-python,  I am getting a message that a feedstock already exists for `xmovie`, but I cant find it [here](https://github.com/conda-forge?q=xmovie&type=&language=&sort=) or in the [staged_recipes PRs](https://github.com/conda-forge/staged-recipes/pulls?q=xmovie). Could you advise me how to resolve this? Many thanks.

2021-04-13 17:34 UTC, dopplershift commented
If you look at the `recipe/xmovie/meta.yaml` that's actually uploaded to this PR, it looks completely like the template and only mentions "simplejson".

2021-04-13 17:46 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/xmovie```) and found it was in an excellent condition.

2021-04-13 17:46 UTC, jbusecke commented
Sorry for being an absolute idiot and not checking. I modified the example recipe by accident. Sorry for wasting time here.

2021-04-13 18:14 UTC, dopplershift commented
No worries, I ran through the same checks looking for an existing feedstock until I decided to look at `meta.yaml` for a clue, and got a big one. 😆

2021-04-13 18:19 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/xmovie```) and found some lint.

Here's what I've got...


For **recipes/xmovie**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2021-04-13 18:22 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/xmovie```) and found it was in an excellent condition.

2021-04-13 18:36 UTC, jbusecke commented
Alright. I think I have this all ironed out, and this should be ready to merge. Thanks for the assist @dopplershift!

2021-04-13 19:19 UTC, dopplershift requested changes
Looks pretty good. Just need this from the top of the template:

> Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe

2021-04-13 19:23 UTC, jbusecke commented
Ah right. Thanks again.

2021-04-14 16:20 UTC, dopplershift requested changes
Missed this before. Everything else looks ready to go.

2021-04-14 16:20 UTC, dopplershift commented on recipes/xmovie/meta.yaml
> +  number: 0
Need to remove this duplicated `build` section.

2021-04-15 14:11 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/xmovie```) and found some lint.

Here's what I've got...


For **recipes/xmovie**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2021-04-15 14:48 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/xmovie```) and found it was in an excellent condition.

2021-04-15 20:31 UTC, jbusecke commented
Fixed that duplicate, @dopplershift. Sorry for the added trouble on this. I owe you 🍺/☕️ in a not to distant future where I could visit Boulder

2021-04-15 21:13 UTC, dopplershift commented
No worries! Though I'm definitely not turning down opportunities to have beer with people in that not-too-distant future.

2021-04-15 21:15 UTC, dopplershift requested changes

2021-04-15 21:15 UTC, dopplershift commented on recipes/xmovie/meta.yaml
> +  number: 0
I have bad news...at some point you removed the `noarch: Python`

2021-04-15 23:02 UTC, dopplershift approved these changes
🎉

2021-04-15 23:03 UTC, merged