Add recipe for acrv-datasets
conda-forge/staged-recipes pull request #14547
Opened 2021-04-13 23:20 UTC by btalb

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

This package is part of the [Best of ACRV](https://roboticvision.org/best-of-acrv). I am happy to take care of maintenance duties for this feedstock.

2021-04-13 23:21 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/acrv-datasets```) and found some lint.

Here's what I've got...


For **recipes/acrv-datasets**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2021-04-13 23:55 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/acrv-datasets```) and found it was in an excellent condition.

2021-04-14 01:01 UTC, Tobias-Fischer commented
Hi @conda-forge/help-python - this is @btalb's first package. He's a colleague of mine and doesn't have rights to tag teams yet, so I'm doing it.

/cc @wolfv - FYI, @btalb is planning to put up quite a few robotics related packages up in the next few days. They are part of the legacy of the Australian Centre for Robotic Vision.

2021-04-14 17:19 UTC, dopplershift requested changes
Looks good overall, just a couple minor things.

2021-04-14 17:19 UTC, dopplershift commented on recipes/acrv-datasets/meta.yaml
> +  doc_url: https://github.com/best-of-acrv/acrv_datasets
Pretty sure both of these should be `acrv-datasets`.

2021-04-14 17:19 UTC, dopplershift commented on recipes/acrv-datasets/meta.yaml
> +  summary: Datasets manager for the Best of ACRV
All three of these are duplicated (with different vaules) below.

2021-04-14 23:29 UTC, btalb commented
Thanks @dopplershift for catching those mistakes. Should be resolved now.

2021-04-15 05:50 UTC, merged