Initial package for sgkit.
conda-forge/staged-recipes pull request #14569
Opened 2021-04-15 18:15 UTC by jeromekelleher

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-04-15 18:16 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/sgkit```) and found some lint.

Here's what I've got...


For **recipes/sgkit**:

 * The recipe could do with some maintainers listed in the `extra/recipe-maintainers` section.
 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [28]
 * The extra section contained an unexpected subsection name. maintainers is not a valid subsection name.
 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.

For **recipes/sgkit**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2021-04-16 07:39 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/sgkit```) and found some lint.

Here's what I've got...


For **recipes/sgkit**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [30]
 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.
 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2021-04-16 07:45 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/sgkit```) and found some lint.

Here's what I've got...


For **recipes/sgkit**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [29]

2021-04-16 07:52 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/sgkit```) and found some lint.

Here's what I've got...


For **recipes/sgkit**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2021-04-16 07:57 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/sgkit```) and found it was in an excellent condition.

2021-04-16 08:54 UTC, jeromekelleher commented
Hooray, looks like this is working!

@eric-czech, would you mind having a quick look over please? Also, can I put you down as a maintainer (to reduce the bus factor)?

I've made it a "noarch" package, which is the right approach I think, since we're not shipping any compiled code.

2021-04-20 18:19 UTC, jeromekelleher commented
@eric-czech, @tomwhite any takers for reviewing this and volunteering to be named as a maintainer? There's no much involved, just clicking "merge" on auto update PRs every now and again.

2021-04-20 18:34 UTC, eric-czech approved these changes

2021-04-20 18:35 UTC, eric-czech commented
> @eric-czech, would you mind having a quick look over please? Also, can I put you down as a maintainer (to reduce the bus factor)?

Hey @jeromekelleher, yea go for it.  Sorry for the delay.

2021-04-21 10:08 UTC, tomwhite commented
@jeromekelleher happy to be added as a maintainer if you need another one.

2021-04-21 11:11 UTC, jeromekelleher commented
Thanks @eric-czech and @tomwhite, I've added you both as maintainers.

2021-04-21 11:13 UTC, jeromekelleher commented
@conda-forge/staged-recipes this is ready for final review and merge :heart:

2021-04-21 16:33 UTC, dopplershift requested changes
Just a minor typo, then this is ready to go in.

2021-04-21 16:33 UTC, dopplershift commented on recipes/sgkit/meta.yaml
> +  dev_url: https://github.com/pystatgen/sgki
```suggestion
  dev_url: https://github.com/pystatgen/sgkit
```

2021-04-21 16:36 UTC, jeromekelleher commented on recipes/sgkit/meta.yaml
> +  dev_url: https://github.com/pystatgen/sgki
Doh! :facepalm: Thanks @dopplershift

2021-04-21 16:50 UTC, dopplershift approved these changes

2021-04-21 16:50 UTC, merged

2021-04-21 16:55 UTC, jeromekelleher commented
:tada: Thanks @dopplershift !