Adding Python package: tscv
conda-forge/staged-recipes pull request #14574
Opened 2021-04-16 01:47 UTC by WenjieZ

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-04-16 01:47 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/tscv```) and found some lint.

Here's what I've got...


For **recipes/tscv**:

 * There are too few lines.  There should be one empty line at the end of the file.

2021-04-16 01:50 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/tscv```) and found it was in an excellent condition.

2021-04-16 04:05 UTC, WenjieZ commented
@conda-forge/help-python

First time contributing. Review needed.

2021-04-16 05:23 UTC, WenjieZ commented
@conda-forge-admin, please ping team

2021-04-16 05:23 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/staged-recipes and so here I am doing that.

2021-04-16 16:06 UTC, dopplershift requested changes
Generally in good shape, just a couple minor things to make it noarch.

2021-04-16 16:06 UTC, dopplershift commented on recipes/tscv/meta.yaml
> +  number: 0
This looks like it's pure python, so you can do:
```suggestion
  number: 0
  noarch: python
```

2021-04-16 16:06 UTC, dopplershift commented on recipes/tscv/meta.yaml
> +    - {{ compiler('c') }}
Being pure python, there's no need for a C compiler.
```suggestion
```

2021-04-17 01:26 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/tscv```) and found some lint.

Here's what I've got...


For **recipes/tscv**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2021-04-17 01:30 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/tscv```) and found it was in an excellent condition.

2021-04-20 09:27 UTC, chrisburr commented on recipes/tscv/meta.yaml
> +    - scikit-learn >=0.22
This probably isn't needed in `host`:
```suggestion
```

2021-04-20 09:29 UTC, chrisburr commented on recipes/tscv/meta.yaml
> +    - sklearn
This should only test imports which come from this specific package directly
```suggestion
```

2021-04-20 09:29 UTC, chrisburr commented on recipes/tscv/meta.yaml
> +    - scikit-learn >=0.22
It looks like numpy is also a direct dependency of `tscv`:
```suggestion
    - scikit-learn >=0.22
    - numpy
```

2021-04-21 00:37 UTC, WenjieZ commented
Build error after committing 2/3 of the suggestions: `ModuleNotFoundError: No module named 'numpy'`

The dependency relation (both source and test) of my package is
```
numpy -> tscv
numpy -> scikit-learn -> tscv
```
@chrisburr

2021-04-21 04:03 UTC, chrisburr commented
@WenjieZ The issue is that the package is importing itself in the `setup.py`: https://github.com/WenjieZ/TSCV/blob/5de57c07133fc7a56e862269556e7802a8c97bac/setup.py#L2

As you maintain upstream it should ideally be fixed there. My personal preference is to use `setuptools_scm` but there are several other options which are listed here: https://packaging.python.org/guides/single-sourcing-package-version/#single-sourcing-the-version

2021-04-21 10:35 UTC, merged