Adding easygdf
conda-forge/staged-recipes pull request #14670
Opened 2021-04-21 23:09 UTC by electronsandstuff

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-04-21 23:09 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/easygdf```) and found it was in an excellent condition.

2021-04-21 23:28 UTC, electronsandstuff commented
@conda-forge-admin, please ping team

I think I'm ready for review!

2021-04-21 23:28 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/staged-recipes and so here I am doing that.

2021-04-22 19:09 UTC, dopplershift requested changes
Looks good, just a couple minor items.

2021-04-22 19:09 UTC, dopplershift commented on recipes/easygdf/meta.yaml
> +    - setuptools
Since `setuptools` is only used by `setup.py`, you don't need it listed under `run`.

2021-04-22 19:09 UTC, dopplershift commented on recipes/easygdf/LICENSE
> +BSD 3-Clause License
It looks like the license is included in the PyPI tarball, so you shouldn't add the file manually here.

2021-04-22 19:18 UTC, dopplershift commented on recipes/easygdf/meta.yaml
> +    - setuptools
Ooops, yeah. I forget about that one.

2021-04-22 19:30 UTC, electronsandstuff reviewed
OK, I've deleted the license

2021-04-22 20:05 UTC, dopplershift approved these changes

2021-04-22 20:05 UTC, merged