Add django-elasticsearch-dsl
conda-forge/staged-recipes pull request #14689
Opened 2021-04-22 20:33 UTC by MichelML

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-04-22 20:33 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/django-elasticsearch-dsl```) and found it was in an excellent condition.

2021-04-22 20:34 UTC, MichelML commented
@dopplershift relates to https://github.com/conda-forge/staged-recipes/pull/14686

2021-04-22 20:55 UTC, MichelML commented
ready to merge @dopplershift :+1: 

@conda-forge-admin, please ping team

2021-04-22 20:55 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/staged-recipes and so here I am doing that.

2021-04-23 00:58 UTC, dopplershift requested changes
Found a couple more things now.

2021-04-23 00:58 UTC, dopplershift commented on recipes/django-elasticsearch-dsl/meta.yaml
> +  home: https://github.com/sabricot/django-elasticsearch-dsl
This actually resolves now to https://github.com/django-es/django-elasticsearch-dsl  Can you update? I was really confused for a minute.

2021-04-23 00:58 UTC, dopplershift commented on recipes/django-elasticsearch-dsl/LICENSE
> +Licensed under the Apache License, Version 2.0 (the "License");
Looks like the license is included in the PyPI tarball, so you should not include this file.

2021-04-23 02:55 UTC, MichelML commented
Thanks @dopplershift , will do the change asap tomorrow

2021-04-23 11:59 UTC, MichelML commented
I think it's ready now @dopplershift , thanks for the feedback! :pray:

2021-04-23 17:23 UTC, dopplershift approved these changes

2021-04-23 17:23 UTC, merged