Add pyrolite
conda-forge/staged-recipes pull request #14748
Opened 2021-04-28 01:57 UTC by morganjwilliams

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] ~If static libraries are linked in, the license of the static library is packaged.!~
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-04-28 01:57 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyrolite```) and found it was in an excellent condition.

2021-04-28 02:34 UTC, morganjwilliams commented
Checks are currently failing due to [`pathlib` seeming to be missing](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=310071&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=1290) (despite being a standard library package since Py3.4) - I'll have to debug this one, and it might have to wait for the next `pyrolite` PyPI release if the issue is with dependency specification within the package itself.

2021-04-28 12:50 UTC, eazzzon commented
this is strange, I will take a look as well

2021-05-03 01:29 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyrolite```) and found some lint.

Here's what I've got...


For **recipes/pyrolite**:

 * Non noarch packages should have python requirement without any version constraints.

2021-05-03 01:49 UTC, morganjwilliams commented
@eazzzon looks like that raises a linting flag and won't solve our issue alone.

I had another look at `pathlib`, and it seems there's a separate `pathlib` (and `pathlib2`) package on PyPI. I'm not well versed in the mechanics of the `conda`  and `pip` dependency resolvers, but perhaps the standard library `pathlib` is being ignored and the standalone package version is expected by `pip check` (which in this case may not actually be installed, depending on `conda`'s dependency resolver and how it handles standard library dependencies...).

2021-12-01 10:00 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyrolite```) and found some lint.

Here's what I've got...


For **recipes/pyrolite**:

 * ``requirements: run: mpltern>=0.3.4`` must contain a space between the name and the pin, i.e. ``mpltern >=0.3.4``
 * ``requirements: run: scipy>=1.2`` must contain a space between the name and the pin, i.e. ``scipy >=1.2``
 * ``requirements: run: sympy>=1.7`` must contain a space between the name and the pin, i.e. ``sympy >=1.7``
 * ``requirements: run: tinydb>4.1`` must contain a space between the name and the pin, i.e. ``tinydb >4.1``
 * Non noarch packages should have python requirement without any version constraints.

2021-12-01 10:02 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyrolite```) and found some lint.

Here's what I've got...


For **recipes/pyrolite**:

 * Non noarch packages should have python requirement without any version constraints.

2021-12-02 03:00 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyrolite```) and found it was in an excellent condition.

2021-12-02 03:06 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyrolite```) and found some lint.

Here's what I've got...


For **recipes/pyrolite**:

 * Non noarch packages should have python requirement without any version constraints.

2021-12-02 03:22 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyrolite```) and found some lint.

Here's what I've got...


For **recipes/pyrolite**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2021-12-02 03:48 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyrolite```) and found it was in an excellent condition.

2021-12-02 04:54 UTC, morganjwilliams commented
Hey @eazzzon - with 0.3.1 released (apologies for the long delay on this one, it's been a busy year!), this looks like it's now good to go. There's a residual issue with using `pip check`, which I think is due to a recent update to how `mpltern` has set up versioning; for now I've left this check out and will look to do some debugging to see if it can be addressed. 

Please post here if you're still happy to be a maintainer for the conda recipe side of things, and we can tick the last box above.

2022-01-02 23:01 UTC, eazzzon commented
> Hey @eazzzon - with 0.3.1 released (apologies for the long delay on this one, it's been a busy year!), this looks like it's now good to go. There's a residual issue with using `pip check`, which I think is due to a recent update to how `mpltern` has set up versioning; for now I've left this check out and will look to do some debugging to see if it can be addressed.
> 
> Please post here if you're still happy to be a maintainer for the conda recipe side of things, and we can tick the last box above.

Hi @morganjwilliams, sorry for the late delay, the notification of github is a bit confusing.
Very good news for the recipe, I am very happy to be one of the maintainer.

2022-01-04 23:43 UTC, dopplershift requested changes
Minor tweak to the license metadata and this is good to go.

2022-01-04 23:43 UTC, dopplershift commented on recipes/pyrolite/meta.yaml
> +  license: MIT AND BSD-3-Clause
Probably better to do:
```suggestion
  license: LicenseRef-CSIRO-Open-Source
```
since there's so much legalese at the bottom.

2022-01-05 18:04 UTC, dopplershift approved these changes

2022-01-05 18:04 UTC, merged