Adding neptune-client integrations with ML frameworks (multiple packages)
conda-forge/staged-recipes pull request #14759
Opened 2021-04-29 14:18 UTC by PiotrJander

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-04-29 14:18 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/neptune-lightgbm```, ```recipes/neptune-sklearn```, ```recipes/neptune-tensorflow-keras```, ```recipes/neptune-xgboost```) and found it was in an excellent condition.

2021-04-30 08:57 UTC, HubertJaworski commented
I confirm

2021-04-30 09:02 UTC, aniezurawski commented
I confirm that I am willing to be listed as a maintainer of the submitted packages

2021-04-30 17:03 UTC, dopplershift requested changes
Just a couple minor things. @pitercl @shnela @pkasprzyk can you all confirm you are willing to be maintainers on these recipes?

2021-04-30 17:03 UTC, dopplershift commented on recipes/neptune-xgboost/meta.yaml
> +    - matplotlib
Unless this needs/wants the `pyqt` GUI, better to depend on `matplotlib-base`.

2021-05-04 07:10 UTC, pitercl commented
> Just a couple minor things. @pitercl @shnela @pkasprzyk can you all confirm you are willing to be maintainers on these recipes?
I do confirm. Thanks!

2021-05-04 09:26 UTC, pkasprzyk commented
I also confirm I am willing to be listed as a maintainer of the submitted packages

2021-05-04 09:57 UTC, shnela commented
> Just a couple minor things. @pitercl @shnela @pkasprzyk can you all confirm you are willing to be maintainers on these recipes?

I do.

2021-05-04 11:23 UTC, PiotrJander commented
@dopplershift we now have comments with consent from all team members, and I addressed your other comments, but Windows build fails due to seemingly unsatisfiable dependencies. Could you have a look and help us find out how to fix the problem? I'm asking because it is not clear to me in what way exactly version constraints are incompatible, and why this problem only occurs on Windows and not on the other platforms.

2021-05-04 17:48 UTC, dopplershift commented
The obvious failure would be because tensorflow 2 isn't available from conda-forge on windows. I'm happy to merge these since they're all noarch python. Once they're built in their own feedstocks, it will be easier for you all to test and see if there are any unexpected dependency failures installing on Windows.

2021-05-04 17:48 UTC, merged