Add aedat
conda-forge/staged-recipes pull request #14846
Opened 2021-05-09 22:54 UTC by Tobias-Fischer

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-05-09 22:54 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes```) and found some lint.

Here's what I've got...


For **recipes**:

 * Please do not delete the example recipe found in `recipes/example/meta.yaml`.

2021-05-09 22:55 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/aedat```) and found it was in an excellent condition.

2021-05-10 01:09 UTC, isuruf requested changes
Needs work on license. See https://github.com/conda-forge/conda-forge.github.io/issues/1052

2021-05-10 01:35 UTC, Tobias-Fischer commented
Thanks for the pointer @isuruf.

Licenses packaged thanks to script found in https://github.com/conda-forge/staged-recipes/pull/13208

2021-05-12 23:24 UTC, Tobias-Fischer commented
I now use the same `maturin` mechanism to build the `aedat` package as in https://github.com/conda-forge/pysyntect-feedstock, which enabled me to build the package on Windows as well. All licenses are contained as well.

It would be great if someone could have a look at the PR. Many thanks!

2021-05-13 06:29 UTC, chrisburr commented on recipes/aedat/meta.yaml
> +    - pip
I'm not sure but are these needed in build?
```suggestion
```

2021-05-13 21:10 UTC, merged