Add pyaaf2 recipe
conda-forge/staged-recipes pull request #14887
Opened 2021-05-12 21:23 UTC by vvzen

Hi all!
This is my first PR here, I hope got everything right but there was a lot to cover and read through!
Adding this package for reading .aaf files in Python since it's used as a dependency by https://github.com/PixarAnimationStudios/OpenTimelineIO , which is the main repo I wanted to build a package for.
Thanks!

Valerio

2021-05-12 21:23 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyaaf2```) and found some lint.

Here's what I've got...


For **recipes/pyaaf2**:

 * license_file entry is missing, but is required.

2021-05-12 21:27 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyaaf2```) and found it was in an excellent condition.

2021-05-13 08:13 UTC, wolfv requested changes

2021-05-13 08:13 UTC, wolfv commented on recipes/pyaaf2/meta.yaml
> +  number: 0
It looks like this package could be "noarch": https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-builds

just add `noarch: python`

2021-05-13 08:13 UTC, wolfv commented on recipes/pyaaf2/meta.yaml
> +    - python
When you make this noarch, please specify a lower bound for python, e.g. `python >=3.6`

2021-05-13 08:13 UTC, wolfv commented on recipes/pyaaf2/meta.yaml
> +  doc_url:
if you don't know a good value for this, just remove the keys

2021-05-13 08:34 UTC, merged

2021-05-13 08:34 UTC, wolfv commented
great!

2021-05-13 09:22 UTC, vvzen commented
Best PR experience ever! Thanks :D