Add pandasql
conda-forge/staged-recipes pull request #15070
Opened 2021-05-28 15:48 UTC by psortos

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-05-28 15:48 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pandasql```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/pandasql**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2021-05-28 19:08 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pandasql```) and found some lint.

Here's what I've got...


For **recipes/pandasql**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

For **recipes/pandasql**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2021-05-28 19:09 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pandasql```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/pandasql**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2021-06-01 05:58 UTC, chrisburr commented on recipes/pandasql/meta.yaml
> +  number: 0
This looks like it can be `noarch: python`:

```suggestion
  noarch: python
  number: 0
```

2021-06-01 05:58 UTC, chrisburr commented on recipes/pandasql/meta.yaml
> +    - sqlalchemy
```suggestion
    - pip
    - python
```

2021-06-07 13:41 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pandasql```) and found some lint.

Here's what I've got...


For **recipes/pandasql**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

For **recipes/pandasql**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2021-06-07 13:45 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pandasql```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/pandasql**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2021-06-07 13:56 UTC, psortos commented
@chrisburr applied your recommendations, thank you!

2021-06-09 19:31 UTC, dopplershift requested changes
@oblute can you confirm you are willing to be a maintainer on this recipe?

2021-06-09 19:31 UTC, dopplershift commented on recipes/pandasql/meta.yaml
> +  license: Copyright (c) 2013 Yhat, Inc.
```suggestion
  license: MIT
```

2021-06-09 21:39 UTC, psortos commented on recipes/pandasql/meta.yaml
> +  license: Copyright (c) 2013 Yhat, Inc.
Updated!

2021-06-09 21:39 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pandasql```) and found it was in an excellent condition.

2021-06-09 22:53 UTC, dopplershift approved these changes

2021-06-10 19:26 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pandasql```) and found some lint.

Here's what I've got...


For **recipes/pandasql**:

 * There are too few lines.  There should be one empty line at the end of the file.

2021-06-12 08:45 UTC, chrisburr commented on recipes/pandasql/meta.yaml
> +    - psortos
```suggestion
    - psortos

```

2021-06-14 14:47 UTC, psortos commented on recipes/pandasql/meta.yaml
> +    - psortos
Added this change

2021-06-14 14:55 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pandasql```) and found it was in an excellent condition.

2021-06-14 15:29 UTC, oblute commented
@chrisburr @dopplershift this is ready for review

2021-06-14 19:21 UTC, dopplershift approved these changes

2021-06-14 19:22 UTC, merged