Add recipe for maskslic
conda-forge/staged-recipes pull request #15100
Opened 2021-06-01 11:32 UTC by mcraig-ibme

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-06-01 11:32 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/maskslic```) and found it was in an excellent condition.

2021-06-02 09:22 UTC, mcraig-ibme commented
@conda-forge-admin, please restart ci

2021-06-03 13:00 UTC, mcraig-ibme commented
@conda-forge/help-python ready for review, thanks!

2021-06-09 19:48 UTC, dopplershift requested changes

2021-06-09 19:48 UTC, dopplershift commented on recipes/maskslic/meta.yaml
> +    - cython
I think `cython` should actually be listed as a `build` dependency rather than `host`.

2021-06-09 19:48 UTC, dopplershift commented on recipes/maskslic/meta.yaml
> +    - numpy >=1.7.2
```suggestion
    - {{ pin_compatible('numpy') }}
```
See [here](https://conda-forge.org/docs/maintainer/knowledge_base.html#building-against-numpy)

2021-06-09 20:26 UTC, dopplershift commented on recipes/maskslic/meta.yaml
> +    - cython
Nevermind, the situation for cross-compiling with cython is more complicated and we can delay worrying about that right now (unless you care about OSX arm64 builds).

2022-03-30 12:21 UTC, closed without merging