Adding osqp-eigen recipe
conda-forge/staged-recipes pull request #15309
Opened 2021-06-15 22:04 UTC by GiulioRomualdi

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

The PR is ready to be reviewed @conda-forge/help-c-cpp

This PR closes #15080 
cc @traversaro

2021-06-15 22:04 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/osqp-eigen```) and found some lint.

Here's what I've got...


For **recipes/osqp-eigen**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [28, 29, 30, 31]

For **recipes/osqp-eigen**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2021-06-15 22:09 UTC, traversaro commented on recipes/osqp-eigen/meta.yaml
> +  number: 1
0

2021-06-15 22:11 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/osqp-eigen```) and found it was in an excellent condition.

2021-06-15 22:11 UTC, GiulioRomualdi commented on recipes/osqp-eigen/meta.yaml
> +  number: 1
Fixed here: https://github.com/conda-forge/staged-recipes/pull/15309/commits/8740f5142c813e1800a404f9683d2797a275ce6d

2021-06-15 22:38 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/stable-baselines3```) and found some lint.

Here's what I've got...


For **recipes/stable-baselines3**:

 * Feedstock with the same name exists in conda-forge.

2021-06-15 22:47 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/osqp-eigen```) and found it was in an excellent condition.

2021-06-16 10:28 UTC, traversaro commented
@GiulioRomualdi feel free to add me as well as maintainer, it is a good practice to avoid having just one maintainer in recipes to reduce the bus factor.

2021-06-16 15:41 UTC, traversaro commented
> The PR is ready to be reviewed @conda-forge/help-c-cpp

The CI is now green, @conda-forge/help-c-cpp this is now ready for review.

2021-06-16 15:43 UTC, traversaro requested changes

2021-06-16 15:43 UTC, traversaro commented on recipes/osqp-eigen/build.sh
> +      -DCMAKE_PREFIX_PATH=$PREFIX \
```suggestion
cmake ${CMAKE_ARGS} \
```
See https://github.com/conda-forge/staged-recipes/pull/15301#discussion_r652075460 and https://github.com/conda-forge/staged-recipes/pull/15140#discussion_r646172798 .

2021-06-23 09:23 UTC, traversaro commented
@wolfv just FYI, this is the first package that we migrate from the `robotology` channel to `conda-forge`, hopefully many will follow in the future. : )

2021-06-23 10:44 UTC, merged

2021-06-23 10:44 UTC, wolfv commented
Awesome!