adding numconv recipe
conda-forge/staged-recipes pull request #15411
Opened 2021-06-25 20:50 UTC by kbeeperez

implements: https://github.com/nsls-ii-forge/numconv-feedstock

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-06-25 20:50 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/numconv```) and found it was in an excellent condition.

2021-06-25 22:12 UTC, kbeeperez commented
Attn @mrakitin

2021-06-27 22:31 UTC, kbeeperez commented
@conda-forge/staged-recipes Hello, I need this merged so two other PR can be completed successfully.

2021-06-28 02:42 UTC, dopplershift approved these changes
Recipe looks fine. Need @mrakitin to confirm that they are willing to be a maintainer for this recipe.

2021-06-28 15:08 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/bloptools```, ```recipes/numconv```, ```recipes/sirepo-bluesky```) and found it was in an excellent condition.

2021-06-28 21:59 UTC, dopplershift commented
@kbeeperez Did something go wrong here?

2021-06-28 22:04 UTC, kbeeperez commented
@dopplershift no,  I just added sirepo-bluesky & bloptools recipes to package them in one shot per @mrakitin suggestion because they rely on numconv.

2021-06-28 22:05 UTC, dopplershift commented
Ah, GitHub was only showing me the most recent 2 before...now I see them all.

2021-07-13 17:05 UTC, mrakitin commented
> Recipe looks fine. Need @mrakitin to confirm that they are willing to be a maintainer for this recipe.

Sorry for the delay, was on vacation. Confirming my desire to be a maintainer.

2021-07-21 03:19 UTC, kbeeperez commented
@conda-forge/staged-recipes should be ready to be merged

2021-07-21 18:44 UTC, dopplershift requested changes
Just a couple `matplotlib`->`matplotlib-base` changes and these are ready.

2021-07-21 18:44 UTC, dopplershift commented on recipes/bloptools/meta.yaml
> +    - matplotlib
```suggestion
    - matplotlib-base
```

2021-07-21 18:44 UTC, dopplershift commented on recipes/sirepo-bluesky/meta.yaml
> +    - matplotlib
```suggestion
    - matplotlib-base
```

2021-07-22 14:59 UTC, mrakitin approved these changes

2021-07-22 20:03 UTC, dopplershift approved these changes

2021-07-22 20:03 UTC, merged

2021-07-22 20:05 UTC, mrakitin commented
Thanks, @dopplershift!