Add schist package
conda-forge/staged-recipes pull request #15432
Opened 2021-06-28 10:42 UTC by dawe

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-06-28 10:42 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/schist```) and found some lint.

Here's what I've got...


For **recipes/schist**:

 * Failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint .` from the recipe directory.

2021-06-28 10:58 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/schist```) and found it was in an excellent condition.

2021-06-28 11:10 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/schist```) and found some lint.

Here's what I've got...


For **recipes/schist**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.

2021-06-28 11:14 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/schist```) and found it was in an excellent condition.

2021-06-28 12:22 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/schist```) and found some lint.

Here's what I've got...


For **recipes/schist**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2021-06-28 12:24 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/schist```) and found it was in an excellent condition.

2021-06-28 14:53 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/schist```) and found some lint.

Here's what I've got...


For **recipes/schist**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2021-06-28 14:58 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/schist```) and found it was in an excellent condition.

2021-06-28 19:11 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/schist```) and found some lint.

Here's what I've got...


For **recipes/schist**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2021-06-28 19:19 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/schist```) and found it was in an excellent condition.

2021-06-28 19:25 UTC, dopplershift requested changes
I'm not sure what of any of these you tried previously, though.

2021-06-28 19:25 UTC, dopplershift commented on recipes/schist/LICENSE
> +Copyright 2020 Davide Cittaro
No need to include this file manually since it's included in the GitHub tarball.

2021-06-28 19:25 UTC, dopplershift commented on recipes/schist/meta.yaml
> +  version: 0.7.7
```suggestion
  version: {{ version }}
```

2021-06-28 19:25 UTC, dopplershift commented on recipes/schist/meta.yaml
> +  url: https://github.com/dawe/schist/archive/refs/tags/v0.7.7.tar.gz
```suggestion
  url: https://github.com/dawe/schist/archive/refs/tags/v{{ version }}.tar.gz
```

2021-06-28 19:25 UTC, dopplershift commented on recipes/schist/meta.yaml
> +    - xlrd <2.0
I don't think you need all these under `host`?
```suggestion
```

2021-06-28 19:25 UTC, dopplershift commented on recipes/schist/meta.yaml
> +    - python
```suggestion
    - python >=3.6
```

2021-06-28 19:25 UTC, dopplershift commented on recipes/schist/meta.yaml
> +    - python
```suggestion
    - python >=3.6
```

2021-06-28 19:25 UTC, dopplershift commented on recipes/schist/meta.yaml
> +  name: schist
```suggestion
  name: {{ name }}
```

2021-06-29 06:36 UTC, dawe commented
@dopplershift thanks for the review, it works now with the exception of win. I had to drop support for py37 as well due to some issues with the dependencies.

2021-06-29 14:17 UTC, dopplershift approved these changes
Recipe looks good. @leomorelli can you confirm that you are willing to be a maintainer for this recipe?

2021-06-29 14:41 UTC, leomorelli commented
Yes, I confirm.

2021-06-29 15:09 UTC, merged