Added recipe for `pyrobex`
conda-forge/staged-recipes pull request #15441
Opened 2021-06-28 18:29 UTC by sarthakpati

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-06-28 18:30 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/docly```, ```recipes/pyrobex```) and found some lint.

Here's what I've got...


For **recipes/docly**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2021-06-28 18:32 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyrobex```) and found it was in an excellent condition.

2021-06-28 18:43 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyrobex```) and found some lint.

Here's what I've got...


For **recipes/pyrobex**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.

2021-06-28 18:46 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyrobex```) and found it was in an excellent condition.

2021-06-28 20:06 UTC, sarthakpati commented
@conda-forge/help-python this is ready for merge!

2021-06-29 14:35 UTC, dopplershift requested changes
Let's see if it works after this change.

2021-06-29 14:35 UTC, dopplershift commented on recipes/pyrobex/LICENSE
> +
This is already included in the PyPI tarball so you shouldn't include it manually in the recipe.

2021-06-29 14:35 UTC, dopplershift commented on recipes/pyrobex/meta.yaml
> +  skip: True
Need to remove this since you're effectively skipping all builds.
```suggestion
```

2021-06-29 15:13 UTC, dopplershift approved these changes

2021-06-29 15:14 UTC, merged