Initial Opuslib recipe
conda-forge/staged-recipes pull request #15488
Opened 2021-07-02 19:46 UTC by JennaLipscomb

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-07-02 19:47 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/opuslib```) and found some lint.

Here's what I've got...


For **recipes/opuslib**:

 * The `requirements/` sections should be defined in the following order: build, host, run; instead saw: host, run, build.
 * license_file entry is missing, but is required.

For **recipes/opuslib**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2021-07-02 19:53 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/opuslib```) and found some lint.

Here's what I've got...


For **recipes/opuslib**:

 * The `requirements/` sections should be defined in the following order: build, host, run; instead saw: host, run, build.

For **recipes/opuslib**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2021-07-08 13:45 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/opuslib```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/opuslib**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2021-07-08 16:33 UTC, JennaLipscomb commented
@oblute @mxr-conda agree to maintain?

2021-07-08 19:03 UTC, dopplershift requested changes

2021-07-08 19:03 UTC, dopplershift commented on recipes/opuslib/meta.yaml
> +  number: 0
Since this is pure python, this can be noarch python:
```suggestion
  number: 0
  noarch: python
```

2021-07-08 19:03 UTC, dopplershift commented on recipes/opuslib/meta.yaml
> +    - libopus
No need for a build section, only need `libopus` for run, and need to add a Python version constraint for noarch python:
```suggestion
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - libopus
```

2021-07-08 20:43 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/opuslib```) and found it was in an excellent condition.

2021-07-09 20:45 UTC, dopplershift approved these changes
Just need a confirmation from (someone in) @mxr-conda that they are willing to be a maintainer.

2021-07-12 16:43 UTC, mxr-conda commented
@dopplershift good to maintain

2021-07-12 17:29 UTC, merged