Add Qt-main recipe
conda-forge/staged-recipes pull request #15572
Opened 2021-07-08 20:00 UTC by andfoy

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-07-08 20:00 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/qt-main```) and found some lint.

Here's what I've got...


For **recipes/qt-main**:

 * The recipe must have some tests.

2021-07-08 20:04 UTC, andfoy commented
@conda-forge/staged-recipes is it possible to run recipes on CentOS 7 here?

2021-07-09 00:40 UTC, isuruf commented
Please send this PR to `qt-feedstock` first so that we can review it and compare against the current recipe.

2021-07-09 20:27 UTC, andfoy commented
The test-run PR is available at: https://github.com/conda-forge/qt-feedstock/pull/198

2021-12-01 19:06 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/qt-main```) and found some lint.

Here's what I've got...


For **recipes/qt-main**:

 * Feedstock with the same name exists in conda-forge.

2021-12-01 19:08 UTC, andfoy commented
@isuruf, do you know why the linter is complaining? I don't see any `qt-main-feedstock` in the organization

2021-12-01 19:12 UTC, isuruf commented on recipes/qt-main/meta.yaml
> +{% set name = "qt" %}
```suggestion
{% set name = "qt-main" %}
```

2021-12-01 19:16 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/qt-main```) and found it was in an excellent condition.

2021-12-01 19:32 UTC, isuruf commented on recipes/qt-main/meta.yaml
> +    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.14") }}  # [osx]
```suggestion
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.14") }}  # [osx]
    - qt {{ version }}
```

2021-12-01 19:32 UTC, andfoy commented on recipes/qt-main/meta.yaml
> +    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.14") }}  # [osx]
Isn't it `qt-main` there?

2021-12-01 20:24 UTC, andfoy commented
@isuruf, do we need tests to pass here?

2021-12-02 17:21 UTC, andfoy commented
@isuruf, this recipe was not designed with CentOS 6 in mind, and it won't work on it. Also we require clang 12 on Mac, which cannot be set up here unless the version is hardcoded in `conda_build_config`. Is it possible to merge it as it was approved?

2021-12-02 21:31 UTC, isuruf commented
> Also we require clang 12 on Mac, which cannot be set up here unless the version is hardcoded in conda_build_config

I don't understand this.

> @isuruf, this recipe was not designed with CentOS 6 in mind, and it won't work on it

Both CentOS 6 and 7 is tested here. So the CentOS 7 job should work.

2021-12-02 21:58 UTC, andfoy commented
> I don't understand this.

For some reason, the dependency on libclang is version 13 and the compilers (via `clang_osx`) is 11, this error was fixed on the feedstock by constraining the libclang version to the same version that `c/cxx_compiler_version` has

2021-12-02 22:09 UTC, isuruf commented
> For some reason, the dependency on libclang is version 13 and the compilers (via clang_osx) is 11, this error was fixed on the feedstock by constraining the libclang version to the same version that c/cxx_compiler_version has

What's different from the feedstock and staged-recipes?

2021-12-02 22:52 UTC, andfoy commented
https://github.com/conda-forge/qt-feedstock/blob/2fe1037a06bfe17b6b2a3ab48a8ce56c752d949b/.ci_support/osx_64_.yaml

2021-12-02 22:54 UTC, isuruf commented
You were editing that manually?

2021-12-02 22:55 UTC, andfoy commented
Yes, I did edit that manually

2021-12-02 22:56 UTC, isuruf commented
That's not allowed. Those files should not be touched at all.

2021-12-02 22:56 UTC, andfoy commented
What should be the correct way?

2021-12-03 05:10 UTC, ngam commented
> What should be the correct way?

@andfoy, here usually:
https://github.com/andfoy/staged-recipes/blob/add_qt_main/recipes/qt-main/conda_build_config.yaml

Add something like:
```
c_compiler_version:    # [osx]
- '12'                 # [osx]
cxx_compiler_version:  # [osx]
- '12'                 # [osx]
```

2021-12-03 05:12 UTC, ngam requested changes

2021-12-03 05:12 UTC, ngam commented on recipes/qt-main/conda_build_config.yaml
> +  - '10.14'                # [osx and x86_64]
add

```
c_compiler_version:    # [osx]
- '12'                 # [osx]
cxx_compiler_version:  # [osx]
- '12'                 # [osx]
```

2021-12-03 05:14 UTC, andfoy commented
@ngam , I was aware of this before. The error was caused by an internal repodata constraint that was fixed in

2021-12-03 05:18 UTC, ngam commented
> @ngam , I was aware of this before. The error was caused by an internal repodata constraint that was fixed in [conda-forge/conda-forge-repodata-patches-feedstock#195](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/195)

Oh, okay good 👍

2021-12-06 17:22 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/qt-main```) and found some lint.

Here's what I've got...


For **recipes/qt-main**:

 * Feedstock with the same name exists in conda-forge.

2021-12-06 17:23 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/qt-main```) and found it was in an excellent condition.

2021-12-06 22:28 UTC, Tobias-Fischer commented
Latest error on linux_64_centos7 for reference:
```
2021-12-06T19:47:12.1233826Z conda_build.exceptions.OverLinkingError: overlinking check failed 
2021-12-06T19:47:12.1242458Z ['  
ERROR (qt-main,lib/libQt5EglFsKmsSupport.so.5.15.2): $RPATH/libEGL.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', "  
ERROR (qt-main,plugins/mediaservice/libgstmediacapture.so): .. but ['alsa-lib'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)", "  
ERROR (qt-main,plugins/audio/libqtaudio_alsa.so): .. but ['alsa-lib'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)", '  
ERROR (qt-main,plugins/egldeviceintegrations/libqeglfs-x11-integration.so): $RPATH/libEGL.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', "  
ERROR (qt-main,lib/libQt5MultimediaGstTools.so.5.15.2): .. but ['alsa-lib'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)", "  
ERROR (qt-main,plugins/mediaservice/libgstaudiodecoder.so): .. but ['alsa-lib'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)", "  
ERROR (qt-main,plugins/mediaservice/libgstcamerabin.so): .. but ['alsa-lib'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)", "  
ERROR (qt-main,lib/libQt5Network.so.5.15.2): .. but ['krb5'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)", "  
ERROR (qt-main,bin/rcc): .. but ['zstd'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)", " 
ERROR (qt-main,plugins/mediaservice/libgstmediaplayer.so): .. but ['alsa-lib'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)", '  
ERROR (qt-main,lib/libQt5EglFSDeviceIntegration.so.5.15.2): $RPATH/libEGL.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  
ERROR (qt-main,plugins/xcbglintegrations/libqxcb-egl-integration.so): $RPATH/libEGL.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  
ERROR (qt-main,plugins/egldeviceintegrations/libqeglfs-emu-integration.so): $RPATH/libEGL.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  
ERROR (qt-main,plugins/platforms/libqminimalegl.so): $RPATH/libEGL.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', "  
ERROR (qt-main,lib/libQt5Core.so.5.15.2): .. but ['zstd'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)", '  
ERROR (qt-main,plugins/egldeviceintegrations/libqeglfs-kms-egldevice-integration.so): $RPATH/libEGL.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  
ERROR (qt-main,plugins/platforms/libqeglfs.so): $RPATH/libEGL.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?']
```

So a few issues around `$RPATH/libEGL.so.1`, `zstd`, `krb5` and `alsa-lib`.

The libEGL issue can probably be resolved by adding mesa-libEGL to yum_requirements.txt. I'm not sure about the others though ..

2021-12-07 19:06 UTC, merged

2021-12-07 19:06 UTC, isuruf commented
Thanks

2021-12-07 19:12 UTC, andfoy commented
Thanks a lot for the help with the reviewing process