add drfp
conda-forge/staged-recipes pull request #15591
Opened 2021-07-11 11:02 UTC by hadim

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-07-11 11:02 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/drfp```) and found it was in an excellent condition.

2021-07-11 12:10 UTC, hadim commented
@conda-forge/staged-recipes It seems the dep conflicts are not related to this package specifically. I also don't quite understand what is happening. If someone has an idea.

2021-07-12 19:02 UTC, dopplershift requested changes
The build failures are due to the fact that it's trying to build a package for Python 3.6, but numpy >=1.21.0 only supports Python >=3.7. Moving to noarch (and also selecting Python >= 3.7) will fix it.

2021-07-12 19:02 UTC, dopplershift commented on recipes/drfp/meta.yaml
> +  entry_points:
This looks like it's pure Python so this can be noarch Python:
```suggestion
  noarch: python
  entry_points:
```

2021-07-12 19:02 UTC, dopplershift commented on recipes/drfp/meta.yaml
> +    - python
To finish making this noarch, add Python version constraints and remove the selector on `importlib_metadata` (better to have this noarch and unconditionally install `importlib_metadata`):
```suggestion
  host:
    - pip
    - python >=3.7
  run:
    - click >=8.0.1
    - importlib_metadata
    - numpy >=1.21.0
    - python >=3.7
```

2021-07-12 19:04 UTC, hadim commented
@conda-forge-admin please rerender

2021-07-12 19:04 UTC, hadim commented
> The build failures are due to the fact that it's trying to build a package for Python 3.6, but numpy >=1.21.0 only supports Python >=3.7. Moving to noarch (and also selecting Python >= 3.7) will fix it.

Thank you @dopplershift !

2021-07-12 19:04 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/drfp```) and found some lint.

Here's what I've got...


For **recipes/drfp**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.
 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2021-07-12 19:05 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/drfp```) and found it was in an excellent condition.

2021-07-12 19:09 UTC, hadim commented
@conda-forge-admin please rerender

2021-07-12 21:22 UTC, dopplershift approved these changes

2021-07-12 21:23 UTC, dopplershift commented
@hadim FYI, rerendering is never necessary (or useful) on staged-recipes.

2021-07-12 21:23 UTC, merged