adding lixtools recipe
conda-forge/staged-recipes pull request #15648
Opened 2021-07-16 05:03 UTC by kbeeperez

implements: https://github.com/nsls-ii-forge/lixtools-feedstock

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-07-16 05:04 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/lixtools```) and found it was in an excellent condition.

2021-07-16 05:16 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/lixtools```, ```recipes/py4xs```) and found it was in an excellent condition.

2021-07-16 06:07 UTC, kbeeperez commented
Attn @mrakitin

2021-07-16 14:43 UTC, mrakitin requested changes
Looks good overall, I added a comment on how to solve the Windows tests that are currently excluded.

2021-07-16 14:43 UTC, mrakitin commented on recipes/lixtools/meta.yaml
> +    - python -c 'import os, pkg_resources; assert os.path.isfile(pkg_resources.resource_filename("lixtools", "template_report.ipynb"))'  # [not win]
I am against excluding tests for Windows. Could you try to fix it instead? On Windows CLI, single quotes are not accepted. Please use double-quotes. An easy way to test it on your Windows machine is to install the package locally and try this `python -c ...` string.

2021-07-16 14:43 UTC, mrakitin commented on recipes/lixtools/meta.yaml
> +    - mrakitin
Adding @lyang11973 as a core developer of the package. Lin, do you agree to be a maintainer of this conda-forge feedstock?
```suggestion
    - lyang11973
    - mrakitin
```

2021-07-16 14:43 UTC, mrakitin commented on recipes/py4xs/meta.yaml
> +    - mrakitin
```suggestion
    - lyang11973
    - mrakitin
```

2021-07-16 18:00 UTC, mrakitin commented on recipes/lixtools/meta.yaml
> +    - python -c "import os, pkg_resources; assert os.path.isfile(pkg_resources.resource_filename("lixtools", "template_report.ipynb"))"
The double quotes inside should be replaced with single quotes or escaped to properly format the command.

```suggestion
    - python -c "import os, pkg_resources; assert os.path.isfile(pkg_resources.resource_filename('lixtools', 'plate_label_template.html'))"
    - python -c "import os, pkg_resources; assert os.path.isfile(pkg_resources.resource_filename('lixtools', 'template_report.ipynb'))"
```

2021-07-18 17:09 UTC, mrakitin approved these changes
Looks good to me!

@conda-forge/staged-recipes, I agree to be a maintainer of these feedstocks/packages.

2021-07-18 22:22 UTC, dopplershift requested changes
@lyang11973 are you ok with being listed as a maintainer for both of these recipes?

2021-07-18 22:22 UTC, dopplershift commented on recipes/lixtools/meta.yaml
> +    - lixtools
Can you add some better import tests (`__init__` only sets the version)? I see a whole bunch of other imports in other modules that aren't listed above, like dask and scipy.

2021-07-18 22:22 UTC, dopplershift commented on recipes/lixtools/meta.yaml
> +    - matplotlib
```suggestion
    - matplotlib-base
```

2021-07-18 22:22 UTC, dopplershift commented on recipes/py4xs/meta.yaml
> +    - py4xs
Same here, `__init__` does nothing so importing some other modules would be a much better test that things are right here.

2021-07-18 22:22 UTC, dopplershift commented on recipes/py4xs/meta.yaml
> +    - matplotlib
```suggestion
    - matplotlib-base
```

2021-07-18 22:53 UTC, lyang11973 commented
Not sure what I need to do. But sure, I agree to be a maintainer.

On Fri, Jul 16, 2021 at 10:43 AM Maksim Rakitin ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Looks good overall, I added a comment on how to solve the Windows tests
> that are currently excluded.
> ------------------------------
>
> In recipes/lixtools/meta.yaml
> <https://github.com/conda-forge/staged-recipes/pull/15648#discussion_r671308522>
> :
>
> > +    - python >=3.6
>
> +    - matplotlib
>
> +    - numpy
>
> +    - openpyxl >=3
>
> +    - pandas
>
> +    - pillow
>
> +    - py4xs
>
> +    - python-barcode
>
> +    - qrcode
>
> +
>
> +test:
>
> +  imports:
>
> +    - lixtools
>
> +  commands:  # [not win]
>
> +    - python -c 'import os, pkg_resources; assert os.path.isfile(pkg_resources.resource_filename("lixtools", "plate_label_template.html"))'  # [not win]
>
> +    - python -c 'import os, pkg_resources; assert os.path.isfile(pkg_resources.resource_filename("lixtools", "template_report.ipynb"))'  # [not win]
>
>
> I am against excluding tests for Windows. Could you try to fix it instead?
> On Windows CLI, single quotes are not accepted. Please use double-quotes.
> An easy way to test it on your Windows machine is to install the package
> locally and try this python -c ... string.
> ------------------------------
>
> In recipes/lixtools/meta.yaml
> <https://github.com/conda-forge/staged-recipes/pull/15648#discussion_r671309619>
> :
>
> > +test:
>
> +  imports:
>
> +    - lixtools
>
> +  commands:  # [not win]
>
> +    - python -c 'import os, pkg_resources; assert os.path.isfile(pkg_resources.resource_filename("lixtools", "plate_label_template.html"))'  # [not win]
>
> +    - python -c 'import os, pkg_resources; assert os.path.isfile(pkg_resources.resource_filename("lixtools", "template_report.ipynb"))'  # [not win]
>
> +
>
> +about:
>
> +  home: https://github.com/NSLS-II-LIX/lixtools
>
> +  license: BSD-3-Clause
>
> +  license_file: LICENSE
>
> +  summary: Software tools for data collection/processing at NSLS-II LiX
>
> +
>
> +extra:
>
> +  recipe-maintainers:
>
> +    - mrakitin
>
>
> Adding @lyang11973 <https://github.com/lyang11973> as a core developer of
> the package. Lin, do you agree to be a maintainer of this conda-forge
> feedstock?
> ⬇️ Suggested change
>
> -    - mrakitin
>
> +    - lyang11973
>
> +    - mrakitin
>
>
> ------------------------------
>
> In recipes/py4xs/meta.yaml
> <https://github.com/conda-forge/staged-recipes/pull/15648#discussion_r671309984>
> :
>
> > +    - scipy
>
> +
>
> +test:
>
> +  imports:
>
> +    - py4xs
>
> +
>
> +about:
>
> +  home: https://pypi.org/project/py4xs
>
> +  license: MIT
>
> +  license_file: LICENSE.txt
>
> +  summary: py4xs - a python package for processing x-ray scattering data
>
> +  dev_url: https://github.com/NSLS-II-LIX/py4xs
>
> +
>
> +extra:
>
> +  recipe-maintainers:
>
> +    - mrakitin
>
>
> ⬇️ Suggested change
>
> -    - mrakitin
>
> +    - lyang11973
>
> +    - mrakitin
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/conda-forge/staged-recipes/pull/15648#pullrequestreview-708464313>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFNJXD4CFOGVZJKGOTI3Z33TYBARBANCNFSM5AO3CE6Q>
> .
>

2021-07-19 17:53 UTC, dopplershift commented
@lyang11973 You'll receive GitHub notifications about issues and PRs on the repository that holds the recipe (the information that's used to build a package for lixtools on conda-forge).

2021-07-20 01:06 UTC, dopplershift approved these changes

2021-07-20 01:06 UTC, merged

2021-07-25 18:45 UTC, mrakitin commented
@dopplershift, do you know why the final checks before merging did not run the tests? The resulting feedstock with more tests (added here via https://github.com/conda-forge/staged-recipes/pull/15648/commits/5b2c036357baba49c73af4b2ab4ad29a96158d84) uncovered missing dependencies (in particular, `opentrons`, that I am working on within https://github.com/conda-forge/staged-recipes/pull/15705).

2021-07-25 23:45 UTC, dopplershift commented
No, and 🐑 that I missed it.