adding rixs recipe
conda-forge/staged-recipes pull request #15670
Opened 2021-07-18 06:03 UTC by kbeeperez

implements: https://github.com/nsls-ii-forge/rixs-feedstock

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-07-18 06:04 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/rixs```) and found it was in an excellent condition.

2021-07-18 06:21 UTC, kbeeperez commented
Attn @mrakitin

2021-07-20 06:11 UTC, kbeeperez commented
@conda-forge/staged-recipes should be ready to merge now.

2021-07-20 06:12 UTC, kbeeperez commented
Attn @mrakitin is there anything that needs changing?

2021-07-20 17:36 UTC, dopplershift requested changes
@mrakitin are you ok being listed as a maintainer?

2021-07-20 17:36 UTC, dopplershift commented on recipes/rixs/meta.yaml
> +    - matplotlib
```suggestion
    - matplotlib-base
```

2021-07-20 19:39 UTC, dopplershift approved these changes

2021-07-21 19:35 UTC, mrakitin approved these changes
Looks good to me, I added a couple of "cosmetic" suggestions.

@conda-forge/staged-recipes, I agree to maintain this package.

2021-07-21 19:35 UTC, mrakitin commented on recipes/rixs/meta.yaml
> +  name: '{{ name|lower }}'
```suggestion
  name: {{ name|lower }}
```

2021-07-21 19:35 UTC, mrakitin commented on recipes/rixs/meta.yaml
> +  version: '{{ version }}'
```suggestion
  version: {{ version }}
```

2021-07-21 19:35 UTC, mrakitin commented on recipes/rixs/meta.yaml
> +  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
```suggestion
  script: {{ PYTHON }} -m pip install . --no-deps -vv
```

2021-07-23 15:24 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/rixs```, ```recipes/sixtools```) and found it was in an excellent condition.

2021-07-23 15:49 UTC, mrakitin commented on recipes/sixtools/meta.yaml
> +  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
Making the install comamnd consitent:
```suggestion
  script: {{ PYTHON }} -m pip install . --no-deps -vv
```

2021-07-23 15:53 UTC, mrakitin commented
As another recipe was added here, I agree to maintain both `sixtools` and `rixs`.

2021-07-23 19:11 UTC, dopplershift approved these changes

2021-07-23 19:11 UTC, merged