added jazz-hands package
conda-forge/staged-recipes pull request #15681
Opened 2021-07-19 16:48 UTC by athulvis

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-07-19 16:48 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/jazz-hands```) and found it was in an excellent condition.

2021-07-19 18:00 UTC, dopplershift requested changes
The recipe's in pretty good shape, just a few minor things. @tzdwi @theand9 @gjgilbert @astroluv can you confirm that you are each willing to be a maintainer for this recipe?

2021-07-19 18:01 UTC, dopplershift commented
@athulvis You can just commit the necessary changes to your local branch and push them up, no need to make a new PR.

2021-07-19 18:44 UTC, tzdwi commented
> The recipe's in pretty good shape, just a few minor things. @tzdwi @theand9 @gjgilbert @astroluv can you confirm that you are each willing to be a maintainer for this recipe?

Yep, I can be a maintainer!

2021-07-19 19:33 UTC, theand9 commented
> The recipe's in pretty good shape, just a few minor things. @tzdwi @theand9 @gjgilbert @astroluv can you confirm that you are each willing to be a maintainer for this recipe?

Yes, I would love to be a maintainer! Thanks.

2021-07-19 20:06 UTC, gjgilbert commented
> The recipe's in pretty good shape, just a few minor things. @tzdwi @theand9 @gjgilbert @astroluv can you confirm that you are each willing to be a maintainer for this recipe?

Yes, I'm happy to

2021-07-20 06:01 UTC, athulvis commented on recipes/jazz-hands/meta.yaml
> +  skip: True  # [py<36]
@dopplershift Adding `noarch: python` shows this lint 
```
. has some lint:
  noarch: python recipes are required to have a lower bound on the python version.
 Typically this means putting `python >=3.6` in **both** `host` and `run` but you should 
check upstream for the package's Python compatibility.
```
How can I avoid this?

2021-07-20 06:09 UTC, athulvis commented on recipes/jazz-hands/meta.yaml
> +  skip: True  # [py<36]
Sorry. Fixed it. Added version for python in requirements.

2021-07-20 07:25 UTC, athulvis commented
@dopplershift I have updated the recipe with the suggested changes. Thank you

2021-07-20 09:02 UTC, athulvis commented
@dopplershift  I have updated the suggested changes. Please have a look. Sorry for my PR deletions.

2021-07-20 17:56 UTC, dopplershift approved these changes
Looks good. Just need confirmation from @astroluv that they are willing to be a maintainer.

2021-07-20 18:32 UTC, athulvis commented
@dopplershift Thank you. I have a doubt. Can I add other maintainers later , if needed? Can I invoke new PR for that if the current one is appproved?

2021-07-20 19:43 UTC, dopplershift commented
Yes, you can always add new maintainers once the feedstock has been created. There's even a [bot command](https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user) to make the PR for you without triggering a build.

2021-07-21 15:14 UTC, astroluv commented
Yes, I can be a maintainer!

Sorry for the delay everyone!

Sincerely,

Teresa

On Tue, Jul 20, 2021 at 3:44 PM Ryan May ***@***.***> wrote:

> Yes, you can always add new maintainers once the feedstock has been
> created. There's even a bot command
> <https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user>
> to make the PR for you without triggering a build.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/conda-forge/staged-recipes/pull/15681#issuecomment-883648053>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI25OTICSR7FUFGZI7ZMNDTTYXGYPANCNFSM5AUCL3AQ>
> .
>

2021-07-21 18:27 UTC, merged

2021-07-22 03:50 UTC, athulvis commented
Thank you!!!