Added modelbase package
conda-forge/staged-recipes pull request #15746
Opened 2021-07-27 06:37 UTC by marvinvanaalst

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-07-27 06:37 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/modelbase```) and found some lint.

Here's what I've got...


For **recipes/modelbase**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [13]

For **recipes/modelbase**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2021-07-27 06:40 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/modelbase```) and found some lint.

Here's what I've got...


For **recipes/modelbase**:

 * about/license_family 'GPL-2.0-or-later' not allowed. Allowed families
are AGPL, APACHE, BSD, CC, GPL, GPL2, GPL3, LGPL, MIT, MOZILLA, NONE,
OTHER, PROPRIETARY, PSF, and PUBLIC-DOMAIN.

For **recipes/modelbase**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2021-07-27 06:44 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/modelbase```) and found it was in an excellent condition.

2021-07-27 20:09 UTC, dopplershift requested changes
Generally in pretty good shape, just mainly a few tweaks to the dependencies.

2021-07-27 20:09 UTC, dopplershift commented on recipes/modelbase/meta.yaml
> +  license: GPL-2.0-or-later
```suggestion
  license: GPL-3.0-or-later
```

2021-07-27 20:09 UTC, dopplershift commented on recipes/modelbase/meta.yaml
> +  skip: True  # [py2k or py<37]
This looks like pure Python, so it should be able to be noarch Python:
```suggestion
  number: 0
  noarch: python
```

2021-07-27 20:09 UTC, dopplershift commented on recipes/modelbase/meta.yaml
> +    - python {{ python }}
```suggestion
    - python >=3.7
```

2021-07-27 20:09 UTC, dopplershift commented on recipes/modelbase/meta.yaml
> +    - python {{ python }}
```suggestion
    - python >=3.7
```

2021-07-27 20:09 UTC, dopplershift commented on recipes/modelbase/meta.yaml
> +    - {{ pin_compatible('numpy') }}
You only need the `pin_compatible` if you're building against NumPy's C-API.
```suggestion
    - numpy
```

2021-07-27 20:09 UTC, dopplershift commented on recipes/modelbase/meta.yaml
> +    - matplotlib
Unless you need a PyQt-based GUI, better to only depend on `matplotlib-base`:
```suggestion
    - matplotlib-base
```

2021-07-28 06:19 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/modelbase```) and found some lint.

Here's what I've got...


For **recipes/modelbase**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2021-07-28 06:20 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/modelbase```) and found it was in an excellent condition.

2021-07-28 06:36 UTC, marvinvanaalst commented
Cheers for looking over it so quickly. So far the whole thing has been a very pleasant experience, thanks for the nice work you guys did! :smile:

2021-08-02 04:34 UTC, dopplershift approved these changes

2021-08-02 04:35 UTC, merged