Collection
conda-forge/staged-recipes pull request #15764
Opened 2021-07-28 19:37 UTC by kbeeperez

implements: https://github.com/nsls-ii-forge/collection-feedstock
https://github.com/nsls-ii-forge/nsls2-analysis-feedstock
https://github.com/nsls-ii-forge/analysis-feedstock

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-07-28 19:38 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/collection```, ```recipes/nsls2-collection```) and found it was in an excellent condition.

2021-07-29 03:30 UTC, mrakitin requested changes
@kbeeperez, it feels a bit wrong.

We need the following 2 recipes:
- `nsls2-analysis` that would contain the combination of `run` requirements from these feedstocks' recipes and won't have the `analysis` dependency:
  - https://github.com/nsls-ii-forge/analysis-feedstock
  - https://github.com/nsls-ii-forge/nsls2-analysis-feedstock
- `nsls2-collection` that would be a copy of the recipe from https://github.com/nsls-ii-forge/collection-feedstock, and will depend on the `nsls2-analysis` metapackage from above.

2021-07-29 21:46 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/nsls2-analysis```, ```recipes/nsls2-collection```) and found it was in an excellent condition.

2021-08-03 18:13 UTC, mrakitin requested changes
@kbeeperez, here are a few suggestions after my review.

We need `xraylarch` (https://github.com/conda-forge/staged-recipes/pull/15706) to exist before we can run a new build. The other packages should already be in conda-forge.

2021-08-03 18:13 UTC, mrakitin commented on recipes/nsls2-analysis/meta.yaml
> +    - dask ={{ dask_pin }}
The `dask_pin` variable is not defined. That should be added on the top of the file next to other Jinja2 vars.

2021-08-03 18:13 UTC, mrakitin commented on recipes/nsls2-analysis/meta.yaml
> +    - edrixs
```suggestion
    # - edrixs
```

2021-08-03 18:13 UTC, mrakitin commented on recipes/nsls2-analysis/meta.yaml
> +    - intel-openmp ={{ mkl_pin }}
`mkl_pin` should be defined too.

2021-08-03 18:13 UTC, mrakitin commented on recipes/nsls2-analysis/meta.yaml
> +    - nsls2forge-utils
```suggestion
```

2021-08-03 18:13 UTC, mrakitin commented on recipes/nsls2-analysis/meta.yaml
> +    - check-results -t version -p ophyd       -e 1.6
```suggestion
```

2021-08-03 18:13 UTC, mrakitin commented on recipes/nsls2-analysis/meta.yaml
> +    - python -c "import pandas; print(pandas.read_excel('test.xls'))"
The `test.xlsx` and `test.xls` files are missing. Please add them to the `recipe` dirs from the nsls2forge feedstocks.

2021-08-03 18:13 UTC, mrakitin commented on recipes/nsls2-collection/meta.yaml
> +    - nsls2-analysis ==2021C2.0=*_1
This is to pick up the build number `0` for the `nsls2-analysis` recipe above.
```suggestion
    - nsls2-analysis ==2021C2.0=*_0
```

2021-08-03 18:13 UTC, mrakitin commented on recipes/nsls2-collection/meta.yaml
> +    - nslsii >=0.1.1
```suggestion
    - nslsii >=0.1.3
```

2021-08-03 18:13 UTC, mrakitin commented on recipes/nsls2-collection/meta.yaml
> +    - chxtools
This is already a dependency of `nsls2-analysis`.
```suggestion
```

2021-08-03 18:13 UTC, mrakitin commented on recipes/nsls2-collection/meta.yaml
> +    - hxntools >=0.5.1
This is already a dependency of `nsls2-analysis`.
```suggestion
```

2021-08-03 18:13 UTC, mrakitin commented on recipes/nsls2-collection/meta.yaml
> +    - sixtools
This is already a dependency of `nsls2-analysis`.
```suggestion
```

2021-08-03 18:13 UTC, mrakitin commented on recipes/nsls2-collection/meta.yaml
> +    - nsls2forge-utils
```suggestion
```

2021-08-03 18:13 UTC, mrakitin commented on recipes/nsls2-collection/meta.yaml
> +    - check-results -t version -p ophyd       -e 1.6
```suggestion
```

2021-08-03 18:13 UTC, mrakitin commented on recipes/nsls2-collection/meta.yaml
> +    - python -c "import pandas; print(pandas.read_excel('test.xls'))"
Please add these missing files for tests.

2021-08-03 18:13 UTC, mrakitin commented on recipes/nsls2-collection/yum_requirements.txt
> +mesa-libGL
The same file should be created for the `nsls2-analysis` recipe.

2021-08-03 18:49 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/csxtools```, ```recipes/nsls2-analysis```, ```recipes/nsls2-collection```) and found some lint.

Here's what I've got...


For **recipes/csxtools**:

 * Feedstock with the same name exists in conda-forge.

2021-08-03 18:50 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/nsls2-analysis```, ```recipes/nsls2-collection```) and found it was in an excellent condition.

2021-08-04 17:13 UTC, mrakitin reviewed
A couple of work-around suggestions before the awaited PRs are merged.

2021-08-04 17:13 UTC, mrakitin commented on recipes/nsls2-analysis/meta.yaml
> +    - suitcase-mongo >=0.3.0
```suggestion
    - suitcase-mongo  # >=0.3.0 # remove the pin until https://github.com/conda-forge/suitcase-mongo-feedstock/pull/5 is merged
```

2021-08-04 17:13 UTC, mrakitin commented on recipes/nsls2-analysis/meta.yaml
> +    - xraylarch
```suggestion
    # - xraylarch  # commented out as https://github.com/conda-forge/staged-recipes/pull/15706 is not merged yet
```

2021-08-04 18:24 UTC, mrakitin reviewed
A few suggestions to relax the hard pins that don't exist for Python 3.7+.

2021-08-04 18:24 UTC, mrakitin commented on recipes/nsls2-analysis/meta.yaml
> + #  - edrixs
```suggestion
    # - edrixs
```

2021-08-04 18:24 UTC, mrakitin commented on recipes/nsls2-analysis/meta.yaml
> +    - ipympl ==0.1.1
```suggestion
    - ipympl >=0.1.1
```

2021-08-04 18:24 UTC, mrakitin commented on recipes/nsls2-analysis/meta.yaml
> +    - ipywidgets ==7.2.1
```suggestion
    - ipywidgets >=7.2.1
```

2021-08-04 20:50 UTC, mrakitin commented
I ran a build with `mamba` locally, and it uncovered a missing dependency of `pyxdameraulevenshtein` for Python 3.7+:
![image](https://user-images.githubusercontent.com/13209176/128252952-fbdd9c3c-f434-4dab-941a-c12a605e4a2a.png)


I submitted a PR to get the missing versions via https://github.com/conda-forge/pyxdameraulevenshtein-feedstock/pull/25 (we did it for our [`nsls2forge` feedstock](https://github.com/nsls-ii-forge/pyxdameraulevenshtein-feedstock/blob/587b50ff408e877cd2fdbb94d6dc1e514aa22a31/recipe/meta.yaml#L16) that way too, and it worked fine).

2021-08-04 20:57 UTC, mrakitin reviewed
A couple of suggestions to have a successful build. Let's exclude `xpdan`/`xpdacq` for now - they can be added to the feedstock once the blocker PR is merged.

2021-08-04 20:57 UTC, mrakitin commented on recipes/nsls2-analysis/meta.yaml
> +    - xpdan
```suggestion
    # - xpdan  # Blocker: https://github.com/conda-forge/pyxdameraulevenshtein-feedstock/pull/25
```

2021-08-04 20:57 UTC, mrakitin commented on recipes/nsls2-collection/meta.yaml
> +    - xpdacq
```suggestion
    # - xpdacq  # Blocker: https://github.com/conda-forge/pyxdameraulevenshtein-feedstock/pull/25
```

2021-08-04 21:04 UTC, mrakitin commented
@dopplershift, we have a couple of blockers, but we commented out the corresponding dependencies for now, that can be added later in the feedstocks. Are you OK with that approach?

Blockers:
- https://github.com/conda-forge/pyxdameraulevenshtein-feedstock/pull/25
- https://github.com/conda-forge/staged-recipes/pull/15706

2021-08-05 15:21 UTC, mrakitin requested changes
Pending https://github.com/conda-forge/xray-vision-feedstock/pull/14. Once merged, my suggestions can be committed to trigger a new build with the updated dependencies.

2021-08-05 15:21 UTC, mrakitin commented on recipes/nsls2-analysis/meta.yaml
> +    # - xpdan  # Blocker: https://github.com/conda-forge/pyxdameraulevenshtein-feedstock/pull/25
The https://github.com/conda-forge/pyxdameraulevenshtein-feedstock/pull/25 is merged now, the dependency can be added back.
```suggestion
    - xpdan
```

2021-08-05 15:21 UTC, mrakitin commented on recipes/nsls2-analysis/LICENSE
> +THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
Could you please use a better-formatted license from https://github.com/bluesky/bluesky/blob/master/LICENSE and change the year to `2021` for both `nsls2-analysis` and `nsls2-collection` recipes?

2021-08-05 15:21 UTC, mrakitin commented on recipes/nsls2-analysis/meta.yaml
> +    # - xraylarch  # commented out as https://github.com/conda-forge/staged-recipes/pull/15706 is not merged yet
Suggesting adding `xrt` to the analysis metapackage, as we may need it along with `srwpy` and other simulation packages.
```suggestion
    # - xraylarch  # commented out as https://github.com/conda-forge/staged-recipes/pull/15706 is not merged yet
    - xrt
```

2021-08-05 15:21 UTC, mrakitin commented on recipes/nsls2-analysis/meta.yaml
> +    - scipy
One more simulation package:
```suggestion
    - scipy
    - shadow3
```

2021-08-05 15:21 UTC, mrakitin commented on recipes/nsls2-analysis/meta.yaml
> +    - pillow
```suggestion
    - pillow
    - pocl  # needed by pyopencl, used by the `xrt` package
```

2021-08-05 15:21 UTC, mrakitin commented on recipes/nsls2-collection/meta.yaml
> +    # - xpdacq  # Blocker: https://github.com/conda-forge/pyxdameraulevenshtein-feedstock/pull/25
```suggestion
    - xpdacq
```

2021-08-05 18:10 UTC, mrakitin commented
@kbeeperez, the `xray-vision` with the fixed dependencies (done via https://github.com/conda-forge/xray-vision-feedstock/pull/14) is available now. Please commit my suggestions.

2021-08-05 21:18 UTC, mrakitin commented on recipes/nsls2-collection/meta.yaml
> +    - srwlpy  # [linux]
This import test was intended to be run against the `srw` package coming from https://github.com/nsls-ii-forge/srw-feedstock/, which we don't package in conda-forge, where `srwpy` (see below) should be the right one.
```suggestion
```

2021-08-05 23:39 UTC, mrakitin commented
Success!

@conda-forge/staged-recipes, I agree to be a maintainer of these feedstocks. Could we please have them metged soon? Thank you!

2021-08-06 15:50 UTC, mrakitin commented
@dopplershift, @ocefpaf, would you be able to review/merge it today? This PR is one of the final ones that NSLS-II needs for the deployment (besides the awaiting https://github.com/conda-forge/staged-recipes/pull/15706).

Thanks a lot!

2021-08-06 17:16 UTC, mrakitin commented on recipes/nsls2-collection/meta.yaml
> +    - pexpect
@kbeeperez, let's add one more package from our LCLS friends (https://github.com/slaclab/pydm).
```suggestion
    - pexpect
    - pydm
```

2021-08-08 21:54 UTC, leofang reviewed
Is it possible to move *.xls and *.xlsx to somewhere else (say a GH repo) and download them at the test stage? This way we can avoid making them be a part of `staged-recipes`'s git history.

2021-08-08 23:56 UTC, mrakitin commented
Hi @leofang! That's a reasonable concern. They can be added at a later time into the feedstock. The files are already in https://github.com/nsls-ii-forge/collection-feedstock/tree/master/recipe, so they can be taken from there. However, we have to do "git surgery" on the commits to this repo to properly exclude. Or squash-merge would take care of it. Would it work that way?

2021-08-09 00:05 UTC, leofang commented
My guess is we can just squash and merge, but let's wait for someone from @conda-forge/staged-recipes to decide 😄 Maybe they'd just be ok with it.

2022-04-18 19:10 UTC, leofang commented
Hi @carterbox any chance you have some bandwidth to help our NSLS-II friends here? 🙂

2022-04-19 00:22 UTC, mrakitin commented
We currently have a workaround using the environment .yml files, so these metapackages may not be needed at this time.

2022-04-19 17:12 UTC, carterbox requested changes
Is there a reason why these meta packages cannot be `noarch`? All conda-forge packages that can be noarch must be marked as `noarch` because it prevents unnecessary builds/migrations.

2022-04-19 17:12 UTC, carterbox commented on recipes/nsls2-analysis/meta.yaml
> +    - python
Since this is a metapackage, it shouldn't have a host/build section?

2022-04-19 17:12 UTC, carterbox commented on recipes/nsls2-collection/meta.yaml
> +    - python
No host/build for metapackages?

2022-09-20 02:40 UTC, mrakitin commented
I don't think it's needed. We have a way to specify all those packages via an environment file. Can be closed.

2023-03-29 00:21 UTC, closed without merging