[recipe][pycppad] add new recipe for pycppad
conda-forge/staged-recipes pull request #15944
Opened 2021-08-19 15:37 UTC by proyan

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-08-19 15:37 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pycppad```) and found some lint.

Here's what I've got...


For **recipes/pycppad**:

 * There are too few lines.  There should be one empty line at the end of the file.

2021-08-19 15:39 UTC, proyan commented
Since this file provides python bindings written in C++ using boost python, @conda-forge/help-c-cpp or @conda-forge/help-python-c could you please provide a review. Thanks.

2021-08-19 15:42 UTC, proyan commented
cc: @jcarpent

2021-08-19 19:15 UTC, xhochy commented on recipes/pycppad/meta.yaml
> +  skip: true  # [win and vc<14]
```suggestion
```

2021-08-19 19:15 UTC, xhochy commented on recipes/pycppad/meta.yaml
> +    - cmake
All point to the same
```suggestion
    - {{ compiler('cxx') }}
    - cmake
```

2021-08-19 19:15 UTC, xhochy commented on recipes/pycppad/meta.yaml
> +    - boost
Is already part of run
```suggestion
```

2021-08-20 13:19 UTC, jcarpent commented
> cc: @jcarpent

I agree to be a maintainer of this package.

2021-08-20 13:25 UTC, jcarpent requested changes
I made some suggestions which should help the linter and make the project compile

2021-08-20 13:25 UTC, jcarpent commented on recipes/pycppad/meta.yaml
> +    - numpy                                  # [build_platform != target_platform]
```suggestion
```

2021-08-20 13:25 UTC, jcarpent commented on recipes/pycppad/meta.yaml
> +    - numpy
```suggestion
```

2021-08-20 13:25 UTC, jcarpent commented on recipes/pycppad/meta.yaml
> +    - {{ pin_compatible('numpy') }}
```suggestion
```

2021-08-20 13:25 UTC, jcarpent commented on recipes/pycppad/meta.yaml
> +    - cppad
```suggestion
    - cppad
    - eigenpy
```

2021-08-20 13:25 UTC, jcarpent commented on recipes/pycppad/meta.yaml
> +    - cppad
```suggestion
    - cppad
    - eigenpy
```

2021-08-20 13:25 UTC, jcarpent commented on recipes/pycppad/meta.yaml
> +
```suggestion
    
    
```

2021-08-20 13:25 UTC, jcarpent commented on recipes/pycppad/bld.bat
> +set PKG_CONFIG_PATH=%LIBRARY_PREFIX%\share\pkgconfig
```suggestion
```

2021-08-20 13:25 UTC, jcarpent commented on recipes/pycppad/meta.yaml
> +  number: 0
```suggestion
  number: 0
  skip: true  # [win]
```

2021-08-20 13:27 UTC, jcarpent commented on recipes/pycppad/bld.bat
> +set PKG_CONFIG_PATH=%LIBRARY_PREFIX%\share\pkgconfig
useless

2021-08-20 16:26 UTC, jcarpent commented on recipes/pycppad/meta.yaml
> +
```suggestion
```

2021-08-20 16:27 UTC, jcarpent commented on recipes/pycppad/meta.yaml
> +
```suggestion
```

2021-08-20 16:35 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pycppad```) and found it was in an excellent condition.

2021-08-20 16:45 UTC, proyan commented
@xhochy The linting is passing now :)

2021-08-21 06:29 UTC, xhochy commented
The build is failing though: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=365986&view=results

2021-08-21 14:29 UTC, proyan commented
I've made a new release that should pass. Could you please launch the build again?

2021-08-21 14:31 UTC, jcarpent commented
@proyan you need to change the version and sha 256 to account for the new release.

2021-08-21 14:31 UTC, proyan commented
Thanks for the ping

2021-08-21 14:40 UTC, jcarpent commented
Currently, there are some troubles to sync the CI with GitHub on conda builds.
See https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=366252&view=results for the current status

2021-08-21 15:23 UTC, jcarpent commented
Good news. The build is passing.
@conda-forge/help-c-cpp @conda-forge/help-python this PR is ready for being merged.

2021-08-22 05:29 UTC, merged