Add triad
conda-forge/staged-recipes pull request #16044
Opened 2021-09-01 09:52 UTC by rdmolony

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

---

@kvnkho I made a stab at getting triad ready for conda-forge, are you happy to be listed as a maintainer?

2021-09-01 09:52 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/triad```) and found some lint.

Here's what I've got...


For **recipes/triad**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2021-09-01 09:54 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/triad```) and found some lint.

Here's what I've got...


For **recipes/triad**:

 * ``requirements: host: python >= 3.6`` should not contain a space between relational operator and the version, i.e. ``python >=3.6``
 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2021-09-01 09:55 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/triad```) and found some lint.

Here's what I've got...


For **recipes/triad**:

 * ``requirements: host: python>=3.6`` must contain a space between the name and the pin, i.e. ``python >=3.6``
 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2021-09-01 09:56 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/triad```) and found some lint.

Here's what I've got...


For **recipes/triad**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2021-09-01 09:57 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/triad```) and found it was in an excellent condition.

2021-09-01 09:58 UTC, rdmolony commented
only took 4 goes to get the python version specified :)

2021-09-01 09:59 UTC, rdmolony commented
Ref fugue-project/triad#70

2021-09-01 16:42 UTC, dopplershift requested changes

2021-09-01 16:42 UTC, dopplershift commented on recipes/triad/meta.yaml
> +test:
Would be good to add an import test:
```suggestion
test:
  imports:
    - triad
```

2021-09-01 16:42 UTC, dopplershift commented on recipes/triad/meta.yaml
> +# when copying and pasting from another recipe, but not really needed.
Go ahead and remove these comments from the template:
```suggestion
```

2021-09-01 16:42 UTC, dopplershift commented on recipes/triad/meta.yaml
> +  # The remaining entries in this section are optional, but recommended.
And remove this too:
```suggestion
```

2021-09-01 16:42 UTC, dopplershift commented on recipes/triad/meta.yaml
> +    - kvnkho
Why aren't you listing yourself here?

2021-09-01 18:01 UTC, rdmolony commented
@goodwanghan I added you in as a maintainer, I hope this is okay with you?

2021-09-01 18:04 UTC, rdmolony commented
thanks for your help @dopplershift

2021-09-01 18:14 UTC, goodwanghan commented
This is great! Thank you!

2021-09-01 18:36 UTC, rdmolony commented
@conda-forge-admin ready for review! Thanks for all your help @dopplershift!

2021-09-02 18:14 UTC, rdmolony commented
@conda-forge-admin ready for review!

2021-09-06 19:42 UTC, rdmolony commented
@conda-forge/help-python would you mind having a look at this PR?  I have made the suggested changes but I'm not sure if they have registered

2021-09-07 06:43 UTC, merged