Add gelidum
conda-forge/staged-recipes pull request #16112
Opened 2021-09-08 16:48 UTC by johnomotani

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-09-08 16:49 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/gelidum```) and found some lint.

Here's what I've got...


For **recipes/gelidum**:

 * ``requirements: run: python >= 3.7.0`` should not contain a space between relational operator and the version, i.e. ``python >=3.7.0``

2021-09-08 16:49 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/gelidum```) and found it was in an excellent condition.

2021-09-09 07:43 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/gelidum```) and found some lint.

Here's what I've got...


For **recipes/gelidum**:

 * The test section contained an unexpected subsection name. import is not a valid subsection name.

2021-09-09 07:47 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/gelidum```) and found it was in an excellent condition.

2021-09-09 08:02 UTC, johnomotani commented
@diegojromerolopez could you please comment here to confirm you're happy to be a maintainer for this feedstock?

2021-09-09 16:23 UTC, diegojromerolopez commented
Yeah, I'm happy @johnomotani.

2021-09-09 16:26 UTC, johnomotani commented
Thanks @diegojromerolopez!

@conda-forge/help-python I think this PR is ready for review merge. Thanks!

2021-09-09 19:00 UTC, dopplershift requested changes
Recipe is in great shape! Just a couple minor nits to fix and this can go in.

2021-09-09 19:00 UTC, dopplershift commented on recipes/gelidum/meta.yaml
> +    - python
Need a version requirement here:
```suggestion
    - python >=3.7
```

2021-09-09 19:00 UTC, dopplershift commented on recipes/gelidum/meta.yaml
> +    - python >=3.7.0
Since we need to change above, we usually just use:
```suggestion
    - python >=3.7
```

2021-09-09 20:52 UTC, johnomotani commented
Thanks @dopplershift, fixed now!

2021-09-10 16:12 UTC, dopplershift approved these changes

2021-09-10 16:12 UTC, merged