Add recipe for pyinaturalist-convert
conda-forge/staged-recipes pull request #16138
Opened 2021-09-11 00:31 UTC by JWCook

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-09-11 00:31 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyinaturalist-convert```) and found it was in an excellent condition.

2021-09-11 01:19 UTC, JWCook commented
@conda-forge/help-python
Ready for review!

2021-09-13 18:55 UTC, dopplershift requested changes
Just need to fix the typos in the URLs, and might as well remove the templating of the hash while you're there. Otherwise, this is good to go with minor tweaks.

2021-09-13 18:55 UTC, dopplershift commented on recipes/pyinaturalist-convert/meta.yaml
> +  home: https://github.com/JWCook/pyinaturalist_convert
Typo in url:
```suggestion
  home: https://github.com/JWCook/pyinaturalist-convert
```

2021-09-13 18:55 UTC, dopplershift commented on recipes/pyinaturalist-convert/meta.yaml
> +  dev_url: https://github.com/JWCook/pyinaturalist_convert
Here too:
```suggestion
  dev_url: https://github.com/JWCook/pyinaturalist-convert
```

2021-09-13 18:55 UTC, dopplershift commented on recipes/pyinaturalist-convert/meta.yaml
> +  sha256: {{ hash_val }}
These days we usually just put the hash directly here rather than templating it.

2021-09-13 19:17 UTC, dopplershift approved these changes

2021-09-13 20:44 UTC, JWCook commented
Fixed! Thanks for reviewing. For some reason the OSX build has been stuck for almost 2 hours. Going to try restarting it.

2021-09-13 21:13 UTC, JWCook commented
@dopplershift There we go, it finished this time. Ready to merge.

2021-09-13 21:29 UTC, merged