Add enterprise-extensions package
conda-forge/staged-recipes pull request #16184
Opened 2021-09-15 20:07 UTC by Hazboun6

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-09-15 20:07 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/enterprise-extensions```) and found some lint.

Here's what I've got...


For **recipes/enterprise-extensions**:

 * The top level meta keys are in an unexpected order. Expecting ['package', 'source', 'build', 'requirements', 'test', 'about', 'extra'].
 * The recipe must have some tests.
 * The test section contained an unexpected subsection name. import is not a valid subsection name.
 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.
 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2021-09-15 20:08 UTC, Hazboun6 commented
@AaronDJohnson and @paulthebaker please comment to let the nice folks at `conda-forge` know you are willing to be maintainers!

2021-09-15 20:11 UTC, AaronDJohnson commented
I am willing to be a maintainer for this project 👍

2021-09-15 20:18 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/enterprise-extensions```) and found some lint.

Here's what I've got...


For **recipes/enterprise-extensions**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.
 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2021-09-15 20:19 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/enterprise-extensions```) and found some lint.

Here's what I've got...


For **recipes/enterprise-extensions**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2021-09-15 20:22 UTC, Hazboun6 commented
@AaronDJohnson any idea what went wrong here? Is there some incompatibility with `noarch` versus dictating a version of python?

2021-09-15 20:34 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/enterprise-extensions```) and found some lint.

Here's what I've got...


For **recipes/enterprise-extensions**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.

2021-09-15 20:38 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/enterprise-extensions```) and found it was in an excellent condition.

2021-09-15 21:05 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/enterprise-extensions```) and found some lint.

Here's what I've got...


For **recipes/enterprise-extensions**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [14]
 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.

2021-09-15 21:15 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/enterprise-extensions```) and found some lint.

Here's what I've got...


For **recipes/enterprise-extensions**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2021-09-15 21:36 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/enterprise-extensions```) and found it was in an excellent condition.

2021-09-16 00:18 UTC, paulthebaker commented
I'm willing to be a maintainer too!

2021-09-16 21:02 UTC, Hazboun6 commented
Okay, @conda-forge/help-python there was some serious linting shrapnel on this one, but I think we've figured out all of the subtleties. A few of the upstream packages for this are **not** available for windows, hence we needed to skip windows builds. I believe that precludes us from doing a `noarch` build, but if that is avoidable please let me know how I could change the recipe. Thanks!

2021-09-17 19:30 UTC, dopplershift commented
This looks like pure Python. What's the reason for skipping on Windows?

2021-09-17 19:41 UTC, Hazboun6 commented
Hi @dopplershift , the previous comment basically tells the story. The build was failing on windows because a few of the upstream packages are not available for windows. You are correct though the package itself is pure python. If there is a way around skipping windows then I'm happy to do it.

2021-09-17 19:49 UTC, Hazboun6 commented
This was the error I was getting in the Azure builds:
```conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {"pint-pulsar[version='>=0.8.2']", "libstempo[version='>=2.4.0']", "scikit-sparse[version='>=0.4.5']", "healpy[version='>=1.14.0']"```

2021-09-17 19:55 UTC, dopplershift commented
The way around is we say "Ok, it's failing due to missing dependencies. We'll just ignore the CI windows build since this is noarch." 😉 

So please go ahead and put this back to noarch Python since it drastically cuts down the builds.

2021-09-17 19:56 UTC, dopplershift commented
This nice thing is that if the other dependencies start working on windows, this package is instantly installable without any changes.

2021-09-20 18:17 UTC, Hazboun6 commented
> The way around is we say "Ok, it's failing due to missing dependencies. We'll just ignore the CI windows build since this is noarch." 😉

Love it. 

@dopplershift Alright! I've made the recipe `noarch`!

2021-09-24 17:19 UTC, Hazboun6 commented
@dopplershift Just pinging you again to remind you that I think this is ready to be merged.

2021-09-28 18:46 UTC, dopplershift requested changes
I found a couple dependency things, but otherwise this looks in great shape.

2021-09-28 18:46 UTC, dopplershift commented on recipes/enterprise-extensions/meta.yaml
> +
I don't think these are needed at build time (when running `setup.py`)?
```suggestion
```

2021-09-28 18:46 UTC, dopplershift commented on recipes/enterprise-extensions/meta.yaml
> +        - numdifftools
This is listed upstream in `requirements.txt`, but not in `install_requires` in `setup.py`, nor does it seem to be actually imported by the package?
```suggestion
```

2021-09-29 22:11 UTC, dopplershift approved these changes
Looks good. Ignoring windows failure due to missing deps.

2021-09-29 22:12 UTC, merged