Add python package muler to conda-forge starting at version 0.2.1
conda-forge/staged-recipes pull request #16223
Opened 2021-09-21 16:46 UTC by gully

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-09-21 16:47 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/muler```) and found it was in an excellent condition.

2021-09-24 17:06 UTC, gully commented
@conda-forge/help-python ready for review :smiley:   :pray:

2021-09-28 18:50 UTC, dopplershift requested changes

2021-09-28 18:50 UTC, dopplershift commented on recipes/muler/meta.yaml
> +# when copying and pasting from another recipe, but not really needed.
```suggestion
```

2021-09-28 18:50 UTC, dopplershift commented on recipes/muler/meta.yaml
> +    - python
```suggestion
    - python >=3.6
```

2021-09-28 18:50 UTC, dopplershift commented on recipes/muler/meta.yaml
> +
```suggestion
```

2021-09-28 18:50 UTC, dopplershift commented on recipes/muler/meta.yaml
> +    - matplotlib
Unless you need a PyQt-based GUI, better to depend on matplotlib-base:
```suggestion
    - matplotlib-base
```

2021-09-28 18:50 UTC, dopplershift commented on recipes/muler/meta.yaml
> +{% set version = "0.2.1" %}
Latest is now 0.2.4. It'd be good to go ahead and updated unless you specifically need 0.2.1.

2021-10-05 15:04 UTC, gully commented
Ok, I made all the changes, thank you so much @dopplershift (nice handle btw).  Awesome service here! 😄

2021-10-06 17:56 UTC, gully commented
@conda-forge/help-python ready for review

2021-10-06 17:59 UTC, merged

2021-10-06 18:01 UTC, synapticarbors commented
I opened a PR upstream to get the license file included in the source distribution. In subsequent releases of the package, please check to see if the manually packaged copy can be removed:

https://github.com/OttoStruve/muler/pull/59