add r-rbiom recipe
conda-forge/staged-recipes pull request #16256
Opened 2021-09-23 21:17 UTC by dansmith01

Generated with conda_r_skeleton_helper

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (LICENSE file included in this PR).
- [x] Source is from official source. (CRAN)
- [x] Package does not vendor other packages.
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe.
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-09-23 21:17 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-rbiom```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/r-rbiom**:

 * Jinja2 variable references are suggested to take a ``{{<one space><variable name><one space>}}`` form. See lines [50].

2021-09-23 22:04 UTC, dansmith01 commented
I agree to be listed as a maintainer.

2021-09-25 20:53 UTC, dansmith01 commented
@conda-forge-admin, please ping team
Ready for review!

2021-09-25 20:53 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/staged-recipes and so here I am doing that.

2021-09-26 18:29 UTC, cbrueffer requested changes

2021-09-26 18:29 UTC, cbrueffer commented on recipes/r-rbiom/meta.yaml
> +    - dansmith01
Please add `conda-forge/r` as maintainer.

2021-09-26 18:29 UTC, cbrueffer commented on recipes/r-rbiom/meta.yaml
> +  license: AGPL-3.0-or-later
```suggestion
  license: AGPL-3.0-only
```

2021-09-26 18:29 UTC, cbrueffer commented on recipes/r-rbiom/meta.yaml
> +  license_file: LICENSE
```suggestion
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3
```

2021-09-26 18:29 UTC, cbrueffer commented on recipes/r-rbiom/meta.yaml
> +  license_file: LICENSE
This makes it use the `r-base` installed license file; please remove the LICENSE file in this recipe.

2021-09-26 19:40 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-rbiom```) and found it was in an excellent condition.

2021-09-26 20:14 UTC, cbrueffer approved these changes

2021-09-26 20:14 UTC, merged

2021-09-26 20:14 UTC, cbrueffer commented
Looks good now, thanks!

2021-09-26 20:24 UTC, dansmith01 commented
@cbrueffer thanks for adding!