Add km3pipe
conda-forge/staged-recipes pull request #16286
Opened 2021-09-27 21:36 UTC by tamasgal

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-09-27 21:37 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/km3pipe```) and found it was in an excellent condition.

2021-09-27 21:37 UTC, tamasgal commented
Posting to confirm I am willing to be a maintainer of this package

2021-09-27 21:38 UTC, tamasgal commented
@conda-forge/staged-recipes ready for review!

2021-09-27 22:48 UTC, tamasgal commented
@conda-forge/staged-recipes ready for review!

2021-09-29 17:27 UTC, dopplershift requested changes
One minor tweak and this is ready.

2021-09-29 17:47 UTC, tamasgal commented on recipes/km3pipe/meta.yaml
> +    - numpy >=1.12
Ah, good catch, thanks! That's a left-over from the old times. I removed it...

2021-09-29 18:03 UTC, dopplershift commented
Are you planning on a new release with that change? Otherwise, we can merge with it put back in the recipe here for now.

2021-09-29 18:05 UTC, tamasgal commented
I am about to make a release and update this PR in a few minutes!

2021-09-29 19:50 UTC, tamasgal commented
Alright, it should be fine now, let's see if the CI agrees...

2021-09-29 22:10 UTC, dopplershift approved these changes

2021-09-29 22:10 UTC, merged