add nd2
conda-forge/staged-recipes pull request #16462
Opened 2021-10-10 13:42 UTC by tlambert03

nd2 (nikon elements) file reader

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-10-10 13:43 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/nd2```) and found it was in an excellent condition.

2021-10-11 16:01 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/nd2```) and found some lint.

Here's what I've got...


For **recipes/nd2**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [27]

2021-10-11 17:41 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/nd2```) and found it was in an excellent condition.

2021-10-11 18:19 UTC, tlambert03 commented
i _think_ this is ready for review @conda-forge/help-python, @conda-forge/help-python-c
In order to test the finished build on linux, I used centos7... the plain `linux_64` still fails but I think that's ok right?  input welcome.

2021-10-19 12:45 UTC, tlambert03 commented
bump @@conda-forge/help-python

2021-11-12 21:36 UTC, isuruf commented on recipes/nd2/meta.yaml
> +    - _openmp_mutex  # [linux]
See conda-forge docs on how to specify openmp

2021-11-12 21:36 UTC, isuruf requested changes
Please don't change files outside of `recipes/nd2`

2021-11-12 21:37 UTC, tlambert03 commented
> Please don't change files outside of `recipes/nd2`

thanks @isuruf... still working on this one.  will clean it up before requesting review

2021-11-12 22:16 UTC, tlambert03 commented
hmm... the windows build is no longer succeeding (it was about a month ago).  Now seeing unresolved symbols:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:src\sdk\Windows\x86_64\lib /LIBPATH:C:\bld\nd2_1636754089901\_h_env\libs /LIBPATH:C:\bld\nd2_1636754089901\_h_env\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64" /LIBPATH:C:\bld\nd2_1636754089901\_h_env\Library\lib /LIBPATH:C:\bld\nd2_1636754089901\_h_env\Library\lib nd2readsdk-static.lib /EXPORT:PyInit_latest build\temp.win-amd64-3.8\Release\src/nd2/_sdk/latest.obj src\sdk\Windows\x86_64\lib\jbig.lib src\sdk\Windows\x86_64\lib\libjpeg.lib src\sdk\Windows\x86_64\lib\limfile.lib src\sdk\Windows\x86_64\lib\lzma.lib src\sdk\Windows\x86_64\lib\nd2readsdk-static.lib src\sdk\Windows\x86_64\lib\tiff.lib src\sdk\Windows\x86_64\lib\tiffxx.lib src\sdk\Windows\x86_64\lib\zlib.lib /OUT:build\lib.win-amd64-3.8\nd2\_sdk\latest.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.8\Release\src/nd2/_sdk\latest.cp38-win_amd64.lib
     Creating library build\temp.win-amd64-3.8\Release\src/nd2/_sdk\latest.cp38-win_amd64.lib and object build\temp.win-amd64-3.8\Release\src/nd2/_sdk\latest.cp38-win_amd64.exp
  limfile.lib(JsonFileDeviceImpl.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
  limfile.lib(IoMemoryBufferImpl.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
  limfile.lib(JsonFileDevice.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
```

 I believe static libs I'm linking against require `msvcp140.dll` ... and i guess that means I need vs2015 here? 
I'm aware that vs2015 is deprecated (and perhaps completely unavailable?) ... any suggestions, preferably short of requesting recompiled libraries?

2021-11-13 16:36 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/nd2```) and found some lint.

Here's what I've got...


For **recipes/nd2**:

 * ``requirements: host: vc=14.0`` must contain a space between the name and the pin, i.e. ``vc =14.0``

2021-11-13 17:06 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/nd2```) and found some lint.

Here's what I've got...


For **recipes/nd2**:

 * ``requirements: host: vc=14`` must contain a space between the name and the pin, i.e. ``vc =14``

2021-11-13 17:07 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/nd2```) and found it was in an excellent condition.

2021-11-13 18:20 UTC, tlambert03 commented
welp, I think this is stuck again.  it's working on mac and linux, but not windows anymore.  I believe (but am not 100% sure) that I need to compile using vs2015 so that I can link the static pre-compiled objects (based on all the errors mentioned above: `error LNK2001: unresolved external symbol __CxxFrameHandler4`).  yes, I understand this is because i'm dealing with precompiled libs... but i'm afraid that's the situation we find ourselves in.

I'm not sure why it worked a month ago on windows... and can no longer access those build logs to check.  (fwiw, It also seems to work fine on `cibuildwheel`):

I tried:
- adding c_compiler `vs2015` to `conda_build_config.yaml` ... but I get an [unsatisfiable dependency](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=411120&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=06d62fd2-ab49-5add-9ee5-83b6882d7d2b&l=649) from conda_build
- adding `vc =14` at various places in the recipe (didn't change anything)

any tips @isuruf, @jaimergp

2021-11-22 19:34 UTC, tlambert03 commented
I've decided not to build for windows for now.  This is ready for review, working on linux (centos7) and mac is enough for me.  Ready for re-review @isuruf, @conda-forge/help-python-c

2021-11-24 11:11 UTC, jaimergp commented
No clue either @tlambert03, we can always enable Windows on the feedstock later.

@isuruf I think the [licensing](https://github.com/tlambert03/nd2/blob/main/LICENSE) / [vendoring](https://github.com/tlambert03/nd2/blob/main/src/sdk/LICENSE) issues are covered now. There's a [detailed analysis of the symbols](https://github.com/tlambert03/nd2/issues/30) in the source repo as well if you need to check something else about these libs.

2021-11-24 11:12 UTC, jaimergp commented on recipes/nd2/meta.yaml
> +  license_file: LICENSE
We need to include the sdk license here too. This field can be a list of paths so, something like this:

```suggestion
  license_file: 
    - LICENSE
    - src/sdk/LICENSE
```

I don't know if the `license` and `license_family` fields need to be updated to reflect this too.

2021-11-24 14:04 UTC, tlambert03 commented
thanks again for all your help @jaimergp!  much appreciated

2022-03-07 13:06 UTC, tlambert03 commented
>  but I think we'd need permission for conda-forge as an entity. Is it possible to ask the authors for a more specific language when it comes to redistribution?

Hi @jaimergp, @mbargull @chrisburr, @goanpeca:

I contact the upstream company and requested explicit permission for conda-forge and pypi to re-distribute binaries.  They sent me an updated email, when I have included in the repo [here](https://github.com/tlambert03/nd2/blob/main/src/sdk/LICENSE) and also included in the sdist.  I cut a new release and am using it here.

Looks like builds are passing.  It would be great to finally have this merged!  Thanks for all your help.

2022-03-07 13:18 UTC, jaimergp commented on recipes/nd2/meta.yaml
> +  license_family: BSD
```suggestion
  license_family: BSD AND LicenseRef-LIMnd2sdk
```

2022-03-07 13:19 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/nd2```) and found some lint.

Here's what I've got...


For **recipes/nd2**:

 * about/license_family 'BSD AND LicenseRef-LIMnd2sdk' not allowed.
Allowed families are AGPL, APACHE, BSD, CC, GPL, GPL2, GPL3, LGPL,
MIT, MOZILLA, NONE, OTHER, PROPRIETARY, PSF, and PUBLIC-DOMAIN.

2022-03-07 13:21 UTC, jaimergp commented on recipes/nd2/meta.yaml
> +  license_family: BSD AND LicenseRef-LIMnd2sdk
```suggestion
  license: BSD-3-Clause AND LicenseRef-LIMnd2sdk
```

2022-03-07 13:22 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/nd2```) and found it was in an excellent condition.

2022-03-07 13:41 UTC, merged

2022-03-07 14:56 UTC, tlambert03 commented
thank you @jaimergp !!