Adding Rb-webrick
conda-forge/staged-recipes pull request #16524
Opened 2021-10-15 04:39 UTC by d-cunningham

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-10-15 04:39 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-webrick```) and found some lint.

Here's what I've got...


For **recipes/r-webrick**:

 * There are too few lines.  There should be one empty line at the end of the file.

2021-11-01 19:30 UTC, d-cunningham commented
@conda-forge/staged-recipes, recipe ready for review

2022-06-25 14:42 UTC, BastianZim requested changes
@d-cunningham Apologies for no review so far but we currently have a very small ruby review team. I have added some small comments and requested a review from the whole team.

2022-06-25 14:42 UTC, BastianZim commented on recipes/r-webrick/meta.yaml
> +  noarch: generic
If you have a skip, it cannot be platform independent.

2022-06-25 14:42 UTC, BastianZim commented on recipes/r-webrick/meta.yaml
> +  skip: {{ win }}
```suggestion
  skip: True  # [win]
```

2022-07-20 16:40 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-webrick```) and found some lint.

Here's what I've got...


For **recipes/r-webrick**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: generic`.

2022-07-20 16:43 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-webrick```) and found it was in an excellent condition.

2023-05-13 14:54 UTC, closed without merging