Add starfleet, a pulsar timing and data analysis metapackage
conda-forge/staged-recipes pull request #16632
Opened 2021-10-24 01:23 UTC by AaronDJohnson

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-10-24 01:32 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/starfleet```) and found some lint.

Here's what I've got...


For **recipes/starfleet**:

 * The home item is expected in the about section.
 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.

2021-10-24 01:35 UTC, AaronDJohnson commented
Some of the subpackages cannot compile on Windows. Also, this is a metapackage, so there is no source location.

2022-02-22 23:57 UTC, AaronDJohnson commented
@conda-forge/help-python I kind of forgot about this for a while, and I think I tagged the wrong thing originally.

2022-02-24 18:32 UTC, carterbox requested changes

2022-02-24 18:33 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/starfleet```) and found some lint.

Here's what I've got...


For **recipes/starfleet**:

 * The home item is expected in the about section.

2022-02-24 18:35 UTC, carterbox commented
>there is no source location to put in the home item.

home is not the dev_url. It is a page explaining the purpose of the package. Do you not have a project page that uses starfleet? Certainly there is some webpage promoting the use of this metapackage, otherwise, why publish it?

2022-10-04 22:14 UTC, closed without merging