Added r-blaster recipe
conda-forge/staged-recipes pull request #16700
Opened 2021-11-01 08:57 UTC by jeevannavar

Checklist
- [ Y ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ Y ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [ Y ] Source is from official source.
- [ Y ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ Y ] If static libraries are linked in, the license of the static library is packaged.
- [ Y ] Build number is 0.
- [ Y ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ N ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
_The other GitHub user listed in the maintainer section is the author of the R package and is willing to be listed here._
- [ Y ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-11-01 08:57 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-blaster```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/r-blaster**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2021-11-02 12:56 UTC, manutamminen commented
I can be listed as a maintainer.

2021-11-02 15:20 UTC, cbrueffer requested changes
Looks good; please fix the two issues I raised and then this is good to go.

2021-11-02 15:20 UTC, cbrueffer commented on recipes/r-blaster/meta.yaml
> +  license: BSD_3_clause
```suggestion
  license: BSD-3-Clause
```

2021-11-02 15:20 UTC, cbrueffer commented on recipes/r-blaster/meta.yaml
> +    - manutamminen
Please add `conda-forge/r` as maintainer.

2021-11-03 09:02 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-blaster```) and found it was in an excellent condition.

2021-11-03 09:12 UTC, jeevannavar commented
> Looks good; please fix the two issues I raised and then this is good to go.

I have fixed both the issues.

2021-11-03 09:44 UTC, merged