Add mne-qt-browser
conda-forge/staged-recipes pull request #16711
Opened 2021-11-01 20:35 UTC by larsoner

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-11-01 20:35 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/mne-qt-browser```) and found some lint.

Here's what I've got...


For **recipes/mne-qt-browser**:

 * Please do not delete the example recipe found in `recipes/example/meta.yaml`.

2021-11-01 20:35 UTC, larsoner commented
@marsipu you need to comment here that you're willing to maintain this conda-forge recipe

2021-11-01 20:38 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/mne-qt-browser```) and found it was in an excellent condition.

2021-11-01 20:41 UTC, larsoner commented on recipes/mne-qt-browser/meta.yaml
> +    - mne-base
@marsipu once we release 0.24 we should remember to update this!

2021-11-01 21:38 UTC, marsipu commented on recipes/mne-qt-browser/meta.yaml
> +{% set version = "0.1.1" %}
I updated the package once more.
```suggestion
{% set version = "0.1.2" %}
```

2021-11-01 21:39 UTC, marsipu commented
Thanks a lot @larsoner for setting this up.

2021-11-01 21:40 UTC, marsipu commented
I am willing to maintain this conda-forge recipe.

2021-11-03 19:58 UTC, marsipu requested changes

2021-11-03 19:58 UTC, marsipu commented on recipes/mne-qt-browser/meta.yaml
> +{% set version = "0.1.3" %}
```suggestion
{% set version = "0.1.4" %}
```

I increased the version-number once more yesterday for the newest feedback on the now merged PR in MNE-Python.

2021-11-03 22:54 UTC, larsoner commented
@conda-forge/staged-recipes, this one seems to be ready for review. Thanks!

2021-11-04 17:02 UTC, ocefpaf commented on recipes/mne-qt-browser/meta.yaml
> +    - python
Please add `>=3.7` here too.

2021-11-04 17:52 UTC, larsoner commented
Done, thanks for the review @ocefpaf

2021-11-04 18:07 UTC, merged