Add aoe2netwrapper package
conda-forge/staged-recipes pull request #16744
Opened 2021-11-02 16:47 UTC by fsoubelet

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-11-02 16:47 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/aoe2netwrapper```) and found it was in an excellent condition.

2021-11-16 19:21 UTC, dopplershift requested changes
Just a couple minor tweaks and this is good to go.

2021-11-16 19:21 UTC, dopplershift commented on recipes/aoe2netwrapper/LICENSE
> +MIT License
This is already included in the PyPI tarball used to build the package, so it should not be included here. Please go ahead and remove.

2021-11-16 19:21 UTC, dopplershift commented on recipes/aoe2netwrapper/meta.yaml
> +  summary: My Python wrapper for the aoe2.net data API
```suggestion
  summary: Python wrapper for the aoe2.net data API
```
?

2021-11-16 20:13 UTC, fsoubelet commented
Thanks for providing pointers @dopplershift, I've made the changes 🙂

2021-11-16 20:37 UTC, dopplershift approved these changes

2021-11-16 20:39 UTC, dopplershift commented
I'm ignoring the Windows failure because it's from an unrelated recipe that was merged.

2021-11-16 20:39 UTC, merged