adding levenshtein-search
conda-forge/staged-recipes pull request #16891
Opened 2021-11-10 17:23 UTC by osamples

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-11-10 17:24 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/levenshtein-search```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/levenshtein-search**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2021-11-10 17:49 UTC, osamples commented
@dopplershift Hi I have worked with you on two previous PRs. This one is related, but I seem to be getting an error. I was hoping you could maybe help explain the error to me if you've run across it before. This is the[ pypi library](https://pypi.org/project/Levenshtein-search/) I am trying to add to conda-forge.

2021-11-11 01:04 UTC, dopplershift commented on recipes/levenshtein-search/meta.yaml
> +    - gcc
Try this:
```suggestion
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
```

2021-11-12 16:22 UTC, osamples commented
@dopplershift Thank you so much for looking into this! It looked like your solution allowed it to build, but the tests failed. Is there another simple fix for this as well?

2021-11-12 17:51 UTC, dopplershift requested changes
These will get this over the finish line I think.

2021-11-12 17:51 UTC, dopplershift commented on recipes/levenshtein-search/meta.yaml
> +    - levenshtein_search
Ugh, it's [capitalized](https://github.com/mattandahalfew/Levenshtein_search#usage):
```suggestion
    - Levenshtein_search
```

2021-11-12 19:38 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/levenshtein-search```) and found it was in an excellent condition.

2021-11-12 20:17 UTC, osamples commented
@dopplershift It worked!! Thank you so much! This is the best news

2021-11-12 20:42 UTC, dopplershift approved these changes
:tada:

2021-11-12 20:42 UTC, merged