[WiP] Add HECSS package
conda-forge/staged-recipes pull request #16913
Opened 2021-11-12 13:15 UTC by jochym

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-11-12 13:15 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/hecss```) and found some lint.

Here's what I've got...


For **recipes/hecss**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

For **recipes/hecss**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2021-11-12 13:18 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/hecss```) and found some lint.

Here's what I've got...


For **recipes/hecss**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2021-11-12 13:19 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/hecss```) and found some lint.

Here's what I've got...


For **recipes/hecss**:

 * Invalid `noarch` value `python >=3.6`. Should be one of `python`, `generic`.

2021-11-12 13:21 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/hecss```) and found it was in an excellent condition.

2021-11-13 00:17 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/hecss```) and found some lint.

Here's what I've got...


For **recipes/hecss**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.

2021-11-13 00:19 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/hecss```) and found some lint.

Here's what I've got...


For **recipes/hecss**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2021-11-13 09:03 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/hecss```) and found it was in an excellent condition.

2021-11-15 20:56 UTC, dopplershift requested changes
Just a couple minor tweaks and this is good.

2021-11-15 20:56 UTC, dopplershift commented on recipes/hecss/meta.yaml
> +  license_family: GPL
```suggestion
  license_family: GPL3
```

2021-11-15 20:56 UTC, dopplershift commented on recipes/hecss/meta.yaml
> +  home: https://github.com/simplejson/simplejson
```suggestion
  home: https://jochym.gitlab.io/hecss
``?

2021-11-15 20:58 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/hecss```) and found some lint.

Here's what I've got...


For **recipes/hecss**:

 * Failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint .` from the recipe directory.

2021-11-15 21:02 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/hecss```) and found it was in an excellent condition.

2021-11-15 21:03 UTC, jochym commented on recipes/hecss/meta.yaml
> +  home: https://github.com/simplejson/simplejson
Thanks for the review. Fixed.

2021-11-16 06:39 UTC, jochym commented
@dopplershift Thanks for the review. Changes committed. Can this be merged now?

2021-11-16 18:50 UTC, dopplershift approved these changes

2021-11-16 18:50 UTC, merged