adding persistent
conda-forge/staged-recipes pull request #16956
Opened 2021-11-15 15:18 UTC by osamples

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-11-15 15:18 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/persistent```) and found it was in an excellent condition.

2021-11-15 15:36 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/btrees```, ```recipes/persistent```) and found it was in an excellent condition.

2021-11-15 15:56 UTC, osamples commented
@conda-forge/help-python The recipes have passed all checks and are ready for your review. Thanks!

2021-11-15 19:24 UTC, osamples commented
@dopplershift These are ready for review - thanks!

2021-11-15 21:01 UTC, dopplershift requested changes
Just a few minor things.

2021-11-15 21:01 UTC, dopplershift commented on recipes/persistent/meta.yaml
> +  license_file: COPYRIGHT.txt
Here too:
```suggestion
  license_file: LICENSE.txt
```

2021-11-15 21:01 UTC, dopplershift commented on recipes/persistent/meta.yaml
> +    - cython
I don't see cython being used anywhere in here?
```suggestion
```

2021-11-15 21:02 UTC, dopplershift commented on recipes/btrees/meta.yaml
> +  license_file: COPYRIGHT.txt
Oh I see now that the license needs the copyright notice. Ok, how about this instead:
```suggestion
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt
```

2021-11-16 06:16 UTC, dopplershift approved these changes

2021-11-16 06:16 UTC, merged