Add sdds package
conda-forge/staged-recipes pull request #17005
Opened 2021-11-18 22:15 UTC by fsoubelet

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-11-18 22:15 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/sdds```) and found some lint.

Here's what I've got...


For **recipes/sdds**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2021-11-18 22:17 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/sdds```) and found it was in an excellent condition.

2021-11-19 06:46 UTC, dopplershift requested changes
Just remove the unneeded license file and this is good to go.

2021-11-19 06:46 UTC, dopplershift commented on recipes/sdds/LICENSE
> +MIT License
This file is already present in the PyPI tarball, so it shouldn't be included here.

2021-11-19 08:33 UTC, fsoubelet commented
Done @dopplershift 

However I'm a little confused as to when to do that, as for instance for https://github.com/conda-forge/staged-recipes/pull/17004 I left the license, which is also included in the tarball.

2021-11-19 09:37 UTC, dopplershift commented
@fsoubelet Just means I missed checking for it. Happens when you're reviewing several of these every day. 😉 

So in the feedstock for tfs-pandas you should delete it too.

2021-11-19 09:37 UTC, dopplershift approved these changes

2021-11-19 09:37 UTC, merged

2021-11-19 09:41 UTC, fsoubelet commented
Noted, I will take care of that.