adding rlr
conda-forge/staged-recipes pull request #17003
Opened 2021-11-18 20:14 UTC by osamples

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L57-L66) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-11-18 20:15 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/rlr```) and found it was in an excellent condition.

2021-11-18 20:38 UTC, osamples commented
@dopplershift Here is the next one - modified to reflect the same changes that the previous one (highered) had.

2021-11-19 06:37 UTC, dopplershift requested changes
Just need to resolve the license file, otherwise this recipe is good to go. @izahn I assume you're ok being listed as a maintainer for this recipe?

2021-11-19 06:37 UTC, dopplershift commented on recipes/rlr/LICENSE
> +The MIT License (MIT)
Where did this license come from? It's not the one in the [upstream repo](https://github.com/dedupeio/rlr/blob/master/COPYING) and it's not an Apache 2.0 license, which what the `setup.py` for this version says it is. I'd be ok with having a generic Apache 2.0 license file here.

2021-11-19 11:07 UTC, izahn commented
Yes happy to be a maintainer

2021-11-22 19:20 UTC, dopplershift approved these changes
Ignoring windows build failure due to missing dependency on noarch.

2021-11-22 19:20 UTC, merged