add trio-parallel
conda-forge/staged-recipes pull request #17111
Opened 2021-11-29 17:51 UTC by carlodri

https://trio-parallel.readthedocs.io/en/latest/

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-11-29 17:51 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/trio-parallel```) and found it was in an excellent condition.

2021-11-29 19:32 UTC, carlodri commented
@conda-forge/staged-recipes for me this is ready to merge

2021-11-29 20:06 UTC, dopplershift requested changes
Looks good, just a minor tweak to the included license files.

2021-11-29 20:06 UTC, dopplershift commented on recipes/trio-parallel/meta.yaml
> +  license_file: LICENSE
Let's include all 3 files:
```suggestion
  license_file:
    - LICENSE
    - LICENSE.APACHE2
    - LICENSE.MIT
```

2021-11-30 21:43 UTC, dopplershift approved these changes

2021-11-30 21:44 UTC, merged