Adding flaremodel
conda-forge/staged-recipes pull request #17147
Opened 2021-12-03 00:21 UTC by ydallilar

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-12-03 00:22 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/flaremodel```) and found some lint.

Here's what I've got...


For **recipes/flaremodel**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [14, 28, 29, 39, 40]
 * ``requirements: host: numpy<1.20`` must contain a space between the name and the pin, i.e. ``numpy <1.20``

For **recipes/flaremodel**:

 * Whenever possible python packages should use pip. See https://conda-forge.org/docs/maintainer/adding_pkgs.html#use-pip

2021-12-03 00:35 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/flaremodel```) and found some lint.

Here's what I've got...


For **recipes/flaremodel**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [14, 28, 29, 30, 40, 41, 42]

For **recipes/flaremodel**:

 * Whenever possible python packages should use pip. See https://conda-forge.org/docs/maintainer/adding_pkgs.html#use-pip

2021-12-03 01:03 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/flaremodel```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/flaremodel**:

 * Whenever possible python packages should use pip. See https://conda-forge.org/docs/maintainer/adding_pkgs.html#use-pip

2021-12-03 01:31 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/flaremodel```) and found it was in an excellent condition.

2021-12-03 03:52 UTC, anilk666 commented
> Checklist
> 
> * [x]  Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
> * [x]  License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
> * [x]  Source is from official source.
> * [x]  Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
> * [x]  If static libraries are linked in, the license of the static library is packaged.
> * [x]  Build number is 0.
> * [x]  A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
> * [x]  GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
> * [x]  When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

https://github.com/conda-forge/staged-recipes/pull/17147#issue-1070097635
anilk666

2021-12-03 07:33 UTC, ydallilar commented
I am willingly listed as sole maintainer of this package.

2021-12-03 12:11 UTC, ydallilar commented
@conda-forge/help-python, ready for review.

2021-12-03 12:50 UTC, ydallilar commented
@conda-forge/help-python ready to review.

2021-12-03 14:36 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/help-python and so here I am doing that.

2022-04-20 00:45 UTC, carterbox commented
conda-forge-admin, please restart ci

2022-04-26 23:05 UTC, carterbox requested changes

2022-04-27 06:03 UTC, ydallilar commented on recipes/flaremodel/meta.yaml
> +    - libcblas
It has been a while. I dont remember. I will check in a few days.

2022-04-30 19:47 UTC, ydallilar commented on recipes/flaremodel/meta.yaml
> +    - libcblas
The C library I am including actually doesn't require blas at all. But, the build fails without. I am assuming it has to do with cython, numpy (or possibly conda-forge blas implementation that comes with it: https://conda-forge.org/docs/maintainer/knowledge_base.html#blas).

2022-11-12 18:44 UTC, closed without merging