Adding Enzyme
conda-forge/staged-recipes pull request #17169
Opened 2021-12-05 18:08 UTC by IvanYashchuk

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-12-05 18:08 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/libenzyme```) and found some lint.

Here's what I've got...


For **recipes/libenzyme**:

 * Failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint .` from the recipe directory.

2021-12-05 18:28 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/libenzyme```) and found it was in an excellent condition.

2021-12-05 18:59 UTC, IvanYashchuk commented
@conda-forge-admin, please ping conda-forge/help-c-cpp

2021-12-05 18:59 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/help-c-cpp and so here I am doing that.

2021-12-10 13:37 UTC, IvanYashchuk commented on recipes/libenzyme/meta.yaml
> +  sha256: ce15ce1b839ba68e0941ce39730ab4df938eb1a6383feaffbccd3276fac22d14
The version is not arbitrary, it's fixed by convention at the beginning of the file `{% set version = "0.0.23" %}`. When the version changes, sha256 would need to be updated as well.

2021-12-10 13:38 UTC, wsmoses commented on recipes/libenzyme/meta.yaml
> +  sha256: ce15ce1b839ba68e0941ce39730ab4df938eb1a6383feaffbccd3276fac22d14
Ah, got it

2022-04-19 18:01 UTC, carterbox requested changes

2022-04-19 18:02 UTC, carterbox commented
@conda-forge-admin, please restart ci

2022-04-19 18:37 UTC, wsmoses commented on recipes/libenzyme/meta.yaml
> +    - test -f $PREFIX/lib/LLVMEnzyme-{{ llvm_major_version }}${SHLIB_EXT}  # [unix]
Can you add a test here for ClangEnzyme and LLDEnzyme in addition to LLVMEnzyme?

2022-04-19 18:40 UTC, wsmoses commented on recipes/libenzyme/meta.yaml
> +    - IvanYashchuk
Feel free to add myself here

@vchuravy @tgymnich may also want to be added

2022-04-19 18:42 UTC, wsmoses commented on recipes/libenzyme/meta.yaml
> +    - llvmdev {{ llvm_major_version }}
It's likely worth adding clangdev here so the nicer helper ClangEnzyme-XX.so gets built too.

2022-11-13 16:10 UTC, closed without merging