Add h3-pyspark recipe
conda-forge/staged-recipes pull request #17209
Opened 2021-12-08 19:57 UTC by kevinschaich

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-12-08 19:58 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/h3-pyspark```) and found some lint.

Here's what I've got...


For **recipes/h3-pyspark**:

 * The recipe could do with some maintainers listed in the `extra/recipe-maintainers` section.
 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.

2021-12-08 19:59 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/h3-pyspark```) and found some lint.

Here's what I've got...


For **recipes/h3-pyspark**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.

2021-12-08 20:00 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/h3-pyspark```) and found it was in an excellent condition.

2021-12-08 20:15 UTC, kevinschaich commented
@conda-forge/help-python Ready for review.

2021-12-08 20:15 UTC, kevinschaich commented
@conda-forge-admin Ready for review

2021-12-09 21:09 UTC, beenje requested changes

2021-12-09 21:09 UTC, beenje commented on recipes/h3-pyspark/meta.yaml
> +  # skip: True  # [py<35]
Please remove this comment

2021-12-09 21:09 UTC, beenje commented on recipes/h3-pyspark/meta.yaml
> +  script: python -m pip install --no-deps --ignore-installed .
Replace this with:

```suggestion
  script: {{ PYTHON }} -m pip install . -vv
```

2021-12-09 21:09 UTC, beenje commented on recipes/h3-pyspark/meta.yaml
> +    - shapely >=1.7.0
Please remove those requirements.

The goal of the test is to check that the package can be installed properly with all its needed dependencies (that you define in run requirements).
`requires` in test is only to install extra things that could be required to run tests.

2021-12-09 21:56 UTC, beenje commented
@conda-forge/help-python, this recipe looks good to me

2021-12-17 18:56 UTC, dopplershift approved these changes

2021-12-17 18:56 UTC, merged