Adding EMD package
conda-forge/staged-recipes pull request #17246
Opened 2021-12-13 14:32 UTC by AJQuinn

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-12-13 14:32 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/emd```) and found some lint.

Here's what I've got...


For **recipes/emd**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2021-12-13 14:48 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/emd```) and found it was in an excellent condition.

2021-12-17 00:44 UTC, dopplershift requested changes
Tweak to the license metadata and this is good to go.

2021-12-17 00:44 UTC, dopplershift commented on recipes/emd/meta.yaml
> +  license:  GPL-2.0-or-later
```suggestion
  license:  GPL-3.0-or-later
```

2021-12-17 18:11 UTC, AJQuinn commented
Thanks for the review @dopplershift -  I've committed the version change, apologies for not spotting the typo! please let me know if there is anything else I should do.

2021-12-17 18:19 UTC, dopplershift approved these changes

2021-12-17 18:19 UTC, merged