Add nagl
conda-forge/staged-recipes pull request #17314
Opened 2021-12-21 17:45 UTC by SimonBoothroyd

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-12-21 17:45 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/nagl```) and found some lint.

Here's what I've got...


For **recipes/nagl**:

 * There are too few lines.  There should be one empty line at the end of the file.

2021-12-21 17:47 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/nagl```) and found it was in an excellent condition.

2021-12-21 18:09 UTC, SimonBoothroyd commented
@conda-forge/help-python this should be ready to go! The package does not support windows so the CI failure due to missing `pytorch` should not be an issue

2021-12-22 00:33 UTC, dopplershift requested changes

2021-12-22 00:33 UTC, dopplershift commented on recipes/nagl/meta.yaml
> +  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
Would be good to go ahead and add the entry point for the CLI:
```suggestion
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - nagl = nagl.cli:cli
```

2021-12-22 00:33 UTC, dopplershift commented on recipes/nagl/meta.yaml
> +    - nagl
Maybe test the cli too?
```suggestion
  imports:
    - nagl
  commands:
    - nagl
```

2021-12-22 00:33 UTC, dopplershift commented on recipes/nagl/meta.yaml
> +  license_file: LICENSE
Probably should include the 3rd party stuff too:
```suggestion
  license: MIT AND BSD-3-CLAUSE
  license_file:
    - LICENSE
    - LICENSE-3RD-PARTY
```

2021-12-22 09:28 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/nagl```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/nagl**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2021-12-22 09:30 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/nagl```) and found it was in an excellent condition.

2021-12-22 09:42 UTC, SimonBoothroyd commented
Thanks @dopplershift for catching these! They should be resolved by 5422805 and 0ccea6e

2021-12-22 18:05 UTC, dopplershift approved these changes
Ignoring failure on Windows due to noarch and missing dependencies.

2021-12-22 18:05 UTC, merged

2021-12-28 12:33 UTC, SimonBoothroyd commented
Thanks @dopplershift !