Add metaimageio
conda-forge/staged-recipes pull request #17347
Opened 2021-12-23 19:30 UTC by auneri

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2021-12-23 19:30 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```metaimageio```) and found some lint.

Here's what I've got...


For **metaimageio**:

 * Please do not delete the example recipe found in `recipes/example/meta.yaml`.
 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2021-12-23 19:37 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/metaimageio```) and found some lint.

Here's what I've got...


For **recipes/metaimageio**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2021-12-23 19:39 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/metaimageio```) and found it was in an excellent condition.

2022-01-04 23:58 UTC, dopplershift requested changes
Just a couple minor changes and this is good to go.

2022-01-04 23:58 UTC, dopplershift commented on recipes/metaimageio/meta.yaml
> +  home: https://auneri.github.io/metaimageio
I think GitHub URLs are case-senstive:
```suggestion
  home: https://auneri.github.io/MetaImageIO
```
(old one was 404-ing)
```suggestion
  home: https://auneri.github.io/metaimageio
```

2022-01-04 23:58 UTC, dopplershift commented on recipes/metaimageio/meta.yaml
> +  sha256: {{ hash }}
Go ahead and just put the hash in here directly and don't bother with templating it--it's not used in multiple places (ever).

2022-01-05 00:50 UTC, auneri commented
All done, thanks @dopplershift for the review

2022-01-05 01:29 UTC, dopplershift approved these changes

2022-01-05 01:30 UTC, merged