Add torch_em recipe
conda-forge/staged-recipes pull request #17417
Opened 2022-01-05 20:48 UTC by constantinpape

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-01-05 20:48 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/torch_em```) and found some lint.

Here's what I've got...


For **recipes/torch_em**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2022-01-05 20:50 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/torch_em```) and found it was in an excellent condition.

2022-01-05 21:43 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/torch_em```) and found some lint.

Here's what I've got...


For **recipes/torch_em**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.

2022-01-05 21:46 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/torch_em```) and found some lint.

Here's what I've got...


For **recipes/torch_em**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2022-01-05 21:48 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/torch_em```) and found it was in an excellent condition.

2022-01-06 10:48 UTC, constantinpape commented
@conda-forge/python this is ready for review now. Thanks!

2022-01-06 20:45 UTC, dopplershift requested changes

2022-01-06 20:45 UTC, dopplershift commented on recipes/torch_em/meta.yaml
> +  skip: true  # [win]
Since this is pure Python, better to make this noarch and we can ignore the Windows faillure:
```suggestion
  noarch: python
```

2022-01-06 20:45 UTC, dopplershift commented on recipes/torch_em/meta.yaml
> +    - python
For noarch:
```suggestion
    - python >=3.6
```

2022-01-06 20:45 UTC, dopplershift commented on recipes/torch_em/meta.yaml
> +    - python
Here too:
```suggestion
    - python >=3.6
```

2022-01-06 21:51 UTC, dopplershift approved these changes
Ignoring Windows failure due to missing deps on noarch.

2022-01-06 21:51 UTC, merged

2022-01-06 21:52 UTC, constantinpape commented
Thanks for the quick review and merging this @dopplershift!