Adding dcc
conda-forge/staged-recipes pull request #17589
Opened 2022-01-19 15:13 UTC by SeanDS

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-01-19 15:14 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/dcc```) and found it was in an excellent condition.

2022-01-19 15:15 UTC, SeanDS commented
@duncanmmacleod are you happy to be a co-maintainer of this?

2022-01-19 16:56 UTC, duncanmmacleod commented
> @duncanmmacleod are you happy to be a co-maintainer of this?

Yes, I'm happy to help maintain this.

2022-01-19 17:00 UTC, duncanmmacleod commented
@conda-forge/staged-recipes, this is ready for review, thanks.

2022-01-20 02:04 UTC, dopplershift requested changes
Minor tweak to the license metadata and this is good to go.

2022-01-20 02:04 UTC, dopplershift commented on recipes/dcc/meta.yaml
> +  license_family: GPL
```suggestion
  license_family: GPL3
```

2022-01-21 13:13 UTC, SeanDS commented
@conda-forge/staged-recipes, this is ready for review again.

2022-01-21 13:14 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/staged-recipes and so here I am doing that.

2022-01-21 19:02 UTC, dopplershift approved these changes

2022-01-21 19:02 UTC, merged