Add zarpaint recipe
conda-forge/staged-recipes pull request #17857
Opened 2022-02-01 20:18 UTC by goanpeca

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-02-01 20:19 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/zarpaint```) and found it was in an excellent condition.

2022-02-01 20:20 UTC, goanpeca commented
Depends on:
- https://github.com/conda-forge/staged-recipes/pull/17848

2022-02-01 20:20 UTC, goanpeca commented
We are in the process of creating conda packages for [napari plugins](https://www.napari-hub.org/) and related dependencies. Once this recipe passes all the checks, every time a new release goes into PyPI, a PR will be automatically open, with usually very minor need for changes so the process of maintaining this moving forward is small. Also the @conda-forge/napari team will be available to help as needed.

You can read a bit more about conda-forge at https://conda-forge.org/#contribute

--- 

@jni, do you agree with being added as a maintainer?

2022-02-02 00:35 UTC, jni commented
Yes.

btw @goanpeca I may have accidentally buried some of these that belong to me because I got notified for all of them. Please ping me on Zulip if I haven't responded on one of my plugins.

2022-02-02 01:08 UTC, goanpeca commented
Will do!

2022-07-11 08:34 UTC, jni commented
@goanpeca @jaimergp this depends on tensorstore right now (#17848), though we're in the process of removing that dependency... Still, it would be good to get that in as it's a very good library. 🙏

2023-04-13 16:22 UTC, goanpeca commented
Still working on this!

2023-04-14 06:38 UTC, jni commented
> Still working on this!

oh good! 😂

2023-11-01 23:51 UTC, jni commented
@goanpeca I'm working on a new zarpaint release for which tensorstore is optional. I'll update this recipe once that's out. 🙏

2023-11-04 23:42 UTC, jni requested changes
@goanpeca new release of zarpaint is out, drops the tensorstore requirement! 🥳

2023-11-04 23:42 UTC, jni commented on recipes/zarpaint/meta.yaml
> +{% set version = "0.2.0" %}
```suggestion
{% set version = "0.3.0" %}
```

2023-11-04 23:42 UTC, jni commented on recipes/zarpaint/meta.yaml
> +  sha256: f73f80d9d517f81a89a5b5b1b15f753ee436e9b1fb8bb404e01c1fc1e67ba714
```suggestion
  sha256: c831eabfe5148d1a41ef29fe2a8fc7da7e61b4bdf8a910b73aaad70730169f03
```

2023-11-04 23:42 UTC, jni commented on recipes/zarpaint/meta.yaml
> +    - napari-plugin-engine >=0.1.4
```suggestion
```

2023-11-04 23:42 UTC, jni commented on recipes/zarpaint/meta.yaml
> +    - napari >=0.4.11.dev80
```suggestion
    - napari >=0.4.18
```

2023-11-04 23:42 UTC, jni commented on recipes/zarpaint/meta.yaml
> +    - tensorstore
```suggestion
```

2023-11-04 23:42 UTC, jni commented on recipes/zarpaint/meta.yaml
> +    - napari-plugin-engine >=0.1.4
(I just saw that the setup.cfg has it but it's a mistake)

2023-11-06 23:10 UTC, goanpeca commented
```bash
+ zarpaint --help
Traceback (most recent call last):
  File "/home/conda/staged-recipes/build_artifacts/zarpaint_1699311916585/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/zarpaint", line 7, in <module>
    from zarpaint._main import main
  File "/home/conda/staged-recipes/build_artifacts/zarpaint_1699311916585/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/site-packages/zarpaint/_main.py", line 5, in <module>
    from ._zarpaint import correct_labels
ImportError: cannot import name 'correct_labels' from 'zarpaint._zarpaint' (/home/conda/staged-recipes/build_artifacts/zarpaint_1699311916585/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/site-packages/zarpaint/_zarpaint.py)

```

@jni, is this expected 🙃 ?

2023-11-08 07:40 UTC, jni commented
Hahahaha no it is not! Hold please!

2023-11-08 07:59 UTC, jni approved these changes
Let's try now... 😅

2023-11-08 07:59 UTC, jni commented on recipes/zarpaint/meta.yaml
> +    - zarpaint --help
```suggestion
```

2023-11-08 07:59 UTC, jni commented on recipes/zarpaint/meta.yaml
> +  sha256: c831eabfe5148d1a41ef29fe2a8fc7da7e61b4bdf8a910b73aaad70730169f03
```suggestion
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zarpaint-{{ version }}.tar.gz
  sha256: dda1352084afad3ea6f0bbfa25c5cec0e8077ccdd34022a12a32bd661af0d41c
```

2023-11-09 02:41 UTC, jni commented
To paraphrase Gordon Gecko, green is good! 😃

2023-11-09 13:43 UTC, goanpeca commented
This one is ready for review @conda-forge/staged-recipes :)

2023-11-18 21:22 UTC, merged