Adding gym-saturation
conda-forge/staged-recipes pull request #17890
Opened 2022-02-01 23:04 UTC by inpefess

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-02-01 23:04 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/gym-saturation```) and found some lint.

Here's what I've got...


For **recipes/gym-saturation**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.
 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2022-02-01 23:07 UTC, inpefess commented
I confirm I'm willing to be listed as a maintainer of the `gym-saturation` package

2022-02-02 18:37 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/gym-saturation```) and found it was in an excellent condition.

2022-02-02 19:42 UTC, inpefess commented
PR is ready for review

2022-02-02 19:42 UTC, inpefess commented
@conda-forge-admin, please ping team

2022-02-02 19:42 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/staged-recipes and so here I am doing that.

2022-02-02 20:07 UTC, BastianZim requested changes

2022-02-02 20:07 UTC, BastianZim commented on recipes/gym-saturation/meta.yaml
> +    - lark-parser
It seems like these should be under `run` as they are required by the package: https://github.com/inpefess/gym-saturation/blob/f1e113b1bd798dea6de7f7ca10a3b6021d330d9f/pyproject.toml#L27-L28

2022-02-02 20:07 UTC, BastianZim commented on recipes/gym-saturation/meta.yaml
> +    - python >=3.7
Upstream lists `importlib_resources`: https://github.com/inpefess/gym-saturation/blob/f1e113b1bd798dea6de7f7ca10a3b6021d330d9f/pyproject.toml#L29

Is that not required?

2022-02-02 20:07 UTC, BastianZim commented on recipes/gym-saturation/meta.yaml
> +    - poetry
```suggestion
    - poetry-core >=1.0.0           
```

2022-02-03 10:12 UTC, inpefess commented
@BastianZim Thank you for your suggestions, I've commited fixes.

2022-02-03 14:13 UTC, ocefpaf commented
@BastianZim you were the first reviewer here so I'll defer to you? Ready for merge?

2022-02-03 14:16 UTC, BastianZim commented
Sorry, you were faster than me I was just double checking everything. :)

Yes, should be good to go!

2022-02-03 14:19 UTC, merged