Adding py-linux-ports recipe
conda-forge/staged-recipes pull request #17946
Opened 2022-02-05 15:54 UTC by sujitmandal

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-02-05 15:54 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/py-linux-ports```) and found it was in an excellent condition.

2022-02-05 16:14 UTC, sujitmandal commented
@conda-forge-coordinator @conda-forge-admin @conda-forge/help-python The recipe has passed all checks and is ready for your review, Thanks.

2022-02-05 16:57 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pstree```, ```recipes/py-linux-ports```, ```recipes/python-gmail```) and found some lint.

Here's what I've got...


For **recipes/pstree**:

 * Feedstock with the same name exists in conda-forge.

2022-02-05 17:04 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/py-linux-ports```, ```recipes/python-gmail```) and found it was in an excellent condition.

2022-02-05 17:05 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/py-linux-ports```, ```recipes/python-gmail```) and found some lint.

Here's what I've got...


For **recipes/py-linux-ports**:

 * Please do not delete the example recipe found in `recipes/example/meta.yaml`.

For **recipes/python-gmail**:

 * Please do not delete the example recipe found in `recipes/example/meta.yaml`.

2022-02-05 17:07 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/py-linux-ports```, ```recipes/python-gmail```) and found it was in an excellent condition.

2022-02-05 17:22 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/py-linux-ports```) and found it was in an excellent condition.

2022-02-10 10:26 UTC, BastianZim commented on recipes/py-linux-ports/meta.yaml
> +  version: "{{ version }}"
```suggestion
  name: {{ name|lower }}
  version: {{ version }}
```

2022-02-10 10:26 UTC, BastianZim commented on recipes/py-linux-ports/meta.yaml
> +  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
```suggestion
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
```

2022-02-10 10:26 UTC, BastianZim commented on recipes/py-linux-ports/meta.yaml
> +  script: "{{ PYTHON }} -m pip install . -vv"
```suggestion
  script: {{ PYTHON }} -m pip install . -vv
```
```suggestion
  script: "{{ PYTHON }} -m pip install . -vv"
```

2022-02-10 10:26 UTC, BastianZim commented on recipes/py-linux-ports/meta.yaml
> +    - python >=3.6
```suggestion
    - python >=2.7
```

Ref https://github.com/sujitmandal/py-linux-ports/blob/ca08fa238cc40ed0e808f2ee1f02be0d10404a7c/setup.py#L25

But you'll need to confirm if this is correct.

2022-02-10 10:26 UTC, BastianZim commented on recipes/py-linux-ports/meta.yaml
> +    - python >=3.6
```suggestion
    - python >=2.7
```

2022-02-10 10:26 UTC, BastianZim commented on recipes/py-linux-ports/meta.yaml
> +    - PyLinuxPorts
```suggestion
test:
  imports:
    - PyLinuxPorts
  commands:
    - pip check
  requires:
    - pip
```
This just double checks that the correct versions are installed.

2022-03-20 14:09 UTC, sujitmandal commented
@conda-forge-coordinator @conda-forge-admin  The recipe has passed all checks.

2022-03-20 23:05 UTC, BastianZim requested changes
Please implement all of my requests before pinging again. It seems like some are still missing.

2022-03-21 15:15 UTC, sujitmandal commented
> changes

i have changes all your suggest please check it.

2022-03-21 16:39 UTC, BastianZim requested changes

2022-03-21 16:39 UTC, BastianZim commented on recipes/py-linux-ports/meta.yaml
> +    - python >=3.6
```suggestion
    - python >=2.7
```

2022-03-21 16:39 UTC, BastianZim commented on recipes/py-linux-ports/meta.yaml
> +  script: "{{ PYTHON }} -m pip install . -vv"
```suggestion
  script: {{ PYTHON }} -m pip install . -vv
```

2022-03-21 16:39 UTC, BastianZim commented on recipes/py-linux-ports/meta.yaml
> +  version: "{{ version }}"
This has not been added yet.

2022-03-22 10:07 UTC, BastianZim approved these changes

2022-03-22 10:08 UTC, merged