Adding pyModelChecking
conda-forge/staged-recipes pull request #17978
Opened 2022-02-09 08:53 UTC by xtrojak

This PR adds a recipe for [pyModelChecking](https://github.com/albertocasagrande/pyModelChecking).

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-02-09 08:54 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pymodelchecking```) and found it was in an excellent condition.

2022-02-09 09:44 UTC, xtrojak commented
@conda-forge-admin, please restart ci

2022-02-11 07:34 UTC, xtrojak commented
@conda-forge-admin, please ping team

2022-02-11 07:34 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/staged-recipes and so here I am doing that.

2022-02-11 10:56 UTC, BastianZim requested changes

2022-02-11 10:58 UTC, BastianZim commented on recipes/pymodelchecking/meta.yaml
> +  license_file: LICENSE
I have created https://github.com/albertocasagrande/pyModelChecking/pull/6 to have it included, until then you can just manually copy the file here.

2022-02-11 15:08 UTC, xtrojak commented on recipes/pymodelchecking/meta.yaml
> +  license: MIT
Yes you are right, I didn't notice `grayskull` generated the recipe with `MIT` licence.

2022-02-11 15:11 UTC, xtrojak commented on recipes/pymodelchecking/meta.yaml
> +  license_file: LICENSE
Thank you for noticing this and creating the PR in the upstream tool. I added the license file in [9c8cc24](https://github.com/conda-forge/staged-recipes/pull/17978/commits/9c8cc24538f149f2eba4c029a5f9866573dd6c00).

2022-02-11 15:47 UTC, merged