Adding "compas-RV2", "compas_cloud", "compas_skeleton", "compas_tna"
conda-forge/staged-recipes pull request #18011
Opened 2022-02-11 15:02 UTC by Licini

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-02-11 15:03 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/compas_rv2```) and found some lint.

Here's what I've got...


For **recipes/compas_rv2**:

 * There are too few lines.  There should be one empty line at the end of the file.

2022-02-11 15:05 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/compas_rv2```) and found it was in an excellent condition.

2022-02-11 16:39 UTC, Licini commented
Hi @conda-forge/help-python , this PR is ready for review

2022-02-11 18:01 UTC, carterbox commented
@Licini, please actually *do* the things on the checklist; don't just check all the boxes. The other maintainers listed on the recipes need to comment here, and the title of this PR does not tell us what packages are being added.

2022-02-11 18:04 UTC, carterbox requested changes
Please complete the items on the checklist.

2022-02-16 12:28 UTC, Licini commented
@brgcode Could you acknowledge here : )

2022-02-17 10:54 UTC, brgcode commented
confirmed!

2022-02-17 16:41 UTC, carterbox requested changes
There is a syntax error from pip when packaging compas-RV2.

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=457350&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=4115

It seems to be because an object is using `None` as an attribute, which is illegal because `None` is a reserved word. Are you sure that your package is functioning correctly? I tried to make an object with a `None` attribute and the python interpreter raises a SyntaxError.

2022-02-17 16:41 UTC, carterbox commented on recipes/compas-RV2/meta.yaml
> +    - compas_rv2
```suggestion
test:
  imports:
    - compas_rv2
  requires:
    - pip
  commands:
    - pip check
```

2022-02-17 16:41 UTC, carterbox commented on recipes/compas-RV2/meta.yaml
> +    - compas_rv2
Since you are sourcing all of your packages from PyPI, please add `pip check` to the test section of all your packages.

2022-02-17 16:41 UTC, carterbox commented on recipes/compas_tna/meta.yaml
> +    - compas_tna
```suggestion
test:
  imports:
    - compas_tna
  requires:
    - pip
  commands:
    - pip check
```

2022-02-17 16:41 UTC, carterbox commented on recipes/compas_skeleton/meta.yaml
> +    - compas_skeleton
```suggestion
test:
  imports:
    - compas_skeleton
  requires:
    - pip
  commands:
    - pip check
```

2022-02-17 16:41 UTC, carterbox commented on recipes/compas_cloud/meta.yaml
> +    - compas_cloud
```suggestion
test:
  imports:
    - compas_cloud
  requires:
    - pip
  commands:
    - pip check
```

2022-02-23 15:56 UTC, Licini commented
> There is a syntax error from pip when packaging compas-RV2.
> 
> https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=457350&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=4115
> 
> It seems to be because an object is using `None` as an attribute, which is illegal because `None` is a reserved word. Are you sure that your package is functioning correctly? I tried to make an object with a `None` attribute and the python interpreter raises a SyntaxError.

Thanks @carterbox ! We updated the package to avoid the error. And added the other changes you suggested. Kindly let me know if everything look fine now.

2022-02-23 18:14 UTC, carterbox approved these changes

2022-02-23 18:14 UTC, merged