Add rabpro
conda-forge/staged-recipes pull request #18055
Opened 2022-02-15 18:46 UTC by jsta

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-02-15 18:46 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/rabpro```) and found some lint.

Here's what I've got...


For **recipes/rabpro**:

 * There are too few lines.  There should be one empty line at the end of the file.
 * ``requirements: host: python>=3.7,<3.10`` must contain a space between the name and the pin, i.e. ``python >=3.7,<3.10``
 * ``requirements: run: geopandas>=0.7.0`` must contain a space between the name and the pin, i.e. ``geopandas >=0.7.0``
 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

For **recipes/rabpro**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-02-15 18:49 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/rabpro```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/rabpro**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-02-15 18:54 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/rabpro```) and found it was in an excellent condition.

2022-02-15 19:17 UTC, jsta commented
I am willing to be listed as a maintainer.

2022-02-15 21:09 UTC, jonschwenk commented
I am willing to be listed as a maintainer.

2022-02-17 15:56 UTC, jsta commented
@conda-forge-admin ping conda-forge/help-python please.

2022-02-17 15:56 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/help-python and so here I am doing that.

2022-02-22 17:23 UTC, carterbox requested changes

2022-02-22 17:23 UTC, carterbox commented on recipes/rabpro/meta.yaml
> +    - python >=3.7,<3.10
```suggestion
    - python >=3.7
```

2022-02-22 17:23 UTC, carterbox commented on recipes/rabpro/meta.yaml
> +    - python >=3.7,<3.10
```suggestion
    - python >=3.7
```
Looks like upstream only has a minimum python version; are you sure that this package isn't forward compatible? If you are afraid of python=4, you can use pin_compatible to the major version.

https://github.com/VeinsOfTheEarth/rabpro/blob/main/setup.py

2022-02-22 20:46 UTC, carterbox requested changes

2022-02-22 20:46 UTC, carterbox commented on recipes/rabpro/meta.yaml
> +    - python >=3.7,<3.10
If `fiona` is incompatible with python 3.11, then that is something that the `fiona` recipe will enforce. This recipe should only describe the requirements of rabpro.

2022-02-22 20:51 UTC, jsta commented
@conda-forge-admin, please restart ci

2022-02-22 21:29 UTC, carterbox approved these changes
Approved, but waiting for Windows build check to finish.

2022-02-22 22:23 UTC, merged