Add capella-console-client
conda-forge/staged-recipes pull request #18059
Opened 2022-02-15 22:07 UTC by jordan-heemskerk

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-02-15 22:07 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/capella-console-client```) and found it was in an excellent condition.

2022-02-15 22:07 UTC, jordan-heemskerk commented
@conda-forge/help-python I believe this is ready for review, thanks

2022-02-16 10:18 UTC, BastianZim requested changes
Just a couple of comments regarding the overall structure and then I'll have a look at the recipe in detail. 

Can you please also run the recipe through [Grayskull](https://github.com/conda-incubator/grayskull) and check some of the formatting?

2022-02-16 10:18 UTC, BastianZim commented on recipes/capella-console-client/meta.yaml
> +build:
Can this be noarch?

2022-02-16 20:29 UTC, jordan-heemskerk commented on recipes/capella-console-client/meta.yaml
> +build:
added

2022-02-16 20:30 UTC, jordan-heemskerk commented on recipes/capella-console-client/meta.yaml
> +    - rich >=10.16.2,<11.0.0
Removed the unneeded host deps, oops

2022-02-16 20:30 UTC, jordan-heemskerk commented
@BastianZim I ran grayskull and used the updated formatting

2022-02-17 09:26 UTC, BastianZim requested changes
Looks good. Just one small thing and then this should be ready to go!

2022-02-17 09:26 UTC, BastianZim commented on recipes/capella-console-client/meta.yaml
> +    - poetry
```suggestion
    - poetry-core >=1.0.0
```
Ref: https://github.com/capellaspace/console-client/blob/bad631f207043231630c9b8c0893a1b4382d4061/pyproject.toml#L64

2022-02-17 17:52 UTC, merged