Enterprise outliers: a pulsar timing outliers analysis package
conda-forge/staged-recipes pull request #18119
Opened 2022-02-21 22:13 UTC by AaronDJohnson

Checklist
- [ X ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ X ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ X ] Source is from official source.
- [ X ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ X ] If static libraries are linked in, the license of the static library is packaged.
- [ X ] Build number is 0.
- [ X ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-02-21 22:13 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I was trying to look for recipes to lint for you, but couldn't find any.
Please ping the 'conda-forge/core' team (using the @ notation in a comment) if you believe this is a bug.

2022-02-21 22:17 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/enterprise_outliers```) and found some lint.

Here's what I've got...


For **recipes/enterprise_outliers**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.
 * ``requirements: build: python>=3.6,<3.10`` must contain a space between the name and the pin, i.e. ``python >=3.6,<3.10``
 * ``requirements: build: Cython>=0.28.5`` must contain a space between the name and the pin, i.e. ``Cython >=0.28.5``
 * ``requirements: host: python>=3.6,<3.10`` must contain a space between the name and the pin, i.e. ``python >=3.6,<3.10``
 * ``requirements: host: numpy>=1.16.3`` must contain a space between the name and the pin, i.e. ``numpy >=1.16.3``
 * ``requirements: host: scipy>=1.2.0`` must contain a space between the name and the pin, i.e. ``scipy >=1.2.0``
 * ``requirements: host: Cython>=0.28.5`` must contain a space between the name and the pin, i.e. ``Cython >=0.28.5``
 * ``requirements: host: scikit-sparse>=0.4.5`` must contain a space between the name and the pin, i.e. ``scikit-sparse >=0.4.5``
 * ``requirements: run: python>=3.6,<3.10`` must contain a space between the name and the pin, i.e. ``python >=3.6,<3.10``
 * ``requirements: run: numpy>=1.16.3`` must contain a space between the name and the pin, i.e. ``numpy >=1.16.3``
 * ``requirements: run: scipy>=1.2.0`` must contain a space between the name and the pin, i.e. ``scipy >=1.2.0``
 * ``requirements: run: Cython>=0.28.5`` must contain a space between the name and the pin, i.e. ``Cython >=0.28.5``
 * ``requirements: run: scikit-sparse>=0.4.5`` must contain a space between the name and the pin, i.e. ``scikit-sparse >=0.4.5``
 * ``requirements: run: enterprise-pulsar>=3.1.0`` must contain a space between the name and the pin, i.e. ``enterprise-pulsar >=3.1.0``
 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

For **recipes/enterprise_outliers**:

 * Recipes should usually depend on `matplotlib-base` as opposed to `matplotlib` so that runtime environments do not require large packages like `qt`.

2022-02-21 22:19 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/enterprise_outliers```) and found some lint.

Here's what I've got...


For **recipes/enterprise_outliers**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.

For **recipes/enterprise_outliers**:

 * Recipes should usually depend on `matplotlib-base` as opposed to `matplotlib` so that runtime environments do not require large packages like `qt`.

2022-02-21 22:20 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/enterprise_outliers```) and found some lint.

Here's what I've got...


For **recipes/enterprise_outliers**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.

2022-02-23 18:05 UTC, gabefreedman commented
This comment confirms that I am willing to be listed as a maintainer of this package.

2022-02-23 18:09 UTC, AaronDJohnson commented
In principle this should also work on Windows, but there are some dependencies that do not support it yet.

2022-02-23 18:09 UTC, AaronDJohnson commented
@conda-forge/help-python this is ready for review.

2022-02-24 18:18 UTC, dopplershift requested changes

2022-02-24 18:18 UTC, dopplershift commented on recipes/enterprise_outliers/meta.yaml
> +  noarch: python
Since this is building an extension, it can't be noarch:
```suggestion
```

2022-02-24 18:18 UTC, dopplershift commented on recipes/enterprise_outliers/meta.yaml
> +    - Cython >=0.28.5
I don't think Cython is needed at run-time.
```suggestion
```

2022-02-24 18:18 UTC, dopplershift commented on recipes/enterprise_outliers/meta.yaml
> +    - llvm-openmp
I don't think this is needed at run-time
```suggestion
```

2022-02-24 18:37 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/enterprise_outliers```) and found some lint.

Here's what I've got...


For **recipes/enterprise_outliers**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2022-02-24 18:46 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/enterprise_outliers```) and found it was in an excellent condition.

2022-02-24 19:12 UTC, AaronDJohnson commented
@dopplershift thanks for your help with this!

2022-02-24 19:12 UTC, dopplershift approved these changes

2022-02-24 19:12 UTC, merged