added sunkit-image recipe
conda-forge/staged-recipes pull request #18143
Opened 2022-02-23 17:26 UTC by nabobalis

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-02-23 17:27 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/sunkit-image```) and found it was in an excellent condition.

2022-02-23 18:09 UTC, Cadair commented on recipes/sunkit-image/meta.yaml
> +    - cadair
:+1:

2022-02-23 18:09 UTC, Cadair commented on recipes/sunkit-image/meta.yaml
> +  doc_url: https://docs.sunpy.org/projects/sunkit-image/en/stable/
```suggestion
  doc_url: https://docs.sunpy.org/projects/sunkit-image/
```

2022-02-23 18:29 UTC, nabobalis commented
Hi @conda-forge/help-python, this PR is ready to review.

2022-02-26 21:59 UTC, carterbox requested changes
Please check the Windows build. Your tests are failing not because of missing dependencies, but because of missing files during the tests.

I suggest checking the build output from pip to ensure that all package data is being included in the manifest and then checking that sunkit-image doesn't have any hardcoded paths. If you are using hardcoded paths to load resources, then I suggest looking at https://importlib-resources.readthedocs.io/en/latest/ instead of trying to manually guess the location of files.

2022-03-08 08:06 UTC, nabobalis commented
Hi @carterbox, sorry for the late reply.

I patched the released version and pushed an update to the recipe. Hopefully its ok now!

2022-03-08 18:56 UTC, carterbox commented
Looks like you still have some platform dependent differences in behavior of your package during the tests, but since it looks like you are a developer of sunkit-image, I guess you're OK with that.

2022-03-08 18:56 UTC, merged

2022-03-08 18:59 UTC, nabobalis commented
> Looks like you still have some platform dependent differences in behavior of your package during the tests, but since it looks like you are a developer of sunkit-image, I guess you're OK with that.

For now, it is something I plan to address in a refactor down the road.