initial commit for pyrsm 0.5.7
conda-forge/staged-recipes pull request #18174
Opened 2022-02-27 07:14 UTC by vnijs

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

Package maintainer `vnijs` confirming that package will be maintained

2022-02-27 07:14 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/example/pyrsm```) and found some lint.

Here's what I've got...


For **recipes/example/pyrsm**:

 * Please move the recipe out of the example dir and into its own dir.
 * Please do not delete the example recipe found in `recipes/example/meta.yaml`.
 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

For **recipes/example/pyrsm**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-02-27 07:29 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/example/pyrsm```, ```recipes/pyrsm```) and found some lint.

Here's what I've got...


For **recipes/example/pyrsm**:

 * Please move the recipe out of the example dir and into its own dir.
 * Please do not delete the example recipe found in `recipes/example/meta.yaml`.
 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

For **recipes/example/pyrsm**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

For **recipes/pyrsm**:

 * ``requirements: host: python >= 3.6`` should not contain a space between relational operator and the version, i.e. ``python >=3.6``
 * ``requirements: run: python >= 3.6`` should not contain a space between relational operator and the version, i.e. ``python >=3.6``

2022-02-27 08:27 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyrsm```) and found some lint.

Here's what I've got...


For **recipes/pyrsm**:

 * ``requirements: host: python >= 3.6`` should not contain a space between relational operator and the version, i.e. ``python >=3.6``
 * ``requirements: run: python >= 3.6`` should not contain a space between relational operator and the version, i.e. ``python >=3.6``

2022-03-07 00:32 UTC, vnijs commented
Just checking if there is anything else I need to do before this can be evaluated. Thanks

2022-03-19 18:38 UTC, vnijs commented
@conda-forge-admin, please ping team

2022-03-19 18:38 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/staged-recipes and so here I am doing that.

2022-03-19 19:00 UTC, BastianZim requested changes

2022-03-19 19:29 UTC, vnijs commented on recipes/pyrsm/meta.yaml
> +  license: GPL-2.0-or-later
@vnijs I would prefer to use AGPL 3but that wasn't listed as an option. Can I use AGPL3 for conda-forge?

2022-03-19 19:58 UTC, BastianZim commented on recipes/pyrsm/meta.yaml
> +  license: GPL-2.0-or-later
Yes, just use the one that I suggested. That is GNU Affero General Public License v3.0. 

By the way, a full list can be found here: https://spdx.org/licenses/

2022-03-19 20:26 UTC, BastianZim approved these changes

2022-03-19 20:51 UTC, merged