grayskull recipe for podaac-data-subscriber
conda-forge/staged-recipes pull request #18221
Opened 2022-03-03 16:26 UTC by kthyng

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-03-03 16:26 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/podaac-data-subscriber```) and found some lint.

Here's what I've got...


For **recipes/podaac-data-subscriber**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2022-03-03 16:28 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/podaac-data-subscriber```) and found it was in an excellent condition.

2022-03-07 21:01 UTC, beenje requested changes
Windows build failed with `Noarch package contains binary script: podaac-data-subscriber.exe`. I think it might be because of the missing `entry_points` definition in build. Add them and I think it should work.

2022-03-10 17:30 UTC, kthyng commented on recipes/podaac-data-subscriber/meta.yaml
> +  number: 0
I would not have figured this one out, thanks.

2022-03-10 17:30 UTC, kthyng commented on recipes/podaac-data-subscriber/meta.yaml
> +    - pip check
Or this...

2022-03-10 18:36 UTC, kthyng commented
@beenje Thanks for your help! It looks like I got it working with your changes. Is there anything else I can do on my end?

2022-03-10 20:21 UTC, beenje commented
Looks good to me now!

2022-03-10 20:21 UTC, merged