add napari-assistant receipe
conda-forge/staged-recipes pull request #18243
Opened 2022-03-05 09:12 UTC by haesleinhuepf

Hi @conda-forge/napari @goanpeca @jaimergp 

I'm submitting my first PR here adding the [napari-assistant](https://pypi.org/project/napari-assistant/). Let me know if I do this right :-)

Thanks!

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-03-05 09:12 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/napari-assistant```) and found some lint.

Here's what I've got...


For **recipes/napari-assistant**:

 * There are too few lines.  There should be one empty line at the end of the file.

2022-03-05 09:13 UTC, haesleinhuepf commented
@conda-forge/napari Are you ok maintaining this together with me? :-)

2022-03-05 09:14 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/napari-assistant```) and found it was in an excellent condition.

2022-03-08 23:55 UTC, goanpeca commented
>+ pip check
>napari-time-slicer 0.4.3 has requirement pyqt5>=5.15.0, but you have pyqt5 5.12.3.


Sometimes pip check does not do what we want it to do, so for this recipe, we need to comment or remove that line `pip check`

2022-03-08 23:55 UTC, goanpeca requested changes

2022-03-08 23:55 UTC, goanpeca commented on recipes/napari-assistant/meta.yaml
> +    - pip check
Comment or remove this line :)

2022-03-09 09:11 UTC, merged