adding zoofs recipe
conda-forge/staged-recipes pull request #18292
Opened 2022-03-10 20:54 UTC by jaswinder9051998

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-03-10 21:17 UTC, jaswinder9051998 commented
@conda-forge/help-python The recipe has passed all checks and is ready for your review. Thanks

2022-03-11 18:40 UTC, BastianZim requested changes
Just one thing then this is good to go!

2022-03-11 18:40 UTC, BastianZim commented on recipes/zoofs/meta.yaml
> +    - Jaswinder
```suggestion
    - jaswinder9051998
```
This needs to be your GitHub username

2022-03-11 21:10 UTC, BastianZim commented
@conda-forge-admin restart ci

2022-03-11 21:24 UTC, BastianZim approved these changes

2022-03-11 21:24 UTC, merged