Adding jsonschema2md package
conda-forge/staged-recipes pull request #18359
Opened 2022-03-16 11:30 UTC by ollyhensby

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-03-16 11:31 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/jsonschema2md```) and found it was in an excellent condition.

2022-03-17 11:39 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/jsonschema2md```) and found some lint.

Here's what I've got...


For **recipes/jsonschema2md**:

 * The recipe must have some tests.

2022-03-17 11:43 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/jsonschema2md```) and found it was in an excellent condition.

2022-03-17 17:54 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/jsonschema2md```) and found some lint.

Here's what I've got...


For **recipes/jsonschema2md**:

 * The recipe must have some tests.

2022-03-17 17:56 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/jsonschema2md```) and found it was in an excellent condition.

2022-03-17 18:06 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I was trying to look for recipes to lint for you, but couldn't find any.
Please ping the 'conda-forge/core' team (using the @ notation in a comment) if you believe this is a bug.

2022-03-18 17:06 UTC, ollyhensby commented
Hello @conda-forge-admin, ready for review and merge to main

2022-03-21 16:37 UTC, BastianZim requested changes

2022-03-21 16:37 UTC, BastianZim commented on recipes/jsonschema2md/meta.yaml
> +build:
This seems like it could be noarch: https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python

2022-03-21 16:37 UTC, BastianZim commented on recipes/jsonschema2md/meta.yaml
> +  run:
Upstream lists more deps: https://github.com/RalfG/jsonschema2md/blob/bcd8827e473922f00f6fe461c1e9a9a014045989/pyproject.toml#L23

Please add them as well.

2022-03-21 16:37 UTC, BastianZim commented on recipes/jsonschema2md/meta.yaml
> +    - poetry
```suggestion
    - poetry >=0.12
```

2022-03-21 16:37 UTC, BastianZim commented on recipes/jsonschema2md/meta.yaml
> +    - tests.py
You can include this kind of test here but a simple import test should be sufficient.

I'd recommend generating this package with Grayskull as Grayskull generally adds a sufficient test.

Ref: https://github.com/conda-incubator/grayskull

2022-03-23 12:21 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/jsonschema2md```) and found some lint.

Here's what I've got...


For **recipes/jsonschema2md**:

 * The top level meta keys are in an unexpected order. Expecting ['package', 'source', 'build', 'requirements', 'test', 'about', 'extra'].
 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.
 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2022-03-23 12:30 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/jsonschema2md```) and found some lint.

Here's what I've got...


For **recipes/jsonschema2md**:

 * The recipe must have a `build/number` section.
 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.

2022-03-23 12:45 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/jsonschema2md```) and found it was in an excellent condition.

2022-03-23 14:43 UTC, ollyhensby commented
Made changes as requested and is now ready to merge with main

2022-03-23 14:46 UTC, BastianZim requested changes
One small thing then this is ready.

2022-03-23 14:46 UTC, BastianZim commented on recipes/jsonschema2md/meta.yaml
> +    - python
```suggestion
    - python >=3.6
```

2022-03-23 14:55 UTC, ollyhensby commented on recipes/jsonschema2md/meta.yaml
> +    - python
Sweet. Just added this to the meta.yaml

2022-03-23 14:58 UTC, BastianZim approved these changes

2022-03-23 14:59 UTC, merged