Add recipe for scikit-datasets.
conda-forge/staged-recipes pull request #18457
Opened 2022-03-24 19:31 UTC by vnmabus

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-03-24 19:34 UTC, vnmabus commented
I confirm I am willing to be listed there.

2022-04-04 13:53 UTC, vnmabus commented
@conda-forge/staged-recipes I think this is ready to review. I am unsure of what to do with the optional dependencies in `extras_require`, as Conda does not support optional dependencies, AFAIK.

2022-04-05 16:55 UTC, dopplershift requested changes
Just needs a minor tweak.

For optional dependencies:
1. If you think it's really important and most users will want it, you can add it as a regular dependency
2.  User [multiple outputs](https://github.com/conda-forge/gstreamer-feedstock/blob/main/recipe/meta.yaml) from the recipe to create a second package that includes some/all of the optional ones
3. Just rely on users installing what they need when they need it.

2022-04-05 16:55 UTC, dopplershift commented on recipes/scikit-datasets/scikit-datasets/meta.yaml
> +    - python
Need to specify a version for Python:
```suggestion
    - python >=3.8
  run:
    - numpy
    - python >=3.8
```

2022-04-05 17:55 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/scikit-datasets/scikit-datasets```) and found some lint.

Here's what I've got...


For **recipes/scikit-datasets/scikit-datasets**:

 * Please do not delete the example recipe found in `recipes/example/meta.yaml`.

2022-04-05 17:56 UTC, vnmabus commented
> Just needs a minor tweak.
> 
> For optional dependencies:
> 
>     1. If you think it's really important and most users will want it, you can add it as a regular dependency
> 
>     2. User [multiple outputs](https://github.com/conda-forge/gstreamer-feedstock/blob/main/recipe/meta.yaml) from the recipe to create a second package that includes some/all of the optional ones
> 
>     3. Just rely on users installing what they need when they need it.

I will take option 3 for now, and study option 2 in the future.

2022-04-05 18:03 UTC, dopplershift requested changes
I didn't notice this before, but currently your recipe is located in `recipes/scikit-datasets/scikit-datasets/meta.yaml`. It should instead be located in `recipes/scikit-datasets/meta.yaml`.

2022-04-05 18:25 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/scikit-datasets```) and found it was in an excellent condition.

2022-04-05 18:26 UTC, vnmabus commented
> I didn't notice this before, but currently your recipe is located in `recipes/scikit-datasets/scikit-datasets/meta.yaml`. It should instead be located in `recipes/scikit-datasets/meta.yaml`.

Yup, my bad. Fixed now.

2022-04-05 18:41 UTC, dopplershift approved these changes

2022-04-05 18:41 UTC, merged