Geomcompare
conda-forge/staged-recipes pull request #18483
Opened 2022-03-26 21:54 UTC by MTachon

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-03-26 21:54 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/geomcompare```) and found some lint.

Here's what I've got...


For **recipes/geomcompare**:

 * Failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint .` from the recipe directory.

2022-03-26 22:02 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/geomcompare```) and found some lint.

Here's what I've got...


For **recipes/geomcompare**:

 * The recipe could do with some maintainers listed in the `extra/recipe-maintainers` section.
 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [14]

2022-03-26 22:07 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/geomcompare```) and found some lint.

Here's what I've got...


For **recipes/geomcompare**:

 * The recipe could do with some maintainers listed in the `extra/recipe-maintainers` section.

2022-03-26 22:12 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/geomcompare```) and found it was in an excellent condition.

2022-03-28 06:55 UTC, MTachon commented
I am the only author of the package and maintainer of this recipe. It is fine for me to be listed here.

2022-09-20 14:47 UTC, ocefpaf requested changes

2022-09-20 14:47 UTC, ocefpaf commented on recipes/geomcompare/meta.yaml
> +  md5: 99115b09a972b0c53babbe074cdd0747
```suggestion
```

2022-09-20 14:47 UTC, ocefpaf commented on recipes/geomcompare/meta.yaml
> +  skip: True  # [py < 39 or osx]
```suggestion
  [skip: True  # [py < 39 or osx]](noarch: python)
```

2022-09-20 14:47 UTC, ocefpaf commented on recipes/geomcompare/meta.yaml
> +    - python
```suggestion
    - python >=3.9
```

2022-09-20 14:47 UTC, ocefpaf commented on recipes/geomcompare/meta.yaml
> +    - python
```suggestion
    - python >=3.9
```

2022-09-20 14:47 UTC, ocefpaf commented on recipes/geomcompare/meta.yaml
> +    - libspatialite
These are not defined upstream. Are they extras?

2022-09-20 14:47 UTC, ocefpaf commented on recipes/geomcompare/meta.yaml
> +    - geomcompare
```suggestion
    - geomcompare
  commands:
    - pip check
  requires:
    - pip
```

2022-09-20 14:47 UTC, ocefpaf commented on recipes/geomcompare/LICENSE.rst
> +GNU General Public License
The license is in the package. You don't need this file here.

2023-04-16 01:32 UTC, closed without merging