Adding fpfs recipe
conda-forge/staged-recipes pull request #18509
Opened 2022-03-29 21:15 UTC by mr-superonion

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-03-29 21:15 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/fpfs```) and found some lint.

Here's what I've got...


For **recipes/fpfs**:

 * about/license_family 'GPL-3.0' not allowed. Allowed families are AGPL,
APACHE, BSD, CC, GPL, GPL2, GPL3, LGPL, MIT, MOZILLA, NONE, OTHER,
PROPRIETARY, PSF, and PUBLIC-DOMAIN.

For **recipes/fpfs**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-03-29 21:21 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/fpfs```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/fpfs**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-03-30 00:36 UTC, mr-superonion commented
Hello @conda-forge/help-python 
The recipe has passed all the checks and is ready for your review.
Best regards

2022-03-30 12:21 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/fpfs```) and found it was in an excellent condition.

2022-03-30 12:40 UTC, mr-superonion commented
@conda-forge-admin This is ready for review, thanks!

2022-03-30 12:42 UTC, mr-superonion commented
@conda-forge-admin, please ping conda-forge/help-python

2022-03-31 14:54 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/fpfs```) and found some lint.

Here's what I've got...


For **recipes/fpfs**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.

2022-03-31 14:56 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/fpfs```) and found some lint.

Here's what I've got...


For **recipes/fpfs**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2022-03-31 14:59 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/fpfs```) and found it was in an excellent condition.

2022-04-03 19:29 UTC, ngam requested changes
almost there

2022-04-03 19:29 UTC, ngam commented on recipes/fpfs/meta.yaml
> +  git_url: https://github.com/mr-superonion/FPFS/
Let's use tar balls instead if possible pls

2022-04-03 19:29 UTC, ngam commented on recipes/fpfs/meta.yaml
> +    - python
```suggestion
    - python >=3.7
```

2022-04-03 19:29 UTC, ngam commented on recipes/fpfs/meta.yaml
> +  skip: True  # [win]
```suggestion
  noarch: python
```

2022-04-03 19:29 UTC, ngam commented on recipes/fpfs/meta.yaml
> +    - python
```suggestion
    - python >=3.7
```

2022-04-03 19:29 UTC, ngam commented on recipes/fpfs/meta.yaml
> +    - fpfs
```suggestion
test:
  imports:
    - fpfs
  requires:
    - pip
  commands:
    - pip check
```

2022-11-12 18:42 UTC, closed without merging