gopeaks first commit
conda-forge/staged-recipes pull request #18628
Opened 2022-04-08 18:44 UTC by gartician

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-04-08 18:44 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/gopeaks```) and found some lint.

Here's what I've got...


For **recipes/gopeaks**:

 * There are 1 too many lines.  There should be one empty line at the end of the file.

2022-04-08 18:58 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/gopeaks```) and found it was in an excellent condition.

2022-04-08 19:08 UTC, gartician commented
Hi conda forge I am willing to be a maintainer of this package.

2022-04-08 19:13 UTC, gartician commented
@conda-forge-admin this package is ready for review!

2022-04-21 16:08 UTC, gartician commented
@conda-forge-admin, please ping conda-forge/staged-recipes

2022-04-21 16:08 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/staged-recipes and so here I am doing that.

2022-04-29 23:40 UTC, carterbox requested changes
I'm pretty sure you aren't including all of the licenses for the dependencies which have been statically linked into this project. Please see this issue for more details:

https://github.com/conda-forge/conda-forge.github.io/issues/1052

2022-04-29 23:40 UTC, carterbox commented on recipes/gopeaks/meta.yaml
> +  skip: win
```suggestion
  skip:  # [win]
```

2022-04-29 23:40 UTC, carterbox commented on recipes/gopeaks/meta.yaml
> +    - go
```suggestion
  build:
    - {{ compiler('go') }}
    - go-licenses
```

2022-05-06 05:49 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/gopeaks```) and found some lint.

Here's what I've got...


For **recipes/gopeaks**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [13]
 * There are 1 too many lines.  There should be one empty line at the end of the file.
 * The extra section contained an unexpected subsection name. skip-lints is not a valid subsection name.

2022-05-06 06:03 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/gopeaks```) and found some lint.

Here's what I've got...


For **recipes/gopeaks**:

 * There are 2 too many lines.  There should be one empty line at the end of the file.

2022-05-06 06:09 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/gopeaks```) and found some lint.

Here's what I've got...


For **recipes/gopeaks**:

 * There are 1 too many lines.  There should be one empty line at the end of the file.

2022-05-06 06:10 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/gopeaks```) and found it was in an excellent condition.

2022-05-08 18:09 UTC, gartician commented
Hi @carterbox thanks for your help with this PR, I think this package is a better fit for the bioconda channel since this is a bioinformatics program. Thank you for your time, and I will close this PR!

2022-05-08 18:09 UTC, closed without merging