Add recipe for readuct
conda-forge/staged-recipes pull request #18632
Opened 2022-04-09 08:41 UTC by awvwgk

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-04-09 08:41 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/scine-readuct```) and found some lint.

Here's what I've got...


For **recipes/scine-readuct**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [28]

2022-04-09 08:51 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/scine-readuct```) and found it was in an excellent condition.

2022-04-09 09:18 UTC, awvwgk commented
@conda-forge/help-c-cpp This recipe is ready for review.

2022-04-12 20:22 UTC, awvwgk commented
@conda-forge/staged-recipes This recipe is ready for review

2022-04-19 11:00 UTC, wolfv commented on recipes/scine-readuct/meta.yaml
> +    fn: dev.tar.gz
this should not be needed actually

2022-04-19 11:00 UTC, wolfv commented on recipes/scine-readuct/meta.yaml
> +    fn: {{ name }}.tar.gz
this shoudl not be needed.

2022-04-19 11:02 UTC, wolfv commented
Looks good to me

2022-04-20 11:29 UTC, awvwgk commented
@wolfv Requested changes have been implemented.

2022-04-30 16:33 UTC, carterbox requested changes
[Link checker reports that](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=498949&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7&t=fa7b4b17-b6ff-5c9c-8cfc-15f888c92310&l=3747) `libblas` and `openmp` are not being linked against on the OSX build. Please switch to dynamic linking or remove these dependencies for that platform.

2022-05-02 21:16 UTC, merged