add yaqd-attune
conda-forge/staged-recipes pull request #18760
Opened 2022-04-25 20:45 UTC by untzag

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-04-25 20:45 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/yaqd-attune```) and found it was in an excellent condition.

2022-04-25 21:42 UTC, ksunden commented
Willing

2022-05-16 18:39 UTC, ksunden commented
@conda-forge/staged-recipes

I believe this is ready for merging

2022-05-16 21:52 UTC, carterbox requested changes
It looks like this is one package, but the yaqd-attune-gui package just adds additional dependencies, yes? In that case, yaqd-attune-gui should be an empty meta-package which depends on yaqd-attune plus the addtional dependencies.

Right now, the two package have duplicate files which is why the build logs show an [overlap warning.](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=497414&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=3556)

[Here is an example](https://github.com/conda-forge/importlib_resources-feedstock/blob/main/recipe/meta.yaml) of a recipe with a main package plus an empty metapackage.

2022-05-16 21:59 UTC, carterbox commented on recipes/yaqd-attune/meta.yaml
> +      script: python -m pip install . -vv
The reason that `{{ PYTHON }}` doesn't work here is that script in the output section expects the name of a script not a script literal.

https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#specifying-files-to-include-in-output

2023-04-13 12:32 UTC, closed without merging