Adding `yt-dlg`
conda-forge/staged-recipes pull request #18819
Opened 2022-05-02 13:21 UTC by HeavyTony2

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-05-02 13:22 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/yt-dlg```) and found it was in an excellent condition.

2022-05-02 14:12 UTC, HeavyTony2 commented
@conda-forge/help-python
I already adressed upstream the dependancy issue with numpy and Pillow for wxpython https://github.com/conda-forge/wxpython-feedstock/pull/81

2022-05-04 19:39 UTC, carterbox requested changes

2022-05-04 19:39 UTC, carterbox commented on recipes/yt-dlg/meta.yaml
> +    - pip check
```suggestion
  commands:
    - pip check
    - yt-dlg --version
```
Test your entry points. On latest you can query the version and return.

2022-05-05 01:10 UTC, HeavyTony2 commented
@carterbox : It requires a graphic display. https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=502046&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7&t=fa7b4b17-b6ff-5c9c-8cfc-15f888c92310&l=2244

2022-05-05 16:23 UTC, merged