add independent fenics-ufl
conda-forge/staged-recipes pull request #18890
Opened 2022-05-10 14:00 UTC by minrk

fenics-ufl is part of the newer fenicsx project, and versioned independently of the previously coordinated fenics recipe, so starting a new feedstock for one package at a time.

Related: #18888

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-05-10 14:01 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/fenics-ufl```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/fenics-ufl**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-05-10 14:09 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/fenics-ufl```) and found it was in an excellent condition.

2022-05-11 09:11 UTC, minrk commented
Ready for review @conda-forge/help-python

2022-05-15 17:29 UTC, carterbox requested changes

2022-05-15 17:29 UTC, carterbox commented on recipes/fenics-ufl/meta.yaml
> +  # 0.4.1 isn't on PyPI
```suggestion
```
Maybe this is copypasta?

2022-05-15 17:29 UTC, carterbox commented on recipes/fenics-ufl/meta.yaml
> +    - setuptools
```suggestion
    - setuptools >=58
```

2022-05-15 17:33 UTC, carterbox approved these changes

2022-05-15 17:43 UTC, merged