add wirerope and methodtools
conda-forge/staged-recipes pull request #18907
Opened 2022-05-11 19:44 UTC by timkpaine

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-05-11 19:44 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/methodtools```, ```recipes/wirerope```) and found some lint.

Here's what I've got...


For **recipes/methodtools**:

 * There are too few lines.  There should be one empty line at the end of the file.
 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

For **recipes/wirerope**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.
 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2022-05-11 19:47 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/methodtools```, ```recipes/wirerope```) and found it was in an excellent condition.

2022-05-11 20:03 UTC, timkpaine commented
@conda-forge/help-python all set!

2022-05-16 11:18 UTC, BastianZim requested changes
Just two small things and this is good to go.

2022-05-16 11:18 UTC, BastianZim commented on recipes/methodtools/meta.yaml
> +    Expand standard functools to methods
If it's a duplicate, you don't need to include it.

2022-05-16 11:18 UTC, BastianZim commented on recipes/methodtools/meta.yaml
> +  run:
For python 2, functools32 is required: https://github.com/youknowone/methodtools#installation

As conda-forge doesn't support Python 2 anymore, I would change the bound to 3.6.

2022-05-16 12:30 UTC, BastianZim commented
Looks good. Please ping me again when the CI is finished and I'll merge it.

2022-05-16 12:30 UTC, BastianZim approved these changes

2022-05-16 13:02 UTC, merged