Add Squidpy recipe
conda-forge/staged-recipes pull request #18954
Opened 2022-05-16 12:09 UTC by michalk8

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-05-16 12:09 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/squidpy```) and found it was in an excellent condition.

2022-05-16 12:10 UTC, michalk8 commented
@giovp please confirm you're willing to maintain this recipe

2022-05-17 06:43 UTC, michalk8 commented
@conda-forge-admin, please restart ci

2022-05-17 08:53 UTC, michalk8 commented
@conda-forge/help-python, ready for review!

2022-05-24 11:59 UTC, BastianZim requested changes

2022-05-29 22:31 UTC, michalk8 commented on recipes/squidpy/meta.yaml
> +    - {{ name|lower }}
Ok, I've changed it just in case.

2022-05-29 22:31 UTC, michalk8 commented on recipes/squidpy/meta.yaml
> +    - dask[array] >=2021.02.0
Thanks, it contains the extra array requirements!.

2022-05-30 09:09 UTC, BastianZim approved these changes

2022-05-30 09:09 UTC, merged