Adding geodemora recipe
conda-forge/staged-recipes pull request #19055
Opened 2022-05-24 11:21 UTC by ramendra1990

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-05-24 11:21 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/geodemora```) and found some lint.

Here's what I've got...


For **recipes/geodemora**:

 * ``requirements: host: python >= 3.8`` should not contain a space between relational operator and the version, i.e. ``python >=3.8``
 * ``requirements: run: python >= 3.8`` should not contain a space between relational operator and the version, i.e. ``python >=3.8``

2022-05-24 11:30 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/geodemora```) and found it was in an excellent condition.

2022-05-24 11:54 UTC, ramendra1990 commented
@conda-forge/help-python the recipe has passed all the checks and is ready for your review. Thanks.

2022-05-28 13:39 UTC, BastianZim requested changes
Just a couple of small things, then this is ready to go 🚀

2022-05-28 13:39 UTC, BastianZim commented on recipes/geodemora/meta.yaml
> +    - geodemora
```suggestion
test:
  imports:
    - geodemora
  commands:
    - pip check
  requires:
    - pip
```

2022-05-28 13:39 UTC, BastianZim commented on recipes/geodemora/meta.yaml
> +    - python >=3.8
```suggestion
    - python >=3.7
```
Ref: https://github.com/ramendra1990/geodemora/blob/2cee3b7398f95baa4433c03573f5b58879ef1d58/setup.py#L30

2022-05-28 13:39 UTC, BastianZim commented on recipes/geodemora/meta.yaml
> +    - python >=3.8
```suggestion
    - python >=3.7
```

2022-05-29 21:13 UTC, merged