[WIP] Adding support for river
conda-forge/staged-recipes pull request #19162
Opened 2022-06-06 22:07 UTC by pbotros

DO NOT MERGE yet. Opening to test CI.

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-06-06 22:07 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/river```) and found some lint.

Here's what I've got...


For **recipes/river**:

 * Feedstock with the same name exists in conda-forge.
 * If python is a host requirement, it should be a run requirement.

2022-06-06 22:24 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/river```) and found it was in an excellent condition.

2022-06-07 04:58 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/river-cpp```) and found it was in an excellent condition.

2022-06-07 15:35 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/river-cpp```, ```recipes/river-py```) and found it was in an excellent condition.

2022-06-07 19:47 UTC, pbotros commented
@conda-forge-admin, please ping help-c-cpp

2022-06-07 19:47 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/help-c-cpp and so here I am doing that.

2022-06-09 01:04 UTC, beckermr requested changes
We should use a run export.

2022-06-09 01:04 UTC, beckermr commented on recipes/river-cpp/meta.yaml
> +  number: 0
We should add a run export giving the Abi range.

2022-06-09 10:30 UTC, beckermr commented on recipes/river-py/meta.yaml
> +    - river-cpp
```suggestion
```

Not needed now due to run export.

2022-06-09 10:31 UTC, beckermr approved these changes

2022-06-09 11:21 UTC, merged

2022-06-09 13:58 UTC, pbotros commented
Thanks @beckermr for the prompt review and feedback!