add digitalearth package
conda-forge/staged-recipes pull request #19178
Opened 2022-06-07 20:25 UTC by MAfarrag

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-06-07 20:25 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/digitalearth```) and found it was in an excellent condition.

2022-06-08 18:46 UTC, MAfarrag commented
@conda-forge/python-help all chacks have passed here please review.

2022-06-08 18:49 UTC, MAfarrag commented
@conda-forge/staged-recipes all chacks have passed here please review.

2022-06-08 19:50 UTC, dopplershift requested changes
A bunch of really minor things. The broken URLs is the main problem.

2022-06-08 19:50 UTC, dopplershift commented on recipes/digitalearth/meta.yaml
> +  license_family: GPL
```suggestion
  license_family: GPL3
```

2022-06-08 19:50 UTC, dopplershift commented on recipes/digitalearth/meta.yaml
> +  home: https://github.com/MAfarrag/digitalearth
```suggestion
  home: https://github.com/MAfarrag/Digital-Earth
```

2022-06-08 19:50 UTC, dopplershift commented on recipes/digitalearth/meta.yaml
> +  dev_url: https://github.com/MAfarrag/digitalearth
```suggestion
  dev_url: https://github.com/MAfarrag/Digital-Earth
```

2022-06-08 19:50 UTC, dopplershift commented on recipes/digitalearth/meta.yaml
> +  doc_source_url: https://github.com/MAfarrag/digitalearth/main/README.md
```suggestion
  doc_source_url: https://github.com/MAfarrag/Digital-Earth/main/README.md
```

2022-06-08 19:50 UTC, dopplershift commented on recipes/digitalearth/meta.yaml
> +    - python  >=3.7.1,<3.10
```suggestion
    - python >=3.7.1,<3.10
```

2022-06-08 19:50 UTC, dopplershift commented on recipes/digitalearth/meta.yaml
> +    - python  >=3.7.1,<3.10
```suggestion
    - python >=3.7.1,<3.10
```

2022-06-08 23:33 UTC, dopplershift approved these changes

2022-06-08 23:49 UTC, MAfarrag commented
@dopplershift thanks for your review, i have made the changes and now all the checks passed. Thanks

2022-06-09 00:23 UTC, merged