add pyglider
conda-forge/staged-recipes pull request #19353
Opened 2022-06-21 15:20 UTC by jklymak

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-06-21 15:20 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyglider```) and found it was in an excellent condition.

2022-06-22 07:35 UTC, jklymak commented
@conda-forge/help-python - I think this is ready for review, but please let me know if there are any errors..

2022-06-25 13:48 UTC, BastianZim requested changes
Just one small cosmetic thing, then this is ready to go 🚀

2022-06-25 13:48 UTC, BastianZim commented on recipes/pyglider/meta.yaml
> +  license_file: LICENSE
```suggestion
  license_file: LICENSE
  dev_url: https://github.com/c-proof/pyglider
```

2022-06-25 14:20 UTC, jklymak commented
@conda-forge/help-python Added the requested field, should be good to go again!  Thanks,

2022-06-25 14:20 UTC, merged

2022-06-25 14:24 UTC, jklymak commented
Thanks for your help @BastianZim