Add recipe for LBFGSpp
conda-forge/staged-recipes pull request #19371
Opened 2022-06-23 11:16 UTC by awvwgk

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-06-23 11:16 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/lbfgspp```) and found some lint.

Here's what I've got...


For **recipes/lbfgspp**:

 * Failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint .` from the recipe directory.

2022-06-23 11:19 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/lbfgspp```) and found it was in an excellent condition.

2022-06-28 21:48 UTC, carterbox requested changes

2022-06-28 21:48 UTC, carterbox commented on recipes/lbfgspp/meta.yaml
> +
```suggestion
  host:
    - eigen =3.0.*
  run:
    - eigen =3.0.*
```
Two things:

1. Upstream [explicitly requires eigen 3.0](https://github.com/yixuan/LBFGSpp/blob/00f0f1bd96689bd40e6c8b16cc135665eed5acc9/CMakeLists.txt#L41)
2. To be nice to users, we add eigen to the run section so when they add this package to requirements, eigen is also added (it's mentioned in the headers).

2022-06-28 21:48 UTC, carterbox commented on recipes/lbfgspp/meta.yaml
> +    - if not exist %LIBRARY_PREFIX%\include\LBFGSB.h exit 1  # [win]
Could you please also compile and run a test program in the test section from the examples to check that this library is compatible with our compilers? Sometimes our compilers are too old and require source patches to silence syntax errors, etc.

2022-06-28 21:55 UTC, carterbox commented on recipes/lbfgspp/meta.yaml
> +
I think the cmake version requirements is actually equivalent to `>=3.0,<4`. Otherwise, the builds would have failed already.

2022-06-29 11:15 UTC, awvwgk commented
@conda-forge/help-c-cpp Requested changes are addressed now.

2022-06-29 15:10 UTC, carterbox requested changes

2022-06-29 15:21 UTC, carterbox requested changes

2022-06-29 15:21 UTC, carterbox commented on recipes/lbfgspp/meta.yaml
> +    - for i in examples/*.cpp; do $CXX $CXXFLAGS -o "$i.out" "$i" && "$i.out"; done  # [unix]
```suggestion
    - for i in examples/*.cpp; do $CXX $CXXFLAGS -I$PREFIX/include/eigen3 -o "$i.out" "$i" && "$i.out"; done  # [unix]
```
This is probably the issue with your script.

2022-06-29 18:58 UTC, awvwgk commented
@conda-forge/help-c-cpp Fixed example compilation. Thanks @carterbox.

2022-06-29 20:00 UTC, merged