Add recipe for fmrib-unpack-fmrib-config
conda-forge/staged-recipes pull request #19372
Opened 2022-06-23 11:26 UTC by pauldmccarthy

Howdy, the `fmrib-unpack-fmrib-config` package contains configuration files for [`fmrib-unpack`](https://github.com/conda-forge/fmrib-unpack-feedstock/), which is a data processing tool for the [UK BioBank](https://biobank.ctsu.ox.ac.uk/). The `fmrib-unpack-fmrib-config` package is already up on PyPi. Thanks!

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-06-23 11:26 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/fmrib-unpack-fmrib-config```) and found some lint.

Here's what I've got...


For **recipes/fmrib-unpack-fmrib-config**:

 * The recipe must have some tests.
 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2022-06-23 11:29 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/fmrib-unpack-fmrib-config```) and found it was in an excellent condition.

2022-06-27 09:17 UTC, pauldmccarthy commented
@conda-forge/staged-recipes, this recipe is ready for review - thanks!

2022-06-27 12:17 UTC, ocefpaf requested changes
No need for a jinja variable fot something that is used once. It decreases recipe readability without adding any advantage.

2022-06-27 12:17 UTC, ocefpaf commented on recipes/fmrib-unpack-fmrib-config/meta.yaml
> +{% set sha256 = "a6665b6687d2f71de9becff0a4e243af23fe98e78a251499346a1b499a8b4758" %}
```suggestion
```

2022-06-27 12:17 UTC, ocefpaf commented on recipes/fmrib-unpack-fmrib-config/meta.yaml
> +  sha256: {{ sha256 }}
```suggestion
  sha256: a6665b6687d2f71de9becff0a4e243af23fe98e78a251499346a1b499a8b4758
```

2022-06-27 13:19 UTC, merged