creating recipe for strawberry-graphql
conda-forge/staged-recipes pull request #19377
Opened 2022-06-23 17:47 UTC by cshaley

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-06-23 17:47 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/strawberry-graphql```) and found it was in an excellent condition.

2022-06-23 18:35 UTC, cshaley commented
@conda-forge/help-python ready for review

2022-06-25 13:37 UTC, BastianZim requested changes
Just a couple of small things, then this is ready to go 🚀

2022-06-25 13:37 UTC, BastianZim commented on recipes/strawberry-graphql/meta.yaml
> +  license_file: LICENSE
```suggestion
  license_file: LICENSE
  dev_url: https://github.com/strawberry-graphql/strawberr
  doc_url: https://strawberry.rocks/docs
```

2022-06-25 13:37 UTC, BastianZim commented on recipes/strawberry-graphql/meta.yaml
> +    - poetry
```suggestion
    - poetry >=0.12
```

2022-06-25 13:37 UTC, BastianZim commented on recipes/strawberry-graphql/meta.yaml
> +    - python >=3.6,<4.0
```suggestion
    - python >=3.7
```
The upper bound is set by conda-forge once we get there.

Ref: https://github.com/strawberry-graphql/strawberry/blob/c88647514cf78c17b151ee6e8e0a17afc89c6ded/pyproject.toml#L25

2022-06-25 13:37 UTC, BastianZim commented on recipes/strawberry-graphql/meta.yaml
> +    - python >=3.6,<4.0
```suggestion
    - python >=3.7
```

2022-06-25 14:16 UTC, cshaley commented
@BastianZim Changes committed and tests passed

2022-06-25 14:20 UTC, BastianZim approved these changes

2022-06-25 14:20 UTC, merged