add pybboxes recipe
conda-forge/staged-recipes pull request #19424
Opened 2022-06-25 20:38 UTC by fcakyon

@conda-forge/help-python|

ready for review!

2022-06-25 20:38 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pybboxes```) and found some lint.

Here's what I've got...


For **recipes/pybboxes**:

 * Please do not delete the example recipe found in `recipes/example/meta.yaml`.

2022-06-25 20:39 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pybboxes```) and found it was in an excellent condition.

2022-06-26 06:56 UTC, fcakyon commented
@conda-forge/help-python|

ready for review!

2022-06-26 13:09 UTC, fcakyon commented
@conda-forge/staged-recipes ready for review!

2022-06-26 21:41 UTC, fcakyon commented
@isuruf do you know why checks fail?

2022-06-27 09:36 UTC, closed without merging

2022-06-28 11:25 UTC, fcakyon commented
Hey @weiji14, sorry for bothering you. Would you help me passing tests for this package? :sweat_smile: I am pinging you since you were the one helping me for SAH conda-forge package :rocket: I

2022-06-28 15:00 UTC, weiji14 reviewed
> Hey @weiji14, sorry for bothering you. Would you help me passing tests for this package? sweat_smile I am pinging you since you were the one helping me for SAHI conda-forge package rocket

Sure, I can spare a few minutes. Maybe try adding `pyhumps` as a host dependency as suggested below. If you want to test things locally, follow instructions at https://conda-forge.org/docs/maintainer/updating_pkgs.html#testing-changes-locally.

2022-06-28 22:56 UTC, carterbox requested changes
@fcakyon, please do not remove our [pull-request checklist ](https://github.com/conda-forge/staged-recipes/blob/main/.github/pull_request_template.md)from the top of your PR. I have restored it for you. All of these things must be complete before your PR is ready to be merged. For example, not all of the persons listed in maintainers has commented.

Your recipe has also not successfully built yet. Do ask specific questions if you need help in the future instead of just "ready for review".

This recipe is waiting on https://github.com/conda-forge/pyhumps-feedstock/issues/2 to be resolved.

2022-06-29 05:45 UTC, fcakyon commented
@devrimcavusoglu, are you willing to be added as a maintainer for the pybboxes conda-forge distribution?

2022-06-29 05:46 UTC, fcakyon commented on recipes/pybboxes/meta.yaml
> +    - pip
@weiji14 unfortunately it still gives pyhumps error

2022-06-29 05:47 UTC, fcakyon commented
@carterbox I have no idea why tests are failing? Is there anyone that can tell me what is missing?

2022-06-29 05:51 UTC, fcakyon commented
Can someone guide me on what to change to pass the tests? @conda-forge/staged-recipes I have read all the knowledge base documentation.

2022-06-29 15:32 UTC, carterbox commented
> This recipe is waiting on https://github.com/conda-forge/pyhumps-feedstock/issues/2 to be resolved.

2022-07-01 16:24 UTC, carterbox commented
Please ping the team again when this issue is resolved.

2022-07-08 09:25 UTC, devrimcavusoglu requested changes
Fields need to be updated

2022-07-08 09:25 UTC, devrimcavusoglu commented on recipes/pybboxes/meta.yaml
> +{% set version = "0.1.2" %}
```suggestion
{% set version = "0.1.3" %}
```

2022-07-08 09:25 UTC, devrimcavusoglu commented on recipes/pybboxes/meta.yaml
> +    - pyhumps
```suggestion
```

2022-07-08 09:25 UTC, devrimcavusoglu commented on recipes/pybboxes/meta.yaml
> +    - pyhumps
```suggestion
```

2022-07-08 09:25 UTC, devrimcavusoglu commented on recipes/pybboxes/meta.yaml
> +  sha256: 83740f0ca0d3cc868bbb5d1a64aa0f44507ea6091eff9ace6906a7e40d6dc82b
```suggestion
  sha256: 18d7cddb7c276aada2f498c916099c7c623a712d6380bcbdcb1ebb803ffda791
```

2022-07-08 17:08 UTC, fcakyon commented
@conda-forge/help-python ready fro review!