Create meta.yaml for pyocd
conda-forge/staged-recipes pull request #19473
Opened 2022-06-29 09:14 UTC by rudispr

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-06-29 09:14 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyocd```) and found some lint.

Here's what I've got...


For **recipes/pyocd**:

 * The top level meta keys are in an unexpected order. Expecting ['package', 'source', 'build', 'requirements', 'test', 'about', 'extra'].
 * There are too few lines.  There should be one empty line at the end of the file.

2022-06-29 09:20 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyocd```) and found it was in an excellent condition.

2022-08-02 09:41 UTC, rudispr commented
@conda-forge-admin, please restart ci

2022-08-10 07:24 UTC, rudispr commented
@conda-forge-admin, please restart ci

2022-08-16 07:20 UTC, rudispr commented
@conda-forge-admin, please restart ci

2022-08-17 11:18 UTC, rudispr commented
Hello @conda-forge/help-python  I'm having some trouble with the intelhex dependency. Could you please have a look at the meta.yaml and see if there is anything I might have missed? The builds keep failing during the tests with the error "The 'intelhex<3.0,>=2.0' distribution was not found and is required by the application" for the _pyocd/pyocd-gdbserver --help_ tests or "pyocd 0.0.0 requires intelhex, which is not installed" for the _pip check_ test. I found it odd that the intelhex package seemed to not be installed, so I added the _python -m intelhex --help_ test, and that passes just fine, indicating that the package is available. Do you know what might be the issue? Thanks!

2022-08-19 03:04 UTC, carterbox commented on recipes/pyocd/meta.yaml
> +    - intelhex
```suggestion
test:
  commands:
    - python -m intelhex --help
#    - pip check  # intelhex not configured for pip
    - pyocd --help
    - pyocd-gdbserver --help
  requires:
    - pip
```

2022-08-19 03:13 UTC, carterbox requested changes

2022-08-19 03:13 UTC, carterbox commented on recipes/pyocd/meta.yaml
> +  number: 0
```suggestion
build:
  noarch: python
  entry_points:
    - pyocd = pyocd.__main__:main
    - pyocd-gdbserver = pyocd.tools.gdb_server:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
```

2022-08-19 03:13 UTC, carterbox commented on recipes/pyocd/meta.yaml
> +    - typing-extensions >=4.0,<5.0
```suggestion
requirements:
  host:
    - pip
    - python >=3.6
  run:
    - capstone >=4.0,<5.0
    - cmsis-pack-manager >=0.4.0,<1.0
    - colorama <1.0
    - dataclasses
    - hidapi >=0.10.1,<1.0
    - intelhex >=2.0,<3.0 
    - intervaltree >=3.0.2,<4.0
    - libusb-package >=1.0,<2.0
    - natsort >=8.0.0,<9.0
    - prettytable >=2.0,<4.0
    - pyelftools <1.0
    - pylink-square >=0.11.1,<1.0
    - python >=3.6
    - pyusb >=1.2.1,<2.0
    - pyyaml >=6.0,<7.0
    - six >=1.15.0,<2.0
    - typing-extensions >=4.0,<5.0
```
https://github.com/pyocd/pyOCD/blob/800abc3dd6f05de890755a542677dabc13296574/setup.cfg#L47

Also, the dataclasses package can be installed on later python versions.

2022-08-19 03:26 UTC, carterbox commented
It looks like pyocd uses pkg_resources to check its own dependencies at runtime instead of just looking for failed imports. You will have to wait until the intelhex conda package is fixed.

2022-08-19 03:30 UTC, carterbox commented
Please ping again when this issue is resolved.

2022-08-19 07:38 UTC, rudispr commented
@conda-forge-admin, please restart ci

2022-08-19 08:31 UTC, rudispr commented
@carterbox  thanks a lot for the help! It looks like intelhex has been patched and pyocd builds successfully. Can we merge it?

2022-08-19 17:40 UTC, merged