get dem-stitcher into conda-forge
conda-forge/staged-recipes pull request #19470
Opened 2022-06-28 23:35 UTC by cmarshak

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-06-28 23:36 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I was trying to look for recipes to lint for you, but couldn't find any.
Please ping the 'conda-forge/core' team (using the @ notation in a comment) if you believe this is a bug.

2022-06-28 23:41 UTC, jhkennedy commented
I am willing to be a maintainer

2022-06-28 23:41 UTC, jhkennedy commented
@conda-forge-admin, please lint

2022-06-28 23:42 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I was trying to look for recipes to lint for you, but couldn't find any.
Please ping the 'conda-forge/core' team (using the @ notation in a comment) if you believe this is a bug.

2022-06-28 23:43 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/dem_stitcher```) and found some lint.

Here's what I've got...


For **recipes/dem_stitcher**:

 * Non noarch packages should have python requirement without any version constraints.

2022-06-28 23:44 UTC, jhkennedy commented
@conda-forge-admin, please lint

2022-06-28 23:44 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/dem_stitcher```) and found some lint.

Here's what I've got...


For **recipes/dem_stitcher**:

 * Non noarch packages should have python requirement without any version constraints.

2022-06-28 23:45 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/dem_stitcher```) and found some lint.

Here's what I've got...


For **recipes/dem_stitcher**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2022-06-28 23:46 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/dem_stitcher```) and found it was in an excellent condition.

2022-06-29 23:06 UTC, cmarshak commented
@conda-forge/help-python, ready for review!

2022-07-21 23:31 UTC, jhkennedy requested changes
I think in general we should avoid a top pin if there's no known issues.

2022-07-21 23:31 UTC, jhkennedy commented on recipes/dem_stitcher/meta.yaml
> +    - python >=3.7,<3.11
```suggestion
    - python >=3.7
```

2022-07-21 23:31 UTC, jhkennedy commented on recipes/dem_stitcher/meta.yaml
> +    - python >=3.7,<3.11
```suggestion
    - python >=3.7
```

2022-07-21 23:32 UTC, jhkennedy approved these changes

2022-07-22 00:08 UTC, jhkennedy commented
@conda-forge/staged-recipess and or @conda-forge/help-python this should be ready to merge!

2022-07-22 12:48 UTC, merged