Add cyeva
conda-forge/staged-recipes pull request #19471
Opened 2022-06-29 06:22 UTC by Clarmy

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-06-29 06:22 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/cyeva```) and found some lint.

Here's what I've got...


For **recipes/cyeva**:

 * Failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint .` from the recipe directory.

2022-06-29 06:27 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/cyeva```) and found it was in an excellent condition.

2022-06-29 07:03 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/cyeva```) and found it was in an excellent condition.

2022-06-29 07:20 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/cyeva```) and found some lint.

Here's what I've got...


For **recipes/cyeva**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.

2022-06-29 07:25 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/cyeva```) and found it was in an excellent condition.

2022-06-29 08:02 UTC, Clarmy commented
@hhuangwx Hi! Can you take a moment to review this recipe for me? Thank you very much.

2022-07-04 09:35 UTC, Clarmy commented
@conda-forge/help-python please review

2022-07-11 02:56 UTC, Clarmy commented on recipes/cyeva/meta.yaml
> +{% set version = "0.1.0.beta.3" %}
Not yet.

2022-07-23 06:40 UTC, carterbox requested changes
The [logs show you are installing an external tests module](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=534047&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=1155) with this package. Do not install tests outside of your package.

You probably need to exit this find_packges to only include `cyeva`.
https://github.com/caiyunapp/cyeva/blob/c6cba335d2eec7bc62629fdf78ed830606046607/setup.py#L41

2022-07-27 02:10 UTC, Clarmy commented
@carterbox I modified the setup.py to exclude `tests`. The [latest log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=541328&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=1059) shows it isn't installed.

2022-07-28 03:32 UTC, Clarmy commented
@conda-forge/help-python  please review

2022-08-13 04:27 UTC, merged