Add nvitop.
conda-forge/staged-recipes pull request #19543
Opened 2022-07-05 10:03 UTC by XuehaiPan

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-07-05 10:03 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/nvitop```) and found some lint.

Here's what I've got...


For **recipes/nvitop**:

 * The top level meta keys are in an unexpected order. Expecting ['package', 'source', 'build', 'requirements', 'test', 'about', 'extra'].
 * Non noarch packages should have python requirement without any version constraints.

For **recipes/nvitop**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-07-05 10:07 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I was trying to look for recipes to lint for you, but couldn't find any.
Please ping the 'conda-forge/core' team (using the @ notation in a comment) if you believe this is a bug.

2022-07-07 15:45 UTC, dopplershift requested changes

2022-07-07 15:45 UTC, dopplershift commented on recipes/nvitop/meta.yaml
> +  skip: true  # [py<35]
This looks like it could be noarch Python:
```suggestion
  noarch: python
```

2022-07-07 15:45 UTC, dopplershift commented on recipes/nvitop/meta.yaml
> +  license: GPL-2.0-or-later
Definitely not 2, but 3. Also seems like 3 only?
```suggestion
  license: GPL-3.0-only
```

2022-07-07 17:27 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/nvitop```) and found some lint.

Here's what I've got...


For **recipes/nvitop**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.

2022-07-08 05:13 UTC, XuehaiPan commented
There is no `conda-forge/nvidia-ml-py-feedstock` for the PyPI package [`nvidia-ml-py`](https://pypi.org/project/nvidia-ml-py), the official NVML Python Bindings from NVIDIA. And the package is not available on anaconda/nvidia (<https://anaconda.org/nvidia/repo>).

Should we vendor the `pynvml.py`? Or we can add the `conda-forge/nvidia-ml-py-feedstock` first like CUDA Toolkit. The PyPI package [`nvidia-ml-py`](https://pypi.org/project/nvidia-ml-py) is released under BSD License.

2022-10-06 16:09 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/nvitop```) and found some lint.

Here's what I've got...


For **recipes/nvitop**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2022-10-07 08:43 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/nvitop```) and found some lint.

Here's what I've got...


For **recipes/nvitop**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2022-10-07 08:45 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/nvitop```) and found it was in an excellent condition.

2022-10-07 08:45 UTC, XuehaiPan commented
@conda-forge/help-python, ready for review!

2022-10-22 14:35 UTC, xhochy approved these changes

2022-10-22 14:35 UTC, merged