Add recipe for scine-database
conda-forge/staged-recipes pull request #19556
Opened 2022-07-06 15:20 UTC by awvwgk

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-07-06 21:20 UTC, awvwgk commented
@conda-forge/help-python-c This recipes is ready for review (C++ library + pybind11 extension module). Package is split to keep build times and package sizes manageable.

For the testing I have to create a mongod process since the tests can't do this themselves for some reason, which adds some complexity and output clutter.

- scine-database check: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=532050&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=5030
- scine-database-python check: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=532050&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=6197

2022-07-19 00:33 UTC, carterbox requested changes
Looks very good, just some minor suggestions.

2022-07-19 00:33 UTC, carterbox commented on recipes/scine-database-python/meta.yaml
> +    - $RECIPE_DIR/test.sh
```suggestion
```
Rename the test to `run_test.sh` and put pip check inside the script.

2022-07-19 00:33 UTC, carterbox commented on recipes/scine-database-python/test.sh
> +
```suggestion

pip check

```

2022-07-19 00:33 UTC, carterbox commented on recipes/scine-database/meta.yaml
> +    - libmongocxx
```suggestion
```
libmongocxx has a run_export

2022-07-19 07:46 UTC, awvwgk commented
@conda-forge/help-c-cpp Requested changes are addressed

2022-07-19 21:54 UTC, carterbox approved these changes

2022-07-19 21:54 UTC, merged