add element-coder
conda-forge/staged-recipes pull request #19628
Opened 2022-07-13 13:50 UTC by kjappelbaum

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-07-13 13:53 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/element-coder```) and found it was in an excellent condition.

2022-07-13 17:09 UTC, kjappelbaum commented
I'm also willing to be a maintainer.

2022-07-14 08:09 UTC, kjappelbaum commented
>Scirus not available on anaconda anywhere it seems
https://anaconda.org/search?q=Scirus

Yep, on it https://github.com/conda-forge/staged-recipes/pull/19636

2022-08-12 14:13 UTC, kjappelbaum commented
@conda-forge/help-python ready for review!

2022-08-23 02:18 UTC, BastianZim requested changes
Just a couple of small things, then this is ready to go 🚀

2022-08-23 02:18 UTC, BastianZim commented on recipes/element-coder/meta.yaml
> +    - python >=3.7
```suggestion
    - python >=3.7
    - setuptools >=35.0.2
    - setuptools_scm >=2.0.0,<3
```

2022-08-23 02:18 UTC, BastianZim commented on recipes/element-coder/meta.yaml
> +    - pip check
```suggestion
    - pip check
    - element_coder.encode --help
    - element_coder.decode --help
```
This checks the CLI. Depends on whether you are actually offering a help function though.

2022-08-23 13:14 UTC, kjappelbaum commented
@BastianZim thanks for the feedback, committed both your suggestions!

2022-08-23 13:39 UTC, BastianZim approved these changes

2022-08-23 13:39 UTC, merged