Adding ghostpii encryption package
conda-forge/staged-recipes pull request #19623
Opened 2022-07-12 20:35 UTC by jackp97

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-07-12 20:35 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/ghostpii```) and found it was in an excellent condition.

2022-07-13 15:17 UTC, jackp97 commented
@conda-forge/help-python ready for review

2022-08-15 16:21 UTC, carterbox requested changes

2022-08-15 16:21 UTC, carterbox commented on recipes/ghostpii/meta.yaml
> +  host:
```suggestion
  host:
     - setuptools >=42
```

2022-08-15 16:21 UTC, carterbox commented on recipes/ghostpii/meta.yaml
> +    - IPython
```suggestion
```
This package is not listed in requirements upstream.

2022-08-15 17:24 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/ghostpii```) and found some lint.

Here's what I've got...


For **recipes/ghostpii**:

 * Failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint .` from the recipe directory.

2022-08-15 17:28 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/ghostpii```) and found it was in an excellent condition.

2022-08-15 20:04 UTC, carterbox commented on recipes/ghostpii/meta.yaml
> +    - IPython
Apparently IPython is imported, [but not listed in the requirements upstream](https://github.com/capnion/ghostpii_client/blob/010bf3a6c2e61719ee5e13f2b776c3f13b27625e/setup.cfg#L22). This is a bug that should be fixed upstream.

2022-08-16 18:17 UTC, merged