Add tisysconfig package
conda-forge/staged-recipes pull request #19633
Opened 2022-07-13 15:13 UTC by JFreitas9

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-07-13 15:14 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/sysconfig```) and found some lint.

Here's what I've got...


For **recipes/sysconfig**:

 * Failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint .` from the recipe directory.

2022-07-13 15:24 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/sysconfig```) and found some lint.

Here's what I've got...


For **recipes/sysconfig**:

 * The license item is expected in the about section.

2022-07-13 15:28 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/sysconfig```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/sysconfig**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-07-26 09:10 UTC, JFreitas9 commented
Hello @conda-forge/staged-recipes please review my pull request.

2022-07-26 09:12 UTC, JFreitas9 commented on recipes/sysconfig/meta.yaml
> +  license: None
I can't find a proper license to add here. Can you help me?

2022-08-02 14:02 UTC, JFreitas9 commented
https://github.com/orgs/conda-forge/teams/staged-recipes

> Hello @conda-forge/staged-recipes please review my pull request.

2022-08-02 14:05 UTC, JFreitas9 commented
@conda-forge/staged-recipes please review my pull request.
Thanks in advance!

2022-08-23 19:27 UTC, carterbox requested changes
Two issues:

1. License. No, we cannot find the license for you. As the maintainer of this package you should be able to find the license. This software must have a license which allows modification and redistribution of the source otherwise, we cannot host this package. Ask the author for the license.

2. conda-force packages must be build from source files using our compilers. They cannot be created using an installer (which is what is being done here) because that usually means repackaging of pre-compiled binaries.

2022-08-23 19:28 UTC, carterbox commented
Closing because there is no evidence that this program is licensed appropriately.

2022-08-23 19:28 UTC, closed without merging