add beaker-py
conda-forge/staged-recipes pull request #19771
Opened 2022-07-23 19:40 UTC by h-vetinari

Needed for [tango](https://github.com/conda-forge/tango-feedstock/pull/12).

The name reflects the upstream name for the python bindings, though we couldn't package the underlying `beaker` (written in Go apparently) as-is because there's https://github.com/conda-forge/beaker-feedstock already.

2022-07-23 19:40 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/beaker-py```) and found it was in an excellent condition.

2022-07-23 20:15 UTC, h-vetinari commented
@dirkgr @epwalsh

Could you comment on the failing test suite here? AFAICT it makes little sense to try to run docker-based tests here (not least since conda-forge's [docker-py](https://github.com/conda-forge/docker-py-feedstock) actually doesn't install a docker-daemon).

2022-07-25 16:11 UTC, epwalsh commented
The test failures are because many of the tests require a Beaker personal access token. I hate to say it but the best option might be to just not run any of the unit tests.

2022-07-25 16:15 UTC, h-vetinari commented
> The test failures are because many of the tests require a Beaker personal access token. I hate to say it but the best option might be to just not run any of the unit tests.

Would it not make sense (medium-term & upstream) to make those tests conditional on the presence of the token, and skip them if it's not present?

2022-07-25 17:01 UTC, epwalsh commented
> Would it not make sense (medium-term & upstream) to make those tests conditional on the presence of the token, and skip them if it's not present?

That's a possibility, but I understated how many tests require a token... it's pretty much 100% of the tests. Though I've proposed an idea internally (https://github.com/allenai/beaker/issues/2239 - repo is private so you won't be able to view the issue, but I'm linking here for my own records) that would allow the Beaker server to issue temporary tokens that could be used by GitHub runners via approved repositories. If that gets implemented then we wouldn't have to skip any tests.

2022-07-25 17:22 UTC, h-vetinari commented
> If that gets implemented then we wouldn't have to skip any tests.

That sounds great, thanks! I like not skipping tests. :)

2022-07-25 18:24 UTC, h-vetinari commented
@conda-forge/help-python

This should be ready for review. :)

2022-07-27 08:45 UTC, jaimergp requested changes
Just a couple questions!

2022-07-27 08:45 UTC, jaimergp commented on recipes/beaker-py/meta.yaml
> +    - rm pyproject.toml
Why is this needed? It only lists the build backend for `pip install`.

```suggestion
```

2022-07-27 08:45 UTC, jaimergp commented on recipes/beaker-py/meta.yaml
> +  skip: true  # [win]
Doesn't this package qualify for `noarch: python`?

```suggestion
  noarch: python
```

2022-07-29 10:12 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/beaker-py```) and found some lint.

Here's what I've got...


For **recipes/beaker-py**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2022-07-29 10:14 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/beaker-py```) and found it was in an excellent condition.

2022-07-29 10:25 UTC, h-vetinari commented
Thanks for the review @jaimergp, this should be ready now I hope.

2022-07-29 10:40 UTC, merged