Add yamlprocessor
conda-forge/staged-recipes pull request #19844
Opened 2022-07-28 11:21 UTC by matthewrmshin

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-07-28 11:22 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/yamlprocessor```) and found it was in an excellent condition.

2022-07-28 11:26 UTC, matthewrmshin commented
I am willing to be listed in the maintainer section.

2022-07-28 13:27 UTC, KrissyRayD242 commented
I am willing to be listed in the maintainer section.

2022-07-28 13:28 UTC, matthewrmshin commented
@conda-forge/help-python, ready for review!

2022-08-23 23:50 UTC, BastianZim requested changes
Just a couple of small things, then this is ready to go 🚀

2022-08-23 23:50 UTC, BastianZim commented on recipes/yamlprocessor/meta.yaml
> +    - python >=3.7
```suggestion
    - python >=3.7
    - pytest-runner
```
Ref: https://github.com/JCSDA-internal/yamlprocessor/blob/1a323c0cad28bf47e2ed200e24ad5e9239a70805/setup.cfg#L40

2022-08-23 23:50 UTC, BastianZim commented on recipes/yamlprocessor/LICENSE
> +BSD 3-Clause License
The license file is already included in the source distribution so you can remove it from here.

2022-08-24 08:42 UTC, matthewrmshin commented
@BastianZim Thanks for reviewing. I have followed your recommendation in the latest change. 👍🏼

2022-08-24 13:46 UTC, BastianZim approved these changes

2022-08-24 13:46 UTC, merged