Adding torchtime
conda-forge/staged-recipes pull request #19896
Opened 2022-08-01 20:44 UTC by philipdarke

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-08-01 20:45 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/torchtime```) and found it was in an excellent condition.

2022-08-03 12:57 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/torchtime```) and found some lint.

Here's what I've got...


For **recipes/torchtime**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.

2022-08-03 13:01 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/torchtime```) and found some lint.

Here's what I've got...


For **recipes/torchtime**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2022-08-03 13:02 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/torchtime```) and found it was in an excellent condition.

2022-08-03 14:59 UTC, philipdarke commented
@conda-forge/help-python, ready for review!

The package depends on `pytorch` which can be installed with `cpuonly` or a version of `cudatoolkit` (see Conda installation here https://pytorch.org/get-started/locally/). Any combination should satisfy the dependency. I think I have achieved this by testing under each CUDA version but I'd appreciate any feedback as this is my first conda-forge recipe.

Thanks very much!

2022-08-15 09:25 UTC, philipdarke commented
@conda-forge-admin, please ping conda-forge/help-python

2022-08-15 09:25 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/help-python and so here I am doing that.

2022-08-28 02:14 UTC, carterbox requested changes
This package contains python only. It doesn't need to be compiled. It is a noarch python package. Ignore fails on Windows if they are because of missing dependencies.

2022-08-28 02:14 UTC, carterbox commented on recipes/torchtime/meta.yaml
> +    - pytorch  # pytorch is globally pinned
You should include the constraints on the runtime dependencies except pytorch

https://github.com/philipdarke/torchtime/blob/7feb206557905282aba4b7bcbf5ab939794b7972/pyproject.toml#L13

2022-08-29 18:43 UTC, philipdarke commented
@conda-forge-admin, please ping conda-forge/help-python

Thanks Daniel - really appreciated.

The only difference to the main branch is now `torchtime/meta.yaml`. I've added the version constraints.

The recipe passes on Linux and Mac OS X, but fails on Windows with the message "Unsatisfiable dependencies for platform win-64: {MatchSpec("pytorch")}". As advised, I'm ignoring this.

Hopefully the recipe is good to go. Let me know if there is anything else.

2022-08-29 18:43 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/help-python and so here I am doing that.

2022-08-29 19:23 UTC, carterbox commented on conda-forge.yml
> +      vmImage: windows-2019
This is not resolved. File changes still exist.

2022-09-01 15:05 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/help-python and so here I am doing that.

2022-09-01 16:47 UTC, carterbox requested changes

2022-09-01 16:47 UTC, carterbox commented on recipes/torchtime/meta.yaml
> +    - numpy >=1.21.0,<1.22
```suggestion
    - python >=3.8,<3.10
    - sktime >=0.12.1,<2
    - requests >=2.27.1,<3
    - scikit-learn >=1.1.1,<2
    - tqdm >=4.64.0,<5
    - pytorch >=1.11.0,<2
    - numpy >=1.21.0,<2
```
I was mistaken. Pytorch is actually only pinned for packages that link against it, but yours isn't compiled, so you can list the version compatibility. 

Also, this package poetry dependency spec is using caret not tilde.

https://github.com/philipdarke/torchtime/blob/7feb206557905282aba4b7bcbf5ab939794b7972/pyproject.toml#L13

https://python-poetry.org/docs/dependency-specification/

2022-09-01 16:47 UTC, carterbox commented on recipes/torchtime/meta.yaml
> +  home: https://philipdarke.com/torchtime
```suggestion
about:
  home: https://philipdarke.com/torchtime
  dev_url: https://github.com/philipdarke/torchtime
```

2022-09-01 16:49 UTC, carterbox commented on recipes/torchtime/meta.yaml
> +    - sktime >=0.12.1,<2
```suggestion
    - sktime >=0.12.1,<1
```

2022-09-01 16:54 UTC, carterbox commented on recipes/torchtime/meta.yaml
> +    - sktime >=0.12.1,<1
```suggestion
    - sktime >=0.12.1,<0.13.0
```
Carot is a complicated package spec

2022-09-09 07:13 UTC, philipdarke commented
@conda-forge-admin, please ping conda-forge/help-python

Thanks for your work on this pull request - is there an action for me at this stage?

2022-09-09 07:13 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/help-python and so here I am doing that.

2022-09-09 21:11 UTC, carterbox commented
Please note the extra constraint on sktime in the test section. This should no longer be necessary when the minimum sktime version is raised to 0.13.

2022-09-14 22:31 UTC, merged