Add pyrdl
conda-forge/staged-recipes pull request #19942
Opened 2022-08-05 16:30 UTC by mjohnson541

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-08-05 16:30 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyrdl```) and found some lint.

Here's what I've got...


For **recipes/pyrdl**:

 * The recipe could do with some maintainers listed in the `extra/recipe-maintainers` section.

2022-08-05 16:40 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyrdl```) and found it was in an excellent condition.

2022-08-05 17:49 UTC, mjohnson541 commented
@conda-forge/staged-recipes ready for review!

2022-08-05 17:49 UTC, mjohnson541 commented
@conda-forge/staged-recipes ready for review!

2022-08-10 23:10 UTC, mjohnson541 commented
@conda-forge-admin, please ping team

2022-08-10 23:10 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/staged-recipes and so here I am doing that.

2022-08-12 15:04 UTC, ocefpaf commented on recipes/pyrdl/build.sh
> +
Is there a `make check` or `ctest` that we can run here?

2022-08-12 15:05 UTC, ocefpaf commented on recipes/pyrdl/meta.yaml
> +{% set version = "1.1.3_rdkit" %}
I'm assuming that the `_rdkit` is not part of the versioning scheme, right?
```suggestion
{% set version = "1.1.3" %}
```

2022-08-12 15:05 UTC, ocefpaf commented on recipes/pyrdl/meta.yaml
> +  url: https://github.com/rareylab/RingDecomposerLib/archive/refs/tags/v{{ version }}.tar.gz
```suggestion
  url: https://github.com/rareylab/RingDecomposerLib/archive/refs/tags/v{{ version }}_rdkit.tar.gz
```

2022-08-12 15:06 UTC, ocefpaf commented on recipes/pyrdl/meta.yaml
> +
```suggestion
```

2022-08-12 15:07 UTC, ocefpaf commented on recipes/pyrdl/meta.yaml
> +    - py_rdl
Are you using the `build/*` files in the import test? If so this package will be broken b/c the test files are not package. If not you can drop the test files b/c I don't see other tests that are using them.

2022-08-12 16:00 UTC, awvwgk requested changes
Note that the ringdecomposerlib is already packaged on conda-forge: https://github.com/conda-forge/ringdecomposerlib-feedstock

2022-08-12 16:24 UTC, mjohnson541 commented
Hmm...in that case would it be better to just add the -DBUILD_PYTHON_WRAPPER=ON flag and import test to the ringdecomposerlib feedstock instead?

2022-08-12 16:27 UTC, awvwgk commented
The Python wrappers link statically against ringdecomposerlib, this means the build files must be patched in any case to prefer dynamic linking. You can either have ringdecomposerlib as requirement in host for this recipe or we add an output to the existing feedstock producing the Python wrapper.

2022-08-13 10:41 UTC, awvwgk commented
I'll build the Python wrapper as additional output in ringdecomposerlib (see https://github.com/conda-forge/ringdecomposerlib-feedstock/pull/2). Any preference on the naming? Either `ringdecomposerlib-python` or `py_rdl` seem like possible choices to me.

2022-08-13 18:37 UTC, mjohnson541 commented
Both of those sound good! Thank you so much!

2022-08-13 18:37 UTC, closed without merging