Add cwl-upgrader
conda-forge/staged-recipes pull request #19970
Opened 2022-08-08 04:55 UTC by kinow

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-08-08 04:55 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/cwl-upgrader```) and found it was in an excellent condition.

2022-08-08 05:21 UTC, kinow commented
@mr-c whenever you have time can you just reply here saying that you are OK being a maintainer of this recipe (pull request requirement). Thanks!

2022-08-08 06:17 UTC, mr-c commented
I'm happy to be a maintainer of this package, yep !

2022-08-08 07:29 UTC, kinow commented
@conda-forge/help-python, ready for review!

2022-08-08 07:30 UTC, kinow commented
This PR was created with greyskull, following the docs from https://conda-forge.org/docs/maintainer/adding_pkgs.html

2022-08-28 02:54 UTC, carterbox requested changes
Please convert this recipe to noarch: python? Suggestion how below.

https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python

2022-08-28 03:01 UTC, carterbox requested changes

2022-08-28 03:01 UTC, carterbox commented on recipes/cwl-upgrader/meta.yaml
> +  skip: true  # [py>=400 or win]
There's a minimum python version upstream. python>=3.6

2022-08-28 11:10 UTC, mr-c commented on recipes/cwl-upgrader/meta.yaml
> +  skip: true  # [py>=400 or win]
```suggestion
```

2022-08-28 20:54 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/cwl-upgrader```) and found some lint.

Here's what I've got...


For **recipes/cwl-upgrader**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.
 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2022-08-28 20:54 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/cwl-upgrader```) and found some lint.

Here's what I've got...


For **recipes/cwl-upgrader**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2022-08-28 20:58 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/cwl-upgrader```) and found it was in an excellent condition.

2022-08-28 21:16 UTC, kinow commented
Thanks for the review @carterbox & @mr-c ! Applied suggested fixes, and then fixed the linter issue. Should be ready for review again :tada:

2022-08-29 06:48 UTC, mr-c approved these changes

2022-08-31 07:54 UTC, mr-c commented
Dear @conda-forge/staged-recipes ; can we get a re-review? `cwl-upgrader` is needed by https://github.com/conda-forge/staged-recipes/pull/19969 (`cwl-utils`) which is then required for the new version of `cwltool` https://github.com/conda-forge/cwltool-feedstock/pull/112

Thanks!

2022-09-03 19:26 UTC, merged

2022-09-05 09:40 UTC, mr-c commented
Thank you @carterbox 🤓