pydevd-pycharm meta.yaml
conda-forge/staged-recipes pull request #19985
Opened 2022-08-08 21:13 UTC by cshaley

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-08-08 21:13 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pydevd-pycharm```) and found it was in an excellent condition.

2022-08-09 15:45 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pydevd-pycharm```) and found some lint.

Here's what I've got...


For **recipes/pydevd-pycharm**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2022-08-09 15:47 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pydevd-pycharm```) and found it was in an excellent condition.

2022-08-09 16:43 UTC, cshaley commented
passing and ready for review https://github.com/orgs/conda-forge/teams/help-python

Adding pydevd-pycharm package to conda forge

2022-08-11 18:26 UTC, cshaley commented
@conda-forge/help-python ready for review

2022-08-22 19:45 UTC, cshaley commented
@ocefpaf @jakirkham Review / merge?

2022-08-22 19:53 UTC, jakirkham commented
@conda-forge-admin, please ping team

@cshaley, please use the command above to request reviews from the team here as opposed to individual pings

2022-08-22 19:53 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/staged-recipes and so here I am doing that.

2022-08-28 03:17 UTC, carterbox requested changes

2022-08-28 03:17 UTC, carterbox commented on recipes/pydevd-pycharm/meta.yaml
> +    - $RPATH/libstdc++.so.6
This should not be required for a python only package. It looks like the "source" tar has [pre-compiled binaries](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=548317&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=7244). This is not allowed. You must compile libraries with our compilers.

2023-05-13 19:53 UTC, closed without merging