Add wurst
conda-forge/staged-recipes pull request #20035
Opened 2022-08-12 12:45 UTC by cmutel

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-08-12 12:45 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/wurst```) and found some lint.

Here's what I've got...


For **recipes/wurst**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2022-08-12 12:47 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/wurst```) and found it was in an excellent condition.

2022-08-12 14:00 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/wurst```) and found some lint.

Here's what I've got...


For **recipes/wurst**:

 * The recipe must have a `build/number` section.
 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2022-08-12 14:02 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/wurst```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/wurst**:

 * Whenever possible python packages should use noarch. See https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-builds

2022-08-14 19:10 UTC, cmutel commented
@conda-forge/help-python, this is ready to review. Thanks for your time and support.

2022-08-22 13:44 UTC, marcelotrevisani commented on recipes/wurst/meta.yaml
> +  build:
```suggestion
  host:
```

2022-08-22 13:47 UTC, marcelotrevisani commented on recipes/wurst/meta.yaml
> +    - python
```suggestion
    - python >=3.6
```

2022-08-22 13:48 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/wurst```) and found some lint.

Here's what I've got...


For **recipes/wurst**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2022-08-22 13:49 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/wurst```) and found it was in an excellent condition.

2022-08-28 03:51 UTC, carterbox requested changes

2022-08-28 03:51 UTC, carterbox commented on recipes/wurst/meta.yaml
> +    - wrapt
https://github.com/polca/wurst/blob/a30a6ebefb5584edb06ce2eff742b2e566e49ae0/setup.py#L17

These requirements do not match what the package claims.

2022-08-28 03:51 UTC, carterbox commented on recipes/wurst/meta.yaml
> +build:
You need to lis[t entry points ](https://github.com/polca/wurst/blob/a30a6ebefb5584edb06ce2eff742b2e566e49ae0/setup.py#L28)in the conda-recipe. Please check the conda-forge docs section on noarch: python.

2022-08-28 03:51 UTC, carterbox commented on recipes/wurst/meta.yaml
> +    - pip check
```suggestion
  commands:
    - pip check
    - wurst-cli --help
```
Test your CLI here.

2022-12-13 08:39 UTC, cmutel commented
@m-rossi Will take over with a clean start. Thanks!

2022-12-13 08:39 UTC, closed without merging