Add RAiDER recipe
conda-forge/staged-recipes pull request #20100
Opened 2022-08-16 23:52 UTC by jhkennedy

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-08-16 23:52 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/raider```) and found some lint.

Here's what I've got...


For **recipes/raider**:

 * ``requirements: run: dem_stitcher>=2.3.0`` must contain a space between the name and the pin, i.e. ``dem_stitcher >=2.3.0``
 * ``requirements: run: gdal>=3.0`` must contain a space between the name and the pin, i.e. ``gdal >=3.0``

2022-08-16 23:54 UTC, jhkennedy commented
@cmarshak @jlmaurer are you willing to be a maintainer?

2022-08-16 23:55 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/raider```) and found it was in an excellent condition.

2022-08-17 00:39 UTC, jlmaurer commented
I am willing to be a maintainer

2022-08-17 00:40 UTC, cmarshak commented
I am willing to be a maintainer

2022-08-17 04:11 UTC, jhkennedy commented
OSX builds are failing due to an issue with the latest `blosc` no longer vendoring `zlib` and `gdal` being linked to the `blosc` export of `zlib` as discussed here: https://github.com/conda-forge/blosc-feedstock/issues/55

Going to pin to GDAL >= 3.5.1 I think.

2022-08-17 05:50 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/raider```) and found some lint.

Here's what I've got...


For **recipes/raider**:

 * ``requirements: run: blosc <= 1.21.0`` should not contain a space between relational operator and the version, i.e. ``blosc <=1.21.0``

2022-08-17 05:51 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/raider```) and found it was in an excellent condition.

2022-08-17 06:33 UTC, jhkennedy commented
@conda-forge/help-python-c, ready for review!

2022-08-30 17:32 UTC, carterbox requested changes
Not required for merging this PR, but things you should address upstream for the next release.

1. The installed artifacts contain[ an empty python module called "tools".](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=552697&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=1814) which is installed directly to site-packages. It seems intentional, but I'm not sure what the purpose is because it is empty when installed to site-packages.

2. I also encourage you to transition your "scripts" to [entrypoints/console scripts](https://setuptools.pypa.io/en/latest/userguide/entry_point.html#console-scripts) by listing function names in the setup.cfg/pyproject.toml. Instead of maintaining a bunch of files in bin which essentially are just redirecting to functions in Raider.

2022-08-30 17:32 UTC, carterbox commented on recipes/raider/meta.yaml
> +    - cython
```suggestion
    - cython
```
Are your sure that cython is need at runtime? Looks like it might only be used to compile extension modules.

2022-08-30 19:07 UTC, jhkennedy commented on recipes/raider/meta.yaml
> +    - cython
```suggestion
```

2022-08-30 19:07 UTC, jhkennedy commented on recipes/raider/meta.yaml
> +    - cython
@carterbox it was listed in the README/docs as a runtime requirement, but looking at it, it appears to just be a build time requirement. They are definitely all mixed together in the package docs. It appears everything still works after force removing it from the environment once its built/installed, so I'm going to remove it.

2022-08-30 19:11 UTC, jhkennedy commented
@carterbox I've addressed the changes you requested, thanks for your review! For the upstream suggestions:

> 1. The installed artifacts contain[ an empty python module called "tools".](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=552697&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=1814) which is installed directly to site-packages. It seems intentional, but I'm not sure what the purpose is because it is empty when installed to site-packages.

I'll open an issue for this ( and possibly a PR -- not my package; just helping them get it on conda-forge) -- I think it's an artifact of how the package and setuptools  is setup, and not intentional.  


> 2. I also encourage you to transition your "scripts" to [entrypoints/console scripts](https://setuptools.pypa.io/en/latest/userguide/entry_point.html#console-scripts) by listing function names in the setup.cfg/pyproject.toml. Instead of maintaining a bunch of files in bin which essentially are just redirecting to functions in Raider.

Definitely -- I'll open an issue (and probably a PR) for that too.

2022-08-30 22:29 UTC, jhkennedy commented
https://github.com/orgs/conda-forge/teams/help-python-c, ready for review!

2022-08-30 22:29 UTC, jhkennedy commented
@conda-forge/help-python-c, ready for review!

2022-09-03 19:30 UTC, merged