add r-redlistr conda recipe
conda-forge/staged-recipes pull request #20171
Opened 2022-08-24 09:58 UTC by Marie59

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-08-24 09:58 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-redlistr```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/r-redlistr**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-08-24 10:21 UTC, Marie59 commented
Hi @conda-forge/r ! This recipe is ready for review

2022-08-24 18:23 UTC, mfansler requested changes

2022-08-24 18:23 UTC, mfansler commented on recipes/r-redlistr/meta.yaml
> +  license: GPL-3
Should be `GPL-3.0-or-later`. This is the SPDX interpretation of `License: GPL (>= 3)`.

2022-08-24 18:23 UTC, mfansler commented on recipes/r-redlistr/meta.yaml
> +    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
Authors also have a separate [`LICENSE` file](https://github.com/red-list-ecosystem/redlistr/blob/master/LICENSE) in the package, which should also be included. The DESCRIPTION file shows `License: GPL (>= 3) | file LICENSE`, indicating the authors are intent on its inclusion.

2022-08-24 18:23 UTC, mfansler commented on recipes/r-redlistr/meta.yaml
> +# Package: redlistr
The commented out copy of the DESCRIPTION file can be removed.

2022-08-25 07:28 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-redlistr```) and found it was in an excellent condition.

2022-08-25 23:18 UTC, mfansler commented on recipes/r-redlistr/meta.yaml
> +    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
@Marie59 still need to add the LICENSE file to the list here.

2022-08-26 07:34 UTC, cbrueffer commented
I think there was a misunderstanding; what Marvin meant is that the package tarball comes with a LICENSE file that you can add to the recipe by adding a `- LICENSE` entry to the `license_file` section. The `LICENSE` file you added in this PR can be removed.

2022-08-26 09:14 UTC, Marie59 commented
Indeed, I misunderstood the issue ! Hope all is well now !

2022-08-26 09:36 UTC, cbrueffer commented
Looks good now, thanks to both of you!

2022-08-26 09:36 UTC, merged