Add album recipe
conda-forge/staged-recipes pull request #20232
Opened 2022-08-29 09:19 UTC by frauzufall

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-08-29 09:19 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/album```) and found some lint.

Here's what I've got...


For **recipes/album**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.

2022-08-29 09:21 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/album```) and found some lint.

Here's what I've got...


For **recipes/album**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2022-08-29 09:26 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/album```) and found it was in an excellent condition.

2022-08-31 10:33 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/album```) and found some lint.

Here's what I've got...


For **recipes/album**:

 * Failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint .` from the recipe directory.

2022-08-31 11:02 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/album```) and found it was in an excellent condition.

2022-08-31 13:38 UTC, frauzufall commented
@conda-forge/help-python, ready for review, thank you!

2022-09-16 07:48 UTC, beenje requested changes

2022-09-16 07:48 UTC, beenje commented on recipes/album/meta.yaml
> +    - pywin32 >=303  # [win]
You should replace that package with `pywin32-on-windows`, which is a virtual package for `pywin32` on windows and empty on non windows platforms. This allows you to remove the selector and make this recipe `noarch: python`. See https://conda-forge.org/docs/maintainer/knowledge_base.html#empty-python-packages

2022-09-16 07:48 UTC, beenje commented on recipes/album/meta.yaml
> +  skip: true  # [py<37]
Make that recipe `noarch: python` instead and set a minimum version on Python in host and run.

2022-09-16 09:25 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/album```) and found some lint.

Here's what I've got...


For **recipes/album**:

 * ``requirements: run: pywin32-on-windows >= 0.1.0`` should not contain a space between relational operator and the version, i.e. ``pywin32-on-windows >=0.1.0``

2022-09-16 09:26 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/album```) and found it was in an excellent condition.

2022-09-16 13:30 UTC, merged