Add Sophus
conda-forge/staged-recipes pull request #20264
Opened 2022-08-31 22:02 UTC by versatran01

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-08-31 22:02 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/sophus```) and found some lint.

Here's what I've got...


For **recipes/sophus**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [30]

2022-08-31 22:02 UTC, versatran01 commented
@conda-forge-admin, please ping team

2022-08-31 22:02 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/staged-recipes and so here I am doing that.

2022-08-31 22:05 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/sophus```) and found it was in an excellent condition.

2022-08-31 22:06 UTC, versatran01 commented
@conda-forge/help-c-cpp, ready for review!

2022-09-05 06:59 UTC, fhill122 commented
there is a typo in cmake args, should be "-DBUILD_SOPHUS_TESTS=OFF" (missing S)

2022-09-07 06:54 UTC, marcelotrevisani commented on recipes/sophus/meta.yaml
> +  skip: true  # [win and vc<14]
```suggestion
  skip: true  # [win]
```

2022-09-10 13:59 UTC, versatran01 commented
@conda-forge-admin, please ping team, this PR is ready.

2022-09-10 13:59 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/team, and so here I am doing that.

2022-09-15 00:05 UTC, carterbox requested changes

2022-09-15 00:05 UTC, carterbox commented on recipes/sophus/meta.yaml
> +    - test -f ${PREFIX}/include/sophus/types.hpp  # [unix]
```suggestion
  commands:
    - test -f ${PREFIX}/include/sophus/types.hpp                # [unix]
    - test -f ${PREFIX}/share/sophus/cmake/SophusTargets.cmake  # [unix]
```

2022-09-15 00:05 UTC, carterbox commented on recipes/sophus/build.sh
> +make install
```suggestion
cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} \
      -DCMAKE_PREFIX_PATH=${PREFIX} \
      -DBUILD_SOPHUS_EXAMPLES=OFF \
      -DBUILD_SOPHUS_TESTS=ON \
      -DSOPHUS_USE_BASIC_LOGGING=ON \
      ..
make -j${CPU_COUNT}
make test
make install
```
You should build and run at least one test to check that the conda-forge compilers are compatible with the source and compiler args.

2022-09-15 03:51 UTC, versatran01 commented on recipes/sophus/meta.yaml
> +  skip: true  # [win]
https://github.com/strasdat/Sophus/issues/358
Here the maintainer says to leave out win for now until ci is setup

2022-09-29 04:56 UTC, versatran01 commented
@conda-forge-admin, please ping team

2022-09-29 04:56 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/staged-recipes and so here I am doing that.

2022-10-06 03:32 UTC, carterbox requested changes

2022-10-06 03:32 UTC, carterbox commented on recipes/sophus/meta.yaml
> +    - eigen
You marked this as resolved, but nothing changed. Why not include the minimum Eigen version specification?

2022-10-06 10:47 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/sophus```) and found some lint.

Here's what I've got...


For **recipes/sophus**:

 * ``requirements: host: eigen >= 3.3`` should not contain a space between relational operator and the version, i.e. ``eigen >=3.3``
 * ``requirements: run: eigen >= 3.3`` should not contain a space between relational operator and the version, i.e. ``eigen >=3.3``

2022-10-06 10:49 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/sophus```) and found it was in an excellent condition.

2022-10-06 16:24 UTC, merged

2023-05-08 14:02 UTC, zzz6519003 commented
@conda-forge-admin is a bot? cool