Add performer-pytorch
conda-forge/staged-recipes pull request #20292
Opened 2022-09-03 11:31 UTC by maresb

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-09-03 11:31 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/performer-pytorch```) and found it was in an excellent condition.

2022-09-03 11:32 UTC, maresb commented
Blocked by #20288 and #20289.

2022-09-04 15:48 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/performer-pytorch```) and found some lint.

Here's what I've got...


For **recipes/performer-pytorch**:

 * ``requirements: build: cmake  != 3.23.0`` should not contain a space between relational operator and the version, i.e. ``cmake !=3.23.0``

2022-09-04 15:50 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/performer-pytorch```) and found it was in an excellent condition.

2022-09-12 22:34 UTC, maresb commented
@conda-forge/help-python, ready for review (despite xfailing win-64 test).

This is a PyTorch noarch package, so win-64 fails simply because there's no PyTorch.

Generated by Grayskull.

2022-09-13 19:23 UTC, BastianZim requested changes
Just the summary could be slightly more descriptive, otherwise, it's fine.

2022-09-13 19:23 UTC, BastianZim commented on recipes/performer-pytorch/meta.yaml
> +  summary: Performer - Pytorch
```suggestion
  summary: An implementation of Performer, a linear attention-based transformer, in Pytorch
```

2022-09-13 20:27 UTC, maresb commented
Thanks @BastianZim for the suggestion! I have committed it, and now things are green (except of course win-64).

2022-09-13 20:27 UTC, merged