Added recipe for ccphylo
conda-forge/staged-recipes pull request #20340
Opened 2022-09-07 11:04 UTC by ptlcc

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-09-07 11:05 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/ccphylo```) and found some lint.

Here's what I've got...


For **recipes/ccphylo**:

 * The recipe could do with some maintainers listed in the `extra/recipe-maintainers` section.
 * license_file entry is missing, but is required.
 * The extra section contained an unexpected subsection name. identifiers is not a valid subsection name.

2022-09-07 11:17 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/ccphylo```) and found some lint.

Here's what I've got...


For **recipes/ccphylo**:

 * Failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint .` from the recipe directory.

2022-09-07 11:29 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/ccphylo```) and found it was in an excellent condition.

2022-09-15 05:25 UTC, ptlcc commented
@conda-forge/help-c-cpp The recipe is ready for review.

2022-09-28 16:44 UTC, saraedum requested changes

2022-09-28 16:44 UTC, saraedum commented on recipes/ccphylo/meta.yaml
> +    - zlib
```suggestion
```

zlib should have a `run_exports` so this should not be necessary.

2022-09-28 16:44 UTC, saraedum commented on recipes/ccphylo/meta.yaml
> +  doc_url: doi:10.1093/biomethods/bpab008
I don't think this will render in a good way. I believe this needs to be a proper URL. (Or do we support DOIs here by now?)

2022-09-28 16:44 UTC, saraedum commented on recipes/ccphylo/meta.yaml
> +  summary: 'CCPhylo is a software suite designed to easen phylogenitic
```suggestion
  summary: 'CCPhylo is a software suite designed to easen phylogenetic 
```

2022-09-28 16:44 UTC, saraedum commented on recipes/ccphylo/meta.yaml
> +  summary: 'CCPhylo is a software suite designed to easen phylogenitic
You might want to split this up into short summary and a longer `description`.

2022-09-28 16:44 UTC, saraedum commented on recipes/ccphylo/meta.yaml
> +   - ccphylo --help | grep CCPhylo >/dev/null
```suggestion
   - ccphylo --help
```

I think this is good enough. Or do you have a special reason to grep for the program name?

2022-09-28 16:44 UTC, saraedum commented on recipes/ccphylo/build.sh
> +mkdir -p $PREFIX/doc/ccphylo
I don't think we usually ships things in `PREFIX/doc`. But I could be mistaken.

2022-09-28 16:44 UTC, saraedum commented on recipes/ccphylo/LICENSE
> +/* Philip T.L.C. Clausen Jul 2022 plan@dtu.dk */
It seems you included the license twice.

2022-09-28 16:44 UTC, saraedum commented on recipes/ccphylo/meta.yaml
> +  skip: True  # [win]
Why is this necessary?

2022-09-28 16:44 UTC, saraedum commented on recipes/ccphylo/LICENSE
> +/* Philip T.L.C. Clausen Jul 2022 plan@dtu.dk */
(since you're one of the authors if I am not mistaken, you could also consider to add the license file to the repository; just as a suggestion.)

2022-09-29 06:56 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pytest-unordered```) and found some lint.

Here's what I've got...


For **recipes/pytest-unordered**:

 * Feedstock with the same name exists in conda-forge.

2023-04-26 18:58 UTC, closed without merging