Add hoomd-dlext
conda-forge/staged-recipes pull request #20439
Opened 2022-09-14 18:50 UTC by nrouizem

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-09-14 18:51 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/hoomd-dlext```) and found some lint.

Here's what I've got...


For **recipes/hoomd-dlext**:

 * The recipe `license` should not include the word "License".
 * If python is a host requirement, it should be a run requirement.

For **recipes/hoomd-dlext**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-09-14 18:54 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/hoomd-dlext```) and found some lint.

Here's what I've got...


For **recipes/hoomd-dlext**:

 * If python is a host requirement, it should be a run requirement.

2022-09-14 18:55 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/hoomd-dlext```) and found it was in an excellent condition.

2022-09-14 21:16 UTC, pabloferz commented
I do agree to appear as a maintainer of the recipe.

2022-09-14 21:57 UTC, nrouizem commented
@conda-forge/staged-recipes ready for review

2022-09-21 19:02 UTC, nrouizem commented
`@conda-forge/staged-recipes` ready for review!

2022-10-06 05:35 UTC, carterbox requested changes

2022-10-06 05:35 UTC, carterbox commented on recipes/hoomd-dlext/meta.yaml
> +    - {{ pin_compatible('hoomd', max_pin='2.x') }}
```suggestion
    - {{ pin_compatible('hoomd', max_pin='x.x') }}
```
Pin already restricted to <3.0 from host spec.

2022-10-06 05:35 UTC, carterbox commented on recipes/hoomd-dlext/meta.yaml
> +  ignore_run_exports: tbb
```suggestion
{% set version = "0.2.1" %}
{% set build = 0 %}

package:
  name: hoomd-dlext
  version: {{ version }}

source:
  url: https://github.com/SSAGESLabs/hoomd-dlext/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 547316c95608d7ee1ca11ace53ccf22dddc88206fa0ac0613020f48bf6081269

build:
  number: {{ build }}
  # Upstream package does not support Windows, Python < 3.6, or PyPy
  skip: true  # [win or py<36 or python_impl == "pypy"]
  string: {{ 'cuda' ~ cuda_compiler_version|string }}_py{{ py }}h{{ PKG_HASH }}_{{ build + 100}}  # [cuda_compiler_version != "None"]
  ignore_run_exports_from:
    - tbb-devel
```
Only use jinja variables for values will change or are used in multiple places

2022-10-07 16:59 UTC, pabloferz commented on recipes/hoomd-dlext/meta.yaml
> +    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != "None"]
We do not use NVCC, but conditionally define some methods depending on whether the hoomd we are building against has or not cuda support.

2022-10-07 20:50 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/hoomd-dlext```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/hoomd-dlext**:

 * Jinja2 variable references are suggested to take a ``{{<one space><variable name><one space>}}`` form. See lines [16].

2022-10-07 20:55 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/hoomd-dlext```) and found it was in an excellent condition.

2022-10-07 21:16 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/hoomd-dlext```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/hoomd-dlext**:

 * Jinja2 variable references are suggested to take a ``{{<one space><variable name><one space>}}`` form. See lines [16].

2022-10-07 21:19 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/hoomd-dlext```) and found it was in an excellent condition.

2022-10-12 20:22 UTC, pabloferz commented
@carterbox Does this look ready now?

2022-10-12 21:11 UTC, carterbox commented
@conda-forge/help-python-c, please review

2022-10-21 21:48 UTC, pabloferz commented
@conda-forge/help-python-c, please review

2022-10-22 17:41 UTC, xhochy commented on recipes/hoomd-dlext/meta.yaml
> +  number: {{ build }}
Otherwise the bot might not be able to automatically bump the build no on PRs
```suggestion
  number: 0
```

2022-10-22 17:41 UTC, xhochy commented on recipes/hoomd-dlext/meta.yaml
> +{% set build = 0 %}
```suggestion
```

2022-10-22 17:41 UTC, xhochy commented on recipes/hoomd-dlext/build.sh
> +cmake -S . -B $BUILD_PATH $CMAKE_FLAGS -Wno-dev
```suggestion
cmake ${CMAKE_ARGS} -S . -B $BUILD_PATH $CMAKE_FLAGS -Wno-dev
```

2022-10-22 17:41 UTC, xhochy commented on recipes/hoomd-dlext/build.sh
> +    CMAKE_FLAGS+=" -DCMAKE_OSX_DEPLOYMENT_TARGET=${MACOSX_DEPLOYMENT_TARGET}"
Part of CMAKE_ARGS
```suggestion
```

2022-10-22 19:58 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/hoomd-dlext```) and found some lint.

Here's what I've got...


For **recipes/hoomd-dlext**:

 * Failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint .` from the recipe directory.

2022-10-24 14:30 UTC, xhochy commented on recipes/hoomd-dlext/meta.yaml
> +  string: {{ 'cuda' ~ cuda_compiler_version|string }}_py{{ py }}h{{ PKG_HASH }}_{{ build + 100 }}  # [cuda_compiler_version != "None"]
```suggestion
  string: {{ 'cuda' ~ cuda_compiler_version|string }}_py{{ py }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
```

2022-10-24 14:46 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/hoomd-dlext```) and found it was in an excellent condition.

2022-10-24 15:16 UTC, xhochy approved these changes

2022-10-25 06:50 UTC, merged