add snowline Laplace approximation and Importance Sampling python package for Bayesian inference
conda-forge/staged-recipes pull request #20535
Opened 2022-09-23 07:46 UTC by JohannesBuchner

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-09-23 07:47 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/snowline```) and found it was in an excellent condition.

2022-09-23 08:45 UTC, JohannesBuchner commented
I am seeing this error:

```
Reloading output folder: /home/conda/staged-recipes/build_artifacts
Mamba failed to solve:
 - pypmc
 - python 3.9.* *_cpython
 - pytest-runner
 - numpy 1.20.*
 - pip
 - iminuit

with channels:
 - local
 - conda-forge
 - conda-forge

The reported errors are:
- Encountered problems while solving:
-   - package pypmc-1.2-py37hc105733_0 requires python_abi 3.7.* *_cp37m, but none of the providers can be installed
```

pypmc is a cpython package that snowline depends on.

I don't understand why "python 3.9.* *_cpython" tries to pull in the py37h version of pypmc.

iminuit is another cpython package that snowline depends on. Its recipe is here: https://github.com/conda-forge/iminuit-feedstock/blob/main/recipe/meta.yaml

This [stackoverflow question](https://stackoverflow.com/questions/73433762/why-does-conda-package-install-complain-about-both-python-abi-3-7-and-3-9) has the same error but from a user perspective.

snowline is pure python, but requires the two cpython packages.

@conda-forge/help-python-c, can you please help?

2022-10-06 04:07 UTC, carterbox requested changes
If this package is pure python, then it can be `noarch: python`.

2022-10-06 04:07 UTC, carterbox commented on recipes/snowline/meta.yaml
> +    - pytest
```suggestion
test:
  imports:
    - snowline
  source_files:
    - tests/*
  requires:
    - pytest >=3
    - pip
  commands:
    - pip check
    - pytest tests/
```

2022-10-06 04:07 UTC, carterbox commented on recipes/snowline/meta.yaml
> +    - iminuit
These do not match the upstream metadata

https://github.com/JohannesBuchner/snowline/blob/6f9b5f767903ebf0537569ff85752a8533664b8a/setup.py#L23

2022-10-06 04:07 UTC, carterbox commented on recipes/snowline/meta.yaml
> +    - pytest-runner
```suggestion
  host:
    - python
    - pytest-runner
    - setuptools
```

2022-10-06 04:09 UTC, carterbox commented on recipes/snowline/meta.yaml
> +    - python
```suggestion
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pytest-runner
    - setuptools
  run:
    - python >=3.5
```

2022-10-06 04:28 UTC, carterbox requested changes
Figure out the tests and fix the incorrect runtime requirements.

2022-10-06 16:20 UTC, carterbox commented
> Tests are fixed by installing openssh to make openmpi work.

Looks like openssh is only required because these packages are being built inside a container? It's not actually a direct dependency of your package. Only direct dependencies of your package go in the requirements section. Packages that are only required for the tests go in the test/requires section, not the requirements/run section.

2022-10-07 06:18 UTC, JohannesBuchner commented
> > Tests are fixed by installing openssh to make openmpi work.
> 
> Looks like openssh is only required because these packages are being built inside a container? It's not actually a direct dependency of your package. Only direct dependencies of your package go in the requirements section. Packages that are only required for the tests go in the test/requires section, not the requirements/run section.

Thank you for pointing this out! I made the change.

2022-11-07 09:12 UTC, JohannesBuchner commented
I think this is ready to be merged

2022-11-07 09:13 UTC, merged