Add JAXopt recipe to conda-forge
conda-forge/staged-recipes pull request #20548
Opened 2022-09-24 09:54 UTC by dirmeier

Hi all,

this PR adds [JAXopt](https://github.com/google/jaxopt) as recipe.

Greets,
Simon

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-09-24 09:54 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/jaxopt```) and found some lint.

Here's what I've got...


For **recipes/jaxopt**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

For **recipes/jaxopt**:

 * Recipes should usually depend on `matplotlib-base` as opposed to `matplotlib` so that runtime environments do not require large packages like `qt`.

2022-09-24 09:57 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/jaxopt```) and found it was in an excellent condition.

2022-09-24 11:33 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/jaxopt```) and found some lint.

Here's what I've got...


For **recipes/jaxopt**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2022-09-24 11:50 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/jaxopt```) and found it was in an excellent condition.

2022-09-24 12:18 UTC, dirmeier commented
Hello @conda-forge/help-python, I think this is ready for review. Would you mind having a look? Thank, Simon

2022-09-26 23:38 UTC, dopplershift requested changes
Just some minor tweaks, including moving to noarch if possible.

2022-09-26 23:38 UTC, dopplershift commented on recipes/jaxopt/meta.yaml
> +  sha256: {{ sha256 }}
Don't worry about templatizing the hash, just put it in here:
```suggestion
  sha256: 9d48c30c78285ec5beea0264bb21fa69bbf9b82354136f0aaab0f956f82dd797
```

2022-09-26 23:38 UTC, dopplershift commented on recipes/jaxopt/meta.yaml
> +{% set sha256 = "9d48c30c78285ec5beea0264bb21fa69bbf9b82354136f0aaab0f956f82dd797" %}
```suggestion
```

2022-09-26 23:38 UTC, dopplershift commented on recipes/jaxopt/meta.yaml
> +  skip: true  # [win or py<37]
This looks like it's pure Python and can be noarch:
```suggestion
  noarch: python
```

We can ignore if this fails on Windows due to missing dependencies.

2022-09-26 23:38 UTC, dopplershift commented on recipes/jaxopt/meta.yaml
> +    - python
For noarch:
```suggestion
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
```

2022-09-27 17:07 UTC, dirmeier commented
Hi @dopplershift , thanks for the review. I commited your changes. The win build now fails as Jax doesn't have a windows install candidate.

2022-09-27 19:00 UTC, dopplershift approved these changes
Ignoring Windows CI failure due to missing dependency.

2022-09-27 19:00 UTC, merged