Adding conda_envfile
conda-forge/staged-recipes pull request #20656
Opened 2022-10-05 06:45 UTC by tdegeus

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-10-05 06:45 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/conda_envfile```) and found it was in an excellent condition.

2022-10-05 07:37 UTC, tdegeus commented
@conda-forge/help-python ready for review

2022-10-07 09:56 UTC, jaimergp commented on recipes/conda_envfile/meta.yaml
> +  doc_url: https://github.com/{{ org }}/{{ name }}
```suggestion
  doc_url: https://conda-envfile.readthedocs.io/
```

2022-10-07 09:59 UTC, tdegeus commented
Thanks @jaimergp . I've updated

2022-10-07 09:59 UTC, jaimergp requested changes
Thanks! This is like a conda-less implementation of some parts of the `MatchSpec.merge` functionality. Nice!

There's an issue with the packaged files, though:

```
  adding 'conda_envfile/__init__.py'
  adding 'conda_envfile/_version.py'
  adding 'tests/__init__.py'
  adding 'tests/test_basic.py'
  adding 'conda_envfile-0.1.0.dist-info/LICENSE'
  adding 'conda_envfile-0.1.0.dist-info/METADATA'
  adding 'conda_envfile-0.1.0.dist-info/WHEEL'
  adding 'conda_envfile-0.1.0.dist-info/entry_points.txt'
  adding 'conda_envfile-0.1.0.dist-info/top_level.txt'
  adding 'conda_envfile-0.1.0.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
```

Your test files are being shipped as a global package, which is usually disregarded. You'll need to adjust the `exclude` options of the `find_packages` call, either in a patch or in a new (micro) release usptream.

Thanks again!

2022-10-07 10:07 UTC, tdegeus commented
Thanks @jaimergp , I had not paid attention. Fixed it upstream.

2022-10-10 13:34 UTC, tdegeus commented
@jaimergp Are you around to re-review?

2022-10-11 09:59 UTC, merged

2022-10-11 10:06 UTC, tdegeus commented
Thanks!