add pytest-redis
conda-forge/staged-recipes pull request #20698
Opened 2022-10-09 10:45 UTC by woutdenolf

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-10-09 10:45 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pytest-redis```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/pytest-redis**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-10-09 10:49 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pytest-redis```) and found some lint.

Here's what I've got...


For **recipes/pytest-redis**:

 * Failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint .` from the recipe directory.

2022-10-09 10:59 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pytest-redis```) and found it was in an excellent condition.

2022-10-10 20:01 UTC, dopplershift requested changes
Just a few tweaks around the license and this is good to go.

2022-10-10 20:01 UTC, dopplershift commented on recipes/pytest-redis/meta.yaml
> +  license: LGPL-3.0-only
Looks like it's [actually](https://github.com/ClearcodeHQ/pytest-redis/blob/c020d6b7d7f78da117f67252dc43f6f4755dc112/src/pytest_redis/__init__.py#L9-L10):
```suggestion
  license: LGPL-3.0-or-later
```

2022-10-10 21:54 UTC, woutdenolf commented on recipes/pytest-redis/COPYING
> +                    GNU GENERAL PUBLIC LICENSE
Thanks for the review! Do you mean I should remove the `license_file:` section from the recipe? And remove the license files as well?

2022-10-10 21:57 UTC, woutdenolf commented on recipes/pytest-redis/COPYING
> +                    GNU GENERAL PUBLIC LICENSE
Or just remove the files and keep the `license_file:` section?

2022-10-10 21:59 UTC, woutdenolf commented on recipes/pytest-redis/COPYING
> +                    GNU GENERAL PUBLIC LICENSE
I assume you meant remove the files and keep the `license_file: section`

2022-10-10 21:59 UTC, woutdenolf commented on recipes/pytest-redis/COPYING
> +                    GNU GENERAL PUBLIC LICENSE
done

2022-10-10 21:59 UTC, woutdenolf commented on recipes/pytest-redis/COPYING.lesser
> +                   GNU LESSER GENERAL PUBLIC LICENSE
I assume you meant remove the files and keep the `license_file: section`

2022-10-10 22:00 UTC, woutdenolf commented on recipes/pytest-redis/COPYING.lesser
> +                   GNU LESSER GENERAL PUBLIC LICENSE
done

2022-10-11 14:41 UTC, dopplershift commented on recipes/pytest-redis/COPYING
> +                    GNU GENERAL PUBLIC LICENSE
That's correct. Thanks!

2022-10-11 14:41 UTC, dopplershift approved these changes

2022-10-11 14:41 UTC, merged