Adding NCAR/vapor python package
conda-forge/staged-recipes pull request #20732
Opened 2022-10-12 01:17 UTC by StasJ

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-10-12 01:17 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/vapor```) and found some lint.

Here's what I've got...


For **recipes/vapor**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [16, 17]
 * ``requirements: build: make=4.3`` must contain a space between the name and the pin, i.e. ``make =4.3``
 * ``requirements: build: cmake=3.21.3`` must contain a space between the name and the pin, i.e. ``cmake =3.21.3``
 * ``requirements: build: unzip=6.0`` must contain a space between the name and the pin, i.e. ``unzip =6.0``
 * ``requirements: build: jupytext=1.13.8`` must contain a space between the name and the pin, i.e. ``jupytext =1.13.8``
 * ``requirements: build: doxygen=1.9.1`` must contain a space between the name and the pin, i.e. ``doxygen =1.9.1``
 * ``requirements: build: python=3.9.5`` must contain a space between the name and the pin, i.e. ``python =3.9.5``
 * ``requirements: build: numpy=1.21.4`` must contain a space between the name and the pin, i.e. ``numpy =1.21.4``
 * ``requirements: build: assimp=5.0.1`` must contain a space between the name and the pin, i.e. ``assimp =5.0.1``
 * ``requirements: build: freetype=2.10.4`` must contain a space between the name and the pin, i.e. ``freetype =2.10.4``
 * ``requirements: build: hdf5=1.12.1`` must contain a space between the name and the pin, i.e. ``hdf5 =1.12.1``
 * ``requirements: build: jpeg=9e`` must contain a space between the name and the pin, i.e. ``jpeg =9e``
 * ``requirements: build: geotiff=1.6.0`` must contain a space between the name and the pin, i.e. ``geotiff =1.6.0``
 * ``requirements: build: udunits2=2.2.26`` must contain a space between the name and the pin, i.e. ``udunits2 =2.2.26``
 * ``requirements: build: netcdf4=1.5.8`` must contain a space between the name and the pin, i.e. ``netcdf4 =1.5.8``
 * ``requirements: build: libtiff=4.3.0`` must contain a space between the name and the pin, i.e. ``libtiff =4.3.0``
 * ``requirements: build: proj=7.2.0`` must contain a space between the name and the pin, i.e. ``proj =7.2.0``
 * ``requirements: build: glm=0.9.9.4`` must contain a space between the name and the pin, i.e. ``glm =0.9.9.4``
 * ``requirements: build: mesalib=21.2.5`` must contain a space between the name and the pin, i.e. ``mesalib =21.2.5``
 * ``requirements: run: xarray=2022`` must contain a space between the name and the pin, i.e. ``xarray =2022``
 * ``requirements: run: matplotlib=3`` must contain a space between the name and the pin, i.e. ``matplotlib =3``
 * ``requirements: run: ipython=8`` must contain a space between the name and the pin, i.e. ``ipython =8``
 * ``requirements: run: jupyter=1`` must contain a space between the name and the pin, i.e. ``jupyter =1``
 * ``requirements: run: py-opencv=4`` must contain a space between the name and the pin, i.e. ``py-opencv =4``
 * ``requirements: run: cppyy=2.2`` must contain a space between the name and the pin, i.e. ``cppyy =2.2``
 * ``requirements: run: python=3.9`` must contain a space between the name and the pin, i.e. ``python =3.9``

For **recipes/vapor**:

 * Recipe with the same name exists in bioconda: please discuss with @conda-forge/bioconda-recipes.
 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-10-12 01:26 UTC, sgpearse commented
To whom it may concern: I am a developer on the NCAR/VAPOR project and am eager to support this important utility on Conda's infrastructure.

2022-10-12 18:45 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/vapor```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/vapor**:

 * Recipe with the same name exists in bioconda: please discuss with @conda-forge/bioconda-recipes.
 * Recipes should usually depend on `matplotlib-base` as opposed to `matplotlib` so that runtime environments do not require large packages like `qt`.

2022-10-12 19:10 UTC, StasJ commented
@conda-forge-admin, please ping conda-forge/help-c-cpp

The linux build is failing with multiple of the following errors:

```
ERROR (vapor,lib/librender.so): $RPATH/libfreetype.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?
```

However all of the libraries the errors reference are in the required packages.

meta.yaml +25:
```
requirements:
   build:
     [...]
     - freetype =2.10.4
```

2022-10-12 19:10 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/help-c-cpp and so here I am doing that.

2022-11-01 00:59 UTC, carterbox requested changes
Please add a `requirements/host` section.

The `requirements/build` section is for build tools like cmake, make, doxygen, and compilers. These tools are only needed during the build and not needed again at runtime.

The `requirements/host` section is for libraries that target platform specific and that are needed at both build/compile time and again at run/link time.

Please move libraries need at compile time to the host section. i.e. numpy, jpeg, libtiff, ...

2022-11-01 00:59 UTC, carterbox commented on recipes/vapor/build.sh
> +    -DCONDA_BUILD=ON \
```suggestion
cmake .. \
    -DBUILD_SHARED_LIBS:BOOL=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DCONDA_BUILD=ON \
```

2022-11-01 00:59 UTC, carterbox commented on recipes/vapor/meta.yaml
> +    - "*.py"
Why? This is all python files? Maybe limit this to a specific directory?

2022-11-01 00:59 UTC, carterbox commented on recipes/vapor/meta.yaml
> +{% set name = "VAPOR" %}
You need to open a PR on bioconda to remove their package at the same time that this one is added to conda-forge if it is the same package.

2022-12-08 05:21 UTC, StasJ commented
> Please add a `requirements/host` section.
> 
> The `requirements/build` section is for build tools like cmake, make, doxygen, and compilers. These tools are only needed during the build and not needed again at runtime.
> 
> The `requirements/host` section is for libraries that target platform specific and that are needed at both build/compile time and again at run/link time.
> 
> Please move libraries need at compile time to the host section. i.e. numpy, jpeg, libtiff, ...

@carterbox if I move the libraries to `requirements/host` like so:
```
requirements:
  build:
    - make
    - ...
  host:
    - udunits2 =2.2
    - netcdf4 =1.5
    - ...
  run:
    - py-opencv 
    - ...
```

I get the following errors:
```
WARNING (vapor,lib/libvdc.dylib): Needed DSO lib/libudunits2.0.dylib found in ['udunits2']
WARNING (vapor,lib/libvdc.dylib): .. but ['udunits2'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
WARNING (vapor,lib/libvdc.dylib): Needed DSO lib/libnetcdf.19.dylib found in ['libnetcdf']
WARNING (vapor,lib/libvdc.dylib): .. but ['libnetcdf'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
...
```

And then conda fails to install the dependencies with the package.

2022-12-08 16:33 UTC, carterbox commented
If your binary links to those libraries, then are needed at runtime. If they are not needed, but your binary contains references/symbols of those libraries, then you are overlinking.

2022-12-08 19:28 UTC, StasJ commented
> If your binary links to those libraries, then are needed at runtime. If they are not needed, but your binary contains references/symbols of those libraries, then you are overlinking.

My binary links to those libraries and they are needed at runtime, the issue is Conda does not install them, despite being listed in `host`, so they are not available at runtime.

2023-06-18 01:32 UTC, closed without merging