Adding recipe for zenodo-backpack
conda-forge/staged-recipes pull request #20914
Opened 2022-10-27 05:40 UTC by chklovski

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-10-27 05:40 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/zenodo-backpack```) and found some lint.

Here's what I've got...


For **recipes/zenodo-backpack**:

 * license_file entry is missing, but is required.

For **recipes/zenodo-backpack**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-10-27 05:52 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/zenodo-backpack```) and found some lint.

Here's what I've got...


For **recipes/zenodo-backpack**:

 * about/license_family 'GPL-2.0-or-later' not allowed. Allowed families
are AGPL, APACHE, BSD, CC, GPL, GPL2, GPL3, LGPL, MIT, MOZILLA, NONE,
OTHER, PROPRIETARY, PSF, and PUBLIC-DOMAIN.

2022-10-27 05:53 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/zenodo-backpack```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/zenodo-backpack**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-10-27 17:05 UTC, dopplershift requested changes
Just a minor tweak to the license metadata and this is good to go.

2022-10-27 17:05 UTC, dopplershift commented on recipes/zenodo-backpack/meta.yaml
> +  license: GPL3
Not sure why the linter okayed this, but it should be:

```suggestion
  license: GPL-3.0-or-later
```

2022-10-27 23:52 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/zenodo-backpack```) and found it was in an excellent condition.

2022-10-28 12:48 UTC, xhochy requested changes

2022-10-28 12:48 UTC, xhochy commented on recipes/zenodo-backpack/meta.yaml
> +test:
Please add a call to `pip check` to check for the integrity with of the requirements specification.
```suggestion
test:
  requires:
    - pip
  commands:
    - pip check
```

2022-10-28 12:48 UTC, xhochy commented on recipes/zenodo-backpack/meta.yaml
> +    - conda=conda.cli.pip_warning:main
This should not be listed here.
```suggestion
    - conda=conda.cli.pip_warning:main
```

2022-10-28 14:36 UTC, xhochy approved these changes

2022-10-28 14:36 UTC, merged