Committing recipe for conda-forge release of pdffit2
conda-forge/staged-recipes pull request #21039
Opened 2022-11-05 13:21 UTC by dragonyanglong

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-11-05 13:21 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/diffpy.pdffit2```) and found some lint.

Here's what I've got...


For **recipes/diffpy.pdffit2**:

 * Failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint .` from the recipe directory.

2022-11-05 13:23 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/diffpy.pdffit2```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/diffpy.pdffit2**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-11-06 10:44 UTC, dragonyanglong commented
please review and merge.

2022-11-10 06:56 UTC, dragonyanglong commented
@conda-forge-admin  ready for review!

2022-11-20 01:12 UTC, dragonyanglong commented
@conda-forge/staged-recipes, hi please review.

2022-11-27 12:00 UTC, dragonyanglong commented
@conda-forge/help-python ready for review.

2022-11-27 15:38 UTC, xhochy requested changes
Please remove the comments from the example

2022-11-27 15:38 UTC, xhochy commented on recipes/diffpy.pdffit2/meta.yaml
> +{% set name = "simplejson" %}
Please use the variables here to template the recipe.

2022-11-27 15:38 UTC, xhochy commented on recipes/diffpy.pdffit2/meta.yaml
> +  preserve_egg_dir: True
```suggestion
```

2022-11-27 15:38 UTC, xhochy commented on recipes/diffpy.pdffit2/meta.yaml
> +    - gsl {{ gsl }}
Should be in host without the variable.

2022-11-27 15:38 UTC, xhochy commented on recipes/diffpy.pdffit2/meta.yaml
> +#   #   - pip
Please add pip check

2022-11-28 04:46 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/diffpy.pdffit2```) and found some lint.

Here's what I've got...


For **recipes/diffpy.pdffit2**:

 * Failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint .` from the recipe directory.

2022-11-28 04:56 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/diffpy.pdffit2```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/diffpy.pdffit2**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-11-28 05:15 UTC, dragonyanglong commented
Dear @xhochy , @conda-forge/help-python thanks for your review. The yaml file is updated per your comments, please review.

2022-11-28 13:12 UTC, xhochy requested changes

2022-11-28 13:12 UTC, xhochy commented on recipes/diffpy.pdffit2/meta.yaml
> +  license: Modified BSD
Can you please fix the linter comment? It looks like this is BSD-3-clause

2022-11-28 16:24 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/diffpy.pdffit2```) and found it was in an excellent condition.

2022-11-28 16:24 UTC, dragonyanglong commented
Thanks @xhochy , I updated it. Please review.

2022-11-30 06:43 UTC, dragonyanglong commented
please hold on this PR, we are updating some codes of the package to be released. Once done, I will let you know. thanks.

2022-12-11 04:18 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/diffpy.pdffit2```) and found some lint.

Here's what I've got...


For **recipes/diffpy.pdffit2**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2022-12-11 04:20 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/diffpy.pdffit2```) and found it was in an excellent condition.

2022-12-11 08:27 UTC, dragonyanglong commented
@conda-forge/help-python @xhochy  this is ready for review now. Thanks so much!

2022-12-11 08:36 UTC, dragonyanglong commented
@conda-forge/staged-recipes

2022-12-11 21:08 UTC, xhochy requested changes

2022-12-11 21:08 UTC, xhochy commented on recipes/diffpy.pdffit2/meta.yaml
> +    - sbillinge
@sbillinge Please confirm that you're happy to be a maintainer here.

2022-12-11 21:57 UTC, sbillinge commented
I confirm

On Sun, Dec 11, 2022, 4:08 PM Uwe L. Korn ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In recipes/diffpy.pdffit2/meta.yaml
> <https://github.com/conda-forge/staged-recipes/pull/21039#discussion_r1045296702>
> :
>
> > +  home: https://github.com/diffpy/diffpy.pdffit2
> +  summary: PDFfit2 - real space structure refinement program.
> +  description: |
> +    PDFgui is a software for pair distribution function simulation and
> +    structure refinement, which provides a simple, fast, and easy-to-use user
> +    interface for chemists, physicists, and materials scientists.
> +  license: BSD-3-Clause
> +  license_family: BSD
> +  license_file: LICENSE.txt
> +  doc_url: https://www.diffpy.org/doc/pdffit2
> +  dev_url: https://github.com/diffpy/diffpy.pdffit2
> +
> +extra:
> +  recipe-maintainers:
> +    - dragonyanglong
> +    - sbillinge
>
> @sbillinge <https://github.com/sbillinge> Please confirm that you're
> happy to be a maintainer here.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/conda-forge/staged-recipes/pull/21039#pullrequestreview-1212754621>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABAOWUMIOHHKKZVTJSNCQYTWMY7DXANCNFSM6AAAAAARX5UCYA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-11 22:00 UTC, xhochy approved these changes

2022-12-11 22:00 UTC, merged