pyvisa-sim
conda-forge/staged-recipes pull request #21162
Opened 2022-11-15 07:00 UTC by mtsolmn

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-11-15 07:00 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyvisa-sim```) and found some lint.

Here's what I've got...


For **recipes/pyvisa-sim**:

 * `noarch` packages can't have skips with selectors. If the selectors are necessary, please remove `noarch: python`.

2022-11-15 07:06 UTC, mtsolmn commented
@MatthieuDartiailh saw the comment about adding `pyvisa-sim` to `conda-forge` in this issue: https://github.com/pyvisa/pyvisa-sim/issues/62 and here: https://github.com/conda-forge/pyvisa-py-feedstock/issues/22

I doubt I will be able to meaningfully help maintain the package, but I've added you to the maintainer list. Comment to accept and please add anyone else who you think can help maintain this. Thanks

2022-11-15 07:12 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyvisa-sim```) and found it was in an excellent condition.

2022-11-15 07:37 UTC, MatthieuDartiailh commented
I agree to maintain the package once this PR is merged.

2022-11-16 06:43 UTC, mtsolmn commented
@conda-forge-admin, please rerender

2022-11-16 07:44 UTC, mtsolmn commented
@MatthieuDartiailh do you have any idea why the pytests are failing? If you don't know and don't think it's an issue, then I would remove the purest commands from the recipe and publish. Let me know your thoughts, thanks.

2022-11-16 07:52 UTC, MatthieuDartiailh commented
It looks like some changes in pyvisa (notably handling of GPIB secondary address) broke some of the tests of pyvisa-sim. I will have to try to fix them at one point, but I have limited bandwidth for this project.

2022-11-17 03:53 UTC, mtsolmn commented
@MatthieuDartiailh I totally get it. I think the repository is fine as is, and the package is working nominally, even if the built-in tests haven't been appropriately updated. I've gone ahead and removed the tests from the CI pipeline for publishing.

2022-11-18 01:50 UTC, mtsolmn commented
@conda-forge/help-python ready to merge :)

2022-11-21 20:08 UTC, xhochy requested changes

2022-11-21 20:08 UTC, xhochy commented on recipes/pyvisa-sim/meta.yaml
> +    - pytest
This doesn't seem to be used in the tests here.
```suggestion
```

2022-11-21 20:08 UTC, xhochy commented on recipes/pyvisa-sim/meta.yaml
> +    - python >3.6
Better use `>=`. `>` is not so common and harder to comprehend.

2022-11-22 09:01 UTC, xhochy approved these changes

2022-11-22 09:01 UTC, merged