add "sepal-ui" to conda-forge
conda-forge/staged-recipes pull request #21231
Opened 2022-11-21 21:10 UTC by 12rambau

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-11-21 21:10 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/sepal-ui```) and found it was in an excellent condition.

2022-11-21 21:37 UTC, 12rambau commented
@conda-forge-admin, please ping team

2022-11-21 21:37 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/staged-recipes and so here I am doing that.

2022-11-21 21:37 UTC, 12rambau commented
The build failed because of one of my dependencies: planet. 

Is it because it's a pre-release?

2022-11-21 22:13 UTC, dopplershift commented
The latest version in the [planet feedstock](https://github.com/conda-forge/planet-feedstock) is 1.5.2, so there's no package meeting the version you're requesting available in conda-forge. We definitely would not want to update to the pre-release on the main conda-forge channel.

2022-11-21 22:18 UTC, 12rambau commented
They have forced their users (me included) to upgrade to v2 6 month ago, it's so different that it's impossible to be compatible with both (and way too much work). I guess I'll be forced to wait for the release from their side

2022-12-02 02:24 UTC, BastianZim commented
You could ask the maintainer of the feedstock to also publish the pre-release version or make a PR yourself. Some more info is here: https://conda-forge.org/docs/maintainer/knowledge_base.html#pre-release-builds

2022-12-06 03:39 UTC, 12rambau commented on recipes/sepal-ui/meta.yaml
> +    - planet ==2.0a2
```suggestion
    - planet >=2.0
```

2022-12-09 07:07 UTC, 12rambau commented on recipes/sepal-ui/meta.yaml
> +    - planet >=2.0
```suggestion
    - planet >=2.0a6
```

2022-12-11 14:57 UTC, 12rambau commented
@BastianZim, the maintainer of the planet feedstock created a [2.0a6 pre-release](https://github.com/conda-forge/planet-feedstock/pull/32), how can I add it to my recipe ? (I tried setting the exact version number but it didn't worked). Would you mind pointing me to the right direction ?

2022-12-11 15:08 UTC, BastianZim commented
That’s because they are on a different channel, these docs should help: https://conda-forge.org/docs/maintainer/knowledge_base.html#creating-a-pre-release-build

In short, create a conda_build_config.yaml in your recipe folder and add the following:

channel_sources:
  - conda-forge/label/planet_dev,conda-forge

2022-12-11 22:26 UTC, BastianZim requested changes
Just thing and this is good to go.

2022-12-11 22:26 UTC, BastianZim commented on recipes/sepal-ui/meta.yaml
> +    - LICENSE.txt
```suggestion
    - LICENSE.txt
    - sepal_ui/templates/map_app/LICENSE
    - sepal_ui/templates/panel_app/LICENSE
```

2022-12-15 16:52 UTC, merged