Add Ruff recipe
conda-forge/staged-recipes pull request #21281
Opened 2022-11-25 01:23 UTC by charliermarsh

This PR adds [Ruff] to conda-forge. As Ruff is written in Rust, and distributed via Maturin, I've mirrored the setup from `pysyntect` (https://github.com/conda-forge/staged-recipes/pull/11315), including adding all of the licenses to `library_licenses` via [`get-license-helper`](https://github.com/cds-astro/get-license-helper).

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-11-25 01:24 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/ruff```) and found it was in an excellent condition.

2022-11-26 21:31 UTC, charliermarsh commented
@conda-forge/staged-recipes ready for review!

2022-11-26 21:32 UTC, charliermarsh commented
https://github.com/orgs/conda-forge/teams/staged-recipes ready for review!

2022-11-26 21:32 UTC, charliermarsh commented
@conda-forge/staged-recipes ready for review!

2022-11-27 15:43 UTC, xhochy commented
I cannot review this PR on mobile ad the diff is too large. I guess this is because it statically contains all licenses. Please don't include them in git but download them during the build. This way it will also always include the licenses matching the current release.

2022-11-27 16:02 UTC, charliermarsh commented
Ah ok, can do! I was just following the pysyntect example which does include the licenses in Git (https://github.com/conda-forge/pysyntect-feedstock/tree/main/recipe/library_licenses).

The challenge with bundling at build time is that there are probably 5-10 licenses that are very hard to pick up using automated tools and had to be copied in manually. I’ll have to special-case or omit those.

2022-11-27 16:05 UTC, xhochy commented
Add the hard ones then manually in git and do the other automated. That combination should be a good compromise.

2022-11-27 16:10 UTC, charliermarsh commented
Sounds good, thanks for the review. Will fix.

2022-11-28 03:27 UTC, charliermarsh commented
Ok, this now uses the same approach as [wasmer-feedstock](https://github.com/conda-forge/wasmer-feedstock/blob/main/recipe/bld.bat), which is to bundle a single YAML file at build-time via [`cargo-bundle-licenses`](https://github.com/sstadick/cargo-bundle-licenses).

2022-11-28 03:29 UTC, charliermarsh commented
There are a few warnings for missing licenses, but I see those exact same warnings when I run `cargo-bundle-licenses` on the `wasmer` repo.

2022-11-28 13:38 UTC, xhochy requested changes

2022-11-28 13:38 UTC, xhochy commented on recipes/ruff/build.sh
> +cargo install cargo-bundle-licenses
Please add `cargo-bundle-licenses` to `build` instead of building it from source.

2022-11-28 13:38 UTC, xhochy commented on recipes/ruff/conda_build_config.yaml
> +channel_sources:
This file should not be needed.

2022-11-28 13:38 UTC, xhochy commented on recipes/ruff/meta.yaml
> +    - pip
This mixes host and build dependencies. Probably the following should work:
```suggestion
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - maturin
    - toml
```

2022-11-28 13:38 UTC, xhochy commented on recipes/ruff/meta.yaml
> +    - /usr/lib/libresolv.9.dylib  # [osx]
Normally, Rust binaries should work without this.
```suggestion
```

2022-11-28 13:38 UTC, xhochy commented on recipes/ruff/build.sh
> +export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=$CC
Should not be needed.
```suggestion
```

2022-11-28 15:02 UTC, charliermarsh commented
(Will re-request a review once builds are passing.)

2022-11-30 04:57 UTC, charliermarsh commented
Okay, should be in better shape! Ready for re-review at your convenience.

2022-11-30 09:45 UTC, xhochy approved these changes

2022-11-30 09:45 UTC, merged