Add meta.yaml file for momlevel package
conda-forge/staged-recipes pull request #21312
Opened 2022-11-26 15:28 UTC by jkrasting

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-11-26 15:28 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/momlevel```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/momlevel**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-11-26 16:47 UTC, jkrasting commented
@conda-forge/help-python, ready for review!

2022-11-26 21:25 UTC, BastianZim requested changes
Just a couple of small things, then this is ready to go 🚀

2022-11-26 21:25 UTC, BastianZim commented on recipes/momlevel/meta.yaml
> +    - pip
```suggestion
    - pip
    - setuptools-git-versioning
```
Ref: https://github.com/jkrasting/momlevel/blob/1cfa0f4c84172b77535dee87c9bb10c08424e2cb/pyproject.toml#L2

2022-11-26 21:25 UTC, BastianZim commented on recipes/momlevel/meta.yaml
> +  license: Public Domain
This license is not allowed, as mentioned by the linker. If it is not a standard license, please create a custom License Ref: https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions

2022-11-27 15:02 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/momlevel```) and found some lint.

Here's what I've got...


For **recipes/momlevel**:

 * The about section contained an unexpected subsection name. license-ref-1 is not a valid subsection name.

2022-11-27 15:09 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/momlevel```) and found some lint.

Here's what I've got...


For **recipes/momlevel**:

 * The about section contained an unexpected subsection name. license-ref is not a valid subsection name.

2022-11-27 15:26 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/momlevel```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/momlevel**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-11-27 15:33 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/momlevel```) and found it was in an excellent condition.

2022-11-27 15:34 UTC, jkrasting commented
Thanks @BastianZim!

@conda-forge/help-python, ready for review!

2022-11-27 18:21 UTC, jkrasting commented
@conda-forge-admin, please restart ci

2022-11-28 01:57 UTC, merged