Add recipe for delta-spark library
conda-forge/staged-recipes pull request #21556
Opened 2022-12-15 21:55 UTC by nkarpov

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-12-15 21:55 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/delta-spark```) and found it was in an excellent condition.

2022-12-15 22:26 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/delta-spark```) and found some lint.

Here's what I've got...


For **recipes/delta-spark**:

 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).
 * When defining a source/url please add a sha256, sha1 or md5 checksum (sha256 preferably).

2022-12-15 22:53 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/delta-spark```) and found it was in an excellent condition.

2022-12-15 23:52 UTC, nkarpov commented
@conda-forge/help-python, ready for review!

2022-12-23 18:52 UTC, nkarpov commented
@conda-forge/staged-recipes hello, just following the note here https://conda-forge.org/docs/maintainer/adding_pkgs.html please let me know if there's anything else I can do to help push this over the line. Thanks!

2023-01-03 15:52 UTC, nkarpov commented
Hello @conda-forge-admin - checking in again, please let me know what I can do to help get this in. Thank you!

2023-01-18 02:12 UTC, nkarpov commented
Hello - checking in again. I believe I followed everything as noted on the contribution website https://conda-forge.org/docs/maintainer/adding_pkgs.html#checklist

Please let me know what can be done to help get this reviewed. Thanks!

2023-01-25 21:46 UTC, nkarpov commented
Hello - checking in again. Please let me know what can be done to help get this reviewed. Thanks!

2023-02-02 01:54 UTC, BastianZim requested changes
Just two things and this is good to go.

2023-02-02 01:54 UTC, BastianZim commented on recipes/delta-spark/meta.yaml
> +    folder: python
If most of the files needed are not included in the PyPI source, it is easier to use GitHub release.

In this case https://github.com/delta-io/delta/archive/refs/tags/v2.2.0.tar.gz and you can create the sha256 with `curl -sL https://github.com/username/reponame/archive/vX.X.X.tar.gz | openssl sha256`

2023-02-02 01:54 UTC, BastianZim commented on recipes/delta-spark/meta.yaml
> +  dev_url: https://github.com/delta-io/delta
```suggestion
```
Duplicate

2023-02-02 17:19 UTC, nkarpov commented
@BastianZim awesome thank you for the tip w the GitHub release! Pulling those files separately was dumb and frustrating.

2023-02-02 19:48 UTC, BastianZim requested changes

2023-02-02 19:48 UTC, BastianZim commented on recipes/delta-spark/LICENSE.txt
> +Copyright (2021) The Delta Lake Project Authors.  All rights reserved.
Since you're pulling from GitHub, this file can probably be removed from here as it will be in the GitHub tar ball.

2023-02-02 19:48 UTC, BastianZim commented on recipes/delta-spark/NOTICE.txt
> +Delta Lake
Same here

2023-02-02 19:48 UTC, BastianZim commented on recipes/delta-spark/meta.yaml
> +    sha256: 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5
```suggestion
source:
  url: https://github.com/delta-io/delta/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 18ad6b9630e02847fa145327cfb7d2a62b58f347f828846200167f4604b20182
```

2023-02-03 16:17 UTC, merged