Added pyhash as a package
conda-forge/staged-recipes pull request #21565
Opened 2022-12-16 22:07 UTC by thewchan

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-12-16 22:08 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyhash```) and found it was in an excellent condition.

2022-12-16 23:37 UTC, thewchan commented
@conda-forge/help-c-cpp @conda-forge/help-python-c Might need some help with win build here, seems like it got confused with some path situation?

2022-12-29 16:08 UTC, thewchan commented
@conda-forge/staged-recipes Calling for help again re: win build.

2023-01-04 04:45 UTC, carterbox requested changes

2023-01-04 04:45 UTC, carterbox commented on recipes/pyhash/meta.yaml
> +    - cpuid
```suggestion
    - cpuid  # [x86]
```
https://github.com/flier/pyfasthash/blob/20a53f9bb7bf15f98e3e549f523b49e1e0f62e15/setup.py#L272

2023-01-04 04:45 UTC, carterbox commented on recipes/pyhash/meta.yaml
> +    - pytest-runner
```suggestion
```
None of these are required at runtime. They are for tests only.

2023-01-04 04:45 UTC, carterbox commented on recipes/pyhash/meta.yaml
> +  number: 0
```suggestion
build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:
   - PYTHON_HOME=$PREFIX
```
https://github.com/flier/pyfasthash/blob/20a53f9bb7bf15f98e3e549f523b49e1e0f62e15/setup.py#L75-L94

2023-01-04 05:02 UTC, carterbox commented on recipes/pyhash/meta.yaml
> +    - setuptools >=42,<58
```suggestion
    - setuptools >=42,<58
    # Setup checks for pytest at build time
    - pytest-benchmark
    - pytest-runner
```

2023-01-04 05:26 UTC, carterbox commented
Now the errors are compiler syntax errors. You'll have to ask upstream about those.

2023-04-15 15:08 UTC, thewchan commented
@conda-forge/staged-recipes @carterbox I checked upstream and it seems like they do not commit to support win, so I just skipped it. This is ready for final review then.

2023-04-18 15:50 UTC, merged