Initial commit for this recipe
conda-forge/staged-recipes pull request #21562
Opened 2022-12-16 20:31 UTC by mhearne-usgs

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-12-16 20:31 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/esi-utils-cartopy```) and found some lint.

Here's what I've got...


For **recipes/esi-utils-cartopy**:

 * Non noarch packages should have python requirement without any version constraints.

For **recipes/esi-utils-cartopy**:

 * Recipes should usually depend on `matplotlib-base` as opposed to `matplotlib` so that runtime environments do not require large packages like `qt`.
 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-12-16 20:33 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/esi-utils-cartopy```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/esi-utils-cartopy**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-12-16 21:12 UTC, mhearne-usgs commented
@conda-forge/help-python Can someone please merge this? Thank you in advance!

2022-12-22 17:42 UTC, mhearne-usgs commented
@ocefpaf I requested a review from the python team - is there someone else I should be pinging?

2022-12-22 18:34 UTC, ocefpaf commented on recipes/esi-utils-cartopy/meta.yaml
> +# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe
Ping!

2022-12-22 18:40 UTC, ocefpaf requested changes

2022-12-22 18:40 UTC, ocefpaf commented on recipes/esi-utils-cartopy/meta.yaml
> +    - pyproj
Upstream declares only `esi_utils_geo>=0.9.0`.

2022-12-22 18:40 UTC, ocefpaf commented on recipes/esi-utils-cartopy/meta.yaml
> +    - esi-utils-geo
```suggestion
    - esi-utils-geo >=0.9.0
```

2022-12-22 18:40 UTC, ocefpaf commented on recipes/esi-utils-cartopy/meta.yaml
> +    - {{ compiler('c') }}
This one does not seem to have any compiled extension.

```suggestion
```

2022-12-22 18:40 UTC, ocefpaf commented on recipes/esi-utils-cartopy/meta.yaml
> +  # noarch: python
```suggestion
  noarch: python
```

2022-12-22 18:40 UTC, ocefpaf commented on recipes/esi-utils-cartopy/meta.yaml
> +    - python
```suggestion
    - python >=3.8
```

2022-12-22 18:40 UTC, ocefpaf commented on recipes/esi-utils-cartopy/meta.yaml
> +    - python
```suggestion
    - python >=3.8
```

2022-12-22 21:47 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/esi-utils-cartopy```) and found some lint.

Here's what I've got...


For **recipes/esi-utils-cartopy**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

For **recipes/esi-utils-cartopy**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-12-22 21:48 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/esi-utils-cartopy```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipes/esi-utils-cartopy**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-12-22 22:00 UTC, mhearne-usgs commented
@conda-forge-admin please rerender

2022-12-22 22:04 UTC, mhearne-usgs commented
@ocefpaf The linux docker build failed, but it *looks* like its a network error. Tried re-rendering to restart the job, but that didn't appear to do what I wanted. If in fact this is a network error and I need to re-run the linux pipeline, how do I accomplish that?

2022-12-22 22:06 UTC, ocefpaf commented
> Tried re-rendering to restart the job, but that didn't appear to do what I wanted

re-render only works for feedstocks

> how do I accomplish that?

Closing and re-opening works. Or send a new commit. You still need to remove all the comments and to fix the license? I
I'll send those commits in a moment.

2022-12-22 22:06 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/esi-utils-cartopy```) and found it was in an excellent condition.

2022-12-22 22:27 UTC, merged