Add Cerbere recipe
conda-forge/staged-recipes pull request #21578
Opened 2022-12-20 15:53 UTC by Marie59

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-12-20 15:53 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/cerbere```) and found some lint.

Here's what I've got...


For **recipes/cerbere**:

 * Recipe maintainer "erwan.bodere" does not exist
 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2022-12-20 15:55 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/cerbere```) and found it was in an excellent condition.

2022-12-20 16:10 UTC, Marie59 commented
Hi @conda-forge/help-python this recipe is ready !

2022-12-20 21:05 UTC, dopplershift requested changes

2022-12-20 21:05 UTC, dopplershift commented on recipes/cerbere/meta.yaml
> +  skip: true
This is skipping all builds. I think this is pure Python and could be noarch?
```suggestion
  noarch: python
```

2022-12-20 21:05 UTC, dopplershift commented on recipes/cerbere/meta.yaml
> +    - python
For noarch, need to put Python version range here:
```suggestion
    - python >=3.6
    - pip
    - wheel

  run:
    - python >=3.6
```

2022-12-20 21:05 UTC, dopplershift commented on recipes/cerbere/meta.yaml
> +    - xarray  >=2022.3.0
Minor lint:
```suggestion
    - xarray >=2022.3.0 
```

2022-12-21 07:45 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/cerbere```) and found some lint.

Here's what I've got...


For **recipes/cerbere**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2022-12-21 07:46 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/cerbere```) and found it was in an excellent condition.

2022-12-21 07:47 UTC, Marie59 commented
Thank you for your help @dopplershift !

2022-12-22 07:55 UTC, Marie59 commented
@conda-forge/help-python I don't understand how to fix the issue with poetry_dynamic_versioning
Could you give me a hint ?

2022-12-22 08:02 UTC, BastianZim commented on recipes/cerbere/meta.yaml
> +    - poetry_dynamic_versioning
```suggestion
    - poetry-dynamic-versioning
```

2022-12-22 08:23 UTC, Marie59 commented on recipes/cerbere/meta.yaml
> +    - poetry_dynamic_versioning
Ooh duh thank you !

2023-01-04 10:01 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I was trying to look for recipes to lint for you, but it appears we have a merge conflict.
Please try to merge or rebase with the base branch to resolve this conflict.

Please ping the 'conda-forge/core' team (using the @ notation in a comment) if you believe this is a bug.

2023-01-04 10:02 UTC, closed without merging