Adding pdal-parallelizer recipe
conda-forge/staged-recipes pull request #21582
Opened 2022-12-21 09:29 UTC by ClementAlba

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-12-21 09:29 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pdal-parallelizer```) and found some lint.

Here's what I've got...


For **recipes/pdal-parallelizer**:

 * The recipe must have some tests.
 * There are too few lines.  There should be one empty line at the end of the file.

For **recipes/pdal-parallelizer**:

 * Recipes should usually depend on `matplotlib-base` as opposed to `matplotlib` so that runtime environments do not require large packages like `qt`.

2022-12-21 10:01 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pdal-parallelizer```) and found some lint.

Here's what I've got...


For **recipes/pdal-parallelizer**:

 * There are too few lines.  There should be one empty line at the end of the file.

2022-12-21 10:50 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pdal-parallelizer```) and found it was in an excellent condition.

2022-12-21 11:23 UTC, ClementAlba commented
@conda-forge/help-python, ready for review

2022-12-21 19:05 UTC, dopplershift requested changes
A minor tweak to make this noarch (really cuts down on the builds), but otherwise this is in great shape.

2022-12-21 19:05 UTC, dopplershift commented on recipes/pdal-parallelizer/meta.yaml
> +  number: 0
This is pure Python and can be marked as a "noarch" build:
```suggestion
  number: 0
  noarch: python
```

2022-12-21 19:05 UTC, dopplershift commented on recipes/pdal-parallelizer/meta.yaml
> +    - python
For noarch:
```suggestion
    - python >=3.7
  run:
    - python >=3.7
```

2022-12-26 08:33 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pdal-parallelizer```) and found some lint.

Here's what I've got...


For **recipes/pdal-parallelizer**:

 * noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

2022-12-26 08:33 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pdal-parallelizer```) and found it was in an excellent condition.

2022-12-26 09:04 UTC, ClementAlba commented
@dopplershift all changes have been made!

2023-01-05 08:34 UTC, ClementAlba commented
@conda-forge/help-python could you please check it again ?

2023-01-05 09:01 UTC, ClementAlba commented
@dopplershift Do you know why it indicate "Changes requested" while I have commit your changes and all the checks have passed ?

2023-02-02 02:13 UTC, BastianZim requested changes
Just a couple of small things, then this is ready to go 🚀

2023-02-02 02:13 UTC, BastianZim commented on recipes/pdal-parallelizer/meta.yaml
> +  script: "python -m pip install . --no-deps --ignore-installed -vv "
```suggestion
  script: {{ PYTHON }} -m pip install . -vv
```
This is sufficient.

2023-02-02 02:13 UTC, BastianZim commented on recipes/pdal-parallelizer/meta.yaml
> +    - pdal_parallelizer
```suggestion
    - pdal_parallelizer
  commands:
    - pip check
  requires:
    - pip
```
Tests some more stuff

2023-02-02 13:54 UTC, merged