Add Grafana-client recipe
conda-forge/staged-recipes pull request #21588
Opened 2022-12-22 13:12 UTC by Marie59

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-12-22 13:13 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/grafana-client```) and found it was in an excellent condition.

2022-12-22 13:31 UTC, Marie59 commented
@conda-forge/help-python this recipe is ready ! Thanks

2023-02-02 02:20 UTC, BastianZim requested changes
This can probably be noarch

2023-02-02 02:20 UTC, BastianZim commented on recipes/grafana-client/meta.yaml
> +    - setuptools-scm
```suggestion
```

2023-02-02 02:20 UTC, BastianZim commented on recipes/grafana-client/meta.yaml
> +  skip: true  # [py2k]
```suggestion
  noarch: python
```

2023-02-02 02:20 UTC, BastianZim commented on recipes/grafana-client/meta.yaml
> +    - python
```suggestion
    - python >=3.6
```

2023-02-02 02:20 UTC, BastianZim commented on recipes/grafana-client/meta.yaml
> +    - python
```suggestion
    - python >=3.6
```

2023-02-02 02:20 UTC, BastianZim commented on recipes/grafana-client/meta.yaml
> +    - dataclasses  # [py<=36]
```suggestion
    - dataclasses
```
Ref: https://conda-forge.org/docs/maintainer/knowledge_base.html#empty-python-packages

2023-02-02 02:20 UTC, BastianZim commented on recipes/grafana-client/meta.yaml
> +    - importlib-metadata  # [py<=37]
```suggestion
    - importlib-metadata
```

2023-02-02 21:13 UTC, BastianZim commented
@conda-forge-admin, please lint

2023-02-02 21:23 UTC, merged