Add ratarmountcore
conda-forge/staged-recipes pull request #21609
Opened 2022-12-25 10:08 UTC by ap--

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2022-12-25 10:08 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/ratarmountcore```) and found it was in an excellent condition.

2022-12-25 10:13 UTC, ap-- commented
@mxmlnkn please confirm to be maintainer whenever you have time. There's absolutely no rush :christmas_tree: :relaxed:

2022-12-25 10:44 UTC, mxmlnkn commented
I agree to be maintainer.

Merry Christmas to everyone involved.

2022-12-26 12:47 UTC, ap-- commented
@conda-forge/help-python, ready for review! 🎄

2023-01-17 20:10 UTC, mxmlnkn commented
@conda-forge/help-python, ready for review!

2023-01-20 18:55 UTC, dopplershift requested changes
Just a few minor tweaks.

2023-01-20 18:55 UTC, dopplershift commented on recipes/ratarmountcore/meta.yaml
> +  home: https://github.com/mxmlnkn/ratarmount/ratarmountcore
```suggestion
  home: https://github.com/mxmlnkn/ratarmount/tree/master/core
```

2023-01-20 18:55 UTC, dopplershift commented on recipes/ratarmountcore/meta.yaml
> +  number: 0
Looks like this is pure Python and could be noarch:
```suggestion
build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
```

2023-01-20 18:55 UTC, dopplershift commented on recipes/ratarmountcore/meta.yaml
> +    - importlib-metadata  # [py<38]
For noarch (we can just unconditionally depend on the other packages):
```suggestion
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dataclasses
    - importlib-metadata
```

2023-01-20 20:30 UTC, ap-- commented
@dopplershift thank you so much for the review.
I committed your suggested changes.

For the future: is it generally recommended to permanently pull in dependencies for earlier python versions in favour of noarch?

2023-01-20 20:49 UTC, dopplershift commented
> For the future: is it generally recommended to permanently pull in dependencies for earlier python versions in favour of noarch?

Yes, noarch drastically simplifies the build matrix and removes the need for many other rebuilds, like for new versions of Python.

2023-01-20 20:49 UTC, dopplershift approved these changes

2023-01-20 20:49 UTC, merged