Add animatplot-ng
conda-forge/staged-recipes pull request #21668
Opened 2023-01-06 17:43 UTC by johnomotani

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-01-06 17:44 UTC, johnomotani commented
@dschwoerer, @ZedThree could you please comment here to say you're happy to be maintainers? Thanks!

2023-01-07 18:45 UTC, johnomotani commented
@conda-forge/help-python I think this is ready to merge. Thanks!

2023-02-02 03:02 UTC, BastianZim requested changes
Just a couple of small things, then this is ready to go 🚀

2023-02-02 03:02 UTC, BastianZim commented on recipes/animatplot-ng/meta.yaml
> +{% set sha256 = "65255641d524a66bf7506c48d05cea3dd6ee6f4b48a88810754a8e8cb0041172" %}
```suggestion
```
We prefer to have this hardcoded so that it's easier for the bot.

2023-02-02 03:02 UTC, BastianZim commented on recipes/animatplot-ng/meta.yaml
> +  sha256: {{ sha256 }}
```suggestion
  sha256: 65255641d524a66bf7506c48d05cea3dd6ee6f4b48a88810754a8e8cb0041172
```

2023-02-02 03:02 UTC, BastianZim commented on recipes/animatplot-ng/meta.yaml
> +  script: {{ PYTHON }} -m pip install . --no-deps -vv
```suggestion
  script: {{ PYTHON }} -m pip install . -vv
```
This is sufficient.

2023-02-02 03:02 UTC, BastianZim commented on recipes/animatplot-ng/meta.yaml
> +    - pip
```suggestion
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
```

2023-02-02 16:56 UTC, merged