Adding openmm-nonbonded-slicing
conda-forge/staged-recipes pull request #21662
Opened 2023-01-05 23:37 UTC by craabreu

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-01-05 23:37 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/openmm-nonbonded-slicing```) and found it was in an excellent condition.

2023-01-06 03:25 UTC, craabreu commented
Hi @jananzhu, I'm adding you as a maintainer here, ok?

2023-01-06 16:06 UTC, jananzhu commented
@craabreu Sounds good, I'm willing to be a maintainer for this package.

2023-01-06 17:15 UTC, craabreu commented
@conda-forge/staged-recipes, ready for review

@conda-forge-admin, please ping team @conda-forge/staged-recipes

2023-01-06 17:16 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I was asked to ping @conda-forge/staged-recipes and so here I am doing that.

2023-02-16 11:47 UTC, craabreu commented
@conda-forge/staged-recipes or @conda-forge/help-python-c, would you please review this PR?

@conda-forge-admin, please ping team @conda-forge/staged-recipes

@conda-forge-admin, please ping team @conda-forge/help-python-c

2023-02-16 11:48 UTC, craabreu commented
@conda-forge-admin, please ping team @conda-forge/help-python-c

2023-05-16 13:16 UTC, craabreu commented
@conda-forge-admin, please ping team @conda-forge/help-python

2023-05-16 13:17 UTC, craabreu commented
Could you please review this recipe? It passed all tests on Jan 5.

2023-10-21 19:57 UTC, xhochy requested changes

2023-10-21 19:57 UTC, xhochy commented on recipes/openmm-nonbonded-slicing/build.sh
> +cmake ${CMAKE_FLAGS} ${SRC_DIR}
```suggestion
cmake ${CMAKE_ARGS} ${CMAKE_FLAGS} ${SRC_DIR}
```

2023-10-21 19:57 UTC, xhochy commented on recipes/openmm-nonbonded-slicing/build.sh
> +CMAKE_FLAGS="  -DCMAKE_INSTALL_PREFIX=${PREFIX}"
By using the provided CMAKE_ARGS you should be able to get rid of most of the flags here.

2023-10-21 19:57 UTC, xhochy commented on recipes/openmm-nonbonded-slicing/meta.yaml
> +{% set user = "craabreu" %}
Don't template this but write it plain.

2023-10-21 19:57 UTC, xhochy commented on recipes/openmm-nonbonded-slicing/meta.yaml
> +  missing_dso_whitelist:
Should no longer be necessary.

2023-10-21 19:57 UTC, xhochy commented on recipes/openmm-nonbonded-slicing/meta.yaml
> +    - conda-build
You have this as you are calling the recipe with it.
```suggestion
```

2023-12-11 23:17 UTC, craabreu reviewed
Thank you, @xhochy, for reviewing. I followed the suggestions as closely as possible. I had to update the recipe and building script to reflect changes in the package. I also updated the recipe following the latest version of the `openmm-torch` feedstock.

2023-12-11 23:17 UTC, craabreu commented on recipes/openmm-nonbonded-slicing/meta.yaml
> +{% set user = "craabreu" %}
Done.

2023-12-17 21:12 UTC, xhochy approved these changes

2023-12-17 21:12 UTC, merged