add recipe for trie
conda-forge/staged-recipes pull request #21733
Opened 2023-01-14 11:24 UTC by spinoch

2023-01-14 13:07 UTC, spinoch commented
@conda-forge/help-python ready for review :) , along with #21729, #21730, #21731, #21732

2023-03-01 22:45 UTC, BastianZim requested changes
Just a couple of small things, then this is ready to go 🚀

2023-03-01 22:45 UTC, BastianZim commented on recipes/trie/meta.yaml
> +  skip: true  # [py>=310]
```suggestion
  noarch: python
```

2023-03-01 22:45 UTC, BastianZim commented on recipes/trie/meta.yaml
> +    - python
```suggestion
    - python >=3.8,<4
```

2023-03-01 22:45 UTC, BastianZim commented on recipes/trie/meta.yaml
> +    - python
```suggestion
    - python >=3.8,<4
```

2023-03-01 22:45 UTC, BastianZim commented on recipes/trie/meta.yaml
> +    - typing-extensions >=4.0.0,<5  # [py<38]
```suggestion
```
This keeps in noarch. Conda-forge only supports python>=3.8 for non noarch packages so we can just restrict it.

2024-01-01 02:56 UTC, closed without merging