Adding DBnomics
conda-forge/staged-recipes pull request #21750
Opened 2023-01-17 11:13 UTC by michaelweinold

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-01-17 11:17 UTC, michaelweinold commented
@cbenz please add a comment in this thread confirming you want to be added as a feedstock maintainer (compare the PR checklist at the top).

2023-01-17 11:17 UTC, michaelweinold commented
I confirm I want to be added as a maintainer.

2023-01-20 19:05 UTC, dopplershift commented
Please don't modify recipes outside your own. Only add your recipe.

2023-01-20 19:11 UTC, michaelweinold commented
> Please don't modify recipes outside your own. Only add your recipe.

Whoops, sorry. I thought I had eroneously pulled these files into my branch with https://github.com/conda-forge/staged-recipes/pull/21750/commits/4583ba867280adee7f5f1e823f823b684624c14a. Commit has been reverted.

2023-01-20 21:03 UTC, dopplershift requested changes
Thanks for cleaning up the commit. Just a minor tweak to the metadata and this looks good.

I also need confirmation from @cbenz that they are willing to be listed as a maintainer for this recipe.

2023-01-20 21:03 UTC, dopplershift commented on recipes/dbnomics/meta.yaml
> +  license: AGPL-3.0-only
Looks like it's actually ["or later"](https://git.nomics.world/dbnomics/dbnomics-python-client/-/blob/master/dbnomics/__init__.py#L10):
```suggestion
  license: AGPL-3.0-or-later
```

2023-04-14 09:21 UTC, cbenz commented
I confirm I want to be added as a maintainer.

2023-04-14 09:23 UTC, michaelweinold commented
@dopplershift - I believe this PR is now ready for review. Thank you for your patience!

2023-04-14 16:50 UTC, dopplershift approved these changes

2023-04-14 16:50 UTC, merged