Add vodex recipe
conda-forge/staged-recipes pull request #21827
Opened 2023-01-23 14:40 UTC by goanpeca

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-04-11 20:13 UTC, goanpeca commented
We are in the process of creating conda packages for [napari plugins](https://www.napari-hub.org/) and related dependencies. Once this recipe passes all the checks, every time a new release goes into PyPI, a PR will be created automatically, with usually very minor need for changes so the process of maintaining this moving forward is small. Also the `@conda-forge/napari` team will be available to help as needed.

You can read a bit more about conda-forge at https://conda-forge.org/#contribute

---

@LemonJust do you agree with being added as maintainer?

2023-04-11 21:00 UTC, LemonJust commented
@goanpeca, I agree with being added as a maintainer! What would I need to do? :)

2023-04-12 16:44 UTC, goanpeca commented
>What would I need to do? :)

Once this recipe passes all the checks, every time a new release goes into PyPI, a PR will be created automatically, with usually very minor need for changes so the process of maintaining this moving forward is small. Also the `@conda-forge/napari` team will be available to help as needed.

You can read a bit more about conda-forge at https://conda-forge.org/#contribute :)

2023-04-12 16:58 UTC, goanpeca commented
This one is ready for review @conda-forge/staged-recipes :)

2023-04-12 17:29 UTC, dopplershift requested changes
Correct the license metadata and this is good to go.

2023-04-12 17:29 UTC, dopplershift commented on recipes/vodex/meta.yaml
> +  license: MIT
```suggestion
  license: BSD-3-Clause
```

2023-04-12 17:33 UTC, dopplershift approved these changes

2023-04-12 17:53 UTC, merged