Add sdformat-mjcf package
conda-forge/staged-recipes pull request #21855
Opened 2023-01-25 08:28 UTC by traversaro

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-01-25 20:54 UTC, traversaro commented
@conda-forge/help-python the PR is ready for review.

2023-01-25 21:43 UTC, dopplershift requested changes
Just some minor changes to make testing easier and this is good to go.

2023-01-25 21:43 UTC, dopplershift commented on recipes/sdformat-mjcf/meta.yaml
> +  imports:
If you want to keep the test files around, you can use [`source_files`](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#source-files):
```suggestion
test:
  source_files:
    - sdformat_mjcf/tests
  imports:
```

2023-01-25 21:43 UTC, dopplershift commented on recipes/sdformat-mjcf/meta.yaml
> +    - git
```suggestion
    - pytest ./gz-mujoco-test-src/sdformat_mjcf/ -v
  requires:
    - pip
    - pytest
```

2023-01-25 22:34 UTC, traversaro commented
Thanks @dopplershift !

2023-01-25 22:47 UTC, traversaro commented
@dopplershift with an additional change https://github.com/conda-forge/staged-recipes/pull/21855/commits/b8047c14e2eff5b3d925ec1665f7877b18dedd72 the `source_files` feature is working fine.

2023-01-26 00:08 UTC, dopplershift approved these changes

2023-01-26 00:08 UTC, merged