Adding my command line toolbox - cltoolbox
conda-forge/staged-recipes pull request #21868
Opened 2023-01-26 05:43 UTC by timcera

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-03-11 01:36 UTC, timcera commented
Hello @conda-forge/staged-recipes,

Been awhile and wondered if there was any problems that needed fixing?

2023-03-15 19:32 UTC, dopplershift requested changes
Just a couple minor things.

2023-03-15 19:32 UTC, dopplershift commented on recipes/cltoolbox/meta.yaml
> +    - python
```suggestion
    - python >=3.8
```

2023-03-15 19:32 UTC, dopplershift commented on recipes/cltoolbox/meta.yaml
> +  license: BSD-3-Clause
```suggestion
  license: BSD-3-Clause AND MIT
```

2023-03-16 17:58 UTC, dopplershift approved these changes

2023-03-16 17:58 UTC, merged