Add recipe for mobie python package
conda-forge/staged-recipes pull request #21875
Opened 2023-01-26 14:31 UTC by tischi

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-01-26 19:23 UTC, dopplershift requested changes
Just a couple minor tweaks and this is good to go.

2023-01-26 19:23 UTC, dopplershift commented on recipes/mobie/meta.yaml
> +  license: BSD
```suggestion
  license: BSD-2-clause
```

2023-01-26 19:23 UTC, dopplershift commented on recipes/mobie/meta.yaml
> +  home: "https://github.com/mobie/mobie-viewer-fiji"
The package metadata was wrong, this is the correct URL:
```suggestion
  home: "https://github.com/mobie/mobie-cmd"
```

2023-01-27 09:06 UTC, tischi commented
@dopplershift 
Thank you so much ❤️ ! 
I committed your suggested changes!

2023-01-27 19:28 UTC, dopplershift approved these changes

2023-01-27 19:28 UTC, merged