Add ratarmount
conda-forge/staged-recipes pull request #21896
Opened 2023-01-29 11:43 UTC by ap--

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-01-29 15:03 UTC, ap-- commented
@mxmlnkn when you have time, please reply that you agree to be a maintainer 😃

2023-01-29 15:06 UTC, mxmlnkn commented
I agree to be a maintainer.

2023-01-29 15:09 UTC, ap-- commented
@conda-forge/help-python, ready for review!

FYI: This package is a noarch package. But the tests on OSX and Windows don't succeed because it's not possible to setup the requirements for fusepy to pass the test. fusepy takes the same approach in conda-forge, and labels itself as noarch and relying on the user to install libfuse (linux), osxfuse/maxfuse (osx) or a compatible fuse implementation for windows.

See: 
- staged-recipes PR for fusepy: https://github.com/conda-forge/staged-recipes/pull/6054
- fusepy-feedstock recipe: https://github.com/conda-forge/fusepy-feedstock/blob/main/recipe/meta.yaml

Let me know if my approach is incorrect here and I will modify the recipe accordingly.

Cheers,
Andreas 😃

2023-03-01 22:57 UTC, BastianZim requested changes
Just one small thing and this is good to go.

2023-03-01 22:57 UTC, BastianZim commented on recipes/ratarmount/meta.yaml
> +test:
Please still include the import test, even if it fails on OSX and Win. As it is noarch, it will only be built on Linux on the feedstock.

2023-03-01 23:25 UTC, ap-- commented
Thank you for the review!
I added the import check and removed the workarounds I added to make the osx tests pass.

2023-03-01 23:34 UTC, merged