Add libebm, the native library for the conda-forge package interpret
conda-forge/staged-recipes pull request #22091
Opened 2023-02-20 21:39 UTC by paulbkoch

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-02-20 21:54 UTC, paulbkoch commented
@conda-forge-admin, please rerender

2023-02-20 22:10 UTC, paulbkoch commented
@conda-forge-admin, please rerender

2023-02-20 22:21 UTC, paulbkoch commented
@conda-forge-admin, please rerender

2023-02-20 22:41 UTC, paulbkoch commented
@conda-forge-admin, please rerender

2023-02-21 00:15 UTC, paulbkoch commented
@conda-forge/help-c-cpp, ready for review!

2023-02-21 00:16 UTC, paulbkoch commented
This package is needed to implement the partitioning mentioned by @carterbox in https://github.com/conda-forge/conda-forge.github.io/issues/1900

2023-02-21 17:51 UTC, carterbox commented
What is the new package structure that this feedstock solves? i.e. Why isn't this just an output of interpret-core?

2023-02-21 19:01 UTC, paulbkoch commented
The two benefits of having a new feedstock, which you pointed out in https://github.com/conda-forge/conda-forge.github.io/issues/1900#issuecomment-1434050358 @carterbox, were:
1) Reduceing build times and avoiding redundant builds
2) being able to have a conda_build_config.yaml and conda-forge.yml that would only apply to the native build

I would like to make the interpret-core and interpret packages both noarch, and have this native package compile for all the supported native architectures that are supported by conda-forge, which makes the conda-forge.yml problematic in a single unified feedstock.

I do think however that merging the interpret-core and interpret feedstocks afterwards might make sense, but I haven't come to that bridge yet.

2023-02-21 20:00 UTC, carterbox commented
Fine, but also consider that there are 12 staged recipes ahead of you in the [c-cpp review queue](https://github.com/conda-forge/staged-recipes/pulls?q=is%3Apr+is%3Aopen+sort%3Acreated-asc+label%3Areview-requested+label%3Ac-cpp), you will get your package deployed faster if you prototype your recipes on your local machine and deploy to your exisiting feedstocks.

2023-02-21 20:34 UTC, paulbkoch commented
Understood, and thank you for your help maintaining conda-forge.

2023-03-10 22:27 UTC, carterbox requested changes

2023-03-11 00:31 UTC, paulbkoch commented on recipes/libebm/meta.yaml
> +  # url: https://github.com/interpretml/interpret/archive/v{{ version }}.tar.gz
The native library could be used separately and could also be updated independently from the python package in the future.  We haven't really advertised this yet though or supported it.  I don't mind matching the interpret version numbers for now though, so I have updated it to 0.3.1 to coincide with the next release of interpret, which I will put out as soon as we resolve these partitioning questions.

2023-03-11 00:32 UTC, paulbkoch commented on recipes/libebm/meta.yaml
> +  number: 0
Hi @carterbox -- I pushed an update that included this run_exports change along with version update number change.

2023-03-11 00:55 UTC, paulbkoch commented
https://github.com/orgs/conda-forge/teams/help-c-cpp, ready for review!

2023-03-11 00:55 UTC, paulbkoch commented
@conda-forge/help-c-cpp, ready for review!

2023-03-11 01:36 UTC, carterbox commented on recipes/libebm/meta.yaml
> +    otool -L "$PREFIX/lib/libebm.dylib"  # [osx]
```suggestion
  commands:
    - if not exist %LIBRARY_BIN%\libebm.dll exit 1  # [win]
    - test -f $PREFIX/lib/libebm.so       # [linux]
    - test -f $PREFIX/lib/libebm.dylib     # [osx]
```

2023-03-11 01:50 UTC, merged