added initial recipe:
conda-forge/staged-recipes pull request #22114
Opened 2023-02-22 15:28 UTC by k-dominik

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-02-22 15:31 UTC, k-dominik commented
@conda-forge-admin, please rerender

2023-02-23 19:03 UTC, k-dominik commented
Heya @conda-forge/help-python-c, this PR is ready to be reviewed :)

2023-03-10 22:38 UTC, carterbox requested changes

2023-03-10 22:38 UTC, carterbox commented on recipes/marching_cubes/meta.yaml
> +    - libgomp  # [linux]
```suggestion
  build:
    - cmake
    - make  # [not win]
    - {{ compiler("cxx") }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - boost-cpp
    - pybind11
```
https://conda-forge.org/docs/maintainer/knowledge_base.html#openmp

2023-03-10 22:51 UTC, carterbox approved these changes

2023-03-10 23:13 UTC, merged