Adding r-rlemon interface to C++ LEMON graph library
conda-forge/staged-recipes pull request #22147
Opened 2023-02-26 16:27 UTC by cpalmer718

This recipe for the [rlemon package from CRAN](https://cran.r-project.org/web/packages/rlemon/index.html) was generated with [conda_r_skeleton_helper](https://github.com/bgruening/conda_r_skeleton_helper).

Notes:
- This library is intended as a future dependency for the CRAN package optmatch, but following the instructions in the skeletion helper, this PR is just for the single package.
- This library is not to be confused with [r-lemon](https://anaconda.org/conda-forge/r-lemon), which is remarkably something else. The unfortunate partial name collision is inherited from CRAN and is seemingly unavoidable.
- The recipe succeeds with `build-locally.py` on a linux-64 machine.
- I'm the only listed individual maintainer, and agree to being there.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-02-28 20:43 UTC, mfansler requested changes
Everything looks good, except need the `missing_dso_whitelist` rather than changing `rpaths`.

2023-03-01 02:10 UTC, cpalmer718 commented
@mfansler Thanks so much for the comment, that was super helpful. Windows builds are pretty far from my expertise, so that would have taken me way longer to find!

2023-03-01 17:09 UTC, mfansler requested changes

2023-03-01 17:09 UTC, mfansler commented on recipes/r-rlemon/meta.yaml
> +    - m2w64-libwinpthread-git          # [win]
This shouldn't be necessary.

```suggestion
```

2023-03-01 17:09 UTC, mfansler commented on recipes/r-rlemon/meta.yaml
> +    - m2w64-libwinpthread-git      # [win]
Use the jinja variable:
```suggestion
    - {{ native }}libwinpthread-git  # [win]

2023-03-01 20:13 UTC, mfansler approved these changes
@conda-forge/help-r looks good to merge!

2023-03-03 18:55 UTC, mfansler commented
@conda-forge/help-r please review

2023-03-15 19:51 UTC, merged