Add demcmc recipe
conda-forge/staged-recipes pull request #22212
Opened 2023-03-06 12:47 UTC by dstansby

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-03-06 13:49 UTC, dstansby commented
@conda-forge/help-python this is good for review 😃

2023-03-16 19:21 UTC, dopplershift requested changes

2023-03-16 19:21 UTC, dopplershift commented on recipes/demcmc/meta.yaml
> +  home: https://demcmc.readthedocs.io
```suggestion
  home: https://demcmc.readthedocs.io
  dev_url: https://github.com/dstansby/demcmc
```

2023-03-16 19:21 UTC, dopplershift commented on recipes/demcmc/meta.yaml
> +  skip: true  # [py<38]
Since this is pure Python it'd be much better to make this noarch...
```suggestion
  noarch: python
```

2023-03-16 19:21 UTC, dopplershift commented on recipes/demcmc/meta.yaml
> +    - xarray
...and then change:
```suggestion
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - astropy
    - emcee
    - matplotlib-base
    - netcdf4
    - numpy
    - pooch
    - xarray
```

2023-05-11 22:05 UTC, merged