Add Parsita
conda-forge/staged-recipes pull request #22240
Opened 2023-03-08 11:00 UTC by drhagen

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-03-08 21:52 UTC, drhagen commented
@conda-forge/help-python, ready for review!

2023-03-11 10:56 UTC, beckermr requested changes
We'll add the `<4` constraint globally to conda-forge if we need it later.

2023-03-11 10:56 UTC, beckermr commented on recipes/parsita/meta.yaml
> +    - python >=3.7,<4.0
```suggestion
    - python >=3.7
```

2023-03-11 10:56 UTC, beckermr commented on recipes/parsita/meta.yaml
> +    - python >=3.7,<4.0
```suggestion
    - python >=3.7
```

2023-03-11 12:08 UTC, drhagen commented on recipes/parsita/meta.yaml
> +    - python >=3.7,<4.0
Sounds good to me!

2023-03-11 12:08 UTC, beckermr approved these changes

2023-03-11 12:23 UTC, merged