Adding watex- machine learning research in water exploration package
conda-forge/staged-recipes pull request #22253
Opened 2023-03-09 09:13 UTC by WEgeophysics

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-03-10 04:23 UTC, WEgeophysics commented
@conda-forge/help-python

2023-03-10 11:25 UTC, WEgeophysics commented
@conda-forge-admin, please ping team¶

2023-03-10 11:29 UTC, WEgeophysics commented
@conda-forge/staged-recipes

2023-03-11 07:26 UTC, WEgeophysics commented
@conda-forge/staged-recipes All tests are passed. ``watex``  library is ready for review. Thanks

2023-03-11 07:44 UTC, WEgeophysics commented
@conda-forge/help-python  
@conda-forge/staged-recipes 
All tests are passed. Ready for review. Thanks

2023-03-11 10:44 UTC, beckermr requested changes
One item then it is ready to go!

2023-03-11 10:44 UTC, beckermr commented on recipes/watex/meta.yaml
> +  number: 1
```suggestion
  number: 0
```

2023-03-11 11:06 UTC, beckermr approved these changes

2023-03-11 11:06 UTC, merged

2023-03-11 11:07 UTC, WEgeophysics commented
fix build number 

> One item then it is ready to go!

fix the build number and set it to 0. Thank you for your contribution.