add r-didimputation
conda-forge/staged-recipes pull request #22278
Opened 2023-03-13 15:35 UTC by okankcb

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-03-15 19:49 UTC, mfansler requested changes

2023-03-16 10:52 UTC, FernandezMathieu commented on recipes/r-didimputation/meta.yaml
> +
ajoute ici la ligne : 
`- m2w64-libwinpthread-git   # [win]`

2023-03-16 12:50 UTC, okankcb commented on recipes/r-didimputation/meta.yaml
> +    - _openmp_mutex
@mfansler I am informing you that the correction has been made as requested. The package will no longer force the choice of a BLAS implementation. As requested, BLAS, LAPACK, and OpenMP will now be under the host during compilation.

Thank you for your message and for informing me of this issue.

2023-03-16 18:41 UTC, mfansler approved these changes

2023-03-16 18:43 UTC, mfansler commented
@okankcb thanks for contributing this recipe! <3

2023-03-16 18:44 UTC, merged