Adding yourdfpy
conda-forge/staged-recipes pull request #22292
Opened 2023-03-15 16:17 UTC by ruben-arts

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-03-15 19:20 UTC, dopplershift requested changes
Minor changes to make this package noarch.

2023-03-15 19:20 UTC, dopplershift commented on recipes/yourdfpy/meta.yaml
> +  skip: true  # [py<37]
This is pure Python and could be noarch:
```suggestion
  noarch: python
```

2023-03-15 22:31 UTC, ruben-arts commented on recipes/yourdfpy/meta.yaml
> +    - six
Thanks for both tips! I was not aware of this as I just used grayskull. Is there a list of these easy checks?

2023-03-16 03:34 UTC, dopplershift approved these changes

2023-03-16 03:34 UTC, merged