Add molmass
conda-forge/staged-recipes pull request #22291
Opened 2023-03-15 13:24 UTC by n-elie

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-03-17 13:36 UTC, n-elie commented
@conda-forge/help-python Ready for review

2023-03-29 08:49 UTC, beenje requested changes

2023-03-29 08:49 UTC, beenje commented on recipes/molmass/meta.yaml
> +        - python
No need to redefine python as it's part of `molmass` run requirement

2023-03-29 09:38 UTC, n-elie commented on recipes/molmass/meta.yaml
> +        - python
@beenje Thanks for review, I applied all the suggested changes. However, removing `python` from outputs requirements leads to the following error:
```
Error: Failed to render jinja template in /home/conda/staged-recipes-copy/recipes/molmass/meta.yaml:
'PYTHON' is undefined
```
Any idea on how could I fix this?

2023-03-29 19:49 UTC, n-elie commented on recipes/molmass/meta.yaml
> +        - python
Ok I found that I need to remove python from `run` section but not from `host`

2023-03-30 10:42 UTC, merged