add recipe for jupysql
conda-forge/staged-recipes pull request #22390
Opened 2023-03-27 06:03 UTC by sterlinm

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-03-27 06:19 UTC, sterlinm commented
I am willing to be listed as a maintainer.

2023-03-27 12:55 UTC, sterlinm commented
@conda-forge/help-python, ready for review!

2023-03-27 12:56 UTC, sterlinm commented
@conda-forge-admin, please ping conda-forge/help-python for review

2023-03-27 19:08 UTC, dopplershift requested changes
Just some change to make this noarch.

2023-03-27 19:08 UTC, dopplershift commented on recipes/jupysql/meta.yaml
> +  script: {{ PYTHON }} -m pip install . -vv
This package is pure Python and can be noarch:
```suggestion
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
```

2023-03-27 19:08 UTC, dopplershift commented on recipes/jupysql/meta.yaml
> +    - importlib-metadata  # [py<38]
For noarch (better to just unconditionally depend on `importlib-metadata`):
```suggestion
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - prettytable
    - ipython >=1.0
    - sqlalchemy <2
    - sqlparse
    - ipython_genutils >=0.1.0
    - jinja2
    - ploomber-core >=0.2.4
    - importlib-metadata
```

2023-03-28 05:24 UTC, sterlinm commented
Thanks so much! Applied both changes.

2023-03-28 19:48 UTC, dopplershift approved these changes

2023-03-28 19:48 UTC, merged