add r-modeltime.resample
conda-forge/staged-recipes pull request #22567
Opened 2023-04-14 14:11 UTC by nicornk

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-04-14 14:12 UTC, nicornk commented
@conda-forge/r This is my first R contribution, please have a look :)

2023-04-14 14:39 UTC, nicornk commented
@conda-forge/staged-recipes ready for review.

2023-04-14 15:47 UTC, mfansler requested changes
Please update with the suggested requirements.

2023-04-14 15:47 UTC, mfansler commented on recipes/r-modeltime.resample/meta.yaml
> +    - r-tune
Only non-base libraries listed under "Depends" or "Imports" should be specified.

```suggestion
  host:
    - r-base
    - r-cli
    - r-crayon
    - r-dials
    - r-dplyr
    - r-forcats
    - r-ggplot2
    - r-glue
    - r-hardhat
    - r-magrittr
    - r-modeltime >=0.3.0
    - r-parsnip >=0.1.4
    - r-plotly
    - r-progressr
    - r-purrr
    - r-recipes
    - r-rlang >=0.1.2
    - r-rsample
    - r-stringr
    - r-tibble
    - r-tictoc
    - r-tidyr
    - r-timetk >=2.5.0
    - r-tune
    - r-workflows
    - r-yardstick
```

2023-04-14 15:47 UTC, mfansler commented on recipes/r-modeltime.resample/meta.yaml
> +    - r-tune
Same as above:

```suggestion
  run:
    - r-base
    - r-cli
    - r-crayon
    - r-dials
    - r-dplyr
    - r-forcats
    - r-ggplot2
    - r-glue
    - r-hardhat
    - r-magrittr
    - r-modeltime >=0.3.0
    - r-parsnip >=0.1.4
    - r-plotly
    - r-progressr
    - r-purrr
    - r-recipes
    - r-rlang >=0.1.2
    - r-rsample
    - r-stringr
    - r-tibble
    - r-tictoc
    - r-tidyr
    - r-timetk >=2.5.0
    - r-tune
    - r-workflows
    - r-yardstick
```

2023-04-14 15:47 UTC, mfansler commented on recipes/r-modeltime.resample/meta.yaml
> +    - conda-forge/r
Did you want to be a maintainer on the feedstock? If so, add your GitHub user name to the list. This is not a requirement - just wondering.

2023-04-14 15:47 UTC, mfansler commented on recipes/r-modeltime.resample/meta.yaml
Generally, we want R recipes generated by [`conda_r_skeleton_helper`](https://github.com/bgruening/conda_r_skeleton_helper), and this includes a commented-out copy of the package's DESCRIPTION file. This helps expedite review. It does not need to be added now, but in the future please use [`conda_r_skeleton_helper`](https://github.com/bgruening/conda_r_skeleton_helper) and retain the DESCRIPTION section.

2023-04-16 18:42 UTC, nicornk commented on recipes/r-modeltime.resample/meta.yaml
I was not aware of [conda_r_skeleton_helper](https://github.com/bgruening/conda_r_skeleton_helper). This is helpful ;) 
It would be helpful if this tool would be mentioned here: 
https://conda-forge.org/docs/maintainer/adding_pkgs.html

2023-04-16 18:59 UTC, nicornk commented
@mfansler Ready for another round of review.

2023-04-16 19:19 UTC, mfansler approved these changes

2023-04-16 19:19 UTC, mfansler commented on recipes/r-modeltime.resample/meta.yaml
It is: https://conda-forge.org/docs/maintainer/adding_pkgs.html#generating-the-recipe

2023-04-16 19:22 UTC, merged