Adding junifer
conda-forge/staged-recipes pull request #22569
Opened 2023-04-14 16:13 UTC by synchon

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-04-14 16:32 UTC, synchon commented
Hi, I'm not sure if I should add `noarch: generic` or `noarch: python` as I have a constraint of Python >= 3.8, @conda-forge-admin, please ping conda-forge/help-python .

2023-04-14 16:40 UTC, synchon commented
This is my confirmation for willing to be listed as the recipe maintainer.

2023-04-28 09:26 UTC, synchon commented
@conda-forge-admin, please ping team

2023-04-28 16:47 UTC, dopplershift requested changes
Just a couple minor tweaks and this is good to go.

2023-04-28 16:47 UTC, dopplershift commented on recipes/junifer/meta.yaml
> +  skip: true  # [py<38]
Better to make this noarch:
```suggestion
  noarch: python
```

2023-04-28 16:47 UTC, dopplershift commented on recipes/junifer/meta.yaml
> +    - importlib-metadata  # [py<310]
You can't use selectors in noarch recipes. In this case, it's better to just unconditionally depend on `importlib-metadata`:
```suggestion
```

2023-05-01 10:24 UTC, synchon commented
@dopplershift Thanks for the initial review! I believe I have addressed your comments. :)

2023-05-02 11:07 UTC, synchon commented
@conda-forge-admin, please ping team

2023-05-03 19:58 UTC, dopplershift approved these changes

2023-05-03 19:59 UTC, merged