Adding `arraymap` package
conda-forge/staged-recipes pull request #22573
Opened 2023-04-15 00:29 UTC by flexatone

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-04-15 00:30 UTC, flexatone commented
I am willing to be a recipe maintainer.

2023-04-15 00:31 UTC, chaburkland commented
I am willing to be a recipe maintainer

2023-04-15 01:14 UTC, flexatone commented
@conda-forge/help-python-c, ready for review!

2023-05-10 15:13 UTC, flexatone commented
https://github.com/orgs/conda-forge/teams/help-python-c, ready for review!

2023-05-25 16:33 UTC, flexatone commented
@conda-forge/help-python , ready for review!

2023-05-27 14:11 UTC, xhochy requested changes

2023-05-27 14:11 UTC, xhochy commented on recipes/arraymap/meta.yaml
> +    - numpy >=1.18.5  # [py>=39]
Don't constrain this so it uses the global pinning.
```suggestion
    - numpy
```

2023-05-27 14:11 UTC, xhochy commented on recipes/arraymap/meta.yaml
> +    - numpy >=1.18.5  # [py>=39]
```suggestion
    - {{ pin_compatible('numpy') }}
```

2023-05-27 14:11 UTC, xhochy commented on recipes/arraymap/meta.yaml
> +  skip: true  # [py<37]
Not needed anymore 
```suggestion
```

2023-05-27 17:47 UTC, flexatone commented
Thanks, @xhochy for the corrections, much appreciated!

2023-05-27 18:16 UTC, xhochy approved these changes

2023-05-27 18:16 UTC, merged