Add steinbock recipe
conda-forge/staged-recipes pull request #22597
Opened 2023-04-17 19:23 UTC by goanpeca

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-04-17 19:26 UTC, goanpeca commented
We are in the process of creating conda packages for [napari plugins](https://www.napari-hub.org/) and related dependencies. Once this recipe passes all the checks, every time a new release goes into PyPI, a PR will be created automatically, with usually very minor need for changes so the process of maintaining this moving forward is small. Also the `@conda-forge/napari` team will be available to help as needed.

You can read a bit more about conda-forge at https://conda-forge.org/#contribute

---

@jwindhager do you agree with being added as maintainers?

2023-04-20 16:12 UTC, jwindhager commented
Hi @goanpeca, steinbock is currently being maintained by @Milad4849

2023-04-24 10:50 UTC, Milad4849 commented
Hi @goanpeca, you can add me as a maintainer.

2023-05-02 20:11 UTC, goanpeca commented
Windows failure is expected. Package is noarch and some win deps are missing.
        
This one is ready for review @conda-forge/staged-recipes :)

2023-05-05 18:58 UTC, dopplershift commented
The build error on windows isn't about missing dependencies, it's complaining about `steinbock.exe`. Missing entry point?

2023-07-25 20:23 UTC, goanpeca commented
>The build error on windows isn't about missing dependencies, it's complaining about steinbock.exe. Missing entry point?

You are right @dopplershift!

My bad, fixed it!

2023-07-28 18:07 UTC, goanpeca commented
This one is ready for review @conda-forge/staged-recipes :)

2023-08-01 17:04 UTC, jaimergp commented on recipes/steinbock/meta.yaml
> +    # - steinbock
Let's have at least something to test that the entry point was created:

```suggestion
    - which steinbock
```

2023-08-01 17:07 UTC, jaimergp commented on recipes/steinbock/yum_requirements.txt
Do we need these here?

2023-08-03 21:10 UTC, goanpeca commented on recipes/steinbock/yum_requirements.txt
Testing now

2023-08-03 21:15 UTC, goanpeca commented on recipes/steinbock/yum_requirements.txt
Removed!, not needed

2023-11-23 18:04 UTC, goanpeca commented
This one is ready for review @conda-forge/staged-recipes :)

2023-12-04 19:03 UTC, xhochy requested changes

2023-12-04 19:03 UTC, xhochy commented on recipes/steinbock/meta.yaml
> +    - which steinbock
This is failing on Windows.

2023-12-08 19:53 UTC, merged