Adding xsocs Python application
conda-forge/staged-recipes pull request #22705
Opened 2023-04-27 14:49 UTC by t20100

This PR adds the [xsocs](https://gitlab.esrf.fr/kmap/xsocs) pure Python package.

This recipe provides both `xsocs-base` and `xsocs` since the later relies on `pyqt` while the former can be used without the GUI part.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-04-27 15:08 UTC, t20100 commented
I agree to be listed here as a maintainer.

2024-01-02 03:41 UTC, carterbox requested changes

2024-01-02 03:41 UTC, carterbox commented on recipes/xsocs/meta.yaml
> +        - {{ pin_subpackage('xsocs-base', max_pin="x.x.x.x") }}
```suggestion
        - {{ pin_subpackage('xsocs-base', exact=True) }}
```

2024-01-02 03:41 UTC, carterbox commented on recipes/xsocs/meta.yaml
> +    - t20100
```suggestion
extra:
  recipe-maintainers:
    - t20100
  feedstock-name: xsocs
```

2024-01-02 03:41 UTC, carterbox commented on recipes/xsocs/meta.yaml
> +  name: xsocs-base
```suggestion
  name: xsocs-split
```

2024-01-02 03:44 UTC, carterbox requested changes

2024-01-02 03:44 UTC, carterbox commented on recipes/xsocs/meta.yaml
> +        - xsocs gui --help
```suggestion
    test:
      imports:
        - xsocs
      commands:
        - xsocs gui --help
        - pip check
      requires:
        - pip
```

2024-01-02 03:59 UTC, merged

2024-01-08 09:42 UTC, t20100 commented
@carterbox thanks for the review and the improvements!