Adding DSSAT R package as r-dssat
conda-forge/staged-recipes pull request #22778
Opened 2023-05-09 15:09 UTC by palderman

@conda-forge/help-r, ready for review!

2023-05-14 01:11 UTC, mfansler requested changes
Everything looks good. I think we just need explicit comments that you're each (@palderman @gonzarizzo) okay to be listed as maintainers.

2023-05-17 21:23 UTC, palderman commented
@mfansler, yes, I'm okay with being maintainer.

Sorry for the delayed response. I didn't read carefully enough and missed the fact that I also needed to confirm.

2023-05-17 21:24 UTC, mfansler approved these changes

2023-05-17 21:25 UTC, merged

2023-05-17 21:26 UTC, mfansler commented
Thanks for contributing this recipe! <3