Add r-cmprskcoxmsm and r-twang
conda-forge/staged-recipes pull request #22788
Opened 2023-05-10 12:01 UTC by leej3

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-05-10 19:19 UTC, mfansler requested changes
Thanks for adding these recipes! I've suggested a couple minor changes, but then should be good.

2023-05-10 19:19 UTC, mfansler commented on recipes/r-cmprskcoxmsm/meta.yaml
> +    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
Expand license consistent with CRAN:

```suggestion
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
```

2023-05-10 19:19 UTC, mfansler commented on recipes/r-twang/meta.yaml
> +    - r-xtable
Makevars shows they link against BLAS/LAPACK. Even though it didn't show an issue, it won't hurt to have this in the metadata.

```suggestion
    - r-xtable
    - libblas
    - liblapack
```

2023-05-11 07:54 UTC, leej3 commented
Thanks for the review and the pointers.

2023-05-11 09:00 UTC, mfansler approved these changes

2023-05-11 09:00 UTC, merged