Add libnpp recipe
conda-forge/staged-recipes pull request #22832
Opened 2023-05-16 15:24 UTC by adibbley

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-05-22 19:47 UTC, robertmaynard requested changes
Feedback based on the meta.yaml for libcublas

2023-05-22 19:47 UTC, robertmaynard commented on recipes/libnpp/meta.yaml
> +        - arm-variant * {{ arm_variant_type }}  # [aarch64]
```suggestion
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - sysroot_{{ target_platform }} 2.17  # [linux]
```

2023-05-22 19:47 UTC, robertmaynard commented on recipes/libnpp/meta.yaml
> +        - arm-variant * {{ arm_variant_type }}  # [aarch64]
```suggestion
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - sysroot_{{ target_platform }} 2.17    # [linux]
```

2023-05-22 19:47 UTC, robertmaynard commented on recipes/libnpp/meta.yaml
> +        - arm-variant * {{ arm_variant_type }}  # [aarch64]
```suggestion
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - sysroot_{{ target_platform }} 2.17    # [linux]
```

2023-05-30 19:57 UTC, bdice approved these changes

2023-05-30 20:37 UTC, robertmaynard approved these changes

2023-06-01 07:47 UTC, merged

2023-06-01 07:48 UTC, jakirkham commented
Thanks all! 🙏

Let's ship this one. Happy to follow up on anything in the feedstock