Add napari-indices recipe
conda-forge/staged-recipes pull request #22963
Opened 2023-05-30 16:33 UTC by goanpeca

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-07-13 02:26 UTC, goanpeca commented
Haven't heard from the author in some time. The author can be added as maintainer in a subsequent PR.
        
This one is ready for review @conda-forge/staged-recipes :)

2023-08-01 17:31 UTC, jaimergp commented on recipes/napari-indices/meta.yaml
> +  home: https://github.com/Emmanulla0/napari-indices
```suggestion
  home: https://pypi.org/project/napari-indices/
```

Github repo is 404.

2023-08-01 17:38 UTC, jaimergp commented on recipes/napari-indices/meta.yaml
> +    - spectral
```suggestion
    - spectral
    - tifffile
```

2023-08-01 17:46 UTC, jaimergp commented on recipes/napari-indices/meta.yaml
> +  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-indices-{{ version }}.tar.gz
Project imports PyQt5 directly.

2023-08-01 17:47 UTC, jaimergp requested changes
Project imports PyQt5 directly. Needs to be patched.

2023-08-03 21:24 UTC, goanpeca commented
>Project imports PyQt5 directly. Needs to be patched.

Fixed 👍🏼

2023-11-23 18:03 UTC, goanpeca commented
This one is ready for review @conda-forge/staged-recipes :)

2023-12-04 18:59 UTC, xhochy approved these changes
Requested changes were addressed.

2023-12-04 19:00 UTC, merged