Add r-admm
conda-forge/staged-recipes pull request #23285
Opened 2023-07-06 10:50 UTC by TanguyGen

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-07-06 17:07 UTC, TanguyGen commented
@conda-forge/help-r

2023-07-11 04:33 UTC, mfansler requested changes
Thanks for submitting this. There are a few things to tidy up before merging.

2023-07-11 04:33 UTC, mfansler commented on recipes/r-admm/meta.yaml
> +    - $RPATH/Rblas.dll
The preferred approach to this is done in this PR: https://github.com/conda/conda-build/pull/4786

```suggestion
    - '*/R.dll'        # [win]
    - '*/Rlapack.dll'  # [win]
    - '*/Rblas.dll'    # [win]
```

2023-07-11 04:33 UTC, mfansler commented on recipes/r-admm/meta.yaml
> +    - m2w64-libwinpthread-git  # [win]
These shouldn't be here:

```suggestion
```

2023-07-11 04:33 UTC, mfansler commented on recipes/r-admm/meta.yaml
> +    - llvm-openmp  # [osx]
The only thing needed here should be:

```suggestion
    - {{ native }}libwinpthread-git  # [win]
```

The other stuff will automatically get injected as run exports.

2023-07-11 04:33 UTC, mfansler commented on recipes/r-admm/meta.yaml
> +  license: GPL-2.0-or-later
The DESCRIPTION file shows license is `GPL (>= 3)`, so:

```suggestion
  license: GPL-3.0-or-later
```

2023-07-11 04:33 UTC, mfansler commented on recipes/r-admm/meta.yaml
> +    - libopenblas
Instead, keep BLAS implementation open, and put OpenMP dependency here:

```suggestion
    - libblas
    - libgomp          # [linux]
    - llvm-openmp      # [osx]
```

2023-07-11 15:40 UTC, mfansler reviewed
Everything here looks good, but there is something strange in the logs for the Windows build (also builds the recipe `tyro`). I'm going to rerun the checks and see if it resolves itself.

2023-07-11 16:05 UTC, TanguyGen commented
Thank you really much for reviewing this package !

2023-07-11 17:09 UTC, mfansler commented
Sorry for the technical difficulties - unsure why the CI is being buggy. Anyway, this round seems to be working, so I'll merge once I confirm no a clean run. 🤞

2023-07-11 17:20 UTC, TanguyGen commented
It's kind of strange I didn't have this issue before but I looked into it earlier during the precedent built when it was still running and I saw no trace of Tyro until the very end of the build 
Thanks again !!

2023-07-11 19:45 UTC, mfansler approved these changes

2023-07-11 19:45 UTC, merged