Adding cellhint
conda-forge/staged-recipes pull request #23605
Opened 2023-08-07 22:56 UTC by ChuanXu1

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-08-08 06:54 UTC, ChuanXu1 commented
@conda-forge/help-python The recipe has passed all checks and is ready for review. Thx.

2023-08-10 05:58 UTC, beenje requested changes

2023-08-10 05:58 UTC, beenje commented on recipes/cellhint/meta.yaml
> +    - python-annoy
The upstream project has a minimum version specified: https://github.com/Teichlab/cellhint/blob/c0795803e7da5a1ce864c09c7e3a70faae9e3818/requirements.txt#L7C1-L7C6

```suggestion
    - python-annoy >=1.17.0
```

2023-08-10 07:41 UTC, ChuanXu1 commented
@beenje, changes have been made according to your suggestion, and passed checks. Please review, thx!

2023-08-10 10:49 UTC, merged