Added r-rang as a package
conda-forge/staged-recipes pull request #23638
Opened 2023-08-10 17:11 UTC by thewchan

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-08-10 17:25 UTC, thewchan commented
Needs https://github.com/conda-forge/staged-recipes/pull/23639

2023-08-11 16:58 UTC, thewchan commented
@conda-forge/staged-recipes @conda-forge/help-r there's some win build dependencies issue but this is no arch anyway. Otherwise it's ready for review!

2023-08-17 00:30 UTC, mfansler requested changes
Thanks for another one! Minor touch-up on the license; otherwise 👌

2023-08-17 00:30 UTC, mfansler commented on recipes/r-rang/meta.yaml
> +  license: GPL-3.0-only
CRAN shows `GPL (>=3)`, so...

```suggestion
  license: GPL-3.0-or-later
```

2023-08-21 14:50 UTC, merged