Add tasklib recipe
conda-forge/staged-recipes pull request #23661
Opened 2023-08-12 18:48 UTC by jfishe

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-08-12 19:01 UTC, jfishe commented
@conda-forge-admin, please ping team @conda-forge/help-python tasklib is ready for review.

2023-08-13 08:50 UTC, beenje requested changes

2023-08-13 08:50 UTC, beenje commented on recipes/tasklib/meta.yaml
> +  number: 0
This should be a `noarch: python` recipe.

2023-08-13 08:50 UTC, beenje commented on recipes/tasklib/meta.yaml
> +    - backports.zoneinfo  # [py<39]
You can't use selector with `noarch` recipe but you don't have to.
The `backports.zoneinfo` conda-forge package won't install anything for python >= 3.9. It's one of those [empty packages](https://conda-forge.org/docs/maintainer/knowledge_base.html#empty-python-packages) in that case. You can put it as run requirement for all python versions.

2023-08-13 08:50 UTC, beenje commented on recipes/tasklib/meta.yaml
> +  summary: Official Taskwarrior library for Python
You could add: `doc_url: https://tasklib.readthedocs.io/`

2023-08-14 05:12 UTC, merged