added recipe for `antspyx`
conda-forge/staged-recipes pull request #23686
Opened 2023-08-15 22:22 UTC by sarthakpati

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-08-16 06:42 UTC, traversaro commented
It seems that CMake is trying to use the Unix Makefiles generator. Can you try to add make to the build dependencies?

2023-08-16 08:14 UTC, jaimergp commented on recipes/antspyx/meta.yaml
> +    - ninja
```suggestion
    - make
```

2023-08-16 16:52 UTC, jaimergp commented on recipes/antspyx/meta.yaml
> +    - libpng
```suggestion
```

2023-10-07 20:27 UTC, carterbox requested changes
This project is revending and statically linking [libITK](https://github.com/conda-forge/libitk-feedstock). libITK is already available on our channel, and the checklist for this PR explicitly mentions static linking and revending.

Please dynamically link to our exisiting libITK package instead of building it again and statically linking.

2025-03-26 15:14 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/antspyx/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/antspyx/meta.yaml**:

 * ❌ This recipe is using a compiler, which now requires adding a build dependence on `{{ stdlib("c") }}` as well. Note that this rule applies to each output of the recipe using a compiler. For further details, please see https://github.com/conda-forge/conda-forge.github.io/issues/2102.

For **recipes/antspyx/meta.yaml**:

 * ℹ️ No valid build backend found for Python recipe for package `antspyx` using `pip`. Python recipes using `pip` need to explicitly specify a build backend in the `host` section. If your recipe has built with only `pip` in the `host` section in the past, you likely should add `setuptools` to the `host` section of your recipe.
 * ℹ️ PyPI default URL is now pypi.org, and not pypi.io. You may want to update the default source url.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/14086858439](https://github.com/conda-forge/conda-forge-webservices/actions/runs/14086858439). Examine the logs at this URL for more detail.</sub>

2025-03-26 15:30 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/antspyx/meta.yaml```) and found it was in an excellent condition.

2025-03-26 18:37 UTC, sarthakpati commented
@conda-forge/help-python-c I need some help with this recipe.

Even though I have requested `libitk` as a requirement, the recipe is still building the complete ITK package. I have no idea how to proceed.

2025-03-29 12:24 UTC, traversaro commented
> @conda-forge/help-python-c I need some help with this recipe.
> 
> Even though I have requested `libitk` as a requirement, the recipe is still building the complete ITK package. I have no idea how to proceed.

It seems that the upstream project build system unconditionally builds itk, see https://github.com/ANTsX/ANTsPy/blob/v0.5.4/CMakeLists.txt#L14-L24 . For what regards the packaging, probably the easiest option is just to add a patch that remove/uncomments those lines.

2025-03-31 01:26 UTC, sarthakpati commented
Thanks, @traversaro! I have put a patch, let's see how it goes. 🤞🏽

2025-03-31 01:28 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/antspyx/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/antspyx/meta.yaml**:

 * ❌ The build section contained an unexpected subsection name. patches is not a valid subsection name.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/14162142371](https://github.com/conda-forge/conda-forge-webservices/actions/runs/14162142371). Examine the logs at this URL for more detail.</sub>

2025-03-31 17:31 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/antspyx/meta.yaml```) and found it was in an excellent condition.

2025-04-12 00:48 UTC, carterbox requested changes

2025-04-12 00:48 UTC, carterbox commented on recipes/antspyx/meta.yaml
> +  noarch: python
Please read the documentation about noarch packages. You cannot use compilers in a noarch recipe. Therefore, this is not a noarch package.

2025-04-12 00:48 UTC, carterbox commented on recipes/antspyx/meta.yaml
> +    - libstdcxx
Please read the documentation for conda-build. the host and build sections have specific meaning which is related to cross-compilation. The build section is for tools like compilers, and the host section is for libraries to which this package links. It should only be necessary to add python dependencies to the run requirements because most conda packages have run_exports defined.

2025-04-12 00:48 UTC, carterbox commented on recipes/antspyx/meta.yaml
> +    - python {{ python_min }}
using python_min is only needed for noarch packages, which this is not.

2025-05-01 15:03 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/antspyx/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/antspyx/meta.yaml**:

 * ❌ The home item is expected in the about section.
 * ❌ Non noarch packages should have python requirement without any version constraints.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/14777634806](https://github.com/conda-forge/conda-forge-webservices/actions/runs/14777634806). Examine the logs at this URL for more detail.</sub>

2025-05-02 00:40 UTC, sarthakpati commented
I am getting a memory error with Windows [[ref](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/1237676/logs/24)]:

```sh
[SNIP!]
2025-05-02T00:00:45.2884015Z Not enough memory resources are available to process this command.
2025-05-02T00:00:45.2884911Z   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\include\vector(1541,1): fatal error C1060: compiler is out of heap space (compiling source file D:\bld\antspyx_1746143175403\work\src\main.cpp) [D:\bld\antspyx_1746143175403\work\build\cp312-cp312-win_amd64\lib.vcxproj]
[SNIP!]
```

Recipe is functional for Linux and OSX, though.

2025-05-05 20:04 UTC, sarthakpati commented
@conda-forge/help-python-c this recipe is ready for review

2025-05-12 13:07 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/antspyx/meta.yaml```) and found it was in an excellent condition.

2025-05-12 18:13 UTC, sarthakpati commented
Hi @xhochy, thank you for your review. I have accepted all your suggestions and the recipe is ready to be reviewed again.

Windows builds are still failing with the same error as before [[ref](https://github.com/conda-forge/staged-recipes/pull/23686#issuecomment-2846068715)], though:

```sh
[SNIP!]
2025-05-02T00:00:45.2884015Z Not enough memory resources are available to process this command.
2025-05-02T00:00:45.2884911Z   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\include\vector(1541,1): fatal error C1060: compiler is out of heap space (compiling source file D:\bld\antspyx_1746143175403\work\src\main.cpp) [D:\bld\antspyx_1746143175403\work\build\cp312-cp312-win_amd64\lib.vcxproj]
[SNIP!]
```

2025-05-15 17:05 UTC, xhochy commented
Please skip windows here. You can only correct that on the feedstock AFAIK.

2025-05-15 18:07 UTC, sarthakpati commented
> Please skip windows here. You can only correct that on the feedstock AFAIK.

I am assuming that since this is a `noarch` recipe, I cannot add a `skip` parameter for the `build`. I guess we just ignore windows builds for now?

2025-05-15 18:09 UTC, xhochy commented
This isn't a noarch recipe. It has compiled code, thus it cannot be one.

2025-05-15 18:30 UTC, sarthakpati commented
Sorry, you are right! I was looking at another recipe and got confused. Updated with `skip`.

2025-05-20 14:48 UTC, sarthakpati commented
@xhochy this recipe is ready for review and merge

2025-06-13 13:03 UTC, xhochy approved these changes

2025-06-13 13:03 UTC, merged