Add aioresponses
conda-forge/staged-recipes pull request #23776
Opened 2023-08-23 20:35 UTC by MementoRC

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-08-23 21:46 UTC, MementoRC commented
@conda-forge/help-python, Hello, ready for review

2023-11-15 01:24 UTC, BastianZim requested changes

2023-11-15 01:24 UTC, BastianZim commented on recipes/aioresponses/fix-version.patch
What is the reason that this is not included upstream?

2023-11-15 17:33 UTC, MementoRC commented on recipes/aioresponses/fix-version.patch
I have removed it, it's not necessary

2023-11-15 17:39 UTC, MementoRC commented
Oh, looks like someone else got the package on conda-forge. SHould I simply close this?

2023-11-15 19:50 UTC, BastianZim commented
Yes, you can just close it, if it's the same.

2023-11-15 20:51 UTC, MementoRC commented
This is very puzzling, I created and worked on these proposals since Aug 23rd, yet the maintainer of the other one submitted his 2 days ago!
Just another ant being squashed?  I have to say my enthusiasm for contributing to conda-forge has been beaten into submission and scalded self-esteem

2023-11-15 20:51 UTC, closed without merging

2023-11-20 22:03 UTC, BastianZim commented
Sorry to hear that. As we are all volunteers and reviewing in our spare time, it can be that some recipes are missed. If you think that your recipe is not being noticed, please feel free to ping the review group again or post a comment in our chat room and someone should come by.