Add bech32 package
conda-forge/staged-recipes pull request #23778
Opened 2023-08-23 22:53 UTC by MementoRC

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-08-23 23:45 UTC, MementoRC commented
@conda-forge/help-python, Hello, ready for review

2023-11-15 01:22 UTC, BastianZim requested changes

2023-11-15 01:22 UTC, BastianZim commented on recipes/bech32/tests.py
We generally don't like to include these files as they need to be continuously updated. It would probably be better if you switch to GitHub as a source and then just include it from there.

2023-11-15 19:49 UTC, BastianZim commented on recipes/bech32/tests.py
Ahh I see. No, then PyPi and manually including it is fine.

2023-11-27 17:10 UTC, MementoRC commented
@conda-forge/help-python ready for review

2023-11-27 17:11 UTC, MementoRC commented on recipes/bech32/tests.py
Done

2024-01-17 21:08 UTC, MementoRC commented
@BastianZim Are thre requested changes that I missed?

2024-01-17 22:07 UTC, merged

2024-01-17 22:08 UTC, BastianZim commented
Sorry, missed it. If that's the case, you can ping me directly as well.

2024-01-17 23:03 UTC, MementoRC commented
@BastianZim Cool, thank you.
I have a few packages that need older versions of a package (github or pypi), how to go about adding them to conda-forge?
Thank you

2024-01-17 23:04 UTC, BastianZim commented
Are there newer version of the package already in conda-forge? Otherwise, just open a PR here and add a comment why you are adding an older version.

2024-01-17 23:16 UTC, MementoRC commented
I want to create a recipe for an active repo but add older version of the
package as well, in case I stumble upon dependencies that are strictly
asking for these versions
Thank you

On Wed, Jan 17, 2024 at 5:05 PM Bastian Zimmermann ***@***.***>
wrote:

> Are there newer version of the package already in conda-forge? Otherwise,
> just open a PR here and add a comment why you are adding an older version.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/conda-forge/staged-recipes/pull/23778#issuecomment-1897328724>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWGZEZY76LE65LJDWVR2PD3YPBKKBAVCNFSM6AAAAAA34EXCRCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJXGMZDQNZSGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-17 23:18 UTC, BastianZim commented
Is this just in case or do you have a concrete example?

2024-01-17 23:29 UTC, MementoRC commented
I have a concrete example: bip-utils (not submitted yet) requires `cbor2 ~=5.1, but current version is 5.6.0 and 5.1 is only available on pypi

2024-01-17 23:34 UTC, BastianZim commented
Ahh, in that case: please open an issue in the feedstock and can you also provide this link: https://conda-forge.org/docs/maintainer/updating_pkgs.html#maintaining-several-versions

2024-01-17 23:59 UTC, MementoRC commented
Great. I will submit the recipe. I will need to submit it separately then so that it can be merged, then submit the recipe that depends upon it once I added the version

2024-01-18 16:25 UTC, MementoRC commented
@BastianZim I seem to have misunderstood your instructions. I merged the v18.0.0 branch, but it fails (for known issues, but i forgot how much I had struggled with the v18.0.0). So now the coincurve-feedstock is failing, do you mind taking a look, ideally, I'd need to un-merge the branch, but I rather not do anything else that may cause more issues. Thank you

2024-01-18 16:33 UTC, BastianZim commented
Just responded in the PR.