Adding mpcmd
conda-forge/staged-recipes pull request #23811
Opened 2023-08-27 14:45 UTC by dotmet

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-08-30 15:55 UTC, synapticarbors requested changes

2023-08-30 15:55 UTC, synapticarbors commented on recipes/mpcmd/meta.yaml
> +  # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
Please remove comments that are not specific to this package

2023-08-30 15:55 UTC, synapticarbors commented on recipes/mpcmd/meta.yaml
> +build:
It looks like this package should be `noarch: python`:

https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python

2023-08-30 15:55 UTC, synapticarbors commented on recipes/mpcmd/meta.yaml
> +  url: https://files.pythonhosted.org/packages/bf/8c/07e22c42458f6dac37409979358b366cdf0c242bf648183cbdab6fba8eb5/mpcmd-0.0.5.tar.gz
Please use the canonical url shown in the example `meta.yaml`:
https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L16

2023-08-30 15:55 UTC, synapticarbors commented on recipes/mpcmd/meta.yaml
> +test:
We encourage adding a `pip check` when possible:

https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L61-L64

2023-08-30 16:40 UTC, dotmet commented
@synapticarbors Sorry, i am not familiar with the procedure, there are some incorrect operations. I will rewrite some parts of this package using cpp, so I decide to use conda-forge channel. I will check the reviews and update the yaml file tomorrow. Thanks :)

2023-09-07 23:15 UTC, dotmet commented
@conda-forge/help-python ready for review

2023-09-24 12:20 UTC, closed without merging