Update receipes
conda-forge/staged-recipes pull request #24049
Opened 2023-09-21 14:29 UTC by jaydu1

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-09-21 18:42 UTC, jaydu1 commented
@conda-forge/help-python, ready for review!

2023-09-27 17:17 UTC, synapticarbors requested changes
In addition to my comments, you shouldn't delete or modify other files that are in `staged-recipes` related to other packages.

2023-09-27 17:17 UTC, synapticarbors commented on recipes/pyvitae/meta.yaml
> +# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe
As it says here, please remove comments not specific to the package you are submitting here.

2023-09-27 17:17 UTC, synapticarbors commented on recipes/pyvitae/meta.yaml
> +  build:
It doesn't look like this package compiles C-extensions. If so, then you can drop the `build` section under `requirements`.

2023-09-27 17:17 UTC, synapticarbors commented on recipes/pyvitae/meta.yaml
> +build:
I think this package can be `noarch: python`. See:
https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python

If that's the case, remove the `skip: True` line and change the `python` requirements to `- python >=3.7`.

2023-09-27 17:17 UTC, synapticarbors commented on recipes/pyvitae/meta.yaml
> +  host:
Typically under `host` you only need `python` and `pip`. The rest are only needed to run your package and not required in the build stage.

2023-09-27 17:17 UTC, synapticarbors commented on recipes/pyvitae/meta.yaml
> +  # requires:
I would include the `pip check` test.

2023-09-28 12:29 UTC, synapticarbors commented
It looks like conda-forge never had tensorflow==2.3. You can see all of the available versions here:
https://anaconda.org/conda-forge/tensorflow/files

or using `mamba repoquery search tensorflow`

2023-09-28 17:28 UTC, jaydu1 commented
Hi @synapticarbors , thanks for reviewing the code. I have tried to resolve most of the problems, but still cannot make it work  on the win-64 platform. 

The Azure log file says there is no `tensorflow >= 2.4` available. And I found `tensorflow>=2` is only available in the conda main channel:
`conda search  "tensorflow>=2.4" --subdir win-64 -c main`

Do you know any way to include the conda main cannel to the recipe? Thanks in advance.

> It looks like conda-forge never had tensorflow==2.3. You can see all of the available versions here: https://anaconda.org/conda-forge/tensorflow/files
> 
> or using `mamba repoquery search tensorflow`

2023-09-28 17:33 UTC, synapticarbors commented
It looks like conda-forge doesn't build Tensorflow for windows. There are several complicated packages that we've punted on the Windows build for one reason or another (the same is true for Pytorch). We can ignore that here since this is noarch python. Users will still have the option to get tensorflow through another channel. 

If you could just fix the issue where you touched or deleted other files outside of the package you were working on, I'd be happy to merge this.

2023-09-28 17:39 UTC, jaydu1 commented
Thanks for the prompt reply! I think I have fixed the issues you mentioned above, except I didn't include the `pip check` test, because it does not correctly identify some conda dependencies.

2023-10-03 13:40 UTC, jaydu1 commented
Hi @synapticarbors , is there any other change I need to make? Otherwise could u help to merge it? Many thanks!

2023-10-03 13:51 UTC, synapticarbors commented
There's just the issue of backing out changes to recipes not related to your specific package. After you do that, I'm happy to merge this PR.

2023-10-03 14:33 UTC, closed without merging