Add Checkov
conda-forge/staged-recipes pull request #24278
Opened 2023-10-16 13:02 UTC by nick-harmening

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-10-16 13:03 UTC, borchero commented
Fine to be listed as maintainer ✅

2023-10-18 07:12 UTC, xhochy requested changes

2023-10-18 07:12 UTC, xhochy commented on recipes/checkov/meta.yaml
> +  skip: true  # [py<38]
```suggestion
```

2023-10-18 07:12 UTC, xhochy commented on recipes/checkov/meta.yaml
> +    - pyston ==2.3.5  # [py<311 and ( linux or darwin )]
```suggestion
    - pyston-autoload ==2.3.5  # [py<311 and unix]
    - pyston ==2.3.5  # [py<311 and unix]
```

2023-10-18 15:41 UTC, xhochy commented
Depends on https://github.com/conda-forge/pyston_lite-feedstock/pull/4

2023-10-25 08:56 UTC, xhochy requested changes
We prefer to use solely `x86_64`.

2023-10-25 08:56 UTC, xhochy commented on recipes/checkov/meta.yaml
> +  skip: true  # [py<39 or (py<311 and osx and x86)]
```suggestion
  skip: true  # [py<39 or (py<311 and osx and x86_64)]
```

2023-10-25 08:56 UTC, xhochy commented on recipes/checkov/meta.yaml
> +    - pyston_lite_autoload ==2.3.5  # [py<311 and unix and x86]
```suggestion
    - pyston_lite_autoload ==2.3.5  # [py<311 and unix and x86_64]
```

2023-10-25 08:56 UTC, xhochy commented on recipes/checkov/meta.yaml
> +    - pyston_lite ==2.3.5  # [py<311 and unix and x86]
```suggestion
    - pyston_lite ==2.3.5  # [py<311 and unix and x86_64]
```

2023-10-29 20:13 UTC, xhochy approved these changes

2023-10-29 20:13 UTC, merged