Adding SSp_Detector recipe
conda-forge/staged-recipes pull request #24304
Opened 2023-10-18 15:49 UTC by sjg2203

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from an official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-10-18 16:08 UTC, sjg2203 commented
@conda-forge/help-python Ready for review!

2023-10-19 07:40 UTC, sjg2203 commented
@conda-forge/help-python Ready for review!

2023-10-24 13:26 UTC, sjg2203 commented
@conda-forge-admin (@ocefpaf) & @conda-forge/help-python Ready for review!

2023-10-24 13:58 UTC, ocefpaf requested changes
Please don't remove recipes. You should rebase or start from a fresh clone to avoid that. Also, when possible please use `grayskull pypi --strict-conda-forge SSp_Detector` to create the recipe. It produces a recipe that is almost merge-ready and much easier to review.

2023-10-24 13:58 UTC, ocefpaf commented on recipes/SSp_Detector/meta.yaml
> +  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
```suggestion
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
```

2023-10-24 13:58 UTC, ocefpaf commented on recipes/SSp_Detector/meta.yaml
> +    - scipy
```suggestion
    - scipy >=1.11
```

2023-10-25 13:02 UTC, sjg2203 commented
Hi @ocefpaf, should be ready for review now!
Thanks for the help

2023-10-26 10:36 UTC, sjg2203 commented
@conda-forge-admin (@ocefpaf) & @conda-forge/help-python @conda-forge/staged-recipes Ready for review!

2023-10-26 19:42 UTC, ocefpaf commented on recipes/SSp_Detector/meta.yaml
> +    - SSp_Detector
Why not the pip check?

2023-10-26 19:43 UTC, ocefpaf commented
Please do note remove an existing recipe. Rebase to fix that or send a fresh PR if that is easier for you.

2023-10-27 10:30 UTC, closed without merging