Add roocs-grids
conda-forge/staged-recipes pull request #24319
Opened 2023-10-20 10:04 UTC by sol1105

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-10-20 10:08 UTC, cehbrecht commented
@sol1105 I confirm to be a maintainer of the roocs-grid package.

2023-10-20 14:14 UTC, Zeitsperre commented
@sol1105 Sure! I don't mind helping out here!

2023-10-20 14:28 UTC, sol1105 commented
@Zeitsperre @cehbrecht Great, thank you :+1:

2023-10-21 20:17 UTC, xhochy requested changes

2023-10-21 20:17 UTC, xhochy commented on recipes/roocs-grids/meta.yaml
> +test:
Please also add this to ensure no new requirements will be missed in the future.
```suggestion
test:
  requires:
    - pip
  commands:
    - pip check 
```

2023-10-23 09:52 UTC, sol1105 commented
@xhochy: Thank you for your feedback. Maybe you can help me as well with the following issue: Windows fails to extract the `tar.gz` - file, which causes the checks to fail:
```
Source cache directory is: C:\bld\src_cache
Downloading source to cache: roocs_grids-0.1.1_30f48caa04.tar.gz
Downloading https://pypi.io/packages/source/r/roocs-grids/roocs_grids-0.1.1.tar.gz
Success
Extracting download
Traceback (most recent call last):
  File "C:\Miniforge\lib\shutil.py", line 816, in move
    os.rename(src, real_dst)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\bld\\tmpl9uye9no\\roocs_grids-0.1.1\\aux' -> 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmpyip3kvr0\\aux'
```

I tried to disable Windows build by adding:
```
build:
    ...
    skip: True  # [win]
```
Then the windows check is successful, but the linting check fails.

2023-10-23 15:18 UTC, cehbrecht commented
@sol1105 can we do it like in the `cdo` package?

2023-10-24 04:20 UTC, sol1105 commented
@cehbrecht When requiring a minimum python version (`python>=3.8`),  `noarch: python` is required.
Yesterday I tried the cdo case:
```
build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: True # [win]
```
and whatever fix googling suggested for the minimum python version:
```
build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: True  # [win]
  skip: True  # [py<38]
```
but both failed the checks.

@Zeitsperre Ok, will do :+1:

2023-10-25 20:28 UTC, Zeitsperre commented on recipes/roocs-grids/meta.yaml
>      - pytest-runner
I think we can drop `pytest-runner`. I think it's old/obsolete.

2023-10-26 04:43 UTC, sol1105 commented
@Zeitsperre Yes, that worked out, thanks.

@xhochy It would be ready for another review

2023-10-27 20:01 UTC, xhochy requested changes

2023-10-27 20:01 UTC, xhochy commented on recipes/roocs-grids/meta.yaml
> +    - python
This should be the same as in run.
```suggestion
    - python >=3.8
```

2023-10-30 07:12 UTC, sol1105 commented
@xhochy Okay, thank you, I made the requested change

2023-11-13 10:22 UTC, sol1105 commented
@conda-forge/help-python, ready for review

Thanks

2023-11-18 21:11 UTC, xhochy approved these changes

2023-11-18 21:11 UTC, merged