Adding `simdutf`
conda-forge/staged-recipes pull request #24320
Opened 2023-10-20 13:23 UTC by SimeonStoykovQC

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-11-13 13:45 UTC, xhochy requested changes

2023-11-13 13:45 UTC, xhochy commented on recipes/simdutf/LICENSE.txt
> +Copyright 2021 The simdutf authors
The license is already part of the tarball and should not be duplicated here.

2023-11-13 13:45 UTC, xhochy commented on recipes/simdutf/meta.yaml
> +  number: 0
As you don't have a build script for windows, you need to skip it here.
```suggestion
  number: 0
  skip: true  # [win]
```

2023-11-13 13:45 UTC, xhochy commented on recipes/simdutf/meta.yaml
> +  license_file: LICENSE.txt
```suggestion
  license_file: LICENSE-MIT
```

2023-11-13 13:45 UTC, xhochy commented on recipes/simdutf/meta.yaml
> +    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
Please remove these comments.
```suggestion
```

2023-11-13 13:45 UTC, xhochy commented on recipes/simdutf/meta.yaml
> +
Shared libraries should come with a run_exports.
```suggestion
  run_exports:
    - {{ pin_subpackage('simdutf', max_pin='x') }}
```

2023-11-13 15:39 UTC, xhochy requested changes

2023-11-13 15:39 UTC, xhochy commented on recipes/simdutf/bld.bat
> +cmake %CMAKE_ARGS% -GNinja -DSIMDUTF_TOOLS=OFF -DBUILD_SHARED_LIBS=ON ..
Please add a check to line 3 and 4 that the commands succeeded. CMD doesn't do this by default.

2023-11-13 15:39 UTC, xhochy commented on recipes/simdutf/meta.yaml
> +requirements:
```suggestion

requirements:
```

2023-11-13 15:39 UTC, xhochy commented on recipes/simdutf/meta.yaml
> +    - if not exist "%LIBRARY_LIB%\simdutf.lib" exit 1  # [win]
```suggestion
    - if not exist "%LIBRARY_BIN%\simdutf.dll" exit 1  # [win]
    - if not exist "%LIBRARY_LIB%\simdutf.lib" exit 1  # [win]
```

2023-11-13 17:52 UTC, SimeonStoykovQC commented on recipes/simdutf/meta.yaml
> +requirements:
Can this be added to the linter

2023-11-14 09:37 UTC, xhochy approved these changes

2023-11-14 09:37 UTC, merged