Adding libfilepattern recipe
conda-forge/staged-recipes pull request #24433
Opened 2023-11-06 21:08 UTC by sameeul

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-11-06 21:19 UTC, sameeul commented
@JesseMckinzie: Can you please acknowledge here that you will be  a recipe maintainer for this package?

2023-11-06 21:23 UTC, JesseMckinzie commented
I will be a recipe maintainer for this package

2023-11-06 21:45 UTC, sameeul commented
https://github.com/orgs/conda-forge/teams/help-c-cpp : Ready for review.

2023-11-09 15:15 UTC, xhochy requested changes

2023-11-09 15:15 UTC, xhochy commented on recipes/libfilepattern/build.sh
> +cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=${PREFIX} -DCMAKE_INSTALL_PREFIX=${PREFIX} -Dfilepattern_SHARED_LIB=ON  ../src/filepattern/cpp/
```suggestion
cmake $CMAKE_ARGS -DCMAKE_BUILD_TYPE=Release -Dfilepattern_SHARED_LIB=ON  ../src/filepattern/cpp/
```

2023-11-09 15:15 UTC, xhochy commented on recipes/libfilepattern/bld.bat
> +cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_FLAGS_RELEASE="/MT /O2 /D NDEBUG" -DCMAKE_PREFIX_PATH=%LIBRARY_PREFIX% -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ../src/filepattern/cpp/
```suggestion
cmake %CMAKE_ARGS% -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_FLAGS_RELEASE="/MT /O2 /D NDEBUG" ../src/filepattern/cpp/
```

2023-11-09 15:15 UTC, xhochy commented on recipes/libfilepattern/build.sh
> +cmake --build . --target install --parallel
```suggestion
cmake --build . --target install --parallel -j${CPU_COUNT}
```

2023-11-09 15:59 UTC, sameeul commented
Thanks for looking at it. I updated the code as suggested.

2023-11-13 19:25 UTC, sameeul commented
@xhochy: I have updated the code as suggested. Is it good to merge now?

2023-11-18 21:07 UTC, xhochy approved these changes

2023-11-18 21:07 UTC, merged