Add r-pim using the conda-forge-r-helper script
conda-forge/staged-recipes pull request #24471
Opened 2023-11-10 20:26 UTC by pettyalex

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-11-14 05:20 UTC, pettyalex commented
@conda-forge/help-r I believe this is ready to go

2023-11-21 18:21 UTC, mfansler requested changes
Thanks for submitting this! Just a minor touchup on the license and should be good.

2023-11-21 18:21 UTC, mfansler commented on recipes/r-pim/meta.yaml
> +  license: GPL-2.0-only
DESCRIPTION shows `GPL (>= 2)`, so...

```suggestion
  license: GPL-2.0-or-later
```

2023-11-21 18:21 UTC, mfansler commented on recipes/r-pim/meta.yaml
> +    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
With `GPL (>= 2)` I usually include both, which is consistent with how CRAN website displays it.

```suggestion
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
```

2023-11-21 20:39 UTC, mfansler approved these changes

2023-11-21 20:39 UTC, merged