add `uuid-utils`
conda-forge/staged-recipes pull request #24476
Opened 2023-11-11 19:27 UTC by moritzwilksch

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-11-12 07:43 UTC, xhochy requested changes
If this is rust, it should be a compiled package

2023-11-12 07:43 UTC, xhochy commented on recipes/uuid-utils/meta.yaml
> +  noarch: python
```suggestion
```

2023-11-12 07:43 UTC, xhochy commented on recipes/uuid-utils/meta.yaml
> +requirements:
```suggestion
requirements:
  build:
    - {{ compiler('rust') }}
```

2023-11-12 10:19 UTC, moritzwilksch commented
Thanks, I still need to add the `build.sh` and `build.bat` then and collect the licenses of the rust dependencies using `cargo-bundle-licenses` right?

2023-11-14 20:41 UTC, xhochy requested changes

2023-11-14 20:41 UTC, xhochy commented on recipes/uuid-utils/bld.bat
> +set RUSTFLAGS="--cfg uuid_unstable"
Quoting is different on Windows
```suggestion
set "RUSTFLAGS=--cfg uuid_unstable"
```

2023-11-15 16:32 UTC, moritzwilksch commented
@conda-forge/help-python, ready for review!

2023-11-17 15:04 UTC, xhochy requested changes
Please remove debug code.

2023-11-17 15:04 UTC, xhochy commented on recipes/uuid-utils/build.sh
> +ls -la
```suggestion
```

2023-11-17 15:05 UTC, xhochy approved these changes

2023-11-17 18:48 UTC, merged