R packages crew and crew.cluster, along with prerequisites.  From conda_r_skeleton_helper
conda-forge/staged-recipes pull request #24498
Opened 2023-11-14 21:20 UTC by brendanf

Checklist
- [*] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [*] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [*] Source is from official source.
- [*] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [*] Build number is 0.
- [*] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [*] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-12-18 14:35 UTC, brendanf commented
@conda-forge/help-r
The Windows error is
[`ERROR (r-getip,lib/R/library/getip/libs/x64/getip.dll): $RPATH/R.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.
.. is this binary repackaging?`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=843842&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=7c0f8eae-6d6f-51bf-636f-73a1a7fb1bc4&l=1039).

I'm far from an expert on getting things to build in Windows.  I would expect that `R.dll` should be packaged by `r-base`, but it somehow isn't being found in this check (although the actual `R CMD install` seems to have worked fine). I can't see that `getip` is doing anything unconventional with library paths.  Anyone have any advice?

2024-02-03 04:12 UTC, mfansler requested changes
LGTM - just a minor touch up, and we need to wait for `r-getip` and `r-nanonext` to get generated.

2024-02-03 04:12 UTC, mfansler commented on recipes/r-mirai/meta.yaml
> +  home: https://shikokuchuo.net/mirai/, https://github.com/shikokuchuo/mirai/
split urls:

```suggestion
  home: https://shikokuchuo.net/mirai/
  dev_url: https://github.com/shikokuchuo/mirai/
```

2024-02-03 04:12 UTC, mfansler commented on recipes/r-crew/meta.yaml
> +  home: https://wlandau.github.io/crew/, https://github.com/wlandau/crew
split urls

```suggestion
  home: https://wlandau.github.io/crew/
  dev_url: https://github.com/wlandau/crew
```

2024-02-03 04:12 UTC, mfansler commented on recipes/r-crew.cluster/meta.yaml
> +  home: https://wlandau.github.io/crew.cluster/, https://github.com/wlandau/crew.cluster
split urls

```suggestion
  home: https://wlandau.github.io/crew.cluster/
  dev_url: https://github.com/wlandau/crew.cluster
```

2024-02-18 08:57 UTC, brendanf commented
@conda-forge-admin please rerender

2024-02-18 09:01 UTC, brendanf commented
@conda-forge-admin, please restart ci

2024-02-18 10:07 UTC, brendanf commented
@conda-forge/help-r Now that the prerequisites are available, this builds on Linux and OSX.  Windows is failing due to #25319

2024-02-23 17:06 UTC, mfansler approved these changes

2024-02-23 17:06 UTC, merged

2024-02-23 17:12 UTC, mfansler commented
Thanks for adding these! ❤️ 

Note that since these have interdependencies (`crew.cluster -> crew -> mirai`), the CI on the feedstocks will likely fail in the first round and require manual restarts. I'll try to keep an eye out, but you can get view the CI jobs by clicking the indicator (red "X" or green check) next to commit on the feedstock pages. Options to "Re-run" failed jobs should be there.