Adding testgres
conda-forge/staged-recipes pull request #24535
Opened 2023-11-19 22:48 UTC by demonolock

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-11-20 12:48 UTC, demonolock commented
This is ready for review @conda-forge/staged-recipes

2024-03-03 19:40 UTC, xhochy requested changes
Let's make this noarch. This will simplify maintenance a lot.

2024-03-03 19:40 UTC, xhochy commented on LICENSE.txt
Please don't delete this file.

2024-03-03 19:40 UTC, xhochy commented on recipes/testgres/meta.yaml
> +    - ipaddress  # [py<33]
```suggestion
```

2024-03-03 19:40 UTC, xhochy commented on recipes/testgres/meta.yaml
> +  number: 0
```suggestion
  number: 0
  noarch: python 
```

2024-03-03 19:40 UTC, xhochy commented on recipes/testgres/meta.yaml
> +    - python
```suggestion
    - python >=3.6
```

2024-03-03 19:40 UTC, xhochy commented on recipes/testgres/meta.yaml
> +    - python
```suggestion
    - python >=3.6
```

2024-03-03 19:40 UTC, xhochy commented on recipes/testgres/meta.yaml
> +test:
```suggestion
test:
  requires:
    - pip
  commands:
    - pip check 
```

2024-03-03 19:40 UTC, xhochy requested changes
Let's make this noarch. This will simplify maintenance a lot.

2024-03-14 20:52 UTC, demonolock commented on LICENSE.txt
removing the file reverted

2024-03-15 06:15 UTC, xhochy approved these changes

2024-03-15 06:15 UTC, merged

2024-03-16 14:02 UTC, ocefpaf commented on LICENSE
> +testgres is released under the PostgreSQL License, a liberal Open Source license, similar to the BSD or MIT licenses.
This file should be removed, no? It is in the root directory.