Add libcramjam
conda-forge/staged-recipes pull request #24637
Opened 2023-12-01 10:56 UTC by milesgranger

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-12-01 16:08 UTC, milesgranger commented
@conda-forge/staged-recipes, ready for review. 👌

2023-12-01 16:59 UTC, mfansler reviewed
*(Soft review from not a Rust expert)*

The header only seems to expose snappy. Is this still in development?

Also, I see everything is checked off, but this is statically redistributing several libraries. One should include additional licenses for these if they don't all fall under BSD3. E.g., [`zstd` distributes with MIT](https://github.com/gyscos/zstd-rs/blob/main/LICENSE).

2023-12-01 17:29 UTC, milesgranger commented
Thanks @mfansler!

> The header only seems to expose snappy. Is this still in development?

This portion is, yes. Just starting off with exposed C functions but having on conda-forge will ease later development. 

> One should include additional licenses for these if they don't all fall under BSD3.

Sorry, maybe I misunderstood, but I thought that was what the `THIRDPARTY.yml` generation was doing, no?

2023-12-01 17:32 UTC, mfansler commented
> > One should include additional licenses for these if they don't all fall under BSD3.
> 
> Sorry, maybe I misunderstood, but I thought that was what the `THIRDPARTY.yml` generation was doing, no?

You're right - all good!

2023-12-01 17:39 UTC, mfansler approved these changes
This looks good to me - verified artifacts, reasonable tests, logs all passing!

However, I'm not a regular in the Rust review pool, so I'll defer to someone more experienced to merge.

2023-12-01 17:40 UTC, milesgranger commented
Great, thanks for the initial look and feedback! :+1:

2023-12-04 19:30 UTC, xhochy requested changes

2023-12-04 19:30 UTC, xhochy commented on recipes/libcramjam/meta.yaml
> +# when copying and pasting from another recipe, but not really needed.
```suggestion
```

2023-12-04 19:30 UTC, xhochy commented on recipes/libcramjam/meta.yaml
> +    - test -e $PREFIX/lib/libcramjam.dylib                   # [osx]
```suggestion
    - test -e $PREFIX/lib/libcramjam${SHLIB_EXT}                      # [unix]
```

2023-12-05 20:40 UTC, xhochy approved these changes

2023-12-05 20:40 UTC, merged