Adding the igrafx mining sdk
conda-forge/staged-recipes pull request #24695
Opened 2023-12-06 14:51 UTC by Dourouve

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-12-13 13:20 UTC, Dourouve commented
@conda-forge/help-python All checks have passed. The recipe is ready for your review

2024-03-28 08:16 UTC, Dourouve commented
@conda-forge/help-python
It has been 3 months since this package passed all its tests and it does not yet have a review.

2024-05-10 21:30 UTC, BastianZim requested changes

2024-05-10 21:30 UTC, BastianZim commented on recipes/igrafx-mining-sdk/meta.yaml
> +    - pytest-dependency ==0.5.1
Can you please update these dependencies according to https://github.com/igrafx/mining-python-sdk/blob/7ef88c2e9f11bcfe1334d03ddcefbffb12e5a639/pyproject.toml#L12 and not make them as strict as you currently have it?

2024-06-18 15:02 UTC, Dourouve commented
@conda-forge/help-python @BastianZim  All checks have passed and the requested changes have been made. The recipe is ready for your review. Thanks.

2024-06-21 10:32 UTC, BastianZim requested changes
Just a couple more things.

2024-06-21 10:32 UTC, BastianZim commented on recipes/igrafx-mining-sdk/meta.yaml
> +    - poetry ==1.7.1
As your package is noarch, this section is not needed.

```suggestion
```

2024-06-21 10:32 UTC, BastianZim commented on recipes/igrafx-mining-sdk/meta.yaml
> +    - poetry ==1.7.1
```suggestion
    - poetry-core
```

2024-06-21 10:32 UTC, BastianZim commented on recipes/igrafx-mining-sdk/meta.yaml
> +    - SQLAlchemy >=2.0.29
Is this really needed here?

2024-06-21 10:32 UTC, BastianZim commented on recipes/igrafx-mining-sdk/meta.yaml
> +    - poetry ==1.7.1
I don't see this is the requirements.

2024-06-21 10:32 UTC, BastianZim commented on recipes/igrafx-mining-sdk/meta.yaml
> +    - pytest-dependency >=0.5.1
I don't think these are required for running. If they are just needed for the test, specifying there is sufficient.

2024-06-21 10:32 UTC, BastianZim commented on recipes/igrafx-mining-sdk/meta.yaml
> +    - pytest ./tests/test_01_column_mapping.py
```suggestion
    - pytest ./tests/test_01_column_mapping.py
    - pip check
```
To check dependencies

2024-06-21 14:25 UTC, Dourouve commented
@conda-forge/help-python @BastianZim I have modified the recipe according to your suggestions. All checks are passing. Thanks.

2024-07-31 09:08 UTC, Dourouve commented
@conda-forge/help-python @BastianZim 
It has been a while months since this package passed. Please review.

2024-11-28 08:18 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/igrafx-mining-sdk/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/igrafx-mining-sdk/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `run` section of the recipe, you should usually use `python >={{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).
 * ℹ️ PyPI default URL is now pypi.org, and not pypi.io. You may want to update the default source url.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12064985589](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12064985589). Examine the logs at this URL for more detail.</sub>

2024-11-28 19:53 UTC, xhochy commented
Please address the linter comments

2024-11-29 08:50 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/igrafx-mining-sdk/meta.yaml```) and found it was in an excellent condition.

2024-11-29 09:59 UTC, xhochy approved these changes

2024-11-29 09:59 UTC, merged