Adding r-prais
conda-forge/staged-recipes pull request #24776
Opened 2023-12-13 13:01 UTC by pn-alex

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-12-14 04:48 UTC, mfansler reviewed
Thanks for submitting this! ❤️ 

Looks good, but appears it needs `r-pcse` to be added. Feel free to add that as part of this PR - the CI will automatically build them in the correct order. Alternatively, a separate PR is also fine.

2023-12-14 04:48 UTC, mfansler commented on recipes/r-prais/meta.yaml
> +# Encoding: UTF-8
Drop superfluous comment:

```suggestion
```

2023-12-18 16:33 UTC, pn-alex commented
@conda-forge/help-r, ready for review! :)

2023-12-18 17:56 UTC, mfansler requested changes
License needs a minor adjustment; otherwise good.

2023-12-18 17:56 UTC, mfansler commented on recipes/r-pcse/meta.yaml
> +  license: GPL-3
DESCRIPTION shows `License: GPL (>= 3)`, so

```suggestion
  license: GPL-3.0-or-later
```

2023-12-19 08:20 UTC, merged