Adding sasktran2
conda-forge/staged-recipes pull request #24787
Opened 2023-12-14 13:45 UTC by dannyzed

Adds the SASKTRAN2 radiative transfer model

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2023-12-14 21:18 UTC, dannyzed commented
@conda-forge/help-python-c, ready for review!

2023-12-14 21:20 UTC, dannyzed commented
@conda-forge-admin, please ping team

2023-12-17 20:44 UTC, xhochy requested changes

2023-12-17 20:44 UTC, xhochy commented on recipes/sasktran2/meta.yaml
> +    - libtmglib =*=*netlib
The global pinning will take care of that.
```suggestion
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - libtmglib
```

2023-12-17 20:44 UTC, xhochy commented on recipes/sasktran2/meta.yaml
> +    - libgomp  # [linux]
They should already come in via run_exports 
```suggestion
```

2023-12-17 20:44 UTC, xhochy commented on recipes/sasktran2/meta.yaml
> +    - llvm-openmp  # [mac]
```suggestion
    - llvm-openmp  # [osx]
```

2023-12-17 20:44 UTC, xhochy commented on recipes/sasktran2/meta.yaml
> +    - python {{ python }}
```suggestion
    - python
```

2023-12-17 20:44 UTC, xhochy commented on recipes/sasktran2/meta.yaml
> +    - python {{ python }}
```suggestion
    - python
```

2024-01-13 20:46 UTC, xhochy approved these changes

2024-01-13 20:46 UTC, merged