add r-sensemakr and r-srvyr packages
conda-forge/staged-recipes pull request #24880
Opened 2024-01-01 22:23 UTC by vitodelgrec

Checklist
- [ x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ x] Source is from official source.
- [ x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ x] If static libraries are linked in, the license of the static library is packaged.
- [ x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ x] Build number is 0.
- [ x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-01-01 22:42 UTC, vitodelgrec commented
@conda-forge/help-r, ready for review!

2024-01-02 15:09 UTC, mfansler requested changes
Thanks for submitting these! ❤️ 

A few minor changes are suggested.

2024-01-02 15:09 UTC, mfansler commented on recipes/r-sensemakr/meta.yaml
> +  license: GPL-2.0-or-later
License reads `GPL-3`, so

```suggestion
  license: GPL-3.0-only
```

2024-01-02 15:09 UTC, mfansler commented on recipes/r-sensemakr/meta.yaml
> +    - vitodelgrec
We suggest including the Conda Forge R Team:

```suggestion
    - conda-forge/r
    - vitodelgrec
```

2024-01-02 15:09 UTC, mfansler commented on recipes/r-srvyr/meta.yaml
> +    - vitodelgrec
We suggest including the Conda Forge R Team:

```suggestion
    - conda-forge/r
    - vitodelgrec
```

2024-01-02 15:09 UTC, mfansler commented on recipes/r-srvyr/meta.yaml
> +  home: http://gdfe.co/srvyr/, https://github.com/gergness/srvyr/
Split URLs:

```suggestion
  home: http://gdfe.co/srvyr/
  dev_url: https://github.com/gergness/srvyr/
```

2024-01-02 16:09 UTC, vitodelgrec commented
> Thanks for submitting these! ❤️
> 
> A few minor changes are suggested.

Thank you for the suggested changes @mfansler , all changes done and ready for review!

2024-01-02 16:38 UTC, mfansler approved these changes

2024-01-02 16:39 UTC, merged