Add keybert v0.8.3
conda-forge/staged-recipes pull request #25151
Opened 2024-01-27 16:56 UTC by thomasmarwitz

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-01-28 09:20 UTC, ThomasMarwitzQC commented
@conda-forge-admin please rerender

2024-01-28 09:24 UTC, ThomasMarwitzQC commented
@conda-forge-admin, please rerender

2024-03-02 21:24 UTC, xhochy requested changes

2024-03-02 21:24 UTC, xhochy commented on conda-forge.yml
> +build_platform:
Please don't touch this file on staged-recipes. You can do this in thr feedstock later on.

2024-03-04 16:35 UTC, thomasmarwitz commented
@conda-forge-admin, please rerender

2024-03-04 16:38 UTC, thomasmarwitz commented
@conda-forge-admin, please rerender

2024-03-14 08:10 UTC, xhochy requested changes

2024-03-14 08:10 UTC, xhochy commented on recipes/keybert/meta.yaml
> +  skip: true  # [win]
This can be noarch. A failing CI on Windows because of a missing dependency is ok.
```suggestion
  noarch: python 
```

2024-03-14 09:40 UTC, merged