Add ast-grep recipe.
conda-forge/staged-recipes pull request #25196
Opened 2024-01-31 21:29 UTC by asford

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-01-31 21:29 UTC, asford commented on recipes/ast-grep/meta.yaml
> +  skip: true # [win]
```suggestion
  skip: true  # [win]
```

2024-02-02 04:56 UTC, asford commented on recipes/ast-grep/0001-Downgrade-tree-sitter-cpp-for-statis_assert-build-er.patch
> +Subject: [PATCH] Downgrade tree-sitter-cpp for statis_assert build error
```suggestion
Subject: [PATCH] Downgrade tree-sitter-cpp for static_assert build error
```

2024-02-02 05:15 UTC, asford commented
@conda-forge/help-rust 

This feedstock is ready for review.

I need to make a changed to a pinned dependency due to a failure in static linking.
This is because the dependency has an improper use of `static_assert` for the C standard used in compilation of the feedstock.

This builds properly outside of the build container, so I suspect there may be some config needed to pass appropriate CFLAGS need to define the C standard version used during compilation? 
I think downgrading this dependency is acceptable for the time being.

2024-02-04 08:26 UTC, xhochy requested changes
You could probably set a newer C std by appending it to the CFLAGS

2024-02-04 08:26 UTC, xhochy commented on recipes/ast-grep/meta.yaml
> +    - __osx >=10.12     # [osx and x86_64]
```suggestion
    - __osx >= {{ MACOSX_DEPLOYMENT_TARGET|default('10.12') }}     # [osx and x86_64]
```

2024-02-04 08:26 UTC, xhochy commented on recipes/ast-grep/meta.yaml
> +  # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
```suggestion
```

2024-02-04 08:26 UTC, xhochy commented on recipes/ast-grep/meta.yaml
> +  home: https://github.com/simplejson/simplejson
This needs to be updated.

2024-02-13 05:15 UTC, asford commented on recipes/ast-grep/meta.yaml
> +  home: https://github.com/simplejson/simplejson
```suggestion
  home: https://github.com/ast-grep/ast-grep
```

2024-02-13 05:39 UTC, asford commented on recipes/ast-grep/meta.yaml
> +    - __osx >= {{ MACOSX_DEPLOYMENT_TARGET|default('10.12') }}     # [osx and x86_64]
```suggestion
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET | default('10.12') }}     # [osx and x86_64]
```

2024-02-13 05:44 UTC, asford commented
> You could probably set a newer C std by appending it to the CFLAGS

Thanks, I wasn't able to fully diagnose this yet but think we can roll with a build now with the downgraded dep.

2024-02-15 21:03 UTC, xhochy approved these changes

2024-02-15 21:03 UTC, merged