add recipe for r-getip, using cran_r_skeleton_helper
conda-forge/staged-recipes pull request #25207
Opened 2024-02-02 14:29 UTC by brendanf

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-02-02 14:30 UTC, brendanf commented
Split out from #24498

2024-02-03 03:30 UTC, mfansler requested changes

2024-02-03 03:30 UTC, mfansler commented on recipes/r-getip/meta.yaml
> +  number: 0
Fix DSO issue (following [proposed fix](https://github.com/conda/conda-build/pull/4786)):

```suggestion
  missing_dso_whitelist:
    - '*/R.dll'           # [win]
  number: 0
```

2024-02-03 03:34 UTC, mfansler commented
> I would expect that `R.dll` should be packaged by `r-base`, but it somehow isn't being found in this check (although the actual `R CMD install` seems to have worked fine). I can't see that `getip` is doing anything unconventional with library paths. Anyone have any advice?

The linking analysis doesn't check the R-specific library path, so we have to whitelist it. Similarly, can come up for `libRblas.dll` and `libRlapack.dll`.

2024-02-03 08:37 UTC, brendanf commented
I notice that the linter now complains about `conda-forge/r` in the maintainer list.  Is that something that needs to be addressed?

2024-02-03 08:44 UTC, brendanf commented
@conda-forge/r Should be ready to go.  Thanks @mfansler for the fix.

2024-02-03 10:52 UTC, mfansler commented
> I notice that the linter now complains about `conda-forge/r` in the maintainer list. Is that something that needs to be addressed?

No, [that's a bug](https://github.com/conda-forge/conda-smithy/issues/1817).

2024-02-03 10:54 UTC, mfansler approved these changes

2024-02-03 10:55 UTC, merged

2024-02-03 10:55 UTC, mfansler commented
Thanks for submitting this! ❤️