adding r-sbl package
conda-forge/staged-recipes pull request #25201
Opened 2024-02-01 15:15 UTC by Troelsmou

Adding r-sbl package

Used the conda skeleton R helper to build the package

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-02-03 03:57 UTC, mfansler requested changes
Thanks for submitting this! ❤️ 

A few things to touch up, but mostly good.

2024-02-03 03:57 UTC, mfansler commented on recipes/r-sbl/GPL-3.txt
Please remove. We use the copy packaged in `r-base`, staying consistent with CRAN.

2024-02-03 03:57 UTC, mfansler commented on recipes/r-sbl/meta.yaml
> +    - 'GPL-3.txt'
Use `r-base` copy:

```suggestion
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
```

2024-02-03 03:57 UTC, mfansler commented on recipes/r-sbl/meta.yaml
> +  license: GPL-3.0-or-later
DESCRIPTION shows `GPL-3` so

```suggestion
  license: GPL-3.0-only
```

2024-02-03 03:57 UTC, mfansler commented on recipes/r-sbl/meta.yaml
> +    - "Troelsmou"
Shouldn't need quotes.

```suggestion
    - Troelsmou
```

2024-02-03 04:01 UTC, mfansler commented on recipes/r-sbl/meta.yaml
> +    - "Troelsmou"
Also, as a first time contributor, please explicitly comment that you wish to be a maintainer. That is, you have the option to not be a maintainer if you'd like.

2024-02-05 12:42 UTC, mfansler commented
Unless a package has compilation, it should be `noarch`. Please remove the skip on Windows and restore the `noarch`. It is fine if it fails the Windows run - only Linux needs to pass.

2024-02-05 13:19 UTC, Troelsmou commented
I think this should work now?

2024-02-06 12:35 UTC, dbast approved these changes

2024-02-06 12:35 UTC, merged