Add graspologic-native
conda-forge/staged-recipes pull request #25270
Opened 2024-02-06 09:46 UTC by johandahlberg

This PR adds a conda recipe for `graspologic-native` (https://github.com/microsoft/graspologic-native), the rust library companion of the python library `graspologic`. The python library will be added in a new PR once this has been merged.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-02-06 09:53 UTC, johandahlberg commented
@fbdtemme and @bdpedigo are you ok with being listed as maintainers for this package?

2024-02-06 09:56 UTC, fbdtemme commented
Of course 🙂

2024-02-06 18:31 UTC, bdpedigo commented
> @fbdtemme and @bdpedigo are you ok with being listed as maintainers for this package?

sure

2024-02-07 07:22 UTC, johandahlberg commented
@conda-forge/help-python, ready for review!

2024-02-29 13:26 UTC, johandahlberg commented
@conda-forge/help-python could some please have a look at this?

2024-03-02 19:52 UTC, xhochy requested changes

2024-03-02 19:52 UTC, xhochy commented on recipes/graspologic-native/meta.yaml
> +    - python >=3.6,<3.12                     # [build_platform != target_platform]
This should not be pinned.
```suggestion
    - python                     # [build_platform != target_platform]
```

2024-03-04 08:28 UTC, johandahlberg commented
@ambarrio please verify that you want to be a maintainer of this package.

2024-03-04 11:34 UTC, ambarrio commented
> @ambarrio please verify that you want to be a maintainer of this package.

Yes, please. Thank you!

2024-03-04 12:37 UTC, johandahlberg commented
@xhochy thank you for the review! I have included your proposed change. Anything else you would like to see, or is this ready to merge?

2024-03-07 09:29 UTC, marcelm commented
@conda-forge-admin, please ping @conda-forge/help-python this is ready to be merged 

(Not a maintainer or author, just interested in seeing this merged as well.)

2024-03-14 08:04 UTC, xhochy requested changes

2024-03-14 08:04 UTC, xhochy commented on recipes/graspologic-native/conda_build_config.yaml
> +  - 11.0 # [osx]
```suggestion
MACOSX_DEPLOYMENT_TARGET: # [osx and x86_64]
  - 11.0 # [osx and x86_64]
```

2024-03-14 08:04 UTC, xhochy commented on recipes/graspologic-native/meta.yaml
> +    - python
You also need to add a run dependency on __osx for the deployment target here, see https://conda-forge.org/news/2024/01/29/rust-175-osx-sdk/

2024-03-14 09:36 UTC, johandahlberg commented
@xhochy Thank you so much for the comments. I have addressed now. Let me know if you see any other issues.

2024-03-14 09:39 UTC, xhochy approved these changes

2024-03-14 09:39 UTC, merged