Add universaltest package
conda-forge/staged-recipes pull request #25328
Opened 2024-02-09 17:16 UTC by bourtemb

Add recipe for UniversalTest Tango-Controls device server

Checklist
- [x ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-02-09 17:29 UTC, bourtemb commented
@beenje , could you please confirm here that you are willing to be listed as maintainer of this universaltest package?
Many thanks in advance.

2024-02-10 10:29 UTC, beenje commented
I'm willing to be a maintainer!

2024-02-10 10:42 UTC, beenje commented
I see it's failing on windows with cpptango 9.3. Is is supposed to pass? We could build for 9.4 and 9.5 only otherwise.

2024-02-12 09:07 UTC, bourtemb commented
> I see it's failing on windows with cpptango 9.3. Is is supposed to pass? We could build for 9.4 and 9.5 only otherwise.

I based my recipe on the one used for the Starter. I guess it is working ok for the Starter? I just changed the DCMAKE_BUILD_TYPE to Debug instead of Release in bld.bat.

2024-02-12 09:44 UTC, bourtemb commented
When looking at the errors on Windows, it looks like we are encountering this issue when compiling on Windows with cpptango 9.3
: https://gitlab.com/tango-controls/cppTango/-/issues/680

So we should probably not try to compile UniversalTest with C++17 when using cppTango 9.3.
Do you know how we could do that?

2024-02-12 09:50 UTC, bourtemb commented
> > I see it's failing on windows with cpptango 9.3. Is is supposed to pass? We could build for 9.4 and 9.5 only otherwise.
> 
> I based my recipe on the one used for the Starter. I guess it is working ok for the Starter? I just changed the DCMAKE_BUILD_TYPE to Debug instead of Release in bld.bat.

Well, I actually based my recipe on the ones from tango-starter and tango-test.
I just noticed that tango-starter is not compiling on Windows with cppTango 9.3.
So let's do the same here.

2024-02-12 11:36 UTC, bourtemb commented
@conda-forge/help-c-cpp this PR is ready for review!

2024-02-12 14:27 UTC, xhochy requested changes
What's the reason you aren't build for `Release` here?

2024-02-12 14:27 UTC, xhochy commented on recipes/universaltest/build.sh
> +      -DCMAKE_BUILD_TYPE=Debug \
```suggestion
      -DCMAKE_BUILD_TYPE=Release \
```

2024-02-12 14:27 UTC, xhochy commented on recipes/universaltest/bld.bat
> +      -DCMAKE_BUILD_TYPE=Debug ^
```suggestion
      -DCMAKE_BUILD_TYPE=Release ^
```

2024-02-12 16:47 UTC, bourtemb commented
> What's the reason you aren't build for `Release` here?

It's because UniversalTest will be used by people playing with Tango-Controls framework features and potentially detect some bugs in the framework.  
It's then easier to debug or to report bugs when it's compiled in Debug mode.  
Debugging capabilities have been privileged over performances here.

2024-02-12 19:21 UTC, xhochy approved these changes

2024-02-12 19:21 UTC, merged