Adding DAML
conda-forge/staged-recipes pull request #25393
Opened 2024-02-13 20:12 UTC by aria-ml

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

@conda-forge/help-python

2024-02-14 22:34 UTC, aria-ml commented
@conda-forge/help-python ready for review :)

2024-03-02 20:22 UTC, xhochy requested changes

2024-03-02 20:22 UTC, xhochy commented on azure-pipelines.yml
> -  - template: ./.azure-pipelines/azure-pipelines-win.yml
Please don't touch this file.

2024-03-02 20:22 UTC, xhochy commented on recipes/daml/conda_build_config.yaml
> +python:
You should not be specifying the Python via this technique. We have a global pinning for that.

2024-03-02 20:22 UTC, xhochy commented on recipes/daml/meta.yaml
> +    - daml
```suggestion
    - daml
  requires:
    - pip
  commands:
    - pip check
```

2024-03-12 02:48 UTC, aria-ml commented
@conda-forge/help-python @xhochy ready for review, thanks for taking a look!

2024-03-14 07:47 UTC, xhochy requested changes

2024-03-14 07:47 UTC, xhochy commented on recipes/daml/meta.yaml
> +  build:
```suggestion
  host:
```

2024-03-14 07:47 UTC, xhochy commented on recipes/daml/meta.yaml
> +    - python
This needs a minimal Python version pin

2024-03-22 15:05 UTC, xhochy approved these changes

2024-03-22 15:05 UTC, merged