add `hugo`
conda-forge/staged-recipes pull request #25456
Opened 2024-02-18 20:35 UTC by moritzwilksch

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-02-18 21:54 UTC, xhochy requested changes

2024-02-18 21:54 UTC, xhochy commented on recipes/hugo/meta.yaml
> +    - {{ compiler('go') }}
```suggestion
    - {{ compiler('go-nocgo') }}
```

2024-02-18 21:54 UTC, xhochy commented on recipes/hugo/conda_build_config.yaml
> +go_compiler:
Please get rid of this file.

2024-02-18 21:54 UTC, xhochy commented on recipes/hugo/build.sh
> +export CGO_ENABLED=1
If you set this flag, you want go-cgo instead of nocgo. Change the compiler and get rid of setting this flag manually

2024-02-20 09:04 UTC, moritzwilksch commented
```
+ hugo help
/home/conda/staged-recipes/build_artifacts/hugo_1708329513420/test_tmp/run_test.sh: line 7:  6140 Segmentation fault      (core dumped) hugo help
```

2024-02-21 16:00 UTC, xhochy commented on recipes/hugo/meta.yaml
> +  number: 0
This is known to avoid segfaults.
```suggestion
  number: 0
  binary_relocation: false
```

2024-02-21 16:01 UTC, xhochy commented on recipes/hugo/meta.yaml
> +  home: https://gohugo.io/
```suggestion
  home: https://gohugo.io/
  dev_url: https://github.com/gohugoio/hugo
```

2024-02-21 16:01 UTC, xhochy commented on recipes/hugo/meta.yaml
> +    - LICENSE
```suggestion
    - LICENSE
    - library_licenses/
```

2024-02-21 20:23 UTC, xhochy commented on recipes/hugo/meta.yaml
> +    - library_licenses/
```suggestion
    - library_licenses
```

2024-02-21 20:26 UTC, xhochy approved these changes

2024-02-21 20:30 UTC, moritzwilksch commented
should I try to add a windows build as well before we merge?

2024-02-21 20:35 UTC, xhochy commented
> should I try to add a windows build as well before we merge?

Only the license files is an issue, then we can merge.

2024-02-21 20:36 UTC, xhochy commented on recipes/hugo/meta.yaml
> +    - library_licenses
Revert
```suggestion
    - library_licenses/
```

2024-02-21 20:37 UTC, xhochy commented
> should I try to add a windows build as well before we merge?

Yes, please do so. I thought I had seen a `bld.bat` but there is none. It's probably quite simply a copy of the build.sh with different slashes and `%` instead of `$`.

2024-02-22 20:07 UTC, xhochy requested changes

2024-02-22 20:07 UTC, xhochy commented on recipes/hugo/build.bat
This needs to be named bld.bat

2024-02-22 20:07 UTC, xhochy requested changes

2024-02-22 20:07 UTC, xhochy commented on recipes/hugo/build.bat
> +SETLOCAL ENABLEEXTENSIONS
```suggestion
@echo on
```

2024-02-22 20:41 UTC, xhochy commented on recipes/hugo/bld.bat
> +go build -ldflags "-X main.revision=conda-forge" -v -o %PREFIX%\bin\hugo
```suggestion
go build -ldflags "-X main.revision=conda-forge" -v -o %LIBRARY_PREFIX%\bin\hugo.exe
```

2024-02-22 21:03 UTC, xhochy approved these changes

2024-02-22 21:03 UTC, merged