add uv 0.1.7
conda-forge/staged-recipes pull request #25524
Opened 2024-02-22 14:08 UTC by bollwyvl

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-02-23 11:25 UTC, xhochy commented
I think it might be better suited to build this directly from the GitHub source. Then we might be able to avoid including Python at all.

2024-02-23 12:51 UTC, bollwyvl commented
> from the GitHub source

Sure, can try that to get down to just the three builds of the `(bin|Scripts)/uv(.exe)`.

2024-02-23 12:58 UTC, xhochy commented
Happy to help if there are any problems but for me the current setup via PyPI seems way too complex to sustainably maintain.

2024-02-23 20:46 UTC, xhochy requested changes

2024-02-23 20:46 UTC, xhochy commented on recipes/uv/bld.bat
> +move "%PREFIX%\bin\uv.exe" "%PREFIX%\Scripts\uv.exe" ^
What's the reason you put this here? Normally, we would place it in `%LIBRARY_PREFIX%\bin`

2024-02-23 21:41 UTC, bollwyvl commented
Sure, can update for that path.

On Fri, Feb 23, 2024, 14:46 Uwe L. Korn ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In recipes/uv/bld.bat
> <https://github.com/conda-forge/staged-recipes/pull/25524#discussion_r1501150278>
> :
>
> > @@ -0,0 +1,24 @@
> ***@***.*** on
> +
> +cd crates\uv
> +
> +cargo install ^
> +    --locked ^
> +    --path . ^
> +    --profile release ^
> +    --root "%PREFIX%" ^
> +    || exit 1
> +
> +md "%PREFIX%\Scripts" ^
> +    || echo "`%PREFIX%\Scripts` already exists"
> +
> +move "%PREFIX%\bin\uv.exe" "%PREFIX%\Scripts\uv.exe" ^
>
> What's the reason you put this here? Normally, we would place it in
> %LIBRARY_PREFIX%\bin
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/conda-forge/staged-recipes/pull/25524#pullrequestreview-1898905287>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAALCRAD55KELCT7454HRALYVD533AVCNFSM6AAAAABDVAR2C6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOJYHEYDKMRYG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-25 08:58 UTC, xhochy approved these changes

2024-02-25 08:58 UTC, xhochy commented on recipes/uv/bld.bat
> +    --root "%PREFIX%" ^
```suggestion
    --root "%LIBRARY_PREFIX%" ^
```

2024-02-25 08:58 UTC, xhochy commented on recipes/uv/bld.bat
> +    || exit 2
```suggestion
```

2024-02-25 09:34 UTC, merged