Add recipe for agox
conda-forge/staged-recipes pull request #25614
Opened 2024-03-02 10:47 UTC by awvwgk

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-03-02 14:06 UTC, awvwgk commented on recipes/agox/meta.yaml
> +t
```suggestion
```

2024-03-02 14:19 UTC, awvwgk commented on recipes/agox/meta.yaml
> +  number: 0
```suggestion
  number: 0
  skip: true  # [win]
```

2024-03-02 15:22 UTC, xhochy requested changes

2024-03-02 15:22 UTC, xhochy commented on recipes/agox/meta.yaml
> +    - numpy <1.24,>=1.18
Omit the pins so that the global pinning is used here.
```suggestion
    - numpy
```

2024-03-02 15:22 UTC, xhochy commented on recipes/agox/meta.yaml
> +    - numpy <1.24,>=1.18
Make it compatible with the numpy used during the build.
```suggestion
    - numpy <1.24
    - {{ pin_compatible('numpy') }}
```

2024-03-03 09:07 UTC, awvwgk commented
@conda-forge/help-python This recipe is ready for review

2024-03-03 15:43 UTC, xhochy approved these changes

2024-03-03 15:43 UTC, merged