adding shadie package
conda-forge/staged-recipes pull request #25723
Opened 2024-03-13 18:35 UTC by elissasoroj

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-03-13 18:35 UTC, elissasoroj commented
I confirm that I am willing to maintain this package

2024-03-14 09:56 UTC, elissasoroj commented
@conda-forge/help-python, ready for review!

2024-03-16 10:47 UTC, xhochy requested changes

2024-03-16 10:47 UTC, xhochy commented on recipes/shadie/meta.yaml
> +  noarch: python
If your package contains compiled code, it cannot be noarch.
```suggestion
```

2024-03-16 10:47 UTC, xhochy commented on recipes/shadie/meta.yaml
> +    # Compilers are named 'c', 'cxx' and 'fortran'.
```suggestion
```

2024-03-16 10:47 UTC, xhochy commented on recipes/shadie/meta.yaml
> +    - python >=3.10
```suggestion
    - python
```

2024-03-16 10:47 UTC, xhochy commented on recipes/shadie/meta.yaml
> +    - python >=3.6
```suggestion
    - python
```

2024-03-16 10:47 UTC, xhochy commented on recipes/shadie/meta.yaml
> +test:
```suggestion
test:
  requires:
    - pip
  commands:
    - pip check
```

2024-03-22 15:07 UTC, xhochy requested changes

2024-03-22 15:07 UTC, xhochy commented on recipes/shadie/meta.yaml
> +    - bioconda::python-newick >=1.3.0 #for msprime
It is not OK to depend on bioconda. Everything needs to be in conda-forge.

2024-03-24 19:40 UTC, closed without merging