adding Forte
conda-forge/staged-recipes pull request #25725
Opened 2024-03-13 21:54 UTC by loriab

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-04-22 21:27 UTC, fevangelista commented
I'm willing to be a maintainer of this package.

2024-04-25 22:38 UTC, loriab commented
@conda-forge/help-c-cpp, ready for review!

2024-04-26 19:47 UTC, xhochy requested changes

2024-04-26 19:47 UTC, xhochy commented on recipes/forte/meta.yaml
> +  sha256: {{ sha256 }}
Please put the sha directly here to minimize the jinja templating.

2024-04-26 19:47 UTC, xhochy commented on recipes/forte/build.sh
> +${BUILD_PREFIX}/bin/cmake ${CMAKE_ARGS} ${ARCH_ARGS} \
```suggestion
cmake ${CMAKE_ARGS} \
```

2024-04-26 19:47 UTC, xhochy commented on recipes/forte/build.sh
> +if [ "$(uname)" == "Darwin" ]; then
```suggestion
if [[ "${target_platform}" == osx-* ]]; then
```

2024-04-26 19:47 UTC, xhochy commented on recipes/forte/build.sh
> +ARCH_ARGS=""
```suggestion
```

2024-04-27 03:36 UTC, loriab commented
Thanks for the review, @xhochy. I think I've addressed the points.

2024-04-27 18:56 UTC, xhochy approved these changes

2024-04-27 18:57 UTC, merged

2024-04-27 19:03 UTC, loriab commented
Thanks for the merge!