Add jnv
conda-forge/staged-recipes pull request #25806
Opened 2024-03-20 22:26 UTC by pavelzw

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-03-20 22:48 UTC, pavelzw commented
Issue looks like https://github.com/rust-lang/cc-rs/issues/958

2024-03-24 09:25 UTC, moritzwilksch requested changes
🙃

2024-03-24 09:25 UTC, moritzwilksch commented on recipes/jnv/meta.yaml
> +    - pavelzw
```suggestion
    - pavelzw
    - moritzwilksch
```

2024-04-07 11:18 UTC, pavelzw commented
```
  checking host system type... 
  --- stderr
  configure.ac:11: installing 'config/ar-lib'
  configure.ac:8: installing 'config/compile'
  configure.ac:19: installing 'config/config.guess'
  configure.ac:19: installing 'config/config.sub'
  configure.ac:9: installing 'config/install-sh'
  configure.ac:9: installing 'config/missing'
  Makefile.am: installing 'config/depcomp'
  configure.ac: installing 'config/ylwrap'
  parallel-tests: installing 'config/test-driver'
  Invalid configuration `/home/conda/staged-recipes/build_artifacts/jnv_1712488275842/_build_env/bin/x86_64-conda-linux-gnu': more than four components
  configure: error: /bin/sh /home/conda/staged-recipes/build_artifacts/jnv_1712488275842/work/target/x86_64-unknown-linux-gnu/release/build/j9-sys-b50a7ed31c9b8fd9/out/jq_build/config/config.sub /home/conda/staged-recipes/build_artifacts/jnv_1712488275842/_build_env/bin/x86_64-conda-linux-gnu failed
  thread 'main' panicked at /home/conda/staged-recipes/build_artifacts/jnv_1712488275842/_build_env/.cargo/registry/src/index.crates.io-6f17d22bba15001f/autotools-0.2.6/src/lib.rs:781:5:
```

2024-07-29 14:02 UTC, pavelzw commented
@conda-forge/help-rust this is ready for review

2024-08-08 08:08 UTC, xhochy requested changes

2024-08-08 08:08 UTC, xhochy commented on recipes/jnv/build.sh
> +cargo install --root "$PREFIX" --path .
```suggestion
cargo install --no-track --root "$PREFIX" --path .
```

2024-08-08 08:08 UTC, xhochy commented on recipes/jnv/bld.bat
> +cargo install --root "%PREFIX%" --path . || goto :error
```suggestion
cargo install --no-track --root "%PREFIX%" --path . || goto :error
```

2024-08-08 11:57 UTC, merged