Adding pyrte_rrtmgp recipe
conda-forge/staged-recipes pull request #25894
Opened 2024-03-28 09:59 UTC by giancastro

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-03-28 11:11 UTC, giancastro commented
@conda-forge-admin please rerender

2024-03-28 11:20 UTC, giancastro commented
@conda-forge-admin please rerender

2024-03-28 11:26 UTC, giancastro commented
@conda-forge-admin, please rerender

2024-03-28 11:34 UTC, martin-g commented
@conda-forge-admin please rerender

2024-03-28 11:38 UTC, jaimergp commented
staged-recipes doesn't need to be rerendered. You can skip things but also feel free to ignore those builds that do not matter. Once approved and merged, the resulting feedstock will only generate the config for the platforms that are not skipped.

2024-03-28 11:39 UTC, jaimergp commented on recipes/pyrte_rrtmgp/meta.yaml
> +    - m2w64-binutils      # [win]
Please just use `{{ compiler('<language>') }}` functions.

2024-03-29 00:37 UTC, RobertPincus commented
I am willing to act as a maintainer of this recipe.

2024-11-19 12:07 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyrte_rrtmgp/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/pyrte_rrtmgp/meta.yaml**:

 * ❌ This recipe is using a compiler, which now requires adding a build dependence on `{{ stdlib("c") }}` as well. Note that this rule applies to each output of the recipe using a compiler. For further details, please see https://github.com/conda-forge/conda-forge.github.io/issues/2102.

2024-11-21 14:05 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pyrte_rrtmgp/meta.yaml```) and found it was in an excellent condition.

2024-11-21 14:52 UTC, giancastro commented
@conda-forge/help-python, ready for review!

2024-11-23 13:47 UTC, xhochy requested changes

2024-11-23 13:47 UTC, xhochy commented on recipes/pyrte_rrtmgp/meta.yaml
> +    - numpy >=1.21.0
This should be unpinned to use the globally pinned version.
```suggestion
    - numpy
```

2024-11-23 13:47 UTC, xhochy commented on recipes/pyrte_rrtmgp/meta.yaml
> +    - libuv ==1.44.2
If required, this should be in host.
```suggestion
```

2024-11-25 20:29 UTC, xhochy approved these changes

2024-11-25 20:29 UTC, merged