Add recipe for egobox
conda-forge/staged-recipes pull request #26088
Opened 2024-04-18 13:59 UTC by relf

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-04-18 19:02 UTC, relf commented
Hi @conda-forge/help-python, ready for review, thanks!

2024-04-19 16:11 UTC, synapticarbors requested changes
Please see the following about adding bundled licenses for rust:
https://conda-forge.org/docs/maintainer/adding_pkgs/#rust

2024-04-20 08:29 UTC, relf commented
@synapticarbors thanks for reviewing!

2024-04-26 12:38 UTC, relf commented
@conda-forge/help-rust, the PR looks good to me, anything else to do?

2024-04-26 14:53 UTC, xhochy requested changes
See https://conda-forge.org/news/2024/03/24/stdlib-migration/

2024-04-26 14:53 UTC, xhochy commented on recipes/egobox/conda_build_config.yaml
> +MACOSX_DEPLOYMENT_TARGET: # [osx and x86]
```suggestion
c_stdlib_version: # [osx and x86]
```

2024-04-26 14:53 UTC, xhochy commented on recipes/egobox/meta.yaml
> +    - {{ compiler('c') }}
```suggestion
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
```

2024-04-26 14:53 UTC, xhochy commented on recipes/egobox/meta.yaml
> +    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
```suggestion
```

2024-04-26 18:44 UTC, relf commented
@xhochy, thanks for reviewing.

2024-04-26 19:41 UTC, xhochy approved these changes

2024-04-26 19:42 UTC, merged