adding litesata
conda-forge/staged-recipes pull request #26094
Opened 2024-04-18 21:03 UTC by timkpaine

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-04-19 14:01 UTC, timkpaine commented
@conda-forge/help-python all set!

2024-05-10 22:39 UTC, BastianZim requested changes
Just one small thing.

2024-05-10 22:39 UTC, BastianZim commented on recipes/litesata/meta.yaml
> +    - litesata_gen --help
```suggestion
    - litesata_gen --help
    - pip check
requires:
    - pip
```

2024-05-10 22:39 UTC, BastianZim commented on recipes/litesata/meta.yaml
> +  fn: {{ version }}.tar.gz
```suggestion
```

2024-05-10 22:45 UTC, timkpaine commented
Thanks @bastianzim but id like to keep this in line with prior packages that are the same:
- https://github.com/conda-forge/staged-recipes/pull/26117
- https://github.com/conda-forge/staged-recipes/pull/26093
- https://github.com/conda-forge/staged-recipes/pull/22532
- https://github.com/conda-forge/staged-recipes/pull/22508
- https://github.com/conda-forge/staged-recipes/pull/22507
- https://github.com/conda-forge/staged-recipes/pull/22332

Also for pip check see:
- https://github.com/conda-forge/staged-recipes/pull/26117#discussion_r1581899783
- https://github.com/conda-forge/staged-recipes/pull/26093#discussion_r1597173893

2024-05-10 22:56 UTC, merged