Add C package xclip
conda-forge/staged-recipes pull request #26165
Opened 2024-04-27 12:26 UTC by ehfd

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-04-27 12:30 UTC, ehfd commented
Courtesy of @danielnachun. I would like to merge this into conda-forge. Thanks.

2024-04-27 12:30 UTC, ehfd commented
@conda-forge-admin, please ping conda-forge/help-python-c, ready for review!

2024-04-27 12:31 UTC, ehfd commented
@conda-forge-admin, please ping conda-forge/help-c, ready for review!

2024-04-27 12:32 UTC, ehfd commented
@conda-forge-admin, please ping conda-forge/help-c-cpp, ready for review!

2024-04-28 19:49 UTC, ehfd commented
@conda-forge-admin, please ping conda-forge/help-c-cpp, ready for review!

2024-04-28 19:50 UTC, ehfd commented
Ready to be merged. Windows build impossible due to fork command.

2024-04-29 18:57 UTC, xhochy requested changes

2024-04-29 18:57 UTC, xhochy commented on recipes/xclip/COPYING
> +                    GNU GENERAL PUBLIC LICENSE
It looks like this should be in the tarball. If so, please remove this from the recipe submission.

2024-04-29 18:57 UTC, xhochy commented on recipes/xclip/meta.yaml
> +  sha256: {{ sha256 }}
```suggestion
  sha256: ca5b8804e3c910a66423a882d79bf3c9450b875ac8528791fb60ec9de667f758

```

2024-04-29 18:57 UTC, xhochy commented on recipes/xclip/meta.yaml
> +{% set sha256 = "ca5b8804e3c910a66423a882d79bf3c9450b875ac8528791fb60ec9de667f758" %}
No need for templating this, it is only used once.
```suggestion
```

2024-04-29 18:57 UTC, xhochy commented on recipes/xclip/meta.yaml
> +    - {{ pin_compatible('xorg-libxmu') }}
These have run_exports and thus should be automatically added here.
```suggestion
```

2024-04-29 18:57 UTC, xhochy commented on recipes/xclip/meta.yaml
> +    - gnuconfig  # [unix]
You don't seem to use this package in the build script.

2024-04-29 18:57 UTC, xhochy commented on recipes/xclip/meta.yaml
> +  run_exports:
This package only contains an executable, not a shared library, so it shouldn't have a `run_exports`.

2024-04-29 19:13 UTC, xhochy commented
As with the other PR, this should be fix in `xorg-libxmu-feedstock`

2024-04-29 20:28 UTC, ehfd commented
@xhochy Everything should be ready after https://github.com/conda-forge/xorg-libxmu-feedstock/pull/9

2024-05-03 13:48 UTC, ehfd commented
@conda-forge-admin, please rerender

2024-05-03 20:35 UTC, ehfd commented
@xhochy All ready. Windows build is not done because 1) it uses `fork()`, and 2) this isn't an official X11 package, so I'm not trying that hard to work around `fork()`.

2024-05-05 11:07 UTC, ehfd commented
@conda-forge-admin, please ping conda-forge/help-c-cpp, ready for review!

2024-05-30 08:57 UTC, ehfd commented
This is an optional dependency of (indirectly) `pandas` and (directly) `pyperclip`.

2024-06-01 17:00 UTC, merged