[WIP] Add onnxruntime-extensions package
conda-forge/staged-recipes pull request #26170
Opened 2024-04-27 21:23 UTC by Chizkiyahu

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-04-27 22:12 UTC, Chizkiyahu commented
@conda-forge-admin, please ping team conda-forge/help-python-c
install with `pip install .` on the local machine works ok 
but building with conda  fails 
thanks

2024-04-28 06:21 UTC, xhochy requested changes

2024-04-28 06:21 UTC, xhochy commented on recipes/onnxruntime-extensions/meta.yaml
> +    - numpy >=1.18.5
Please don't pin to use the global numpy pin
```suggestion
    - numpy
```

2024-04-28 06:21 UTC, xhochy commented on recipes/onnxruntime-extensions/meta.yaml
> +    - cmake
These two should be in build

2024-04-28 06:21 UTC, xhochy commented on recipes/onnxruntime-extensions/meta.yaml
> +    - {{ pin_compatible('numpy') }}
As numpy has a run_exports, this is no longer necessary.
```suggestion
```

2024-04-29 18:54 UTC, xhochy commented
FYI @cbourjau

2024-04-30 07:58 UTC, cbourjau commented on recipes/onnxruntime-extensions/meta.yaml
> +    - python
The library may also be used without `Python` (directly from C++), may it not?

2024-08-07 16:08 UTC, closed without merging