Add gnucobol
conda-forge/staged-recipes pull request #26192
Opened 2024-04-30 16:02 UTC by pavelzw

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-05-02 17:16 UTC, pavelzw commented
@conda-forge/help-c-cpp, this is ready for review

2024-05-02 18:12 UTC, xhochy commented on recipes/gnucobol/meta.yaml
> +    - cobc --version
As this is a compiler, could you also add a test that it produces working binaries?

2024-05-07 08:50 UTC, xhochy requested changes
On `osx-64` you get

```
2024-05-03T13:08:47.2821510Z WARNING (gnucobol): run-exports library package conda-forge/osx-64::libdb==6.2.32=he49afe7_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
2024-05-03T13:08:47.2823420Z WARNING (gnucobol): run-exports library package conda-forge/osx-64::libxml2==2.12.6=hcacace5_2 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
```

Are these features maybe not correctly detected?

2024-05-07 08:50 UTC, xhochy commented on recipes/gnucobol/meta.yaml
> +    - libdb
These should all come in automatically via their `run_exports`.
```suggestion
```

2024-05-07 08:50 UTC, xhochy commented on recipes/gnucobol/build.sh
> +
Run this in verbose strict mode please.
```suggestion
set -exuo pipefail
```

2024-05-07 08:50 UTC, xhochy commented on recipes/gnucobol/meta.yaml
> +    - libdb
This needs libintl on non-Linux platforms.
```suggestion
    - libdb
    - libintl-devel  # [not linux]
```

See in the `osx-64` build:
```
2024-05-03T13:07:27.6609120Z checking for GNU gettext in libintl... no
```

2024-05-07 08:50 UTC, xhochy commented on recipes/gnucobol/meta.yaml
> +    - make
```suggestion
    - make
    - gettext-tools
```

2024-05-10 18:48 UTC, xhochy approved these changes

2024-05-10 18:49 UTC, merged