Add nestml and ode-toolbox package
conda-forge/staged-recipes pull request #26347
Opened 2024-05-14 07:31 UTC by steffengraber

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ x Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-05-14 11:17 UTC, steffengraber commented
@conda-forge/help-python, ready for review!

2024-05-18 09:56 UTC, xhochy requested changes

2024-05-18 09:56 UTC, xhochy commented on recipes/nestml/meta.yaml
> +  number: {{ build }}
Please set it directly.

2024-05-18 09:56 UTC, xhochy commented on recipes/nestml/meta.yaml
> +    - typing  # [py<35]
Remove this dependency and add a matching python lower bound. Then you can make the whole package noarch.

2024-05-24 07:45 UTC, xhochy approved these changes

2024-05-24 07:46 UTC, merged