Create only_edit_in_recipes.yaml
conda-forge/staged-recipes pull request #26389
Opened 2024-05-16 23:13 UTC by BastianZim

This PR adds a workflow similar to https://github.com/conda-forge/staged-recipes/blob/main/.github/workflows/do_not_edit_example.yml which asks submitters to not change or delete any files outside of the recipes directory. 
This is primarily to prevent changes to the CI infrastructure.

2024-05-16 23:22 UTC, isuruf commented
Need to skip on https://github.com/conda-forge/conda-forge-webservices/blob/32aff9f0bb9cdad9e1ae593d0dd73d9d9b088e68/conda_forge_webservices/linting.py#L67-L70 or when `maintenance` label is on the PR

2024-05-16 23:43 UTC, BastianZim commented
@isuruf Can you have a look at https://github.com/conda-forge/staged-recipes/pull/26389/commits/8e79a6e5067aeb09b7928a8050fa8a089997e8e9

2024-06-07 19:28 UTC, BastianZim commented
@isuruf Gentle ping

2024-06-25 14:46 UTC, BastianZim commented on .github/workflows/only_edit_in_recipes.yaml
> +                    '\nPlease make sure that any changes are reverted before you submit your pull request for review.' +
Thank you!

2024-06-27 15:35 UTC, carterbox requested changes
I'm curious about the "maintenance" label. Does having this label affect the behavior or bots or is it just for humans? Adding `[ci skip]` *does* have an effect on the bots, so if "maintenance" doesn't control bots, the message should ask the user to add `[ci skip]` so that the builds aren't triggered.

For example, this PR should have `[ci skip]` in the title because the CI keeps trying to build recipes, but there is nothing to build.

2024-07-01 13:48 UTC, BastianZim commented
It's purely for convenience, really. The label and the message in the title should do the same.

2024-07-01 18:12 UTC, carterbox commented
Let's just merge this and we can adjust as needed in additional PRs.

2024-07-01 18:12 UTC, merged