Add Kustomize
conda-forge/staged-recipes pull request #26480
Opened 2024-05-28 09:23 UTC by levsha

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-05-29 09:06 UTC, levsha commented
@conda-forge-admin, please ping conda-forge/staged-recipes

2024-05-29 09:07 UTC, levsha commented
@conda-forge-admin, please ping conda-forge/help-go

2024-06-13 15:57 UTC, xhochy requested changes
This needs to bundle third-party licenses.

2024-06-13 15:57 UTC, xhochy commented on recipes/kustomize/build.sh
> +    .
```suggestion
    .

go-licenses save . --save_path="./license-files/"
```

2024-06-13 15:57 UTC, xhochy commented on recipes/kustomize/meta.yaml
> +    - {{ compiler('go') }}
```suggestion
    - {{ compiler('go') }}
    -  go-licenses
```

2024-06-13 15:57 UTC, xhochy commented on recipes/kustomize/meta.yaml
> +  license_file: LICENSE
```suggestion
  license_file:
    - LICENSE
    - license-files/
```

2024-06-15 21:00 UTC, xhochy approved these changes

2024-06-15 21:00 UTC, merged