Adding r-smartsnp recipe using conda_r_skeleton_helper
conda-forge/staged-recipes pull request #26511
Opened 2024-05-30 13:10 UTC by TCLamnidis

Recipe made with: https://github.com/bgruening/conda_r_skeleton_helper

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-05-30 13:32 UTC, TCLamnidis commented
Waiting on: https://github.com/conda-forge/staged-recipes/pull/26512

2024-07-17 11:36 UTC, mfansler requested changes
Thanks for adding this! ❤️ 

Some suggested changes, then should be good to merge.

2024-07-17 11:36 UTC, mfansler commented on recipes/r-smartsnp/meta.yaml
> +    - TCLamnidis
R team would also like to maintain:

```suggestion
    - conda-forge/r
    - TCLamnidis
```

2024-07-17 11:36 UTC, mfansler commented on recipes/r-smartsnp/meta.yaml
> +
Skip windows for now - it will try again once the R4.4 migrator visits the feedstock:

```suggestion
  skip: true  # [win]

```

2024-07-17 11:36 UTC, mfansler commented on recipes/r-smartsnp/meta.yaml
> +    - {{ stdlib("c") }}
Let's move this.

```suggestion
```

2024-07-17 11:36 UTC, mfansler commented on recipes/r-smartsnp/meta.yaml
> +    - {{ compiler('m2w64_c') }}        # [win]
Add the stdlib's here:

```suggestion
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib('c') }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib('m2w64_c') }}          # [win]
```

2024-07-17 11:36 UTC, mfansler commented on recipes/r-smartsnp/meta.yaml
> +  license: MIT
Let's add a dev URL:

```suggestion
  dev_url: https://github.com/ChristianHuber/smartsnp
  license: MIT
```

2024-07-17 11:50 UTC, mfansler approved these changes

2024-07-17 11:55 UTC, merged