Adding pyhdbpp, python extractor for tango-hdb++ databases
conda-forge/staged-recipes pull request #26584
Opened 2024-06-07 07:46 UTC by sergirubio

pyhdbpp is a python module for extracting data from Tango Control System archiving databases (HDB++), it actually supports mysql/mariadb and timescaledb. It is used by some other packages already available in conda-forge (taurus).

@conda-forge/help-python

2024-06-10 07:00 UTC, beenje requested changes

2024-06-13 07:32 UTC, sergirubio commented on recipes/pyhdbpp/meta.yaml
> +  license: LGPL-3.0
thanks for the comment, I updated the license to LGPL-3.0-or-later

2024-06-13 07:32 UTC, sergirubio commented on recipes/pyhdbpp/meta.yaml
> +  sha256: 41b6a82cfdc64aa9770aa1c3e4d05edd767537012a4a6765c633b01fbe1f3b02
hash updated, thanks for the comment

2024-06-14 20:24 UTC, beenje commented
You still have a script in your package that makes the build fail on windows: `[noarch_python] Noarch package contains binary script: hdb2csv.exe`

Could you convert it to an entry-point?

2024-06-18 16:22 UTC, beenje commented
I think you just have to add the entry point to the conda recipe as well

2024-06-20 17:04 UTC, merged