Add py2cfg
conda-forge/staged-recipes pull request #26658
Opened 2024-06-15 10:34 UTC by jan-janssen

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-06-15 12:08 UTC, jan-janssen commented
@conda-forge/staged-recipes, ready for review

2024-06-15 12:08 UTC, jan-janssen commented
@conda-forge/help-python

2024-06-15 12:15 UTC, jan-janssen commented
The windows tests fail, still I would prefer this package to remain `noarch`:
```
import: 'py2cfg'
No broken requirements found.
Traceback (most recent call last):
  File "C:\bld\py2cfg_1718453303736\_test_env\Scripts\py2cfg-script.py", line 5, in <module>
    from py2cfg._runner import main
  File "C:\bld\py2cfg_1718453303736\_test_env\lib\site-packages\py2cfg\_runner.py", line 10, in <module>
    import pty
  File "C:\bld\py2cfg_1718453303736\_test_env\lib\pty.py", line 12, in <module>
    import tty
  File "C:\bld\py2cfg_1718453303736\_test_env\lib\tty.py", line 5, in <module>
    from termios import *
ModuleNotFoundError: No module named 'termios'
```

2024-06-15 20:56 UTC, xhochy approved these changes

2024-06-15 20:57 UTC, xhochy requested changes
It can stay noarch but it should not be installable on Windows

2024-06-15 20:57 UTC, xhochy commented on recipes/py2cfg/meta.yaml
> +    - packaging
```suggestion
    - packaging
    - __unix
```

2024-06-16 05:05 UTC, jan-janssen commented
@xhochy Thanks a lot, I updated the pull request accordingly

2024-06-16 08:09 UTC, xhochy approved these changes

2024-06-16 08:09 UTC, merged