Adding ptflops
conda-forge/staged-recipes pull request #26657
Opened 2024-06-15 07:01 UTC by cnpcshangbo

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-06-15 07:52 UTC, cnpcshangbo commented
@conda-forge/help-python ready for review.

2024-06-17 17:32 UTC, synapticarbors requested changes

2024-06-17 17:32 UTC, synapticarbors commented on recipes/ptflops/conda_build_config.yaml
> +channels:
conda-forge packages should not depend on other non-conda-forge channels. Please remove this. I believe all of the dependencies are available on the `conda-forge` channel.

2024-06-17 17:32 UTC, synapticarbors commented on recipes/ptflops/meta.yaml
> +    - torchvision
`torchvision` doesn't looks like it's required to build the package, so it should be removed from the `host` section

2024-06-17 17:32 UTC, synapticarbors commented on recipes/ptflops/meta.yaml
> +    - torchvision
`torchvision` appears to be an optional dependency listed under the optional `dev` section. Unless there is a compelling reason, I'd remove it here.

2024-06-17 17:32 UTC, synapticarbors commented on recipes/ptflops/meta.yaml
> +test:
Please add a `pip check` test. See:
https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L61-L64

2024-06-20 22:45 UTC, cnpcshangbo commented
@conda-forge/help-python, ready for review!

2024-06-21 11:37 UTC, synapticarbors commented on recipes/ptflops/meta.yaml
> +  url: https://files.pythonhosted.org/packages/95/3d/d2af80d6b90d74f1b73e688c287434912fc4416517c6f7505bb6d2ca77d1/ptflops-0.7.3.tar.gz
Sorry I missed this in my original review, but could you use our canonical `url` definition:
https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L16

With it hardcoded this way, I'm not sure if the bots that automatically submit PRs when the package is updated upstream will be able to work.

2024-06-24 07:50 UTC, cnpcshangbo commented
@conda-forge/help-python, ready for review!

2024-06-24 12:08 UTC, merged