Adding spotiflow
conda-forge/staged-recipes pull request #26670
Opened 2024-06-17 16:32 UTC by AlbertDominguez

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [ x Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-06-18 09:47 UTC, AlbertDominguez commented
@conda-forge/help-python PR is ready for review!

2024-06-18 11:52 UTC, AlbertDominguez commented
@conda-forge/help-python-c just realizing that the python-c label is more appropriate :)

2024-07-20 08:04 UTC, xhochy requested changes

2024-07-20 08:04 UTC, xhochy commented on recipes/spotiflow/meta.yaml
> +    - {{ pin_compatible('numpy') }}
Numpy has a run_exports and this should no longer be used.
```suggestion
```

2024-07-20 08:04 UTC, xhochy commented on recipes/spotiflow/meta.yaml
> +    - {{ pin_compatible('numpy') }}
```suggestion
    - numpy
```

2024-07-20 08:04 UTC, xhochy commented on recipes/spotiflow/meta.yaml
> +    - llvm-openmp  # [osx]
Please also add them in host

2024-07-21 13:15 UTC, AlbertDominguez commented
Thanks for taking a look @xhochy! I think I've assessed all your comments now :)

2024-07-22 07:27 UTC, xhochy requested changes

2024-07-22 07:27 UTC, xhochy commented on recipes/spotiflow/meta.yaml
> +    - make
I only meant the OpenMP libraries. They currently have a bug where they need to be in build and host, all other should only be in build.
```suggestion
```

2024-07-22 08:28 UTC, xhochy approved these changes

2024-07-22 08:29 UTC, merged