Add pylibacl
conda-forge/staged-recipes pull request #26675
Opened 2024-06-18 06:59 UTC by tjtg

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-06-18 07:24 UTC, tjtg commented
@conda-forge/help-python-c this is ready for review

2024-06-25 14:29 UTC, xhochy requested changes

2024-06-25 14:29 UTC, xhochy commented on recipes/pylibacl/meta.yaml
> +    - libacl
Not needed, this will be added by `run_exports`
```suggestion
```

2024-06-25 14:29 UTC, xhochy commented on recipes/pylibacl/conda_build_config.yaml
> +python:
This file should be removed.

2024-07-04 11:36 UTC, tjtg commented on recipes/pylibacl/conda_build_config.yaml
> +python:
Removed in 8dcb0d7

2024-07-04 11:49 UTC, tjtg commented
Thanks for the review. I've made changes to address the comments and this is ready for re-review.

2024-07-05 14:38 UTC, xhochy approved these changes
Looks good, I'll merge once https://github.com/conda-forge/status/issues/181 is resolved

2024-07-08 07:45 UTC, merged