recipe for tantivy
conda-forge/staged-recipes pull request #26705
Opened 2024-06-19 12:14 UTC by mediocretech

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-06-19 15:57 UTC, mediocretech commented
@conda-forge/help-python, ready for review!

2024-07-05 20:26 UTC, xhochy requested changes

2024-07-05 20:26 UTC, xhochy commented on recipes/tantivy/meta.yaml
> +    - rust
If you need rust, you should be putting it as a compiler in build

2024-07-05 20:26 UTC, xhochy commented on recipes/tantivy/meta.yaml
> +    - "*/libgcc*"
This doesn't look right and coukf be related to rust in host

2024-08-01 13:54 UTC, mediocretech commented
Build modification pending https://github.com/conda-forge/staged-recipes/pull/27151

2024-08-19 09:46 UTC, xhochy requested changes

2024-08-19 09:46 UTC, xhochy commented on recipes/tantivy/meta.yaml
> +    - rust <1.80
```suggestion
    - {{ compiler('rust') }} <1.80
```

2024-09-04 09:55 UTC, xhochy requested changes

2024-09-04 09:55 UTC, xhochy commented on recipes/tantivy/meta.yaml
> +  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
You also should call `cargo-bundle-licenses` here

2024-09-14 16:45 UTC, xhochy approved these changes

2024-09-14 16:45 UTC, merged