Add ms_entropy
conda-forge/staged-recipes pull request #26730
Opened 2024-06-21 08:59 UTC by n-elie

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-06-21 09:17 UTC, n-elie commented
@conda-forge-admin please rerender

2024-06-30 07:16 UTC, xhochy requested changes

2024-06-30 07:16 UTC, xhochy commented on recipes/ms_entropy/meta.yaml
> +    - numpy >=1.9.3
Leave this unpinned to get the global pin
```suggestion
    - numpy
```

2024-06-30 07:16 UTC, xhochy commented on recipes/ms_entropy/meta.yaml
> +    - {{ pin_compatible('numpy') }}
This should no longer be used, numpy has a run_exports now
```suggestion
```

2024-07-01 10:39 UTC, xhochy approved these changes

2024-07-01 10:41 UTC, xhochy commented on recipes/ms_entropy/meta.yaml
> +    - numpy
Don't list it at all here. Still, this probably won't fix the build error.
```suggestion
```

2024-07-01 13:08 UTC, xhochy commented
The patch looks empty. This is probably not intended.

2024-11-24 20:04 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/ms_entropy/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/ms_entropy/meta.yaml**:

 * ℹ️ The recipe is not parsable by parser `conda-souschef (grayskull)`. Your recipe may not receive automatic updates and/or may not be compatible with conda-forge's infrastructure. Please check the logs for more information and ensure your recipe can be parsed.
 * ℹ️ PyPI default URL is now pypi.org, and not pypi.io. You may want to update the default source url.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/11999147830](https://github.com/conda-forge/conda-forge-webservices/actions/runs/11999147830). Examine the logs at this URL for more detail.</sub>

2024-11-27 18:39 UTC, merged