Add Travo and Travo-Jupyter recipes
conda-forge/staged-recipes pull request #26770
Opened 2024-06-26 08:48 UTC by cmarmo

Dear conda-forge maintainers,
I would like to maintain the conda recipe for [Travo](https://travo-cr.gitlab.io/travo/).
Travo (from the French *Travaux*) is a lightweight open source Python toolkit automating steps in the assignment workflow for computational practice sessions.

It comes with a simple CLI or Jupyter lab widgets and dashboards: this is why I'm building two subpackages in the recipe. 

Thank you for your attention.

@conda-forge-admin, please ping @conda-forge/help-python

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged (Not applicable).
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-06-27 13:42 UTC, cmarmo commented
After discussion with the other authors, we prefer to have 1.0.0 on conda (if conda maintainers agree to include the package), rather than wit for 1.0.1, I have commented out the test for now and working to a fix for the next bugfix release.
Thanks for your understanding.

2024-07-13 17:59 UTC, xhochy requested changes

2024-07-13 17:59 UTC, xhochy commented on recipes/travo/meta.yaml
> +  name: {{ name }}
```suggestion
  name: {{ name }}-split
```

2024-07-13 17:59 UTC, xhochy commented on recipes/travo/meta.yaml
> +test:
Please move these tests to the outputs

2024-07-13 17:59 UTC, xhochy commented on recipes/travo/meta.yaml
> +          - python >=3.8
```suggestion
        host:
          - python >=3.8
          - {{ pin_subpackage('travo', exact=True }}
```

2024-07-13 17:59 UTC, xhochy commented on recipes/travo/meta.yaml
> +          - python >=3.8
```suggestion
          - python >=3.8
          - {{ pin_subpackage('travo', exact=True }}
```

2024-07-13 17:59 UTC, xhochy commented on recipes/travo/meta.yaml
> +extra:
```suggestion
extra:
  feedstock-name: travo
```

2024-07-16 13:19 UTC, cmarmo commented
Thanks @xhochy !
I believe I have addressed your comments.

2024-07-17 12:19 UTC, xhochy commented on recipes/travo/meta.yaml
> +  - name: travo
I think you need to re-iterate this for all outputs
```suggestion
  - name: travo
    build:
      noarch: python
```

2024-07-18 10:15 UTC, xhochy approved these changes

2024-07-18 10:15 UTC, merged

2024-07-18 19:46 UTC, cmarmo commented
Thanks @xhocky!