Adding r-fedmatch
conda-forge/staged-recipes pull request #26799
Opened 2024-06-28 21:06 UTC by JNuss71

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

I used the [conda_r_skeleton_helper](https://github.com/bgruening/conda_r_skeleton_helper?tab=readme-ov-file) to expedite the package review process for adding the [fedmatch package](https://cran.r-project.org/web/packages/fedmatch).

2024-06-28 21:19 UTC, JNuss71 commented
@conda-forge/help-r, ready for review!

2024-07-09 19:13 UTC, JNuss71 commented
@conda-forge-admin, please ping team

2024-07-09 19:44 UTC, mfansler requested changes
Thanks for adding this! ❤️ 

Mostly looks good - a couple minor changes, then should be good.

2024-07-09 19:44 UTC, mfansler commented on recipes/r-fedmatch/meta.yaml
> +    - r-bh
Boost headers are only needed at build time. We usually remove it from `run:`, when only in `LinkingTo`, i.e.,

```suggestion
```

2024-07-09 19:44 UTC, mfansler commented on recipes/r-fedmatch/meta.yaml
> +    - {{ stdlib("c") }}
A little adjustment for win:

```suggestion
    - {{ stdlib("c") }}        # [not win]
    - {{ stdlib("m2w64_c") }}  # [win]
```

2024-07-09 19:45 UTC, mfansler commented
R Team is happy to help maintain.

2024-07-10 05:05 UTC, mfansler approved these changes

2024-07-10 05:06 UTC, merged