Added r-stochvol as a package
conda-forge/staged-recipes pull request #26802
Opened 2024-06-28 21:13 UTC by thewchan

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-06-29 00:26 UTC, thewchan commented
@conda-forge/staged-recipes @conda-forge/help-r Requesting review here; only win build is failing though not sure why, the error message:

```
ERROR (r-stochvol,lib/R/library/stochvol/libs/x64/stochvol.dll): $RPATH/R.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.
```

2024-07-24 07:27 UTC, mfansler requested changes
Thanks for adding and apologies for the delay!

There are some things to touch up before merging.

2024-07-24 07:27 UTC, mfansler commented on recipes/r-stochvol/meta.yaml
> +
Either skip Windows (`skip: true  # [win]`) or whitelist DLLs (as per https://github.com/conda/conda-build/pull/4786):

```suggestion
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

```

2024-07-24 07:27 UTC, mfansler commented on recipes/r-stochvol/meta.yaml
> +    - {{ posix }}filesystem        # [win]
The `stdlib` is different on Windows; also tidy while we're here:

```suggestion
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
```

2024-07-24 07:27 UTC, mfansler commented on recipes/r-stochvol/meta.yaml
> +  license: GPL-2.0-only
License shows `GPL (>= 2)`, so:

```suggestion
  license: GPL-2.0-or-later
```

2024-07-24 07:27 UTC, mfansler commented on recipes/r-stochvol/meta.yaml
> +    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
Include v3:

```suggestion
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
```

2024-07-24 07:27 UTC, mfansler commented on recipes/r-stochvol/meta.yaml
> +# Encoding: UTF-8
tidy

```suggestion
```

2024-07-24 14:40 UTC, thewchan commented
Thanks @mfansler @conda-forge/staged-recipes @conda-forge/help-r This is now ready for another review

2024-07-25 07:10 UTC, mfansler approved these changes

2024-07-25 07:11 UTC, merged