Adding r-did as a package
conda-forge/staged-recipes pull request #26832
Opened 2024-07-02 19:14 UTC by JNuss71

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

I used the [conda_r_skeleton_helper](https://github.com/bgruening/conda_r_skeleton_helper?tab=readme-ov-file) to expedite the package review process for adding the [did package](https://cran.r-project.org/web/packages/did/).

2024-07-13 20:16 UTC, mfansler requested changes
Thanks for working on this! ❤️ 

I suggest postponing windows build until on the feedstock. Few minor changes and I think this could be merged.

2024-07-13 20:16 UTC, mfansler commented on recipes/r-bmisc/meta.yaml
> +    - liblapacke      # [win]
Should only need:

```suggestion
    - libblas         # [win]
    - liblapack       # [win]
```

2024-07-13 20:16 UTC, mfansler commented on recipes/r-bmisc/meta.yaml
> +
I would suggest just to skip windows for now. We are switching to UCRT-based builds and moving to R 4.3/4.4, whereas this is testing the old build tools on R 4.1.

```suggestion
  skip: true  # [win]

```

2024-07-13 20:16 UTC, mfansler commented on recipes/r-bmisc/meta.yaml
> +  home: https://bcallaway11.github.io/BMisc/, https://github.com/bcallaway11/BMisc
Split URLs

```suggestion
  home: https://bcallaway11.github.io/BMisc/
  dev_url: https://github.com/bcallaway11/BMisc
```

2024-07-13 20:16 UTC, mfansler commented on recipes/r-did/meta.yaml
> +  home: https://bcallaway11.github.io/did/, https://github.com/bcallaway11/did/
Split URLs:

```suggestion
  home: https://bcallaway11.github.io/did/
  dev_url: https://github.com/bcallaway11/did/
```

2024-07-13 20:16 UTC, mfansler commented on recipes/r-drdid/meta.yaml
> +  home: https://psantanna.com/DRDID/, https://github.com/pedrohcgs/DRDID
Split URLs:

```suggestion
  home: https://psantanna.com/DRDID/
  dev_url: https://github.com/pedrohcgs/DRDID
```

2024-07-15 13:21 UTC, JNuss71 commented
Thanks for the suggestions! I merged all of them.

2024-07-15 13:38 UTC, mfansler approved these changes
Ready to go! 🚀

2024-07-15 13:38 UTC, merged