Adding pypolymlp as a package
conda-forge/staged-recipes pull request #26843
Opened 2024-07-03 05:38 UTC by sekocha

`@conda-forge/help-python-c`

Checklist
- [ x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x ] Source is from official source.
- [x ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x ] If static libraries are linked in, the license of the static library is packaged.
- [x ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x ] Build number is 0.
- [ x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-07-08 05:31 UTC, sekocha commented
@conda-forge/help-python-c, ready for review!

2024-08-27 08:59 UTC, sekocha commented
@conda-forge/help-python-c, ready for review!
@conda-forge/staged-recipes

I appreciate it if pypolymlp would be reviewed as a package.
Thank you very much.

Checklist

[ x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
[ x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
[x ] Source is from official source.
[x ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
[x ] If static libraries are linked in, the license of the static library is packaged.
[x ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
[x ] Build number is 0.
[ x] A tarball (url) rather than a repo (e.g. git_url) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
[ x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
[ x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-09-09 05:31 UTC, sekocha commented
@conda-forge/help-python-c, @conda-forge/help-python-c, ready for review!

2024-09-22 21:23 UTC, xhochy requested changes

2024-09-22 21:23 UTC, xhochy commented on recipes/pypolymlp/meta.yaml
> +    - wheel
This should be in host

2024-09-22 21:23 UTC, xhochy commented on recipes/pypolymlp/meta.yaml
> +    - pybind11-global
Move to host

2024-09-22 21:23 UTC, xhochy commented on recipes/pypolymlp/meta.yaml
> +    - llvm-openmp  # [osx]
Please add them also to host, i.e. duplicate them.

2024-09-22 21:23 UTC, xhochy commented on recipes/pypolymlp/meta.yaml
> +    - {{ pin_compatible('numpy') }}
numpy is not in host, thus the pin_compatible function has no effect.

2024-09-22 21:23 UTC, xhochy commented on recipes/pypolymlp/meta.yaml
> +  commands:
```suggestion
test:
  imports:
    - pypolymlp
  requires:
    - pip
  commands:
    - pip check
```

2024-09-25 11:54 UTC, sekocha commented
Thank you for taking the time to review the package. Following the requests, I have revised meta.yaml.

2024-09-25 15:22 UTC, xhochy approved these changes

2024-09-25 15:22 UTC, merged