Add OpenPisco
conda-forge/staged-recipes pull request #26857
Opened 2024-07-04 05:11 UTC by fbordeu

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-07-04 07:08 UTC, fbordeu commented
@cnrdn , @daviddanan 

 GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.

2024-07-05 07:30 UTC, daviddanan commented
I confirm i am willing to be listed here.

2024-07-05 15:37 UTC, cnrdn commented
I confirm i am willing to be listed here.

2024-07-11 09:52 UTC, fbordeu commented
@conda-forge/help-python, ready for review!

Recipe works on windows, linux, mac. 

Thanks for the work.

Felipe

2024-07-20 08:02 UTC, xhochy requested changes

2024-07-20 08:02 UTC, xhochy commented on recipes/OpenPisco/meta.yaml
> +  #url:  /mnt/c/Users/d584808/Downloads/openpisco-1.1.4.tar.bz2
```suggestion
```

2024-07-20 08:02 UTC, xhochy commented on recipes/OpenPisco/meta.yaml
> +  #- name: "openpisco-extensions"
Why is this still commented?

2024-07-20 08:02 UTC, xhochy commented on recipes/OpenPisco/build_core.sh
> +$PYTHON -m pip install --no-deps . -vv
Seems like these scripts aren't necessary.

2024-07-23 22:24 UTC, fbordeu commented
Thanks for the feedback, currently I'm away, without a computer access. Will treat yours remarks in two weeks. Thank again for your time.

2024-08-14 12:37 UTC, fbordeu commented
Hello @conda-forge/help-python, ready for review!

Corrected all the remarks can someone treat this PR.

Thanks to all

2024-08-19 09:38 UTC, xhochy approved these changes

2024-08-19 09:38 UTC, merged