Adding hpfrec
conda-forge/staged-recipes pull request #26855
Opened 2024-07-04 00:26 UTC by mdekstrand

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-07-04 16:43 UTC, mdekstrand commented
@conda-forge/help-python-c, ready for review!

2024-07-05 05:41 UTC, xhochy requested changes

2024-07-05 05:41 UTC, xhochy commented on recipes/hpfrec/meta.yaml
> +    - numpy >=1.25
Always pin exactly in host 
```suggestion
    - numpy 1.25
```

2024-07-05 05:41 UTC, xhochy commented on recipes/hpfrec/meta.yaml
> +    - {{ pin_compatible('numpy') }}
Numpy has a run_exports and this should no longer be used.
```suggestion
```

2024-07-05 19:06 UTC, mdekstrand commented
@xhochy thanks! I've made those changes, but CI is currently failing due to what look like Conda-Forge infrastructure problems.

2024-07-08 11:47 UTC, xhochy approved these changes

2024-07-09 00:38 UTC, mdekstrand commented
@xhochy I also needed to conditionalize the other `numpy`, but this should work I think.

2024-07-11 04:32 UTC, xhochy requested changes
Small comment, otherwise LGTM

2024-07-11 04:32 UTC, xhochy commented on recipes/hpfrec/meta.yaml
> +    - libgomp      # [linux]
Please also put them in host while https://github.com/conda-forge/openmp-feedstock/issues/126 is not clearly resolved.
```suggestion
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
```

2024-07-11 16:31 UTC, mdekstrand commented
@xhochy all done, ready to merge I think!

2024-07-11 18:59 UTC, xhochy approved these changes

2024-07-11 18:59 UTC, merged