Add SQL tools dsq, octosql, sqls, sql-language-server
conda-forge/staged-recipes pull request #27047
Opened 2024-07-21 19:03 UTC by danielnachun

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-07-21 22:25 UTC, danielnachun commented
@conda-forge/staged-recipes This is now ready for review.  I had to skip the windows build for two package:

- `sql-language-server` builds successfully, but hits the well known issue of file paths being too long: https://github.com/conda/conda/issues/7203.  The solutions I tried there did not work so far.
- `sqls` is a CGO package and does not work with MSVC.  I had no success getting to work with MinGW, though this may be easier to iterate on once we have a feedstock.

2024-07-22 07:25 UTC, xhochy requested changes

2024-07-22 07:25 UTC, xhochy commented on recipes/sqls/conda_build_config.yaml
> +  - "10.15"  # [osx]
This should not apply to `osx-arm64`
```suggestion
c_stdlib_version:  # [osx and x86_64]
  - "10.15"  # [osx and x86_64]
MACOSX_SDK_VERSION:  # [osx and x86_64]
  - "10.15"  # [osx and x86_64]
```

2024-07-22 08:43 UTC, danielnachun commented
The requested changes have been made - see the last commit.

2024-07-22 09:12 UTC, xhochy requested changes
Still a bit missing

2024-07-22 09:12 UTC, xhochy commented on recipes/sqls/conda_build_config.yaml
> +  - "10.15"  # [osx]
```suggestion
  - "10.15"  # [osx and x86_64]
MACOSX_SDK_VERSION:  # [osx and x86_64]
  - "10.15"  # [osx and x86_64]
```

2024-07-22 14:51 UTC, merged