Add `argocd`
conda-forge/staged-recipes pull request #27045
Opened 2024-07-21 12:47 UTC by dhirschfeld

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-07-21 12:48 UTC, xhochy requested changes

2024-07-21 12:48 UTC, xhochy commented on recipes/argocd-cli/meta.yaml
> +    - {{ compiler('go') }}
```suggestion
    - {{ compiler('go-ncgo') }}
```

2024-07-21 12:48 UTC, xhochy commented on recipes/argocd-cli/build.sh
> +export CGO_ENABLED=0
```suggestion
```

2024-07-21 12:50 UTC, dhirschfeld commented
Thanks for the review @xhochy! 

I assume by using `go-ncgo` I don't need the `CGO_ENABLED=0` env var?

If so, I'll make the same change to my other PR #27044

2024-07-21 12:53 UTC, dhirschfeld commented
Looks like it doesn't like `go-ncgo`?
```
 - nothing provides requested go-ncgo_linux-64
```

2024-07-21 12:56 UTC, dhirschfeld commented
I'll see if `go` works whilst trying to figure out what was happening with `go-ncgo`...

2024-07-21 16:39 UTC, xhochy commented on recipes/argocd-cli/meta.yaml
> +    - {{ compiler('go') }}
Typo. It should be go-nocgo

2024-07-21 20:57 UTC, dhirschfeld commented
Ping @conda-forge/staged-recipes, @conda-forge/go - this should be good to review/merge!

2024-07-21 23:14 UTC, dhirschfeld commented
Added `go-nocgo` to `kind` (#27044) as well.

2024-07-21 23:15 UTC, dhirschfeld commented on recipes/argocd-cli/meta.yaml
> +    - {{ compiler('go') }}
updated!

2024-07-22 07:08 UTC, xhochy approved these changes

2024-07-22 07:08 UTC, merged