added kvrocks recipe
conda-forge/staged-recipes pull request #27058
Opened 2024-07-22 14:28 UTC by mguijarr

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-08-14 11:40 UTC, mguijarr commented
@conda-forge/staged-recipes, ready for review!

2024-10-13 07:50 UTC, xhochy requested changes

2024-10-13 07:50 UTC, xhochy commented on recipes/kvrocks/meta.yaml
> +  # uncomment the line below, and modify as needed. Use releases if available:
Please remove the comment
```suggestion
```

2024-10-13 07:50 UTC, xhochy commented on recipes/kvrocks/meta.yaml
> +  skip: True  # [win or win_64 or osx]
```suggestion
  skip: True  # [win or osx]
```

2024-10-14 09:10 UTC, mguijarr commented on recipes/kvrocks/meta.yaml
> +  # uncomment the line below, and modify as needed. Use releases if available:
Done

2024-10-14 09:10 UTC, mguijarr commented
@xhochy thanks for the review - made requested changes

2024-10-14 10:09 UTC, xhochy approved these changes

2024-10-14 10:09 UTC, merged