Add grep tools - ast-grep, bingrep, ugrep, ripgrep-all
conda-forge/staged-recipes pull request #27050
Opened 2024-07-21 19:22 UTC by danielnachun

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-07-21 22:32 UTC, danielnachun commented
@conda-forge/staged-recipes This is now ready for review.

I had to skip the Windows build for two packages:
- `bzip3` (optional dependency of `ugrep`) does not seem to support MSVC, and my attempts to use MinGW weren't successful
- `ugrep` uses autotools to configure its build.  I tried to use the `autotools_clang_conda` package without success.  The project also provides `.vcxproj` files that could potentially use `msbuild` to build them, but seems to require vendoring all of the dependencies, which I don't think is a good idea.

2024-07-22 07:13 UTC, xhochy requested changes

2024-07-22 07:13 UTC, xhochy commented on recipes/bzip3/build.sh
> +cmake --build build
```suggestion
cmake --build build -j$CPU_COUNT
```

2024-07-22 07:13 UTC, xhochy commented on recipes/ugrep/meta.yaml
> +    - libzlib
All of these should come as a `run_exports`
```suggestion
```

2024-07-22 07:13 UTC, xhochy commented on recipes/ugrep/build.sh
> +make
```suggestion
make -j$CPU_COUNT
```

2024-07-22 08:42 UTC, danielnachun commented
The requested changes have been made - see the last two commits.

2024-07-22 09:13 UTC, xhochy approved these changes

2024-07-22 09:13 UTC, merged