Add recipe for `r-spgwr`
conda-forge/staged-recipes pull request #27072
Opened 2024-07-23 10:12 UTC by darribas

This PR adds a recipe for `r-spgwr`, built for the [`spgwr`](https://cran.r-project.org/web/packages/spgwr/index.html) R package. It has been built using [`conda_r_skeleton_helper`](https://github.com/bgruening/conda_r_skeleton_helper).

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example). (**DAB NOTE**: there is a license set by the package but it does not include a file for it).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged. (**DAB NOTE**: unsure, not checking)
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md). (**DAB NOTE**: unsure, not checking)
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there. (**DAB NOTE**: @darribas is willing to be listed here)
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

I'm cc'ing @rsbivand as he might have further insight into the license issues I've not been able to clarify above.

Also paging @mfansler as this is my first PR and he suggested he'd be willing to help with the process.

@conda-forge-admin, please ping team (I _think_ I need to do this, otherwise, paging @conda-forge/help-r)

2024-07-23 10:14 UTC, darribas commented
I'm willing to be listed on the maintainer list

2024-07-23 11:15 UTC, rsbivand commented
@darribas: `spgwr` almost got retired last year, and really should not be used, it is not actively maintained. 

`GWmodel` is a bit more actively maintained. 

Beyond that, I never use and recommend that `conda` never be use with R. Anaconda is not a community participant and was unresponsive when approached while I was working on retiring `rgdal` etc. last year. 

I would be happy to ceded maintainership of `spgwr` at the earliest opportunity, provided that the start-up message is kept (asking users to avoid GWR for anything beyond ESDA).

2024-07-23 12:27 UTC, ocefpaf commented
> Beyond that, I never use and recommend that `conda` never be use with R. Anaconda is not a community participant and was unresponsive when approached while I was working on retiring `rgdal` etc. last year.

The conda-forge is not Anaconda. The conda package manager and the conda community are not Anaconda.

2024-07-23 12:36 UTC, mfansler commented
@rsbivand RE: r-rgdal please post an issue on [the Conda Forge feedstock](https://github.com/conda-forge/r-rgdal-feedstock) with your recommendations. Or feel free to reach out to me directly - I'm always happy to maintain open communication with upstream developers.

2024-07-23 13:11 UTC, mfansler commented
@darribas R is distributed with a set of common licenses. CRAN allows packages to ship without an explicit license text if it uses one of those. What we do on Conda Forge is have the individual package make a copy of the license(s) found in the `r-base` package. The `conda_r_skeleton_helper` already did this for you:

```
  license_file:
     - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
```

However, since the actual package has `GPL (>= 2)`, I usually manually expand this to

```
  license_file:
     - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
     - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
```

which keeps parity with how CRAN expands it on the website.

The linter, however, is making a separate complaint about SPDX formatting, namely that `license: GPL (>= 2)` needs to be `GPL-2.0-or-later`.

2024-07-23 13:36 UTC, mfansler requested changes
The technical side of recipe has a few things to touch up, but mostly fine. However, given @rsbivand comments, perhaps you don't require this package after all. Obviously, this depends on your needs. If you are rerunning older code, perhaps you will still want this; if not, it may be prudent to pre-emptively choose not distribute this here if a dominantly better alternative is already available.

If you want to proceed with adding this here, then the noted changes should be made. Otherwise, you can choose to close.

2024-07-23 13:36 UTC, mfansler commented on recipes/r-spgwr/meta.yaml
> +    - {{ compiler('m2w64_c') }}        # [win]
Needs `stdlib` declarations:

```suggestion
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [not win]
    - {{ stdlib('m2w64_c') }}    # [not win]
```

2024-07-23 13:36 UTC, mfansler commented on recipes/r-spgwr/meta.yaml
> +  home: https://github.com/rsbivand/spgwr/, https://rsbivand.github.io/spgwr/
Split URLs:

```suggestion
  home: https://rsbivand.github.io/spgwr/
  dev_url: https://github.com/rsbivand/spgwr/
```

2024-07-23 13:36 UTC, mfansler commented on recipes/r-spgwr/meta.yaml
> +  license: GPL (>= 2)
SPDX:

```suggestion
  license: GPL-2.0-or-later
```

2024-07-23 13:36 UTC, mfansler commented on recipes/r-spgwr/meta.yaml
> +    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
Also include v3:

```suggestion
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
```

2024-07-23 13:36 UTC, mfansler commented on recipes/r-spgwr/meta.yaml
> +
We can skip windows for now and the migrator can retry it on the feedstock.

```suggestion
  skip: true  # [win]

```

2024-08-05 12:59 UTC, darribas commented
@mfansler Thank you so much for the detailed and careful review. I think, based on the discussion above, I will not add `r-spgwr` to conda-forge and instead explore alternatives (e.g., `GWmodel`). These edits are super useful though, I'll revisit them when creating other packages. Closing for now on that basis.

2024-08-05 12:59 UTC, closed without merging