Add `conda-which`
conda-forge/staged-recipes pull request #27108
Opened 2024-07-27 21:47 UTC by kelvinou01

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-07-27 21:48 UTC, kelvinou01 commented
Consent as maintainer here!

2024-07-30 00:18 UTC, synapticarbors requested changes

2024-07-30 00:18 UTC, synapticarbors commented on recipes/conda-which/meta.yaml
> +  host:
`host` is going to need `pip` to install it.

2024-07-30 00:18 UTC, synapticarbors commented on recipes/conda-which/meta.yaml
> +  path: ../
You probably want to remove the `path` specification. This looks to be leftover from your local recipe in the upstream repo.

2024-07-30 00:18 UTC, synapticarbors commented on recipes/conda-which/meta.yaml
> +build:
This likely should be `noarch: python`:
https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python

2024-07-30 00:18 UTC, synapticarbors commented on recipes/conda-which/meta.yaml
> +  script: $PYTHON -m pip install --no-deps .
Please use the `script` line found in:
https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L38

2024-07-30 00:18 UTC, synapticarbors commented on recipes/conda-which/meta.yaml
> +  sha256: d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed
You have a sha256 mismatch. See:
https://conda-forge.org/docs/maintainer/adding_pkgs/#populating-the-hash-field

2024-08-03 21:20 UTC, synapticarbors commented on recipes/conda-which/LICENSE.txt
> +MIT License
You don't need to add this file since it's in the tarball already.

2024-08-03 21:20 UTC, synapticarbors commented on recipes/conda-which/meta.yaml
> +  license_file: LICENSE.txt
This should be `license_file: LICENSE` to match what is in the tarball source distribution.

2024-08-03 21:20 UTC, synapticarbors commented on .ci_support/compute_build_graph.py
>  import functools
Please revert changes to this file. You shouldn't need to modify anything outside of `recipes/conda-which`

2024-08-03 21:31 UTC, kelvinou01 commented
Hey @synapticarbors, thank you for the prompt reviews. I've addressed the issues you've brought up.

2024-08-03 21:48 UTC, merged