add r-fpp3
conda-forge/staged-recipes pull request #27127
Opened 2024-07-30 18:51 UTC by cnrrobertson

Used [r skeleton helper script](https://github.com/bgruening/conda_r_skeleton_helper)

2024-07-30 18:51 UTC, cnrrobertson commented
@conda-forge/help-r, ready for review!

2024-07-31 08:42 UTC, mfansler requested changes
Thanks for adding this! ❤️ 

Couple touch ups, but otherwise looks good.

2024-07-31 08:42 UTC, mfansler commented on recipes/r-fpp3/meta.yaml
> +    https://OTexts.com/fpp3/
Split URLs:

```suggestion
  home: https://OTexts.com/fpp3/
  dev_url: https://github.com/robjhyndman/fpp3package
  doc_url: https://pkg.robjhyndman.com/fpp3package/
```

2024-07-31 08:42 UTC, mfansler commented on recipes/r-fpp3/meta.yaml
> +  license: GPL-3
SPDX

```suggestion
  license: GPL-3.0-only
```

2024-08-08 07:35 UTC, mfansler approved these changes

2024-08-08 07:35 UTC, merged