Adding spaceprime
conda-forge/staged-recipes pull request #27252
Opened 2024-08-12 19:16 UTC by connor-french

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2025-04-29 10:36 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint --conda-forge .` from the recipe directory. You can also examine the [workflow logs](https://github.com/conda-forge/conda-forge-webservices/actions/runs/14729160538) for more detail.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/14729160538](https://github.com/conda-forge/conda-forge-webservices/actions/runs/14729160538). Examine the logs at this URL for more detail.</sub>

2026-05-05 09:58 UTC, connor-french commented
Refreshed this PR — the branch has been rebased on the latest `main`, and the recipe rewritten in the rattler-build `recipe.yaml` format and bumped to v0.0.6 (sdist sha256 `959c2385fa13fce8e24e712aab8d61db55beea1ee5cea2691b1a324be7935eeb`).

The diff is now scoped strictly to `recipes/spaceprime/recipe.yaml` — no changes outside the recipes directory. Ready for re-review whenever someone has a moment, thanks!

2026-05-05 14:48 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/spaceprime/recipe.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/spaceprime/recipe.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use the pin python ${{ python_min }}.* for the `python` entry.
   - For the `run` section of the recipe, you should usually use the pin python >=${{ python_min }} for the `python` entry.
   - For the `tests[].python.python_version` or `tests[].requirements.run` section of the recipe, you should usually use the pin `python_version: ${{ python_min }}.*` or `python ${{ python_min }}.*` for the `python_version` or `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/25383441468](https://github.com/conda-forge/conda-forge-webservices/actions/runs/25383441468). Examine the logs at this URL for more detail.</sub>

2026-05-05 15:10 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/spaceprime/recipe.yaml```) and found some lint.

Here's what I've got...


For **recipes/spaceprime/recipe.yaml**:

 * ❌ Non noarch packages should have python requirement without any version constraints.
 * ❌ Non noarch packages should have python requirement without any version constraints.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/25391874167](https://github.com/conda-forge/conda-forge-webservices/actions/runs/25391874167). Examine the logs at this URL for more detail.</sub>

2026-05-05 17:42 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/spaceprime/recipe.yaml```) and found it was in an excellent condition.

2026-05-05 18:50 UTC, connor-french commented
@conda-forge-admin please ping staged-recipes. After being stale for quite some time, I've revived this branch and it now passes the CI tests

2026-05-05 18:58 UTC, matthewfeickert requested changes
Nice to see a revival. 👍 A few revision requests and a question though.

2026-05-05 18:58 UTC, matthewfeickert commented on recipes/spaceprime/recipe.yaml
> +  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
Remove `name` from context given https://github.com/conda-forge/conda-forge.github.io/issues/2712

```suggestion
context:
  version: "0.0.6"

package:
  name: spaceprime
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/spaceprime/spaceprime-${{ version }}.tar.gz
```

2026-05-05 18:58 UTC, matthewfeickert commented on recipes/spaceprime/recipe.yaml
> +    - python
c.f. https://conda-forge.org/docs/maintainer/example_recipes/pure-python/

```suggestion
    - python ${{ python_min }}.*
    - pip
    - hatchling >=1.12.0
  run:
    - python >=${{ python_min }}
```

2026-05-05 18:58 UTC, matthewfeickert commented on recipes/spaceprime/recipe.yaml
> +        - spaceprime
c.f. https://conda-forge.org/docs/maintainer/example_recipes/pure-python/

```suggestion
        - spaceprime
      python_version:
        - ${{ python_min }}.*
        - "*"
```

2026-05-05 18:58 UTC, matthewfeickert commented on recipes/spaceprime/recipe.yaml
> +      pip_check: false
Why is `pip_check` skipped?

2026-05-05 23:33 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/spaceprime/recipe.yaml```) and found some lint.

Here's what I've got...


For **recipes/spaceprime/recipe.yaml**:

 * ❌ Non noarch packages should have python requirement without any version constraints.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/25408095900](https://github.com/conda-forge/conda-forge-webservices/actions/runs/25408095900). Examine the logs at this URL for more detail.</sub>

2026-05-05 23:42 UTC, connor-french commented on recipes/spaceprime/recipe.yaml
> +      pip_check: false
The [newick package](https://pypi.org/project/newick/), which our main dependency msprime depends on, doesn't have a conda-forge recipe. This causes the pip check to fail. Given that our package is dependency-heavy and relies on some non-python packages for geospatial operations as well, we're recommending all users install via conda rather than pip, similar to the decision made by the authors of [shadie, which also depends on msprime](https://github.com/conda-forge/staged-recipes/pull/25855#issuecomment-2042985066).

2026-05-05 23:47 UTC, connor-french commented on recipes/spaceprime/recipe.yaml
> +        - spaceprime
@matthewfeickert could this change have led to the linting error now being reported? I'm having trouble finding the backtrace of the error, but it appeared after committing this correction. 

p.s. I appreciate your effort in reviewing my recipe!

2026-05-06 00:12 UTC, matthewfeickert requested changes

2026-05-06 00:12 UTC, matthewfeickert commented on recipes/spaceprime/recipe.yaml
> +    - win
```suggestion
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
```

> could this change have led to the linting error now being reported? I'm having trouble finding the backtrace of the error, but it appeared after committing this correction.

Ah, I missed that your recipe wasn't `noarch`

https://conda-forge.org/docs/maintainer/example_recipes/pure-python/#the-build-section

https://github.com/connor-french/spaceprime is pure-Python so it is preferable to have your recipe be `noarch`. However, `noarch` also can't have platform `skips`. Is the reason that you were originally skipping Windows because there is a dependency that doesn't exist on `win-64`? Or is there a fundamental build issue?

2026-05-06 00:12 UTC, matthewfeickert commented on recipes/spaceprime/recipe.yaml
> +      pip_check: false
> The [newick package](https://pypi.org/project/newick/), which our main dependency msprime depends on, doesn't have a conda-forge recipe.

Hm. That's not good. A requirement of conda-forge is that all of your dependencies _also_ exist on conda-forge.

https://github.com/conda-forge/staged-recipes/blob/2ded552bbd2a45a2de83d311e37586809e719cec/README.md#L296-L300

Which as @synapticarbors pointed out in https://github.com/conda-forge/staged-recipes/pull/25855#issuecomment-2023219932 should be addressed to resolve https://github.com/conda-forge/msprime-feedstock/issues/64.

@connor-french @conda-forge/msprime @conda-forge/shadie do you know the maintainers of https://gitlab.mpcdf.mpg.de/dlce-eva/python-newick? Regardless, I would suggest contacting them and asking if they would be willing to contribute `newick` to conda-forge to resolve this. `newick` is a pure-Python recipe and should be straightforward.

If this is an insurmountable challenge then we can discuss more (as you pointed out in the case of `shadie`), but this would be the solution that benefits the most feedstocks and ensures that conda-forge is not distributing broken software.

I'll also point out that `newick` has an infrequent release cycle (https://gitlab.mpcdf.mpg.de/dlce-eva/python-newick/-/tags) so submitting the recipe yourselves would be a low maintenance burden.

2026-05-06 05:16 UTC, matthewfeickert commented on recipes/spaceprime/recipe.yaml
> +      pip_check: false
Given https://github.com/conda-forge/msprime-feedstock/issues/64#issuecomment-4384856169 I think the sustainable solution is to:
1. For the time being, patch `newick` out of the `msprime` `v1.4.1` feedstock recipe (c.f. https://github.com/conda-forge/msprime-feedstock/issues/64#issuecomment-4385222771)
   - This alone is enough to make `msprime`, `shadie`, and `spaceprime` able to run `pip check`.
3. Have `msprime` have `newick` become an optional dependency available by an extra (for Python packages) in a PR to its upstream source https://github.com/tskit-dev/msprime.
4. The next release of `msprime` that includes those changes will require the feedstock patch (from 1.) to be dropped, but that's a trivial change that can get flagged.

2026-05-07 21:05 UTC, matthewfeickert requested changes

2026-05-07 21:05 UTC, matthewfeickert commented on recipes/spaceprime/recipe.yaml
> +      pip_check: false
```suggestion
      pip_check: true
```

@connor-french Now that https://github.com/conda-forge/msprime-feedstock/issues/64 has been resolved and there is a build of `msprime` that includes `newick`

```console
$ pixi search msprime
Using channels: conda-forge
msprime-1.4.1-py311ha7a362d_1 (+ 47 builds)
-------------------------------------------

Name                msprime
Version             1.4.1
Build               py311ha7a362d_1
Size                456.83 KiB
License             GPL-3.0-or-later
Timestamp           2026-05-07 09:27:32 UTC
Subdir              osx-arm64
File Name           msprime-1.4.1-py311ha7a362d_1.conda
URL                 https://conda.anaconda.org/conda-forge/osx-arm64/msprime-1.4.1-py311ha7a362d_1.conda
MD5                 044c683204a487eedc8dc3d185558ff4
SHA256              485626cf76409f1f14120031aeadf4c9297908990a416b02e0faf8b509a841c8

Dependencies:
 - __osx >=11.0
 - demes >=0.2
 - gsl >=2.7,<2.8.0a0
 - newick
 - numpy >=1.23,<3
 - python >=3.11,<3.12.0a0
 - python >=3.11,<3.12.0a0 *_cpython
 - python_abi 3.11.* *_cp311
 - tskit >=1.0

Run exports: not available in repodata
...
```

I think that if these revisions suggestions are applied this should be good to go.

2026-05-08 12:43 UTC, connor-french commented on recipes/spaceprime/recipe.yaml
> +    - win
@matthewfeickert the issue stemmed from our dependency on scikit-allel, which skips windows in their feedstock. I initially thought to just skip win-64 ourselves, but after digging into [scikit-allel's recipe](https://github.com/conda-forge/scikit-allel-feedstock/blob/main/recipe/meta.yaml) it seems like it was from an outdated issue with one of their dependencies, so I opened [an issue](https://github.com/conda-forge/scikit-allel-feedstock/issues/49) on their feedstock to hopefully resolve it.

2026-05-08 17:11 UTC, matthewfeickert requested changes

2026-05-08 17:11 UTC, matthewfeickert commented on recipes/spaceprime/recipe.yaml
> +  version: "0.0.6"
```suggestion
context:
  version: "0.0.6"
  python_min: "3.11"
```

Given 

```
Error:   × Test failed: failed to setup test environment:   × Cannot solve the
  │ request because of: spaceprime ==0.0.6 h65ba511_0 cannot
  │   │ be installed because there are no viable options:
  │   │ └─ spaceprime 0.0.6 would require
  │   │    └─ msprime >=1.4.1, which cannot be installed because there are no
  │   │ viable options:
  │   │       └─ msprime 1.4.1 | 1.4.1 | 1.4.1 | 1.4.1 | 1.4.1 | 1.4.1 | 1.4.1
  │ |
  │   │ 1.4.1 would require
  │   │          └─ python >=3.11,<3.12.0a0, for which no candidates were
  │ found.
  │   │ The following packages are incompatible
  │   │ └─ spaceprime ==0.0.6 h65ba511_0 cannot be installed because there are
  │ no
  │   │ viable options:
  │   │    └─ spaceprime 0.0.6 | 0.0.6 is excluded because due to strict
  │ channel
  │   │ priority not using this option from: 'file:///home/conda/staged-
  │ recipes/
  │   │ build_artifacts/'
  │   │
  │ 
```

2026-05-08 17:11 UTC, matthewfeickert commented on recipes/spaceprime/recipe.yaml
> +    - win
In these situations of a missing dependency on Windows we allow for `noarch: python` to still be used, as that dependency could be added in the future. So even without `scikit-allel` ready now for Windows you can proceed with moving to `noarch: python`.

2026-05-08 21:03 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/spaceprime/recipe.yaml```) and found it was in an excellent condition.

2026-05-08 21:26 UTC, connor-french commented on recipes/spaceprime/recipe.yaml
> +    - win
Okay great, thank you! So is it okay that the CI is failing for the Windows build, but succeeding for Linux and OSX?

2026-05-08 21:44 UTC, matthewfeickert commented on recipes/spaceprime/recipe.yaml
> +    - win
> So is it okay that the CI is failing for the Windows build, but succeeding for Linux and OSX?

Yes, given that this is a missing conda-forge build dependency issue for a pure-Python package and not a fundamentally broken issue with the build of the package itself.

```
Error:   × Test failed: failed to setup test environment:   × Cannot solve the
  │ request because of: The following packages are
  │   │ incompatible
  │   │ └─ spaceprime ==0.0.6 pyhde2aa0e_0 cannot be installed because there
  │ are
  │   │ no viable options:
  │   │    ├─ spaceprime 0.0.6 would require
  │   │    │  ├─ scikit-allel *, which cannot be installed because there are
  │ no
  │   │ viable options:
  │   │    │  │  ├─ scikit-allel 1.3.5 | 1.3.6 | 1.3.7 would require
  │   │    │  │  │  ├─ python_abi 3.10.* *_cp310, which can be installed with
  │ any
  │   │ of the following options:
  │   │    │  │  │  │  └─ python_abi 3.10
  │   │    │  │  │  └─ python >=3.10,<3.11.0a0, which cannot be installed
  │ because
```

https://github.com/conda-forge/scikit-allel-feedstock used to have Windows builds but currently doesn't. So it is hypothetically possible that it could again in the future.

2026-05-08 21:45 UTC, matthewfeickert approved these changes
LGTM now. 👍 Windows builds are failing given https://github.com/conda-forge/scikit-allel-feedstock no longer has `win-64` builds, but the rest is viable `noarch: python`, so this is allowable.

2026-05-08 21:53 UTC, merged

2026-05-08 22:03 UTC, connor-french commented
> LGTM now. 👍 Windows builds are failing given https://github.com/conda-forge/scikit-allel-feedstock no longer has `win-64` builds, but the rest is viable `noarch: python`, so this is allowable.

Thanks for all of your help!