Add r-ftrading
conda-forge/staged-recipes pull request #27306
Opened 2024-08-19 12:02 UTC by janjagusch

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-08-19 12:05 UTC, janjagusch commented
Rendered with https://github.com/bgruening/conda_r_skeleton_helper/commit/0c460dedff2e96548d526c06f1fe466769463160.

2024-09-05 12:23 UTC, mfansler requested changes
Good, just need to bundle extra license file.

2024-09-05 12:23 UTC, mfansler commented on recipes/r-ftrading/meta.yaml
> +    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
There is any additional copyright notice that we should explicitly bundle:

```suggestion
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - inst/COPYRIGHT.html
```

2024-09-10 10:51 UTC, mfansler approved these changes

2024-09-10 10:51 UTC, merged