Add r-roi.plugin.quadprog
conda-forge/staged-recipes pull request #27309
Opened 2024-08-19 12:08 UTC by janjagusch

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-08-19 12:19 UTC, janjagusch commented
Rendered with https://github.com/bgruening/conda_r_skeleton_helper/commit/0c460dedff2e96548d526c06f1fe466769463160.

2024-08-19 12:32 UTC, janjagusch commented
@conda-forge/r, please review. The Windows build is currently failing. Happy to skip that one, but I forgot I'll let you take a closer look first.

2024-09-05 12:15 UTC, mfansler requested changes
Good, just needs license fixed.

2024-09-05 12:15 UTC, mfansler commented on recipes/r-roi.plugin.quadprog/meta.yaml
> +  license: GPL-3.0-or-later
Only see `GPL-3`, so

```suggestion
  license: GPL-3.0-only
```

2024-09-10 07:40 UTC, janjagusch commented
@mfansler, any clue why the `win-64` build is failing? Happy to skip the Windows build otherwise.

Same applies to https://github.com/conda-forge/staged-recipes/pull/27309 and https://github.com/conda-forge/staged-recipes/pull/27308#pullrequestreview-2282744327.

```
Encountered problems while solving:
  - package m2-conda-epoch-20230914-0_x86_64 has constraint msys2-conda-epoch <0.0a0 conflicting with msys2-conda-epoch-20160418-1
  - package m2w64-bwidget-1.9.10-2 requires msys2-conda-epoch 20160418, but none of the providers can be installed
  - package m2w64-bzip2-1.0.6-6 requires msys2-conda-epoch 20160418, but none of the providers can be installed
  - package m2w64-expat-2.1.1-2 requires msys2-conda-epoch 20160418, but none of the providers can be installed
  - package m2w64-fftw-3.3.4-6 requires msys2-conda-epoch 20160418, but none of the providers can be installed
```

2024-09-10 08:05 UTC, mfansler approved these changes
Thanks for adding! ❤️

2024-09-10 08:20 UTC, mfansler commented
Hmm. This got messy because you originally had this in the commit history of `r-symphony` that I just merged.

2024-09-10 08:21 UTC, mfansler commented
You'll need to add back the build scripts.

2024-09-10 08:36 UTC, mfansler commented
> @mfansler, any clue why the `win-64` build is failing? Happy to skip the Windows build otherwise.
> 
> Same applies to #27308 and #27306.
> 
> ```
> Encountered problems while solving:
>   - package m2-conda-epoch-20230914-0_x86_64 has constraint msys2-conda-epoch <0.0a0 conflicting with msys2-conda-epoch-20160418-1
>   - package m2w64-bwidget-1.9.10-2 requires msys2-conda-epoch 20160418, but none of the providers can be installed
>   - package m2w64-bzip2-1.0.6-6 requires msys2-conda-epoch 20160418, but none of the providers can be installed
>   - package m2w64-expat-2.1.1-2 requires msys2-conda-epoch 20160418, but none of the providers can be installed
>   - package m2w64-fftw-3.3.4-6 requires msys2-conda-epoch 20160418, but none of the providers can be installed
> ```

Fine just to leave it, even with no explicit skip. It is [a known weird issue](https://github.com/conda-forge/staged-recipes/issues/25319) that seems to stem from underspecification in Windows solves when there is nothing forcing an epoch in the `build` environment, which happens with **noarch**. It is totally fine to ignore Windows failures for **noarch** recipes.

2024-09-10 10:53 UTC, mfansler approved these changes

2024-09-10 10:53 UTC, merged