Add recipe for cuda-api-wrappers
conda-forge/staged-recipes pull request #27409
Opened 2024-08-27 16:25 UTC by awvwgk

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-08-28 09:12 UTC, awvwgk commented
@conda-forge/help-c-cpp This header-only library recipe is ready for review.

2024-08-29 13:07 UTC, xhochy requested changes

2024-08-29 13:07 UTC, xhochy commented on recipes/cuda-api-wrappers/meta.yaml
> +  skip: True  # [cuda_compiler != 'None']
The failures are actually correct ;)
```suggestion
  skip: True  # [cuda_compiler == 'None']
```

2024-09-04 09:48 UTC, xhochy commented
Can you please fix the lint? Then it is good to go.

2024-09-04 11:19 UTC, awvwgk commented on recipes/cuda-api-wrappers/meta.yaml
> +  host: https://github.com/eyalroz/cuda-api-wrappers
```suggestion
  home: https://github.com/eyalroz/cuda-api-wrappers
```

2024-09-04 14:10 UTC, xhochy approved these changes

2024-09-04 14:10 UTC, merged