Added r-constructive as a package
conda-forge/staged-recipes pull request #27431
Opened 2024-08-29 18:05 UTC by thewchan

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-08-29 20:17 UTC, thewchan commented
@conda-forge/staged-recipes @conda-forge/help-r This is ready for review; though win build fails due to the same issues with other package. The package is no arch though

2024-08-30 07:40 UTC, mfansler requested changes
Thanks for submitting! ❤️ 

A few things to touch up then should be good.

2024-08-30 07:40 UTC, mfansler commented on recipes/r-constructive/meta.yaml
> +    - {{ compiler('m2w64_c') }}        # [win]
Add stdlib's:

```suggestion
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [not win]
    - {{ stdlib('m2w64_c') }}    # [not win]
```

2024-08-30 07:40 UTC, mfansler commented on recipes/r-constructive/meta.yaml
> +
Missing DSO's:

```suggestion
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

```

Note that the latest version of `conda_r_skeleton_helper` includes this by default - be sure to update your copy!

2024-08-30 07:40 UTC, mfansler commented on recipes/r-constructive/meta.yaml
> +  home: https://github.com/cynkra/constructive, https://cynkra.github.io/constructive/
Split:

```suggestion
  home: https://cynkra.github.io/constructive/
  dev_url: https://github.com/cynkra/constructive
```

2024-08-30 17:04 UTC, thewchan commented
thanks @mfansler! All good to go now I think

2024-08-31 09:23 UTC, mfansler approved these changes
Great! (Sorry about my selector typo 😳)

2024-08-31 09:24 UTC, merged