add mlwc package v.0.1.0
conda-forge/staged-recipes pull request #27461
Opened 2024-09-01 02:18 UTC by ToAmano

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-09-01 06:45 UTC, ToAmano commented
@conda-forge/help-python

ready for review! Thank you!

2024-09-01 14:30 UTC, ToAmano commented
@conda-forge/staged-recipes

ready for review! Thank you!

2024-09-02 05:28 UTC, xhochy requested changes
Please remove all commented lines and only use packages from conda-forge.

2024-09-03 10:51 UTC, ToAmano commented
@xhochy 
Thank you for reviewing. I've removed all the comments and packages except conda-forge. Please check it again.

2024-09-04 09:01 UTC, xhochy commented
If I look at the sources, it looks like this is a pure Python package, right? Then it should also be `noarch: python`.

Please also fix the inclusion of the license in the source tarball. I see you are the main author of the package, so it's better to fix it upstream instead of bundling the license with the recipe.

2024-09-07 04:35 UTC, ToAmano commented
@xhochy
Is it necessary to pass the test on `win_64`? It seems Pytorch can not be installed on win_64. 
I would appreciate any suggestion. Thank you.

2024-09-14 12:49 UTC, xhochy requested changes
It's OK for Windows to error on a missing pytorch dependency if this is noarch

2024-09-14 12:49 UTC, xhochy commented on recipes/MLWC/meta.yaml
> +    - cmake
This and boost below are typically only required foe compiled packages. Can you simply remove them?

2024-09-14 12:49 UTC, xhochy commented on recipes/MLWC/meta.yaml
> +test:
```suggestion
test:
  requires:
    - pip
```

2024-09-14 12:49 UTC, xhochy commented on recipes/MLWC/meta.yaml
> +  commands:
```suggestion
  commands:
    - pip check
```

2024-09-21 20:29 UTC, xhochy requested changes

2024-09-21 20:29 UTC, xhochy commented on recipes/MLWC/meta.yaml
> +    - ase
This should be removed
```suggestion
```

2024-09-23 02:41 UTC, ToAmano commented
@xhochy 

Ready for review. Thank you.

2024-09-25 13:49 UTC, xhochy approved these changes

2024-09-25 13:50 UTC, merged