Added R-gsignal recipe
conda-forge/staged-recipes pull request #27475
Opened 2024-09-03 19:10 UTC by dipterix

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-09-03 20:56 UTC, dipterix commented
@conda-forge/help-r Could you help me with the `missing_dso_whitelist` issue here?

```
ERROR (r-gsignal,lib/R/library/gsignal/libs/x64/gsignal.dll): $RPATH/R.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.
```

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1018035&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=7c0f8eae-6d6f-51bf-636f-73a1a7fb1bc4&l=1915

2024-09-04 11:37 UTC, mfansler commented
Note that the latest `conda_r_skeleton_helper` (what is [recommended for CRAN packages](https://conda-forge.org/docs/maintainer/adding_pkgs/#generating-the-recipe)) includes a DSO whitelist.

2024-09-05 01:41 UTC, dipterix commented
@conda-forge/help-r, ready for review!

2024-09-05 07:13 UTC, mfansler requested changes
Thanks for submitting this! ❤️ 

Mostly just some style changes (we prefer not to commit all the skeleton comments), plus a license adjustment.

In the future, please use `conda_r_skeleton_helper` for CRAN packages.

2024-09-05 07:13 UTC, mfansler commented on recipes/r-gsignal/build.sh
> +# for a list of environment variables that are set during the build process.
```suggestion
```

2024-09-05 07:13 UTC, mfansler commented on recipes/r-gsignal/build.sh
> +# https://github.com/jeroen/autobrew/issues/3
```suggestion
```

2024-09-05 07:13 UTC, mfansler commented on recipes/r-gsignal/build.sh
> +grep -va '^Priority: ' DESCRIPTION.old > DESCRIPTION
This is old boilerplate - safe to remove:

```suggestion
```

2024-09-05 07:13 UTC, mfansler commented on recipes/r-gsignal/meta.yaml
> +  # curl -sL https://cran.r-project.org/src/contrib/gsignal_0.3-5.tar.gz | openssl sha256
```suggestion
```

2024-09-05 07:13 UTC, mfansler commented on recipes/r-gsignal/meta.yaml
> +  # If this is a new build for the same version, increment the build number.
```suggestion
```

2024-09-05 07:13 UTC, mfansler commented on recipes/r-gsignal/meta.yaml
> +  # This is required to make R link correctly on Linux.
```suggestion
```

2024-09-05 07:13 UTC, mfansler commented on recipes/r-gsignal/meta.yaml
> +  # DSO whitelist on windows, could be caused by importing other base-R packages
```suggestion
```

2024-09-05 07:13 UTC, mfansler commented on recipes/r-gsignal/meta.yaml
> +# Suggests: knitr, rmarkdown, testthat, ggplot2, gridExtra, microbenchmark, imager, covr
```suggestion
```

2024-09-05 07:13 UTC, mfansler commented on recipes/r-gsignal/meta.yaml
> +
```suggestion
```

2024-09-05 07:13 UTC, mfansler commented on recipes/r-gsignal/meta.yaml
> +
```suggestion
```

2024-09-05 07:13 UTC, mfansler commented on recipes/r-gsignal/meta.yaml
> +    # You can put additional test commands to be run here.
```suggestion
```

2024-09-05 13:41 UTC, dipterix commented
@mfansler I commit all the changes that you have suggested. Sorry I didn't notice that each commit will trigger github action check and is non-stoppable.... Now it's all over the place : O

2024-09-05 14:06 UTC, mfansler approved these changes
Thanks for submitting! ❤️

2024-09-05 14:07 UTC, merged

2024-09-11 08:35 UTC, gjmvanboxtel commented
I confirm that I would like to be added as the maintainer