ADD: add radarx recipe to conda-forge
conda-forge/staged-recipes pull request #27508
Opened 2024-09-07 03:09 UTC by syedhamidali

This repository is very active, so if you need help with a PR, please let the
right people know. There are language-specific teams for reviewing recipes.

| Language        | Name of review team           |
| --------------- | ----------------------------- |
| python          | `@conda-forge/help-python`    |

Description

This PR adds the recipe for radarx, a Python-based radar data toolkit built using xarray structures. The current version is 0.1.dev2, and the recipe is intended to make radarx available via the conda-forge channel.

Checklist

	•	License file is included in the package.
	•	The source is from the official release: [radarx-0.1.dev2](https://pypi.org/project/radarx/).
	•	The package follows conda-forge guidelines and doesn’t vendor other packages.
	•	Build number is set to 0.

2024-09-08 21:31 UTC, syedhamidali commented
@conda-forge/help-python, ready for review!

2024-09-09 17:38 UTC, xhochy requested changes

2024-09-09 17:38 UTC, xhochy commented on recipes/radarx/meta.yaml
> +  sha256: {{ sha256 }}
Please write it here directly and avoid unnecessary Jinja.

2024-09-09 17:38 UTC, xhochy commented on recipes/radarx/meta.yaml
> +{% set version = "0.1.3.dev0" %}
Can you use a release version here, please.

2024-09-09 17:38 UTC, xhochy commented on recipes/radarx/meta.yaml
> +test:
```suggestion
test:
  requires:
    - pip
  commands:
    - pip check
```

2024-09-09 18:55 UTC, syedhamidali commented
@xhochy Thank you for your feedback. I have made all the suggested changes. Could you please review it again?

2024-09-10 16:06 UTC, merged