add ablang
conda-forge/staged-recipes pull request #27522
Opened 2024-09-09 12:10 UTC by mbestipa

- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-09-09 12:11 UTC, mbestipa commented
I confirm I'm willing to be listed here as a maintainer

2024-09-09 16:38 UTC, mbestipa commented
@conda-forge/help-python, ready for review

2024-09-09 17:35 UTC, xhochy requested changes

2024-09-09 17:35 UTC, xhochy commented on recipes/ablang2/conda_build_config.yaml
> +channel_sources:
Please remove this file. Packages on conda-forge should only depend on conda-forge packages.

2024-09-09 17:35 UTC, xhochy commented on recipes/ablang2/meta.yaml
> +    - python >3.6
```suggestion
    - python >=3.6
```
Or should it be 3.7?

2024-09-09 17:35 UTC, xhochy commented on recipes/ablang2/meta.yaml
> +    - python >3.6
```suggestion
    - python >=3.6
```

2024-09-09 17:35 UTC, xhochy commented on recipes/ablang2/meta.yaml
> +    - pytorch >1.9
Same

2024-09-10 11:45 UTC, mbestipa commented
@xhochy I've changed things as the windows build fails without using other channels (no pytorch v2), I'm fine with things not being available in windows

2024-09-19 07:03 UTC, mbestipa commented
@conda-forge/help-python can this be reviewed again?

2024-09-19 07:09 UTC, ocefpaf commented on recipes/ablang2/meta.yaml
> +  skip: True  # [win]
It is OK for noarch package to fails on Windows with a missing dependency. We prefer noarch b/c it is faster to build and the package will be ready when the missing dependency is available on Windows.

2024-09-20 08:54 UTC, mbestipa commented
@ocefpaf is this to your liking?

2024-09-20 09:50 UTC, ocefpaf commented
> @ocefpaf is this to your liking?

My liking doesn't matter here 😄 . But we do need to have some recipe consistency for out build system.

2024-09-20 09:50 UTC, merged

2024-09-20 13:40 UTC, mbestipa commented
> > @ocefpaf is this to your liking?
> 
> My liking doesn't matter here 😄 . But we do need to have some recipe consistency for out build system.

of course, thanks for reviewing it.