Add wrapspawner
conda-forge/staged-recipes pull request #27550
Opened 2024-09-11 17:54 UTC by opoplawski

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-09-11 20:03 UTC, opoplawski commented
@conda-forge/help-python, ready for review!

2024-09-12 02:00 UTC, synapticarbors requested changes

2024-09-12 02:00 UTC, synapticarbors commented on recipes/wrapspawner/meta.yaml
> +  license_file: LICENSE
Add:

`dev_url: https://github.com/jupyterhub/wrapspawner` to `about`.

2025-02-13 20:13 UTC, opoplawski commented on recipes/wrapspawner/meta.yaml
> +  host:
Done, I think

2025-02-13 20:13 UTC, opoplawski commented on recipes/wrapspawner/meta.yaml
> +  license_file: LICENSE
Added

2025-07-31 22:42 UTC, opoplawski commented
@conda-forge/help-python, ready for review!

2025-08-04 17:10 UTC, ocefpaf commented on recipes/wrapspawner/meta.yaml
> +    - python >=3.7
```suggestion
    - python {{ python_min }}
```

2025-08-04 17:10 UTC, ocefpaf commented on recipes/wrapspawner/meta.yaml
> +    - python >=3.7
```suggestion
    - python >={{ python_min }}
```

2025-08-04 17:10 UTC, ocefpaf commented on recipes/wrapspawner/meta.yaml
> +    - tornado
```suggestion
    - tornado
    - python {{ python_min }}
```

2025-08-04 17:18 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/wrapspawner/meta.yaml```) and found it was in an excellent condition.

2025-08-04 17:23 UTC, opoplawski commented
Sorry for not noticing the old python version stuff sooner.

2025-08-04 17:47 UTC, merged