recipe for trivy
conda-forge/staged-recipes pull request #27577
Opened 2024-09-13 14:01 UTC by mediocretech

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-09-13 15:07 UTC, mediocretech commented
@conda-forge/help-go ready for review

2024-09-14 16:44 UTC, xhochy requested changes
Please add go-licenses as done in other go recipes and also copy the build command from there to enable cross-compiling.

2024-09-14 16:44 UTC, xhochy commented on recipes/trivy/meta.yaml
> +    - {{ compiler('go') }}
```suggestion
    - {{ compiler('go-nocgo') }}
```

2024-09-27 08:28 UTC, xhochy requested changes

2024-09-27 08:28 UTC, xhochy commented on recipes/trivy/meta.yaml
> +    - go-licenses save ./cmd/trivy --save_path licenses --ignore github.com/csaf-poc/csaf_distribution --ignore modernc.org/mathutil
You would need to add the two ignored licenses manually to the recipe directory.

2024-10-10 00:54 UTC, mediocretech commented on recipes/trivy/meta.yaml
> +    - go-licenses save ./cmd/trivy --save_path licenses --ignore github.com/csaf-poc/csaf_distribution --ignore modernc.org/mathutil
Thanks @xhochy.  I'm not too familiar with this paradigm, let me know if further changes are needed.

2024-10-10 08:58 UTC, xhochy approved these changes
Licenses look good

2024-10-10 08:59 UTC, merged