introduce sqlite-vec
conda-forge/staged-recipes pull request #27635
Opened 2024-09-19 14:33 UTC by lucasew

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-09-19 14:34 UTC, lucasew commented
I have something already but it is failing at a failed include of `#include "sqlite3ext.h"` and I have no idea of what to try now

2024-09-19 14:41 UTC, lucasew commented
cc @conda-forge/help-c-cpp

2024-09-20 06:46 UTC, wolfv commented
Hi @lucasew - I think you are missing sqlite in your `host` dependencies :) 

The requirements are:

- build: tools that need to _run_ at build time (compilers, cmake, make, ...)
- host: libraries that you want to link with or header files to use (sqlite, for example!)
- run: libraries and run-time dependencies (these are _not_ installed at build time)

2024-09-26 18:12 UTC, lucasew commented
It seems to be working, but usability wise one would need to load the extension by passing the full absolute path to the .so file.

Conda exposes the prefix root in CONDA_PREFIX tho

2024-11-24 20:22 UTC, carterbox commented
> It seems to be working, but usability wise one would need to load the extension by passing the full absolute path to the .so file.

Maybe there is a specific directory for sqlite extension modules? Install there instead? Maybe @conda-forge/sqlite knows?

2024-11-24 20:23 UTC, carterbox requested changes
Missing working build for Windows and OSX.

2025-10-19 11:05 UTC, closed without merging