adding efmtool_link, optlang_enumerator
conda-forge/staged-recipes pull request #27684
Opened 2024-09-24 08:55 UTC by axelvonkamp

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-09-24 09:01 UTC, axelvonkamp commented
I am willing to be listed as maintainer.

2024-09-24 09:03 UTC, axelvonkamp commented
@conda-forge/help-python, ready for review!
I have run  ```conda smithy recipe-lint --conda-forge .``` on both recipes and get " . is in fine form". I cann0t figure out why the conda-forge-linter here gives an error.

2024-09-30 05:22 UTC, xhochy requested changes
To fix the linter, merge main.

2024-09-30 05:22 UTC, xhochy commented on recipes/efmtool_link/meta.yaml
> +    - efmtool_link
Please add a pip check call here

2024-09-30 05:22 UTC, xhochy commented on recipes/optlang_enumerator/meta.yaml
> +    - optlang_enumerator
Pip check

2024-10-18 14:37 UTC, axelvonkamp commented on recipes/efmtool_link/meta.yaml
> +    - efmtool_link
Done.

2024-10-18 14:37 UTC, axelvonkamp commented on recipes/optlang_enumerator/meta.yaml
> +    - optlang_enumerator
Done

2024-11-15 16:53 UTC, merged