add `speedscope`
conda-forge/staged-recipes pull request #27697
Opened 2024-09-25 13:30 UTC by moritzwilksch

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-09-25 13:30 UTC, moritzwilksch commented
@conda-forge/help-nodejs is this how you package npm packages?

2024-09-25 13:44 UTC, xhochy requested changes

2024-09-25 13:44 UTC, xhochy commented on recipes/speedscope/build.sh
> +pnpm install --prod
```suggestion
pnpm import
pnpm install --prod
pnpm pack
npm install -g speedscope-${PKG_VERSION}.tar.gz
```

2024-09-25 13:44 UTC, xhochy commented on recipes/speedscope/build.sh
> +NPM_CONFIG_USERCONFIG=/tmp/nonexistentrc
```suggestion
export NPM_CONFIG_USERCONFIG=/tmp/nonexistentrc
```

2024-09-25 14:30 UTC, moritzwilksch commented
where does npm install the package? Do we need to move some things around?

2024-09-25 15:17 UTC, xhochy commented on recipes/speedscope/build.sh
> +pnpm install --prod
Seems like we need all the dependencies.
```suggestion
pnpm install
```

2024-09-25 15:17 UTC, xhochy commented
> where does npm install the package? Do we need to move some things around?

It should put it into $PREFIX with the binary in `$PREFIX/bin`. Once the jobs is successful, you can look into the CI logs for the content of the package.

2024-09-25 16:00 UTC, moritzwilksch commented
according to [this](https://github.com/protobufjs/protobuf.js/issues/1104) we might need to patch `package.json` and `scripts/build-release.sh`

2024-09-25 16:08 UTC, xhochy commented
CI needs a compiler, but the osx job has the same error as you probably have locally. @JannikWibkerQC can probably help you do the patching correctly.

2024-09-26 09:12 UTC, JannikWibkerQC commented
`speedscope` has a `prepack` script which is a hook being executed whenever `(p)npm pack` (or `(p)npm publish`), thus running `pnpm pack` triggers a build. I tried it locally but it fails. I'd maybe suggest just installing the package using `npm install -g speedscope@{PKG_VERSION}` as this won't run into those issues.

Afterwards you'd still do `pnpm install --prod` and everything pnpm-licenses related.


Not sure what the opinion is on installing from the npm registry vs. building it manually and installing it from there though. [`pnpm`](https://github.com/conda-forge/pnpm-feedstock/blob/main/recipe/build.sh#L24), [`prettier`](https://github.com/conda-forge/prettier-feedstock/blob/main/recipe/build.sh#L19) and [`marp-cli`](https://github.com/conda-forge/marp-cli-feedstock/blob/main/recipe/build.sh#L17
) all install from the registry while [`pnpm-licenses`](https://github.com/conda-forge/pnpm-licenses-feedstock/blob/main/recipe/build.sh#L24) gets build using conda-build.

It is to be noted that building pnpm-licenses using `build.sh` / `bld.bat` was made easier by writing the tool itself and knowing how the build system works 😅 


If you go with the npm registry approach this should work:

```bash
#!/bin/sh

set -exuo pipefail

if [[ "${target_platform}" == "osx-arm64" ]]; then
    export npm_config_arch="arm64"
fi
# Don't use pre-built gyp packages
export npm_config_build_from_source=true

rm $PREFIX/bin/node
ln -s $BUILD_PREFIX/bin/node $PREFIX/bin/node

# install speedscope from the npm registry
# all things coming after this are just concerned with generating the third-party-licenses file
export NPM_CONFIG_USERCONFIG=/tmp/nonexistentrc
npm install -g speedscope@${PKG_VERSION}

pnpm import
pnpm install --prod

# generate third party licenses file
pnpm licenses list --json --prod | pnpm-licenses generate-disclaimer --prod --json-input --output-file=third-party-licenses.txt
```

Like @xhochy mentioned you might need a c compiler:

```yaml
requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
    - nodejs
```

2024-09-26 14:45 UTC, moritzwilksch commented
@conda-forge-admin, please rerender

2024-09-27 08:24 UTC, xhochy approved these changes
If you can build from the source, we would prefer that as it is more self-contained (well npm packages are never self-contained).

2024-09-27 08:24 UTC, merged