Adding cb-clipboard v0.9.0.1
conda-forge/staged-recipes pull request #27710
Opened 2024-09-27 17:33 UTC by eunos-1128

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-09-28 10:49 UTC, eunos-1128 commented
@Slackadays

Could you agree to being one of the maintainers for this conda package as Clipborad author?

2024-09-28 14:10 UTC, Slackadays commented
I can be one of the maintainers

2024-09-28 15:48 UTC, eunos-1128 commented
> I can be one of the maintainers

Thank you!

2024-09-28 15:50 UTC, eunos-1128 commented
@conda-forge/help-c-cpp, , ready for review!

2024-10-10 11:26 UTC, Slackadays commented
And we thought AI was going to take over the world

2024-10-10 12:22 UTC, xhochy requested changes

2024-10-10 12:22 UTC, xhochy commented on recipes/cb-clipboard/recipe.yaml
> +  author: Slackadays
```suggestion
```

2024-10-10 12:22 UTC, xhochy commented on recipes/cb-clipboard/recipe.yaml
> +    - ${{ author }}
```suggestion
    - Slackadays
```

2024-10-10 12:22 UTC, xhochy commented on recipes/cb-clipboard/build.sh
> +    export MACOSX_DEPLOYMENT_TARGET=11.0
Please don't set that manually but rather use the `c_stdlib_version`
```suggestion
```

2024-10-10 12:22 UTC, xhochy commented on recipes/cb-clipboard/build.bat
> +cmake --build . --config Release --parallel %NUMBER_OF_PROCESSORS%
```suggestion
cmake --build . --config Release --parallel %CPU_COUNT%
```

2024-10-10 12:22 UTC, xhochy commented on recipes/cb-clipboard/build.sh
> +export CXXFLAGS="${CXXFLAGS/-Os/-O3}"
`-Os` should not be part of these flags
```suggestion
```

2024-10-10 12:22 UTC, xhochy commented on recipes/cb-clipboard/build.sh
> +    export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
This should be set to a different location by the build tool
```suggestion
```

2024-10-10 12:22 UTC, xhochy commented on recipes/cb-clipboard/build.sh
> +    cmake \
```suggestion
    cmake $CMAKE_ARGS \
```

2024-10-10 12:22 UTC, xhochy commented on recipes/cb-clipboard/build.sh
> +    cmake \
```suggestion
    cmake $CMAKE_ARGS \
```

2024-10-10 12:22 UTC, xhochy commented on recipes/cb-clipboard/recipe.yaml
> +        - wayland
They should come in via their `run_exports`
```suggestion
```

2024-10-11 18:35 UTC, xhochy requested changes

2024-10-11 18:35 UTC, xhochy commented on recipes/cb-clipboard/build.bat
> +    -DCMAKE_INSTALL_PREFIX=%PREFIX% ..
```suggestion
    -DOPENSSL_ROOT_DIR=%LIBRARY_PREFIX%^
    -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ..
```

2024-10-11 18:35 UTC, xhochy commented on recipes/cb-clipboard/build.sh
> +        -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
Don't set that explicitly, use `c_stdlib_version`
```suggestion
```

2024-10-11 19:41 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/cb-clipboard/recipe.yaml```) and found it was in an excellent condition.

2024-10-11 20:08 UTC, Slackadays commented
@eunos-1128 you can do it! 🥇

2024-10-12 08:38 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/cb-clipboard/recipe.yaml```) and found some lint.

Here's what I've got...


For **recipes/cb-clipboard/recipe.yaml**:

 * This recipe is using a compiler, which now requires adding a build dependence on `${{ stdlib("c") }}` as well. Note that this rule applies to each output of the recipe using a compiler. For further details, please see https://github.com/conda-forge/conda-forge.github.io/issues/2102.

2024-10-12 09:01 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/cb-clipboard/recipe.yaml```) and found it was in an excellent condition.

2024-10-12 09:41 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I Failed to even lint the recipe, probably because of a conda-smithy
bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint --conda-forge .` from the recipe directory.


<sub>This message was generated by GitHub actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/11304641991](https://github.com/conda-forge/conda-forge-webservices/actions/runs/11304641991).</sub>

2024-10-12 09:51 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/cb-clipboard/recipe.yaml```) and found it was in an excellent condition.

2024-10-12 10:44 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/cb-clipboard/recipe.yaml```) and found some lint.

Here's what I've got...


For **recipes/cb-clipboard/recipe.yaml**:

 * In your conda_build_config.yaml, please change the name of `MACOSX_DEPLOYMENT_TARGET`, to `c_stdlib_version`!

2024-10-12 10:49 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/cb-clipboard/recipe.yaml```) and found it was in an excellent condition.

2024-10-12 10:59 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I Failed to even lint the recipe, probably because of a conda-smithy
bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint --conda-forge .` from the recipe directory.


<sub>This message was generated by GitHub actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/11305091180](https://github.com/conda-forge/conda-forge-webservices/actions/runs/11305091180).</sub>

2024-10-12 11:03 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/cb-clipboard/recipe.yaml```) and found it was in an excellent condition.

2024-10-12 11:44 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/cb-clipboard/recipe.yaml```) and found some lint.

Here's what I've got...


For **recipes/cb-clipboard/recipe.yaml**:

 * Conflicting specification for minimum macOS deployment target!
If your conda_build_config.yaml sets `MACOSX_DEPLOYMENT_TARGET`, please change the name of that key to `c_stdlib_version`!
Continuing with `max(c_stdlib_version, MACOSX_DEPLOYMENT_TARGET)`.

2024-10-12 11:49 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/cb-clipboard/recipe.yaml```) and found it was in an excellent condition.

2024-10-13 16:19 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I Failed to even lint the recipe, probably because of a conda-smithy
bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint --conda-forge .` from the recipe directory.


<sub>This message was generated by GitHub actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/11315889697](https://github.com/conda-forge/conda-forge-webservices/actions/runs/11315889697).</sub>

2024-10-13 16:39 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/cb-clipboard/recipe.yaml```) and found it was in an excellent condition.

2024-10-13 17:19 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/cb-clipboard/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/cb-clipboard/meta.yaml**:

 * The "test" section was expected to be a dictionary, but got a CommentedSeq.
 * The recipe must have some tests.
 * The "test" section was expected to be a dictionary, but got a CommentedSeq.

2024-10-13 17:42 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/cb-clipboard/meta.yaml```) and found it was in an excellent condition.

2024-10-13 18:01 UTC, eunos-1128 commented
I replaced `recipe.yaml` with `meta.yaml` to use conda-build instead of rattler-build because MacOS build always fails even with the config file defining `c_stdlib_version`.

2024-10-13 22:17 UTC, Slackadays commented
@xhochy The fixes have been implemented

2024-10-14 08:24 UTC, xhochy requested changes

2024-10-14 08:24 UTC, xhochy commented on recipes/cb-clipboard/build.sh
> +        -DCMAKE_OSX_DEPLOYMENT_TARGET=${MACOSX_DEPLOYMENT_TARGET} \
Please don't set this explicitly, this should come via `CMAKE_ARGS`
```suggestion
```

2024-10-14 08:50 UTC, xhochy approved these changes

2024-10-14 09:15 UTC, merged