Add vulkan-validation-layers
conda-forge/staged-recipes pull request #27755
Opened 2024-10-02 22:05 UTC by JarrettSJohnson

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-10-02 22:07 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/vulkan-validation-layers/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/vulkan-validation-layers/meta.yaml**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [25, 26, 27, 28]
 * If python is a host requirement, it should be a run requirement.

2024-10-02 22:50 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/vulkan-validation-layers/meta.yaml```) and found it was in an excellent condition.

2024-10-02 23:32 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/vulkan-validation-layers/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/vulkan-validation-layers/meta.yaml**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [22]

2024-10-03 03:12 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/vulkan-validation-layers/meta.yaml```) and found it was in an excellent condition.

2024-10-03 04:41 UTC, JarrettSJohnson commented
Ready for review, @conda-forge/help-c-cpp.

2024-10-10 10:58 UTC, xhochy requested changes

2024-10-10 10:58 UTC, xhochy commented on recipes/vulkan-validation-layers/meta.yaml
> +    - if not exist %LIBRARY_PREFIX%\\bin\\VkLayer_khronos_validation.dll exit 1  # [win]
Please also check for the library on Linux

2024-10-10 10:58 UTC, xhochy commented on recipes/vulkan-validation-layers/meta.yaml
> +build:
Please add a `run_exports`

2024-10-30 16:40 UTC, JarrettSJohnson commented
Ready for re review,  @conda-forge/help-c-cpp .

2024-11-16 16:55 UTC, xhochy requested changes

2024-11-16 16:55 UTC, xhochy commented on recipes/vulkan-validation-layers/meta.yaml
> +    - test -f $PREFIX/lib/libVkLayer_khronos_validation.so  # [linux]
```suggestion
    - test -f $PREFIX/lib/libVkLayer_khronos_validation${SHLIB_EXT}  # [unix]
```

2024-11-22 08:47 UTC, xhochy approved these changes

2024-11-22 08:48 UTC, merged