Add recipe for opensubdiv
conda-forge/staged-recipes pull request #27800
Opened 2024-10-06 17:03 UTC by traversaro

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-10-06 17:05 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/opensubdiv/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/opensubdiv/meta.yaml**:

 * This recipe is using a compiler, which now requires adding a build dependence on `{{ stdlib("c") }}` as well. Note that this rule applies to each output of the recipe using a compiler. For further details, please see https://github.com/conda-forge/conda-forge.github.io/issues/2102.

For **recipes/opensubdiv/meta.yaml**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2024-10-06 17:11 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/opensubdiv/meta.yaml```) and found it was in an excellent condition.
I do have some suggestions for making it better though...


For **recipes/opensubdiv/meta.yaml**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2024-10-06 19:25 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/opensubdiv/meta.yaml```) and found it was in an excellent condition.

2024-10-07 21:10 UTC, traversaro commented
@conda-forge/staged-recipes @conda-forge/help-c-cpp The PR is ready for review, thanks!

2024-10-10 09:13 UTC, xhochy requested changes

2024-10-10 09:13 UTC, xhochy commented on recipes/opensubdiv/meta.yaml
> +  license: LicenseRef-Pixar
https://github.com/conda-forge/license-expression-feedstock/pull/8 should solve it.
```suggestion
  license: Pixar
```

2024-10-10 09:13 UTC, xhochy commented
I can take care of the license later today.

2024-10-10 09:22 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/opensubdiv/meta.yaml```) and found it was in an excellent condition.
I do have some suggestions for making it better though...


For **recipes/opensubdiv/meta.yaml**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2024-10-10 09:24 UTC, traversaro commented
> I can take care of the license later today.

Thanks! I wanted to open a conda-smithy issue but I forgot to do so, my bad.

2024-10-10 18:06 UTC, xhochy approved these changes

2024-10-10 18:06 UTC, xhochy commented
@conda-forge-admin please relint

2024-10-10 18:40 UTC, merged