add xnautils
conda-forge/staged-recipes pull request #27815
Opened 2024-10-08 04:17 UTC by mthang

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-10-08 04:19 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/xnatutils/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/xnatutils/meta.yaml**:

 * The recipe `license` should not include the word "License".
 * license_file entry is missing, but is required.

For **recipes/xnatutils/meta.yaml**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2024-10-08 04:42 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/xnatutils/meta.yaml```) and found it was in an excellent condition.

2024-10-08 07:57 UTC, mthang commented
@conda-forge-admin can you help to review this recipe.

2024-10-13 07:00 UTC, xhochy requested changes

2024-10-13 07:00 UTC, xhochy commented on recipes/xnatutils/meta.yaml
> +    - xnat-ls --version
This needs to be defined as an entry point.

2024-10-13 07:00 UTC, xhochy commented on recipes/xnatutils/meta.yaml
> +  commands:
```suggestion
  commands:
    - pip check
```

2024-10-14 07:33 UTC, xhochy approved these changes

2024-10-14 07:54 UTC, mthang commented
@xhochy the conda package failed to be built when using pip checks, so I replaced it with pip list instead. I found some conda recipes using pip list instead of pip check. There are few error messages I experienced when using pip check (see below) and I am not the developer of xnat. Any suggestion?

xnat 0.6.2 has requirement importlib-metadata~=6.8, but you have importlib-metadata 8.5.0.
xnat 0.6.2 has requirement pydicom~=2.3, but you have pydicom 3.0.1.
xnat 0.6.2 has requirement python-dateutil~=2.8.2, but you have python-dateutil 2.9.0.

2024-10-14 09:25 UTC, pauldmccarthy commented
@mthang @xhochy I've [updated the xnat feedstock](https://github.com/conda-forge/xnat-feedstock/pull/40), so you should be able to proceed with this PR (allowing ~30 minutes for the new builds to be published).

2024-10-14 22:58 UTC, mthang commented
@pauldmccarthy Thank you for the quick action ! @xhochy thank you for your help ! I will to proceed with the new PR again.

2024-10-28 00:38 UTC, mthang commented
@xhochy can you please review this recipe when you have time.

2024-11-16 17:08 UTC, xhochy approved these changes

2024-11-16 17:10 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/xnatutils/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/xnatutils/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `run` section of the recipe, you should usually use `python >={{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).
 * ℹ️ PyPI default URL is now pypi.org, and not pypi.io. You may want to update the default source url.

2024-11-19 03:53 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/xnatutils/meta.yaml```) and found it was in an excellent condition.

2024-11-19 04:12 UTC, mthang commented
@conda-forge-admin updated the meta.yaml according to the recommendation.

2024-11-21 20:54 UTC, xhochy approved these changes

2024-11-21 20:54 UTC, merged