Add fgclustering
conda-forge/staged-recipes pull request #27912
Opened 2024-10-17 15:12 UTC by IsraMekki0

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-10-17 15:47 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/fgclustering/meta.yaml```) and found it was in an excellent condition.

2024-11-23 15:35 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/fgclustering/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/fgclustering/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `run` section of the recipe, you should usually use `python >={{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).
 * ℹ️ PyPI default URL is now pypi.org, and not pypi.io. You may want to update the default source url.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/11988360778](https://github.com/conda-forge/conda-forge-webservices/actions/runs/11988360778). Examine the logs at this URL for more detail.</sub>

2025-02-18 10:27 UTC, IsraMekki0 commented
@xhochy Sorry if I'm tagging the wrong person. Any update about my pull request? Anything wrong?

2025-03-07 17:58 UTC, xhochy requested changes

2025-03-07 17:58 UTC, xhochy commented on recipes/fgclustering/meta.yaml
> +test:
```suggestion
test:
  requires:
    - pip
  commands:
    - pip check
```

2025-03-16 08:24 UTC, xhochy requested changes
This should also use python_min

2025-03-16 08:24 UTC, xhochy commented on recipes/fgclustering/meta.yaml
> +    - python >=3.7,<3.12
```suggestion
    - python {{ python_min }}
```

2025-03-16 08:24 UTC, xhochy commented on recipes/fgclustering/meta.yaml
> +    - pip
```suggestion
    - pip
    - {{ python_min }}
```

2025-03-16 08:24 UTC, xhochy commented on recipes/fgclustering/meta.yaml
> +    - python >=3.7,<3.12
```suggestion
    - python >={{ python_min }},<3.12
```

2025-03-17 09:01 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint --conda-forge .` from the recipe directory. You can also examine the [workflow logs](https://github.com/conda-forge/conda-forge-webservices/actions/runs/13895392093) for more detail.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/13895392093](https://github.com/conda-forge/conda-forge-webservices/actions/runs/13895392093). Examine the logs at this URL for more detail.</sub>

2025-03-24 10:14 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/fgclustering/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/fgclustering/meta.yaml**:

 * ℹ️ PyPI default URL is now pypi.org, and not pypi.io. You may want to update the default source url.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/14032624564](https://github.com/conda-forge/conda-forge-webservices/actions/runs/14032624564). Examine the logs at this URL for more detail.</sub>

2025-04-13 07:00 UTC, xhochy approved these changes

2025-04-13 10:07 UTC, merged