Add PyWLGK to the conda-forge channel
conda-forge/staged-recipes pull request #27917
Opened 2024-10-17 20:45 UTC by Old-Shatterhand

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] N,A, If static libraries are linked in, the license of the static library is packaged.
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-10-17 20:54 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pywlgk/meta.yaml```) and found it was in an excellent condition.

2024-10-18 10:17 UTC, Old-Shatterhand commented
@conda-forge/help-python The recipe has passed all checks and is ready for your review. Thanks !

2024-10-27 22:00 UTC, Old-Shatterhand commented
@conda-forge/help-python What do I need to do for you to merge this PR? I passed all checked and completed all tasks. About the build number, I'm not sure where to find it, but I guess, it's build 0.

2025-04-21 04:11 UTC, shermansiu commented on recipes/pywlgk/meta.yaml
> +  number: 0
Yeah, the build number is 0. Please check the box off in the checklist at the top.

2025-04-21 04:11 UTC, shermansiu commented
Also, please make the changes requested by the linter.

2025-04-21 04:12 UTC, shermansiu commented
If no static libraries are linked in, then please check that box off in the checklist.

2025-05-09 23:14 UTC, Old-Shatterhand commented
@shermansiu 
I checked the boxes and updated the recipe based on the linter's suggestions. Thank you for your help.

2025-05-10 02:55 UTC, shermansiu requested changes

2025-05-10 02:55 UTC, shermansiu commented on recipes/pywlgk/meta.yaml
> +    - python {{ python_min }}
```suggestion
    - python >={{ python_min }}
```

2025-05-10 02:55 UTC, shermansiu commented on recipes/pywlgk/meta.yaml
> +{% set python_min = "3.8" %}
```suggestion
```
Python 3.8 is already EOL. The environment already sets this by default, so you don't need to define it unless it's higher than 3.9 or whatever the lowest supported version is in the future.

2025-05-10 22:06 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pywlgk/meta.yaml```) and found it was in an excellent condition.

2025-05-10 22:09 UTC, Old-Shatterhand commented
I assume all three prior occurrences of `- python {{ python_min }}` should be changed to `- python >={{ python_min }}`. So, I changed the other two accordingly.

2025-05-10 22:10 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pywlgk/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/pywlgk/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use the pin `python {{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use the pin `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/14949547843](https://github.com/conda-forge/conda-forge-webservices/actions/runs/14949547843). Examine the logs at this URL for more detail.</sub>

2025-05-11 15:57 UTC, Old-Shatterhand commented
Ok, with the latest linter, I'm completely confused where to put this
`python {{ python_min }}`
and where (or why not) to put
`python >={{ python_min }}`
Can you un-confuse me, @shermansiu?
Thank you a lot in advance.

2025-05-15 16:29 UTC, shermansiu commented
@Old-Shatterhand, no, the different sections should have different entries. Commit [1cbde4a](https://github.com/conda-forge/staged-recipes/pull/27917/commits/1cbde4a8f457ac4bed827be87bc23058cd006f1e) was fine and commit [b5fa349](https://github.com/conda-forge/staged-recipes/pull/27917/commits/b5fa3492871e924cdbbff0de21634ae1266c35b9) should be reverted.

2025-05-15 21:11 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pywlgk/meta.yaml```) and found it was in an excellent condition.

2025-07-08 03:11 UTC, merged