Add r-portfolioanalytics
conda-forge/staged-recipes pull request #27960
Opened 2024-10-22 07:25 UTC by janjagusch

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-10-22 07:26 UTC, janjagusch commented on recipes/r-portfolioanalytics/meta.yaml
> +  license: GPL-3
```suggestion
  license: GPL-3.0-or-later
```

2024-10-22 07:27 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-portfolioanalytics/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/r-portfolioanalytics/meta.yaml**:

 * This recipe is using a compiler, which now requires adding a build dependence on `{{ stdlib("c") }}` as well. Note that this rule applies to each output of the recipe using a compiler. For further details, please see https://github.com/conda-forge/conda-forge.github.io/issues/2102.

For **recipes/r-portfolioanalytics/meta.yaml**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2024-10-22 07:31 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-portfolioanalytics/meta.yaml```) and found it was in an excellent condition.

2024-10-22 07:42 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-roi.plugin.symphony/meta.yaml```, ```recipes/r-pso/meta.yaml```, ```recipes/r-portfolioanalytics/meta.yaml```) and found it was in an excellent condition.
I do have some suggestions for making it better though...


For **recipes/r-roi.plugin.symphony/meta.yaml**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

For **recipes/r-pso/meta.yaml**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2024-10-22 07:48 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-portfolioanalytics/meta.yaml```, ```recipes/r-pso/meta.yaml```, ```recipes/r-roi.plugin.symphony/meta.yaml```) and found it was in an excellent condition.

2024-10-22 07:59 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-portfolioanalytics/meta.yaml```, ```recipes/r-rsymphony/meta.yaml```, ```recipes/r-roi.plugin.symphony/meta.yaml```, ```recipes/r-pso/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/r-rsymphony/meta.yaml**:

 * This recipe is using a compiler, which now requires adding a build dependence on `{{ stdlib("c") }}` as well. Note that this rule applies to each output of the recipe using a compiler. For further details, please see https://github.com/conda-forge/conda-forge.github.io/issues/2102.

For **recipes/r-rsymphony/meta.yaml**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2024-10-22 08:04 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-roi.plugin.symphony/meta.yaml```, ```recipes/r-portfolioanalytics/meta.yaml```, ```recipes/r-rsymphony/meta.yaml```, ```recipes/r-pso/meta.yaml```) and found it was in an excellent condition.

2024-10-22 09:48 UTC, mfansler requested changes
some license touch ups

2024-10-22 09:48 UTC, mfansler commented on recipes/r-portfolioanalytics/meta.yaml
> +  license: GPL-3.0-or-later
```suggestion
  license: GPL-3.0-only
```

2024-10-22 09:48 UTC, mfansler commented on recipes/r-pso/meta.yaml
> +  license: LGPL-3.0-or-later
```suggestion
  license: LGPL-3.0-only
```

2024-10-22 09:48 UTC, mfansler commented on recipes/r-roi.plugin.symphony/meta.yaml
> +  license: GPL-3.0-or-later
```suggestion
  license: GPL-3.0-only
```

2024-10-22 09:48 UTC, mfansler commented on recipes/r-rsymphony/meta.yaml
> +  license: EPL-1.0
A copy of this license needs to be included. https://spdx.org/licenses/EPL-1.0.html

2024-10-24 07:23 UTC, janjagusch commented
> some license touch ups

Thanks for the review, @mfansler. The whole stack depends on https://github.com/coin-or/SYMPHONY, which is not yet on CF. I will close this PR until we have `symphony` on CF.

2024-10-24 07:23 UTC, closed without merging