Adding CRAN package 'semaphore'
conda-forge/staged-recipes pull request #28191
Opened 2024-11-12 18:57 UTC by dansmith01

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-11-12 18:58 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-semaphore/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/r-semaphore/meta.yaml**:

 * ❌ This recipe is using a compiler, which now requires adding a build dependence on `{{ stdlib("c") }}` as well. Note that this rule applies to each output of the recipe using a compiler. For further details, please see https://github.com/conda-forge/conda-forge.github.io/issues/2102.
 * ❌ In your conda_build_config.yaml, please change the name of `MACOSX_DEPLOYMENT_TARGET`, to `c_stdlib_version`!

2024-11-12 19:22 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-semaphore/meta.yaml```) and found it was in an excellent condition.

2024-11-13 23:00 UTC, dansmith01 commented
I am listing myself as the maintainer. Recipe built using github.com/bgruening/conda_r_skeleton_helper. Checklist completed.

@conda-forge/help-r Ready for review!

2024-11-16 20:18 UTC, cbrueffer requested changes
Looks good; only one suggestion, then it's ready to go.

2024-11-16 20:18 UTC, cbrueffer commented on recipes/r-semaphore/meta.yaml
> +    - r-bh
```suggestion
    #- r-bh
```

`r-bh` is quite big and only needed during compile-time.

2024-11-17 01:50 UTC, dansmith01 commented
@cbrueffer clever idea! Seems to break the build on OSX though. Revert the changes?

2024-11-17 20:25 UTC, cbrueffer commented
The error is unrelated to the change; there are general macOS build issues at the moment: https://github.com/conda-forge/staged-recipes/issues/28242

2024-11-18 18:16 UTC, merged

2024-11-18 18:20 UTC, dansmith01 commented
Thanks @cbrueffer !