Add recipe for r-glmtrans
conda-forge/staged-recipes pull request #28205
Opened 2024-11-14 09:31 UTC by mlondschien

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- x ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-11-14 09:33 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-glmtrans/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/r-glmtrans/meta.yaml**:

 * ❌ There are too few lines.  There should be one empty line at the end of the file.

2024-11-14 11:01 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-glmtrans/meta.yaml```) and found it was in an excellent condition.

2024-11-14 12:36 UTC, mlondschien commented
Any idea what's going wrong here @conda-forge/r ?

2024-11-14 16:47 UTC, danielnachun commented
It appears you have only committed the `meta.yaml` file for your recipe, but you also need to add `build.sh` and `bld.bat`.  Otherwise Conda doesn’t know how to actually build the recipe.

2024-11-15 07:04 UTC, mlondschien commented
The failing osx build appears to be unrelated.

2024-11-15 07:10 UTC, danielnachun commented
Indeed that seems to be a transient network issue.  Can you restart the CI by closing and reopening the PR?

2024-11-19 08:04 UTC, mlondschien commented
@danielnachun can we merge this?

2024-11-19 09:02 UTC, mfansler requested changes
Mostly there, but some small corrections. Please use `conda_r_skeleton_helper` to generate CRAN skeletons.

2024-11-19 09:02 UTC, mfansler commented on recipes/r-glmtrans/meta.yaml
> +# License: GPL (>= 2)
Where is this from? [CRAN version shows `GPL-2`](https://github.com/cran/glmtrans/blob/27cfd76926c7ff481b64ce82ad56371e15673400/DESCRIPTION#L10).

2024-11-19 09:02 UTC, mfansler commented on recipes/r-glmtrans/meta.yaml
> +  license: GPL-2.0-or-later
[CRAN shows `GPL-2`](https://github.com/cran/glmtrans/blob/27cfd76926c7ff481b64ce82ad56371e15673400/DESCRIPTION#L10), so

```suggestion
  license: GPL-2.0-only
```

2024-11-19 11:40 UTC, mlondschien commented on recipes/r-glmtrans/meta.yaml
> +# License: GPL (>= 2)
```suggestion
# License: GPL-2
```

2024-11-19 13:36 UTC, mfansler approved these changes

2024-11-19 13:37 UTC, merged