Adding Yazi
conda-forge/staged-recipes pull request #28210
Opened 2024-11-14 14:33 UTC by hoxbro

Resolves https://github.com/conda-forge/staged-recipes/issues/28109

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-11-14 14:35 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/yazi/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/yazi/meta.yaml**:

 * ❌ Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [13]
 * ❌ This recipe is using a compiler, which now requires adding a build dependence on `{{ stdlib("c") }}` as well. Note that this rule applies to each output of the recipe using a compiler. For further details, please see https://github.com/conda-forge/conda-forge.github.io/issues/2102.

2024-11-14 14:39 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/yazi/meta.yaml```) and found it was in an excellent condition.

2024-11-14 19:02 UTC, hoxbro commented
@conda-forge/rust, ready for review!

This is my first time creating a rust conda package, so I'm unsure about the static libraries tasks.

2024-11-15 09:06 UTC, hoxbro commented
@conda-forge/help-rust, ready for review. Thank you!

This is my first time creating a rust conda package, so I'm unsure about the static libraries tasks.

2024-11-21 21:04 UTC, xhochy requested changes

2024-11-21 21:04 UTC, xhochy commented on recipes/yazi/build.sh
> +
```suggestion
export CARGO_PROFILE_RELEASE_STRIP=symbols
export CARGO_PROFILE_RELEASE_LTO=fat

```

2024-11-21 21:04 UTC, xhochy commented on recipes/yazi/build.sh
> +cargo install --locked --root "${PREFIX}" yazi-fm yazi-cli
```suggestion
cargo install --no-track --locked --root "${PREFIX}" yazi-fm yazi-cli
```

2024-11-21 21:04 UTC, xhochy commented on recipes/yazi/build.sh
> +rm "$PREFIX/.crates.toml"
```suggestion
```

2024-11-21 21:04 UTC, xhochy commented on recipes/yazi/bld.bat
> +set CARGO_HOME=D:\cargo
```suggestion
set CARGO_PROFILE_RELEASE_STRIP=symbols
set CARGO_PROFILE_RELEASE_LTO=fat

```

2024-11-21 21:04 UTC, xhochy commented on recipes/yazi/bld.bat
> +cargo install --locked --bins --root %PREFIX% yazi-fm yazi-cli
```suggestion
cargo install --no-track --locked --bins --root %LIBRARY_PREFIX% yazi-fm yazi-cli
```

2024-11-21 21:04 UTC, xhochy commented on recipes/yazi/bld.bat
> +if %errorlevel% NEQ 0 exit /b %errorlevel%
```suggestion
```

2024-11-22 07:10 UTC, hoxbro commented
@conda-forge/help-rust, ready for review. Thank you!

2024-11-22 08:06 UTC, xhochy approved these changes

2024-11-22 08:06 UTC, merged