add-marvin
conda-forge/staged-recipes pull request #28254
Opened 2024-11-18 03:05 UTC by raybellwaves

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-11-24 01:07 UTC, synapticarbors requested changes

2024-11-24 01:07 UTC, synapticarbors commented on recipes/marvin/meta.yaml
> +    - python 3.9
I think you need to use the `python_min` convention mentioned in https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python for new `noarch` packages. I tend to use the jinja variable `{% set python_min = "3.9" %}` explicitly at the top of the recipe.

2024-11-24 16:13 UTC, synapticarbors commented
@raybellwaves -- It will take a little bit for `partialjson` to hit the conda-forge CDN, but I'll circle back in a little bit and restart the checks.

2024-11-24 18:07 UTC, synapticarbors commented on recipes/marvin/meta.yaml
> +    - tzdata >=2023.3
I think this needs to be `python-tzdata` to get the python library rather than the C-library of the same name.

2024-11-24 22:07 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/marvin/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/marvin/meta.yaml**:

 * ❌ Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [15]
 * ❌ Non noarch packages should have python requirement without any version constraints.

For **recipes/marvin/meta.yaml**:

 * ℹ️ The recipe is not parsable by parser `conda-forge-tick (the bot)`. Your recipe may not receive automatic updates and/or may not be compatible with conda-forge's infrastructure. Please check the logs for more information and ensure your recipe can be parsed.
 * ℹ️ The recipe is not parsable by parser `conda-souschef (grayskull)`. Your recipe may not receive automatic updates and/or may not be compatible with conda-forge's infrastructure. Please check the logs for more information and ensure your recipe can be parsed.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/11999968683](https://github.com/conda-forge/conda-forge-webservices/actions/runs/11999968683). Examine the logs at this URL for more detail.</sub>

2024-11-24 22:10 UTC, raybellwaves commented
skipping windows as I got `conda_build.exceptions.CondaBuildUserError: Noarch package contains binary script: marvin.exe`

2024-11-24 22:11 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/marvin/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/marvin/meta.yaml**:

 * ℹ️ The recipe is not parsable by parser `conda-forge-tick (the bot)`. Your recipe may not receive automatic updates and/or may not be compatible with conda-forge's infrastructure. Please check the logs for more information and ensure your recipe can be parsed.
 * ℹ️ The recipe is not parsable by parser `conda-souschef (grayskull)`. Your recipe may not receive automatic updates and/or may not be compatible with conda-forge's infrastructure. Please check the logs for more information and ensure your recipe can be parsed.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/11999989562](https://github.com/conda-forge/conda-forge-webservices/actions/runs/11999989562). Examine the logs at this URL for more detail.</sub>

2024-12-03 01:34 UTC, raybellwaves commented
friendly ping for another review @synapticarbors please

2024-12-03 02:55 UTC, merged