Added a recipe for pytransit.
conda-forge/staged-recipes pull request #28286
Opened 2024-11-20 11:55 UTC by hpparvi

This PR adds a recipe for the pytransit package for exoplanet transit modelling.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-11-20 11:57 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/pytransit/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/pytransit/meta.yaml**:

 * ❌ The home item is expected in the about section.

For **recipes/pytransit/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).
 * ℹ️ PyPI default URL is now pypi.org, and not pypi.io. You may want to update the default source url.

2024-11-23 22:20 UTC, mwcraig requested changes
Thanks for opening this, @hpparvi! Just a few minor suggestions and it should be ready to go.

2024-11-23 22:20 UTC, mwcraig commented on recipes/pytransit/meta.yaml
> +  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytransit-{{ version }}.tar.gz
```suggestion
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytransit-{{ version }}.tar.gz
```

2024-11-23 22:20 UTC, mwcraig commented on recipes/pytransit/meta.yaml
> +    - python >={{ python_min }}
```suggestion
    - python {{ python_min }}
```

2024-11-23 22:20 UTC, mwcraig commented on recipes/pytransit/meta.yaml
> +  license_file: LICENSE
```suggestion
  license_file: LICENSE
  home: https://github.com/hpparvi/PyTransit
```

2024-11-23 22:20 UTC, mwcraig commented on recipes/pytransit/meta.yaml
> +  requires:
```suggestion
  requires:
    - python {{ python_min }}
```

2024-11-26 11:53 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/pytransit/meta.yaml```) and found it was in an excellent condition.

2024-11-26 14:56 UTC, hpparvi commented
Many thanks for your comments @mwcraig! The recipe should now be ready for review.

2024-11-26 14:57 UTC, hpparvi commented
@conda-forge/help-python, ready for review!

2024-11-26 16:35 UTC, mwcraig approved these changes

2024-11-26 16:35 UTC, merged