first recipe gatiab
conda-forge/staged-recipes pull request #28297
Opened 2024-11-21 13:44 UTC by Mustapha-hygeos

Checklist
- [x ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x ] Source is from official source.
- [x ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x ] If static libraries are linked in, the license of the static library is packaged.
- [x ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x ] Build number is 0.
- [x ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-11-21 13:46 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/gatiab/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/gatiab/meta.yaml**:

 * ❌ Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [12]
 * ❌ The recipe `license` should not include the word "License".
 * ❌ `noarch` packages can't have skips with selectors. If the selectors are necessary, please remove `noarch: python`.

For **recipes/gatiab/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `run` section of the recipe, you should usually use `python >={{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).
 * ℹ️ License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2024-11-21 15:59 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/gatiab/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/gatiab/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `run` section of the recipe, you should usually use `python >={{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).

2024-11-21 16:14 UTC, Mustapha-hygeos commented
@conda-forge/help-python Hi, the recipe has passed all checks and is ready for you review. Thanks.

2024-11-22 02:12 UTC, synapticarbors requested changes

2024-11-22 02:12 UTC, synapticarbors commented on recipes/gatiab/meta.yaml
> +    - python >=3.9.19
Please use the `python_min` convention for `noarch: python` packages shown in:
https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python

2024-11-23 02:07 UTC, synapticarbors requested changes

2024-11-23 02:07 UTC, synapticarbors commented on recipes/gatiab/meta.yaml
> +    - python {{ python_min }}
This should be `- python >={{ python_min }}`

2024-11-23 02:07 UTC, synapticarbors commented on recipes/gatiab/meta.yaml
> +  requires:
Please add `- python {{ python_min }}` to the `test/requires` section.

2024-11-23 06:52 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/gatiab/meta.yaml```) and found it was in an excellent condition.

2024-11-23 15:21 UTC, merged