Adding r-matchthem from CRAN
conda-forge/staged-recipes pull request #28376
Opened 2024-11-27 07:02 UTC by dillonroach

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-11-27 07:03 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-matchthem/meta.yaml```) and found it was in an excellent condition.

2024-11-27 10:08 UTC, mfansler requested changes
Thanks for submitting!

Minor adjust, then should be good to merge.

2024-11-27 10:08 UTC, mfansler commented on recipes/r-matchthem/meta.yaml
> +  license: GPL-2.0-only
DESCRIPTION shows `GPL (>= 2)`, so

```suggestion
  license: GPL-2.0-or-later
```

2024-11-27 10:08 UTC, mfansler commented on recipes/r-matchthem/meta.yaml
> +    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
Expand

```suggestion
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
```

2024-12-02 06:07 UTC, dillonroach commented on recipes/r-matchthem/meta.yaml
> +  license: GPL-2.0-only
Good catch!, updated.

2024-12-02 06:08 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-matchthem/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/r-matchthem/meta.yaml**:

 * ❌ Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [15]
 * ❌ `noarch` packages can't have skips with selectors. If the selectors are necessary, please remove `noarch: generic`.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12113655284](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12113655284). Examine the logs at this URL for more detail.</sub>

2024-12-02 06:11 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-matchthem/meta.yaml```) and found it was in an excellent condition.

2024-12-02 06:20 UTC, mfansler commented
Keep noarch and let win fail.

2024-12-02 07:52 UTC, mfansler approved these changes

2024-12-02 07:52 UTC, merged