Adding r-lmtp from CRAN
conda-forge/staged-recipes pull request #28377
Opened 2024-11-27 07:06 UTC by dillonroach

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-11-27 07:08 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-lmtp/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/r-lmtp/meta.yaml**:

 * ℹ️ License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12045394177](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12045394177). Examine the logs at this URL for more detail.</sub>

2024-11-27 07:12 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-lmtp/meta.yaml```) and found it was in an excellent condition.

2024-11-27 09:39 UTC, mfansler requested changes
Thanks for adding!

Some minor adjusts, then should be good to merge.

2024-11-27 09:39 UTC, mfansler commented on recipes/r-schoolmath/meta.yaml
> +  license: GPL-2.0-only
DESCRIPTION shows `GPL (>= 2)`, so

```suggestion
  license: GPL-2.0-or-later
```

2024-11-27 09:39 UTC, mfansler commented on recipes/r-schoolmath/meta.yaml
> +    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
Expand

```suggestion
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
```

2024-11-27 09:39 UTC, mfansler commented on recipes/r-lmtp/meta.yaml
> +  home: https://beyondtheate.com/, https://github.com/nt-williams/lmtp
Split URLs

```suggestion
  home: https://beyondtheate.com/
  dev_url: https://github.com/nt-williams/lmtp
```

2024-12-02 06:06 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-lmtp/meta.yaml```, ```recipes/r-schoolmath/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/r-lmtp/meta.yaml**:

 * ❌ Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [15]
 * ❌ `noarch` packages can't have skips with selectors. If the selectors are necessary, please remove `noarch: generic`.

For **recipes/r-schoolmath/meta.yaml**:

 * ❌ Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [15]
 * ❌ `noarch` packages can't have skips with selectors. If the selectors are necessary, please remove `noarch: generic`.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12113628034](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12113628034). Examine the logs at this URL for more detail.</sub>

2024-12-02 06:08 UTC, dillonroach commented on recipes/r-schoolmath/meta.yaml
> +  license: GPL-2.0-only
Thanks for catching this, updated!

2024-12-02 06:13 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-schoolmath/meta.yaml```, ```recipes/r-lmtp/meta.yaml```) and found it was in an excellent condition.

2024-12-02 06:21 UTC, mfansler commented
Keep noarch and let win fail (it's fine)

2024-12-02 07:51 UTC, mfansler approved these changes

2024-12-02 07:52 UTC, merged