Adding Autogrid4 to conda-forge
conda-forge/staged-recipes pull request #28387
Opened 2024-11-28 02:10 UTC by joanimato

Recipe to add Autogrid4 to conda-forge. Linux only build. 

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-11-28 02:12 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/autogrid/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/autogrid/meta.yaml**:

 * ❌ Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [14]

For **recipes/autogrid/meta.yaml**:

 * ℹ️ License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12061266959](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12061266959). Examine the logs at this URL for more detail.</sub>

2024-12-03 23:33 UTC, diogomart commented
Willing to be maintainer. @atillack are you in? ;-)

2024-12-03 23:37 UTC, atillack commented
@diogomart absolutely, i'm in

2024-12-04 00:40 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/autogrid/meta.yaml```) and found it was in an excellent condition.

2024-12-04 02:46 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/autogrid/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/autogrid/meta.yaml**:

 * ℹ️ `libgcc-ng` has been superseded by `libgcc`. Note however, that except in truly exceptional cases, you should not have to add this manually; you can rely on the fact that `{{ compiler("c") }}` and `{{ compiler("cxx") }}` will always create the correct run-export for this. If you need to _ignore_ the run-export for whatever reason, the best way to do it is:
    ```yaml
    build:
      ignore_run_exports_from:
        - {{ compiler("c") }}    # depending on which...
        - {{ compiler("cxx") }}  # ... compilers you use
    ```
 * ℹ️ `libstdcxx-ng` has been superseded by `libstdcxx`. Note however, that except in truly exceptional cases, you should not have to add this manually; you can rely on the fact that `{{ compiler("cxx") }}` will always create the correct run-export for this. If you need to _ignore_ the run-export for whatever reason, the best way to do it is:
    ```yaml
    build:
      ignore_run_exports_from:
        - {{ compiler("cxx") }}
    ```


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12152023087](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12152023087). Examine the logs at this URL for more detail.</sub>

2024-12-04 02:58 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/autogrid/meta.yaml```) and found it was in an excellent condition.

2024-12-07 19:48 UTC, joanimato commented
@conda-forge-admin, please ping conda-forge/help-c-cpp

ready for review.

2024-12-10 20:04 UTC, xhochy requested changes
A lot of things to critic here, but please first review other C++ recipes and have a look at how they use compilers and OpenMP.

2024-12-10 20:04 UTC, xhochy commented on recipes/autogrid/meta.yaml
> +  license_file: LICENSE.txt
```suggestion
  license_file: COPYING
```

2024-12-10 20:04 UTC, xhochy commented on recipes/autogrid/LICENSE.txt
> +GNU GENERAL PUBLIC LICENSE
This is part of the sources as `COPYING`. Please remove this copy.

2024-12-10 20:04 UTC, xhochy commented on recipes/autogrid/meta.yaml
> +    - gcc
Please us the `{{ compiler('…') }}` functions instead of listing `gcc` here.

2024-12-10 20:04 UTC, xhochy commented on recipes/autogrid/build.sh
> +meson setup builddir
```suggestion
meson setup $MESON_ARGS builddir
```

2024-12-10 20:04 UTC, xhochy commented on recipes/autogrid/build.sh
> +export PATH="$BUILD_PREFIX/bin:$PATH"
```suggestion
```

2024-12-10 22:16 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/autogrid/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/autogrid/meta.yaml**:

 * ❌ This recipe is using a compiler, which now requires adding a build dependence on `{{ stdlib("c") }}` as well. Note that this rule applies to each output of the recipe using a compiler. For further details, please see https://github.com/conda-forge/conda-forge.github.io/issues/2102.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12265648951](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12265648951). Examine the logs at this URL for more detail.</sub>

2024-12-10 22:38 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/autogrid/meta.yaml```) and found it was in an excellent condition.

2024-12-18 23:25 UTC, joanimato commented
@xhochy Can you take another look please? 

Thanks!

2025-01-11 13:40 UTC, xhochy requested changes

2025-01-11 13:40 UTC, xhochy commented on recipes/autogrid/meta.yaml
> +
```suggestion
```

2025-01-11 16:37 UTC, carterbox commented on recipes/autogrid/meta.yaml
> +
You shouldn't need to manuallyu specify these libs because they should be exported by packages in the build requirements such as the compiler packages.

2025-01-11 16:53 UTC, carterbox approved these changes

2025-01-11 16:53 UTC, merged

2025-01-11 23:00 UTC, diogomart commented
Thank you @xhochy @carterbox