Adding conda package for drug2cell tool
conda-forge/staged-recipes pull request #28395
Opened 2024-11-28 19:26 UTC by Mennayousef

I am attempting to create a conda recipe package for drug2cell tool.

2024-11-28 19:28 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/drug2cell/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/drug2cell/meta.yaml**:

 * ❌ The recipe could do with some maintainers listed in the `extra/recipe-maintainers` section.
 * ❌ There are 1 too many lines.  There should be one empty line at the end of the file.
 * ❌ noarch: python recipes are required to have a lower bound on the python version. Typically this means putting `python >=3.6` in **both** `host` and `run` but you should check upstream for the package's Python compatibility.

For **recipes/drug2cell/meta.yaml**:

 * ℹ️ No valid build backend found for Python recipe for package `drug2cell` using `pip`. Python recipes using `pip` need to explicitly specify a build backend in the `host` section. If your recipe has built with only `pip` in the `host` section in the past, you likely should add `setuptools` to the `host` section of your recipe.
 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `run` section of the recipe, you should usually use `python >={{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12074556204](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12074556204). Examine the logs at this URL for more detail.</sub>

2024-11-28 19:35 UTC, Mennayousef commented
maintainer

2024-11-28 20:02 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/drug2cell/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/drug2cell/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12074840935](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12074840935). Examine the logs at this URL for more detail.</sub>

2024-11-28 20:24 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/drug2cell/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/drug2cell/meta.yaml**:

 * ❌ The recipe must have some tests.

For **recipes/drug2cell/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12075053995](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12075053995). Examine the logs at this URL for more detail.</sub>

2024-11-28 20:37 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/drug2cell/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/drug2cell/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12075173996](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12075173996). Examine the logs at this URL for more detail.</sub>

2024-12-02 09:18 UTC, mfansler requested changes
Thanks for spending time on this! Unfortunately, I'm not for merging this as it stands.

Conda Forge packages should be properly versioned, either through PyPI or GitHub Releases rather from a commit hash, which is mutable. My recommendation is either that one gets the lab to commit to making releases of some form, or instead move this to Bioconda, which aligns with the intent of the package and also has a lower bar for recipes standards.

2024-12-02 09:29 UTC, mfansler commented
Just noticed that this was merged on Bioconda (https://github.com/bioconda/bioconda-recipes/pull/52452). As a `noarch` recipe, there will not be any advantage to shifting to Conda Forge, even with the version issue addressed. As such, I will close this.

2024-12-02 09:29 UTC, closed without merging