Multiformats
conda-forge/staged-recipes pull request #28404
Opened 2024-11-29 12:14 UTC by lkluft

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-11-29 12:15 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/multiformats-config/meta.yaml```, ```recipes/multiformats/meta.yaml```, ```recipes/bases/meta.yaml```, ```recipes/typing-validation/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/multiformats-config/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `run` section of the recipe, you should usually use `python >={{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).

For **recipes/multiformats/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `run` section of the recipe, you should usually use `python >={{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).

For **recipes/bases/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `run` section of the recipe, you should usually use `python >={{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12084556110](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12084556110). Examine the logs at this URL for more detail.</sub>

2024-11-29 12:16 UTC, d70-t commented
I can help out maintaining from time to time.

2024-11-29 12:59 UTC, xhochy requested changes

2024-11-29 12:59 UTC, xhochy commented on recipes/bases/meta.yaml
> +{% set python_min = "3.7" %}
Not needed as long as you don't need 3.10+
```suggestion
```

2024-11-29 12:59 UTC, xhochy commented on recipes/multiformats-config/meta.yaml
> +{% set python_min = "3.7" %}
Not needed as long as you don't need 3.10+
```suggestion
```

2024-11-29 12:59 UTC, xhochy commented on recipes/multiformats/meta.yaml
> +{% set python_min = "3.7" %}
Not needed as long as you don't need 3.10+
```suggestion
```

2024-11-29 12:59 UTC, xhochy commented on recipes/typing-validation/meta.yaml
> +    - typing_extensions >=4.6.0  # [py<311]
Make this a noarch packages as with the other ones above. This will be simpler to maintain
```suggestion
    - typing_extensions >=4.6.0
```

2024-11-29 13:07 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/multiformats/meta.yaml```, ```recipes/bases/meta.yaml```, ```recipes/typing-validation/meta.yaml```, ```recipes/multiformats-config/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/multiformats/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).

For **recipes/bases/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).

For **recipes/typing-validation/meta.yaml**:

 * ❌ The build section contained an unexpected subsection name. norach is not a valid subsection name.

For **recipes/multiformats-config/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12085281556](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12085281556). Examine the logs at this URL for more detail.</sub>

2024-11-29 13:13 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/multiformats-config/meta.yaml```, ```recipes/multiformats/meta.yaml```, ```recipes/typing-validation/meta.yaml```, ```recipes/bases/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/multiformats-config/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).

For **recipes/multiformats/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).

For **recipes/typing-validation/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).

For **recipes/bases/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12085376407](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12085376407). Examine the logs at this URL for more detail.</sub>

2024-11-29 13:34 UTC, lkluft commented
Thanks for your comments!

I am not really sure about the `python_min` variable though. Removing the variable altogether leads to crashes in Jinja2 because the variable is unset. Is it fine to just don't require a minimum python in those cases?

2024-11-29 16:31 UTC, xhochy commented
The variable should be set to a default of 3.9 (the minimal supported version).

2024-11-29 17:07 UTC, lkluft commented
Okay, thanks 👍 I set `python_min = "3.9"` in all recipes and cleaned the mess of back-and-forth fixes.

2024-11-29 20:05 UTC, xhochy commented
> Okay, thanks 👍 I set `python_min = "3.9"` in all recipes and cleaned the mess of back-and-forth fixes.

No, you should not set it all.

2024-11-30 08:54 UTC, lkluft commented
Unsetting `python_min` causes the Jinja2 exception (see latest pipeline). I am a bit puzzled by this as I have seen other recipes with the same configuration pass.

One hack would be to set `{% set python_min = python_min | default("3.9") %}`, e.g. using the build system value if present, but not failing otherwise. But there may be another problem with the recipes.

2024-12-05 14:27 UTC, d70-t commented
@conda-forge-admin please rerender

2024-12-05 14:59 UTC, d70-t commented
I tried debugging this a little more. I just found by building locally, that the packen `typing-validation` (which can be built without further dependencies) would build fine, if it is the only package in this change, but it crashes with the `python_min` error, if there are other packages / receipes to be built in the same change. So I guess options for moving forward would be:

* split this PR into four, one for each receipe
* try finding out what's the issue when building multiple receipes at once

2025-01-06 15:57 UTC, d70-t reviewed
There's apparently a hack at #28494, which seems to fix the problem when adding multiple recipes in one PR. Should we try that?

2025-01-06 15:57 UTC, d70-t commented on recipes/bases/meta.yaml
> +    - python {{ python_min }}
```suggestion
    - python {{ python_min }}.*
```

2025-01-06 15:57 UTC, d70-t commented on recipes/multiformats-config/meta.yaml
> +    - python {{ python_min }}
```suggestion
    - python {{ python_min }}.*
```

2025-01-06 15:57 UTC, d70-t commented on recipes/multiformats/meta.yaml
> +    - python {{ python_min }}
```suggestion
    - python {{ python_min }}.*
```

2025-01-06 15:57 UTC, d70-t commented on recipes/typing-validation/meta.yaml
> +    - python {{ python_min }}
```suggestion
    - python {{ python_min }}.*
```

2025-01-08 15:30 UTC, closed without merging

2025-01-08 15:30 UTC, lkluft commented
I will close this issue and reopen the PRs for the individual recipes