Add cosmology, flt, gaussiancl, transformcl, and glass
conda-forge/staged-recipes pull request #28405
Opened 2024-11-29 12:15 UTC by Saransh-cpp

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-11-29 12:17 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/transformcl/meta.yaml```, ```recipes/glass/meta.yaml```, ```recipes/cosmology/meta.yaml```, ```recipes/gaussiancl/meta.yaml```, ```recipes/flt/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/transformcl/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).

For **recipes/glass/meta.yaml**:

 * ❌ The home item is expected in the about section.

For **recipes/glass/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `run` section of the recipe, you should usually use `python >={{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).

For **recipes/cosmology/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).

For **recipes/gaussiancl/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).

For **recipes/flt/meta.yaml**:

 * ❌ This recipe is using a compiler, which now requires adding a build dependence on `{{ stdlib("c") }}` as well. Note that this rule applies to each output of the recipe using a compiler. For further details, please see https://github.com/conda-forge/conda-forge.github.io/issues/2102.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12084579425](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12084579425). Examine the logs at this URL for more detail.</sub>

2024-11-29 12:22 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/transformcl/meta.yaml```, ```recipes/cosmology/meta.yaml```, ```recipes/flt/meta.yaml```, ```recipes/gaussiancl/meta.yaml```, ```recipes/glass/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/transformcl/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).

For **recipes/cosmology/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).

For **recipes/gaussiancl/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).

For **recipes/glass/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12084648937](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12084648937). Examine the logs at this URL for more detail.</sub>

2024-11-29 12:25 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/glass/meta.yaml```, ```recipes/transformcl/meta.yaml```, ```recipes/cosmology/meta.yaml```, ```recipes/gaussiancl/meta.yaml```, ```recipes/flt/meta.yaml```) and found it was in an excellent condition.

2024-11-29 14:23 UTC, Saransh-cpp commented
@conda-forge/help-python-c, ready for review!

2024-11-29 16:18 UTC, xhochy requested changes

2024-11-29 16:18 UTC, xhochy commented on recipes/cosmology/meta.yaml
> +{% set python_min = "3.9" %}
```suggestion
```
Only set this if you need 3.10+

2024-11-29 16:18 UTC, xhochy commented on recipes/gaussiancl/meta.yaml
> +{% set python_min = "3.9" %}
```suggestion
```

2024-11-29 16:18 UTC, xhochy commented on recipes/glass/meta.yaml
> +  # healpy does not support windows
You can make this noarch. The CI on Windows will fail with a not-sovable error but we can still merge

2024-11-29 16:18 UTC, xhochy commented on recipes/transformcl/meta.yaml
> +{% set python_min = "3.9" %}
```suggestion
```

2024-11-29 18:23 UTC, Saransh-cpp commented
Thanks for the review, @xhochy! Should be ready again!

2024-11-29 18:24 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/gaussiancl/meta.yaml```, ```recipes/flt/meta.yaml```, ```recipes/glass/meta.yaml```, ```recipes/transformcl/meta.yaml```, ```recipes/cosmology/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/glass/meta.yaml**:

 * ❌ Invalid `noarch` value `Python`. Should be one of `python`, `generic`.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12089202824](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12089202824). Examine the logs at this URL for more detail.</sub>

2024-11-29 18:35 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/flt/meta.yaml```, ```recipes/cosmology/meta.yaml```, ```recipes/glass/meta.yaml```, ```recipes/transformcl/meta.yaml```, ```recipes/gaussiancl/meta.yaml```) and found it was in an excellent condition.

2024-11-29 18:44 UTC, Saransh-cpp commented
The CI is erroring out with -
```
conda_build.exceptions.CondaBuildUserError: Failed to render jinja template in /home/conda/staged-recipes-copy/recipes/cosmology/meta.yaml:
'python_min' is undefined
```

so I guess, I need to set the variable?

2024-11-29 20:01 UTC, xhochy commented
No, this is a CI issue in staged-recipes. Somehow it doesn't work at the moment if not all recipes are `noarch: python`. Can you submit the other recipe as an individual PR, please?

2024-11-29 21:24 UTC, Saransh-cpp commented
Ah, I see, thank you! I have created a new PR for `flt`.

Blocked by #28411

2024-11-29 22:03 UTC, Saransh-cpp commented
Ahh, same error :(

Should I replace `python_min` with the actual version in `requirements`?

2024-12-02 09:35 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/transformcl/meta.yaml```, ```recipes/cosmology/meta.yaml```, ```recipes/gaussiancl/meta.yaml```, ```recipes/glass/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/transformcl/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `run` section of the recipe, you should usually use `python >={{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).

For **recipes/cosmology/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `run` section of the recipe, you should usually use `python >={{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).

For **recipes/gaussiancl/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `run` section of the recipe, you should usually use `python >={{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).

For **recipes/glass/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `run` section of the recipe, you should usually use `python >={{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12116481653](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12116481653). Examine the logs at this URL for more detail.</sub>

2024-12-02 10:02 UTC, Saransh-cpp commented
Not using `{% set python_min = "3.9" %}` gives me an error in the CI, and not using `python_min` altogether throws a linter warning. I have added `python_min` and `{% set python_min = "3.9" %}` back, but please let me know if I am doing something wrong!

2024-12-03 00:02 UTC, Saransh-cpp commented
Hi @matthewfeickert, thanks for the review! I was talking about https://github.com/conda-forge/staged-recipes/pull/28405#issuecomment-2508541328 in the comment related to the CI failure above.

> which I've been told by the conda-forge/core team before is "fine" given

Yes, this should be fine. I was worried about the `python_min` variable, which @xhochy suggested [that I should only set if I need Python 3.10+](https://github.com/conda-forge/staged-recipes/pull/28405#discussion_r1863739052).

> Though as mentioned, probably better to submit each project as its own standalone PR in the future

`flt` (`python-c` package) is already in a separate PR (merged!) - #28411 - as suggested above, and all of these packages are pure Python.

I have squashed the commits so this should be ready for a review again.

@conda-forge/help-python, ready for review!

2024-12-03 01:11 UTC, matthewfeickert commented
> Yes, this should be fine. I was worried about the `python_min` variable, which @xhochy suggested [that I should only set if I need Python 3.10+](https://github.com/conda-forge/staged-recipes/pull/28405#discussion_r1863739052).

Ah, yeah, while that (enforcing lower bounds that were more aggressive than the current subset of CPython versions conda-forge enforces) was the original intended purpose of `python_min` (AFAIK), I added an example to https://deploy-preview-2370--conda-forge-previews.netlify.app/docs/maintainer/knowledge_base/#noarch-python in https://github.com/conda-forge/conda-forge.github.io/pull/2370 of why `python_min` is preferable for every `noarch: python` feedstock as it actively enforces the `requires-python` metadata for the Python package.

2024-12-03 10:21 UTC, Saransh-cpp commented
Ah I see, so I am guessing it is also required to `set` the `python_min` variable at top for the workflows to work? (which is how it is in this PR, so it should be ready to review)

2024-12-03 11:41 UTC, matthewfeickert commented
> Ah I see, so I am guessing it is also required to `set` the `python_min` variable at top for the workflows to work?

Yeah, either a Jinja2 variable as you describe, or as a map in `recipe/conda_build_config.yaml` (c.f. https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python). The Jinja2 variable is easier though as you can keep everything in the `meta.yaml`.

2024-12-03 12:00 UTC, Saransh-cpp commented
Thank you! This should be ready then ✅

2024-12-04 13:21 UTC, Saransh-cpp commented
> No, this is a CI issue in staged-recipes. Somehow it doesn't work at the moment if not all recipes are noarch: python. Can you submit the other recipe as an individual PR, please?

I found the issue. The CI errors out with `python_min` not found if there are multiple packages in the same PR. It does not matter if they are `noarch: python` or not.

I will raise this as an issue. Closing this PR as I am splitting it into multiple individual package PRs.

2024-12-04 13:21 UTC, closed without merging