Adding recipe for Blosc2 3.0.0rc3
conda-forge/staged-recipes pull request #28510
Opened 2024-12-10 17:04 UTC by FrancescAlted

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [X] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-12-10 20:25 UTC, hmaarrfk requested changes
This should not be its own recipe, rather please make a pull request to https://github.com/conda-forge/python-blosc2-feedstock

2024-12-10 20:25 UTC, hmaarrfk commented
converting to draft to avoid accidental merging.

2024-12-10 20:28 UTC, hmaarrfk commented on recipes/blosc2/meta.yaml
> +    .\vcpkg\vcpkg install pkg-config
in short, vcpkg is microsoft's answer to conda.

A different strategy. 

At conda-forge, you must build everything (well most things) with conda-forge's stack.

2024-12-10 22:39 UTC, FrancescAlted commented
> This should not be its own recipe, rather please make a pull request to https://github.com/conda-forge/python-blosc2-feedstock

Ah! I forgot about this. I'll try this tomorrow.

2024-12-10 22:40 UTC, FrancescAlted commented
Should I close this one then?

2024-12-11 04:29 UTC, hmaarrfk commented
> Should I close this one then?

yes, but me closing it seems "agressive" so I wanted to ensure some discussion before doing it.

2024-12-11 04:29 UTC, hmaarrfk commented
> Ah! I forgot about this. I'll try this tomorrow.

I often use https://conda-forge.org/packages/ to find packages by "name"

2024-12-11 07:01 UTC, FrancescAlted commented
Closing this in favor of https://github.com/conda-forge/python-blosc2-feedstock/pull/18

2024-12-11 07:01 UTC, closed without merging