Adding imdclient package of IMDv3
conda-forge/staged-recipes pull request #28554
Opened 2024-12-12 21:00 UTC by hcho38

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-12-12 21:01 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/imdclient/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/imdclient/meta.yaml**:

 * ❌ The about section contained an unexpected subsection name. docurl is not a valid subsection name.
 * ❌ The about section contained an unexpected subsection name. devurl is not a valid subsection name.

For **recipes/imdclient/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `run` section of the recipe, you should usually use `python >={{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12304684940](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12304684940). Examine the logs at this URL for more detail.</sub>

2024-12-12 21:06 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/imdclient/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/imdclient/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `run` section of the recipe, you should usually use `python >={{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12304761062](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12304761062). Examine the logs at this URL for more detail.</sub>

2024-12-12 21:32 UTC, orbeckst commented
@hcho38 can you please add me to the maintainer list? Thanks.

I am willing to be a maintainer.

2024-12-12 21:33 UTC, ljwoods2 commented
I am willing to be a maintainer

2024-12-12 21:33 UTC, orbeckst commented on recipes/imdclient/meta.yaml
> +    - amruthesht
I am willing to be a maintainer (and the package is hosted in my groups GitHub so I have to ensure that at least one person has long-term access).
```suggestion
    - amruthesht
    - orbeckst
```

2024-12-13 15:14 UTC, amruthesht commented
I am willing to be a maintainer

2024-12-13 16:49 UTC, hcho38 commented
@conda-forge/help-python ready for review

2024-12-16 00:47 UTC, synapticarbors requested changes
Overall looks good, but could you have a look at our docs on `noarch: python`:
https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python

We are now enforcing a `python_min`, so you'll want to follow the convention we have there.

2024-12-16 21:35 UTC, hcho38 commented
@synapticarbors I made the changes to the recipe based on your comment and the documentation

2024-12-16 21:46 UTC, synapticarbors commented on recipes/imdclient/meta.yaml
> +    - python {{ python_min }}
```suggestion
    - python >={{ python_min }}
```

2024-12-16 21:46 UTC, synapticarbors commented on recipes/imdclient/meta.yaml
> +    - pip
```suggestion
    - pip
    - python {{ python_min }}
```

2024-12-16 21:49 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/imdclient/meta.yaml```) and found it was in an excellent condition.

2024-12-16 22:00 UTC, merged

2024-12-16 22:27 UTC, orbeckst commented
Thank you, @synapticarbors !

2024-12-16 22:30 UTC, synapticarbors commented
@orbeckst you're welcome! It's always fun to see biophysics folks from my previous life pop up on here.