holoscan 2.6.0.1
conda-forge/staged-recipes pull request #28598
Opened 2024-12-16 16:09 UTC by billysuh7

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

The following dependencies have been whitelisted to have the build going, but we need to provide them (or call them out as not supported) in conda:

* [ ] "*libcuda.so*" # driver
* [ ] "*libgdrapi.so*" # part of gdrcopy (gds-tools) yet not pre-built for conda-forge channel
* [ ] "*libnvidia-ml.so*"  # driver
* [ ] "*libnvinfer_plugin.so*" # NVIDIA's TensorRT not on conda-forge
* [ ] "*libnvonnxparser.so*" # NVIDIA's TensorRT not on conda-forge
* [ ] "*libonnxruntime.so.1.18.1" # onnxruntime conda package is there, but this particular version does not have this DSO
* [ ] "*libtorchvision.so*" # not available even in torchvision package
* [ ] "*libv4l2.so*" # lideo4linux2 lib, not available
* [ ] "*libxpmem.so*" # XPMEM, Linux Cross-Memory Attach kernel module, not available

Currently the resulting holoscan package comes out ~ 1.6G whereas the source tarball is only about 50MB. For some reason, it is including a lot (if not all) of its runtime dependencies in the resulting conda package.

In the local build, I see a long listing like below. For some reason, conda build is patching even the dependencies, and that may be prompting conda to include them in the package because they have been modified. I have not seem this kind of listing when building other packages.

```
Files containing CONDA_PREFIX
-----------------------------
bin/ib_acme (binary): Patching
bin/xmlcatalog (binary): Patching
bin/xmllint (binary): Patching
lib/libX11.so.6.4.0 (binary): Patching
lib/libhwloc.so.15.8.1 (binary): Patching
lib/libibverbs.so.1.14.53.0 (binary): Patching
lib/libnl-cli-3.a (binary): Patching
lib/libnl-cli-3.so.200.26.0 (binary): Patching
lib/libnl-route-3.a (binary): Patching
lib/libnl-route-3.so.200.26.0 (binary): Patching
lib/librdmacm.so.1.3.53.0 (binary): Patching
lib/libvulkan.so.1.3.296 (binary): Patching
lib/libxml2.so.2.13.5 (binary): Patching
lib/rsocket/librspreload.so (binary): Patching
bin/hwloc-compress-dir (text): Patching
bin/hwloc-gather-topology (text): Patching
bin/x86_64-conda-linux-gnu.cfg (text): Patching
bin/xml2-config (text): Patching
lib/-gdb.py (text): Patching
lib/cmake/libjpeg-turbo/libjpeg-turboTargets-release.cmake (text): Patching
lib/cmake/libjpeg-turbo/libjpeg-turboTargets.cmake (text): Patching
lib/gcc/x86_64-conda-linux-gnu/13.3.0/install-tools/mkheaders.conf (text): Patching
lib/gcc/x86_64-conda-linux-gnu/13.3.0/plugin/include/configargs.h (text): Patching
lib/gcc/x86_64-conda-linux-gnu/13.3.0/specs (text): Patching
lib/pkgconfig/absl_absl_check.pc (text): Patching
....

```<snipped>

This PR still very much WIP.

2024-12-16 16:11 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/holoscan/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/holoscan/meta.yaml**:

 * ℹ️ The use of `xz` is deprecated. If your package links to `liblzma`, use the new `liblzma-devel` package. For XZ's command line utilities (like `xz` and `unxz`), use the `xz-tools`package. For the xz-enabled GNU tools (like `grep`), use `xz-gpl-tools`. Note: Command line utilities should go in `requirements/build`.
 * ℹ️ The recipe is not parsable by parser `conda-souschef (grayskull)`. Your recipe may not receive automatic updates and/or may not be compatible with conda-forge's infrastructure. Please check the logs for more information and ensure your recipe can be parsed.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12356648942](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12356648942). Examine the logs at this URL for more detail.</sub>

2024-12-17 16:49 UTC, isuruf commented
Is this the same as https://github.com/nvidia-holoscan/holoscan-sdk? If so, why re-package it when it is open source?

2024-12-18 16:20 UTC, billysuh7 commented
> Is this the same as https://github.com/nvidia-holoscan/holoscan-sdk? If so, why re-package it when it is open source?

Hi @isuruf, the main reason being difficulty associated with building from source in terms of meeting build dependencies. In the recipe we have white-listed a few dependencies that are kernel modules (libxpmem.so, libv4l2.so), cuda drivers (libcuda.so, libnvidia-ml.so) for which there is no conda package and no docker image prebuilt w/ them AFAIK.

Even with binary repackaging we have other hurdles to overcome before holoscan package can be released: conda packages that happen to be missing specific DSO files (libgdrapi.so missing in gds-tools, libonnxruntime.so.1.18.1 missing in onnxruntime 1.18.1, libtorchvision.so missing in torchvision), and then there are DSOs from a product that we don't have (yet)in conda-forge (TensorRT).

For gds-tools, onnxruntime and torchvision I will see when we can get respective owners to provide missing DSO, and for TensorRT we'll have to find out a plan for it with respect to conda.

2025-02-19 19:09 UTC, carterbox requested changes

2025-02-19 19:09 UTC, carterbox commented on recipes/holoscan/build.sh
> +cp -rv bin $PREFIX/
Why are we unpacking a redist instead of building from source when the source is available?

https://github.com/nvidia-holoscan/holoscan-sdk

2025-02-19 19:12 UTC, carterbox commented on recipes/holoscan/compile_examples.sh
> +  -DCUDAToolkit_ROOT=$PREFIX
Also, this test takes a long time to build all the examples. Something shorter like
```
cmake -S $PREFIX/examples/hello_world/cpp $CMAKE_ARGS
```
might be more appropriate.

2025-02-19 19:17 UTC, carterbox commented on recipes/holoscan/build.sh
> +cp -rv bin $PREFIX/
I see that we already discussed this above back in December 2024.

> For gds-tools, onnxruntime and torchvision I will see when we can get respective owners to provide missing DSO, and for TensorRT we'll have to find out a plan for it with respect to conda.

Have you opened issues on the feedstocks for these packages asking for the relevant libraries?

2025-02-22 08:02 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/holoscan/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/holoscan/meta.yaml**:

 * ❌ This recipe is using a compiler, which now requires adding a build dependence on `{{ stdlib("c") }}` as well. Note that this rule applies to each output of the recipe using a compiler. For further details, please see https://github.com/conda-forge/conda-forge.github.io/issues/2102.

For **recipes/holoscan/meta.yaml**:

 * ℹ️ The recipe is not parsable by parser `conda-souschef (grayskull)`. This parser is not currently used by conda-forge, but may be in the future. We are collecting information to see which recipes are compatible with grayskull.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/13471037356](https://github.com/conda-forge/conda-forge-webservices/actions/runs/13471037356). Examine the logs at this URL for more detail.</sub>

2025-02-22 18:15 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/holoscan/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/holoscan/meta.yaml**:

 * ℹ️ The recipe is not parsable by parser `conda-souschef (grayskull)`. This parser is not currently used by conda-forge, but may be in the future. We are collecting information to see which recipes are compatible with grayskull.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/13475399662](https://github.com/conda-forge/conda-forge-webservices/actions/runs/13475399662). Examine the logs at this URL for more detail.</sub>

2025-03-12 17:05 UTC, carterbox commented on recipes/holoscan/build.sh
> +cp -rv python $PREFIX/
Python modules have been moved to site-packages.

2025-03-12 17:07 UTC, carterbox commented on recipes/holoscan/meta.yaml
> +        - rdma-core
The python modules are split into a separate output.

2025-03-12 17:08 UTC, carterbox commented on recipes/holoscan/meta.yaml
> +        - test -d $PREFIX/include/3rdparty
These headers still exist and so do yaml-cpp artifacts.

2025-03-12 17:08 UTC, carterbox commented on recipes/holoscan/meta.yaml
> +  - name: libholoscan-static
the static output has been removed

2025-03-12 19:01 UTC, carterbox requested changes

2025-03-13 14:07 UTC, billysuh7 commented
holoscan is GA. @carterbox would you please review ? Thanks.

2025-03-13 18:13 UTC, carterbox requested changes
There are still many open issues from previous reviews. Please respond to them with questions if you need clarification.

2025-03-13 18:13 UTC, carterbox commented on recipes/holoscan/meta.yaml
> +        - "*libyaml-cpp.so.0.7"                              # Packaged in libholoscan lib, but referened by python/** here
If these libraries are available in libholoscan. Then why no just add libholoscan as a host dependency as suggested in the previous review comment?

https://github.com/conda-forge/staged-recipes/pull/28598#discussion_r1962190367

2025-03-14 14:57 UTC, billysuh7 commented
Hi @carterbox, please let me know if the remaining open issues can be resolved as-is. Holoscan team indicated they'd like to release this (at least the x86-64 one) before Monday (GTC). Thanks.

2025-03-14 15:15 UTC, tbirdso commented on recipes/holoscan/meta.yaml
> +        - test -L $PREFIX/lib/libyaml-cpp.so
Hi @carterbox , joining the discussion as part of the Holoscan team. We've historically packaged `holoscan` for APT with libraries built from source as part of Holoscan or which lacked an APT distribution mechanism for required versions. Acknowledged that there could be risk of dependency conflicts in edge cases here with Conda.

Is this a hard blocker or could we move forward and schedule to revisit Conda dependencies in a near-future release?

2025-03-14 15:18 UTC, tbirdso commented on recipes/holoscan/meta.yaml
> +        - test -d $PREFIX/include/3rdparty
HI @carterbox @billysuh7 , we should reconsider moving headers from Python to C++ Conda packages in the future. Seems like headers should not be a hard blocker for initial Python packaging, do you agree?

See https://github.com/conda-forge/staged-recipes/pull/28598#discussion_r1995762318 for comment on 3rd party artifacts. Current state has passed internal validation.

2025-03-14 15:20 UTC, tbirdso commented on recipes/holoscan/meta.yaml
> +        - pip check
Holoscan CLI has been migrated to a downstream project in a recent release (https://github.com/nvidia-holoscan/holoscan-cli/) and is out of scope for initial packaging work,  no need to validate here.

2025-03-14 19:52 UTC, carterbox commented on recipes/holoscan/meta.yaml
> +        - test -L $PREFIX/lib/libyaml-cpp.so
Yes, this is a hard blocker. yaml-cpp already exists on the channel, and the available versions include 0.7 which I believe is the version used here. No one has mentioned why using the yaml-cpp package is not an acceptable alternative to revending.

https://github.com/conda-forge/yaml-cpp-feedstock
https://anaconda.org/conda-forge/yaml-cpp/files?version=0.7.0

2025-03-14 20:04 UTC, carterbox commented on recipes/holoscan/meta.yaml
> +        - test -d $PREFIX/include/3rdparty
Consider it now. Provide justification for each revended library for why this package is an exception to the packaging standards of this channel.

2025-03-14 20:11 UTC, carterbox commented on recipes/holoscan/meta.yaml
> +        - pip check
I thought I saw a file called `__main__.py` in the install logs.

2025-03-14 20:37 UTC, carterbox commented on recipes/holoscan/meta.yaml
> +        - {{ pin_subpackage("libholoscan", max_pin="x") }}
This was removed.

2025-03-14 20:37 UTC, carterbox commented on recipes/holoscan/meta.yaml
> +      - bin/convert_gxf_entities_to_images.py
A dpendency on python was added.

2025-03-14 20:37 UTC, carterbox commented on recipes/holoscan/meta.yaml
> +      - bin/README.md
No explanation was given. There's still README in bin.

2025-03-14 20:40 UTC, carterbox commented on recipes/holoscan/meta.yaml
> +        This is a runtime package only. Developers should install holoscan or libholoscan-dev to build with Holoscan
The current version of this description is

>         This is a runtime package only. Developers should install holoscan (python) to build with Holoscan

That seems worse to me.

2025-03-14 20:45 UTC, carterbox commented on recipes/holoscan/meta.yaml
> +        - "*libyaml-cpp.so.0.7"                              # Packaged in libholoscan lib, but referened by python/** here
Added the missing host dependency

2025-03-14 20:48 UTC, carterbox commented
@billysuh7

- [ ] https://github.com/conda-forge/staged-recipes/pull/28598#discussion_r1962205590
- [ ] https://github.com/conda-forge/staged-recipes/pull/28598#discussion_r1962207931
- [ ] https://github.com/conda-forge/staged-recipes/pull/28598#discussion_r1962241021
- [ ] https://github.com/conda-forge/staged-recipes/pull/28598#discussion_r1992118004
- [ ] https://github.com/conda-forge/staged-recipes/pull/28598#discussion_r1992119300
- [ ] https://github.com/conda-forge/staged-recipes/pull/28598#discussion_r1996249130

2025-03-14 20:54 UTC, billysuh7 commented on recipes/holoscan/meta.yaml
> +        - test -L $PREFIX/lib/libyaml-cpp.so
@carterbox we are not shipping `libholoscan-dev`, deferring it til next release, because C++ use case has not gone through thorough testing for this release. We are OK in light of this, correct ?

2025-03-14 21:16 UTC, carterbox commented on recipes/holoscan/meta.yaml
> +        - {{ pin_subpackage("libholoscan" ~ soname, exact=True) }}
libprotobuf and libholoscan-dev shouldn't be clobbering. Maybe this is related to revending?

2025-03-14 21:22 UTC, carterbox commented on recipes/holoscan/meta.yaml
> +      skip: true
```suggestion
      # FIXME: Unskip dev package after removing revended packages.
      skip: true
```

2025-03-14 21:24 UTC, carterbox commented on recipes/holoscan/meta.yaml
> +        - pip check
It's not necessary to manually do:

```
- python -c "import holoscan; print(holoscan.__version__)"
```

Testing importability is the purpose of:
```yaml
      imports:
        - holoscan
```

2025-03-14 21:26 UTC, carterbox commented on recipes/holoscan/meta.yaml
> +  - name: libholoscan-static
It should be in the -dev package? Unless holoscan is doing some JIT compilation using this artifact, only developers should need it.

2025-03-14 21:32 UTC, billysuh7 commented on recipes/holoscan/meta.yaml
> +        - {{ pin_subpackage("libholoscan" ~ soname, exact=True) }}
`holoscan` source tarball has` lib/cmake/...` but there is no overlapping files like `utf8_range/utf8_range-targets-release.cmake` above.

2025-03-14 21:32 UTC, billysuh7 commented on recipes/holoscan/meta.yaml
> +        - pip check
Sure, I can remove what I did above

2025-03-14 21:34 UTC, carterbox commented on recipes/holoscan/meta.yaml
> +        - python ={{ python_version }}  # be explicit about python version as holoscan python libs are compiled for given version
I think what you're looking for is something like:

```yaml
run_constrained:
  - libtorch {{ some version spec here }}
```

2025-03-14 21:36 UTC, carterbox commented on recipes/holoscan/meta.yaml
> +        This is a runtime package only. Developers should install holoscan or libholoscan-dev to build with Holoscan
Resolved because dev package is skipped for now

2025-03-14 21:39 UTC, carterbox commented on recipes/holoscan/meta.yaml
> +        - {{ pin_subpackage("libholoscan" ~ soname, exact=True) }}
That message is from an old build. 3.0.0.7. I think we are now at 3.0.0.9 maybe it was cleaned up.

2025-03-14 21:43 UTC, billysuh7 commented on recipes/holoscan/meta.yaml
> +        - {{ pin_subpackage("libholoscan" ~ soname, exact=True) }}
I still see a lot of these with 3.0.0.9 too but only when I enable `libholoscan-dev` build, which is being skipped now.

2025-03-14 21:48 UTC, carterbox commented on recipes/holoscan/meta.yaml
> +        - test -d $PREFIX/include/3rdparty
The issue of revending of third-party headers can be delayed until whenever the -dev package is unskipped.

2025-03-14 21:52 UTC, carterbox commented on recipes/holoscan/meta.yaml
> +        - test -L $PREFIX/lib/libyaml-cpp.so
The issue of revending libyaml-cpp and ucx is still pending. Both would cause collisions with existing packages from the channel.

2025-03-14 22:48 UTC, tbirdso commented on recipes/holoscan/meta.yaml
> +        - test -L $PREFIX/lib/libyaml-cpp.so
Holoscan SDK depends on:
- yaml-cpp 0.7.0: built from source at Holoscan SDK build time with minimal [patch](https://github.com/nvidia-holoscan/holoscan-sdk/blob/main/patches/yaml-cpp.patch)
- UCX 1.17.0: obtained from the Holoscan SDK build environment based on the [TensorRT base container](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorrt)

@billysuh7  could we please generate an rc package relying on the corresponding `conda-forge` packages in place of revending?

2025-03-15 00:16 UTC, billysuh7 commented on recipes/holoscan/meta.yaml
> +  - name: libholoscan-static
Static lib pattern moved to -dev package

2025-03-15 00:16 UTC, billysuh7 commented on recipes/holoscan/meta.yaml
> +        - test -d $PREFIX/include/3rdparty
Thanks. Resolving.

2025-03-15 00:58 UTC, billysuh7 commented on recipes/holoscan/meta.yaml
> +        - {{ pin_subpackage("libholoscan" ~ soname, exact=True) }}
Mystery solved... I need to be more explicit about `lib/cmake` listing in my recipe, I can't just say `lib/cmake` which will include stuff from other packages. Anyway this will be fixed later when `-dev` is shipped in the future.

2025-03-15 00:58 UTC, billysuh7 commented on recipes/holoscan/meta.yaml
> +        - {{ pin_subpackage("libholoscan" ~ soname, exact=True) }}
Will put FIXME comment

2025-03-17 16:45 UTC, merged