Add recipe for bodo
conda-forge/staged-recipes pull request #28648
Opened 2024-12-19 16:43 UTC by srilman

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-12-19 18:36 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/bodo/meta.yaml```) and found it was in an excellent condition.

2024-12-19 18:37 UTC, IsaacWarren commented
I confirm that I am willing to be listed as a maintainer for this recipe.

2024-12-19 18:50 UTC, scott-routledge2 commented
I confirm that I am willing to be listed as a maintainer for this recipe.

2024-12-19 18:58 UTC, ehsantn commented
I confirm that I am willing to be listed as a maintainer for this recipe.

2024-12-19 19:06 UTC, njriasan commented
I confirm that I am willing to be listed as a maintainer for this recipe.

2024-12-19 19:28 UTC, knassre-bodo commented
I confirm that I am willing to be listed as a maintainer for this recipe.

2024-12-19 21:20 UTC, hadia206 commented
I confirm that I am willing to be listed as a maintainer for this recipe.

2024-12-20 17:35 UTC, srilman commented
@conda-forge/help-python-c, ready for review!

2025-01-14 16:37 UTC, srilman commented
@conda-forge/help-python-c, bump

2025-02-17 18:07 UTC, carterbox requested changes

2025-02-17 18:07 UTC, carterbox commented on recipes/bodo/meta.yaml
> +    - libboost-devel =1.85
Use the libboost-headers package since it doesn't look like your are linking to libboost.

There are also overdepending warnings from conda-build about zstd and curl.

2025-02-21 16:40 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/bodo/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/bodo/meta.yaml**:

 * ❌ Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [12]


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/13461195082](https://github.com/conda-forge/conda-forge-webservices/actions/runs/13461195082). Examine the logs at this URL for more detail.</sub>

2025-04-23 15:50 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/bodo/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/bodo/meta.yaml**:

 * ℹ️ top-level output has some malformed specs:
- In section host: `libcurl ~= 8.0`, `hdf5 >=1.14.3,<1.14.4.0a0=mpi_mpich_*`, `mpich 4.1.*=h*`
- In section run: `mpich *=h*`
Requirement spec fields should match the syntax `name [version [build]]`to avoid known issues in conda-build. For example, instead of `name =version=build`, use `name version.* build`. There should be no spaces between version operators and versions either: `python >= 3.8` should be `python >=3.8`.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/14622480174](https://github.com/conda-forge/conda-forge-webservices/actions/runs/14622480174). Examine the logs at this URL for more detail.</sub>

2025-04-24 15:46 UTC, srilman commented
@IsaacWarren @scott-routledge2 Ping

2025-06-20 13:53 UTC, scott-routledge2 commented on recipes/bodo/meta.yaml
> +    - libboost-devel =1.85
Hi @carterbox, thank you for your review. I am taking over this PR from @srilman, I didn't have access to this fork, so I opened a new PR [here](https://github.com/conda-forge/staged-recipes/pull/30214) that supersedes this one. I believe we have addressed all of your comments there.

2025-06-24 16:44 UTC, closed without merging