Add a recipe for openlb 1.7
conda-forge/staged-recipes pull request #28644
Opened 2024-12-19 14:39 UTC by martin-g

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-12-19 14:40 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/openlb/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/openlb/meta.yaml**:

 * ❌ The top level meta keys are in an unexpected order. Expecting ['package', 'source', 'build', 'requirements', 'test', 'about'].
 * ❌ The recipe could do with some maintainers listed in the `extra/recipe-maintainers` section.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12414862960](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12414862960). Examine the logs at this URL for more detail.</sub>

2025-01-03 12:18 UTC, martin-g commented
@conda-forge/help-c-cpp  this is ready for review

2025-01-11 16:50 UTC, carterbox requested changes
Thanks for following our naming convention by appending "-static" to the package name. However, we have a strong preference for dynamic linking on this channel unless there is significant performance uplift from static linking. Could you please patch this project to generate shared libraries instead?

Also, it doesn't seem like you are shipping any header files? How are downstream packages to link against this library without header files or find this library without a package configuration file?

2025-01-14 12:38 UTC, martin-g commented
@carterbox Thank you for the review! I've applied your suggestions! Please take a new look when you have a moment!

2025-01-16 12:33 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint --conda-forge .` from the recipe directory. You can also examine the [workflow logs](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12808933485) for more detail.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12808933485](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12808933485). Examine the logs at this URL for more detail.</sub>

2025-01-16 13:29 UTC, martin-g commented
The linter issue is because I switched to recipe v2 (rattler-build).

2025-01-23 09:38 UTC, xhochy commented
Let's see whether this fixes the linter.

2025-01-23 10:18 UTC, xhochy commented on recipes/openlb/recipe.yaml
> +        then: test -f ${PREFIX}/lib/libolbcore.so
Shouldn't this be?
```suggestion
        then: test -f ${PREFIX}/lib/libolbcore${SHLIB_EXT}
```

2025-01-23 11:54 UTC, martin-g commented on recipes/openlb/recipe.yaml
> +        then: test -f ${PREFIX}/lib/libolbcore.so
Thanks!
Fixed it!

2025-01-23 15:31 UTC, xhochy approved these changes

2025-01-23 15:31 UTC, merged