nvshmem 3.1.7
conda-forge/staged-recipes pull request #28647
Opened 2024-12-19 16:35 UTC by billysuh7

Checklist
- [X] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [X] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [X] Source is from official source.
- [X] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [X] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [X] Build number is 0.
- [X] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [X] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [X] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

Xref: https://github.com/conda-forge/staged-recipes/issues/28111

2024-12-19 16:36 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/nvshmem/meta.yaml```, ```recipes/libnvshmem/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/libnvshmem/meta.yaml**:

 * ❌ The license item is expected in the about section.

For **recipes/libnvshmem/meta.yaml**:

 * ℹ️ The recipe is not parsable by parser `conda-souschef (grayskull)`. This parser is not currently used by conda-forge, but may be in the future. We are collecting information to see which recipes are compatible with grayskull.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12416875254](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12416875254). Examine the logs at this URL for more detail.</sub>

2024-12-19 16:42 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/nvshmem/meta.yaml```, ```recipes/libnvshmem/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/libnvshmem/meta.yaml**:

 * ℹ️ The recipe is not parsable by parser `conda-souschef (grayskull)`. This parser is not currently used by conda-forge, but may be in the future. We are collecting information to see which recipes are compatible with grayskull.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12416965439](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12416965439). Examine the logs at this URL for more detail.</sub>

2025-01-16 01:08 UTC, seth-howell commented on recipes/libnvshmem/meta.yaml
> +        - test -f $PREFIX/lib/libnvshmem.a
Can we also add the bitcode library now? That might be easier than doing another pass.The first 3.2 builds are in URM now:

https://urm.nvidia.com/ui/repos/tree/General/sw-nvshmem-generic-local/NVSHMEM/gpu_comms_cuda12.0_compatibility/3.2.2/libnvshmem_cuda12-linux-x86_64-3.2.2.tar.gz

2025-01-16 01:08 UTC, seth-howell commented on recipes/libnvshmem/meta.yaml
> +source:
I have checked to make sure the files are in the required places.

Let me run an additional test to make sure the binaries can find the libraries correctly.

2025-01-16 16:11 UTC, billysuh7 commented on recipes/libnvshmem/meta.yaml
> +        - test -f $PREFIX/lib/libnvshmem.a
Size is about 60MB which isn't too too bad, but I understand conda generally discourage static packages so I guess I'll take 'em out. About the bitcode - this PR is for nvshmem 3.1.7, so once this has gone through vetting and is released for conda, I can work on the next version and include bitcode at that time.

2025-01-16 18:27 UTC, seth-howell commented on recipes/libnvshmem/meta.yaml
> +        - test -f $PREFIX/lib/libnvshmem.a
Sorry, just libnvshmem.a. libnvshmem_device.a likely has to stay for jit compiling. This is something that's been communicated to me from cuBLASMp.

2025-01-16 18:41 UTC, billysuh7 commented on recipes/libnvshmem/meta.yaml
> +        - test -f $PREFIX/lib/libnvshmem.a
I see. Anyway, I just realized that out of 130MB, the static conda package only takes up 12MB so it is inconsequential either way :) For now I'll take out libnvshmem.a

2025-01-17 18:15 UTC, seth-howell commented on recipes/libnvshmem/meta.yaml
> +source:
I have confirmed the following:

Various NVSHMEM Bootstraps can be used, as long as the LD_LIBRARY_PATH is properly specified to include the desired packages.
The Bootstraps can be found automatically by the library
The performance tests in src can be compiled against NVSHMEM. The kitmaker libraries work properly.

From my end, the configuration is good.

2025-02-05 14:22 UTC, adibbley commented on recipes/libnvshmem/meta.yaml
> +        - test -f $PREFIX/lib/libnvshmem.a
Typically we have been fine adding any static library to `-static` outputs, was there another reason we would take out `libnvshmem.a` for now?

2025-02-05 16:49 UTC, seth-howell commented on recipes/libnvshmem/meta.yaml
> +        - test -f $PREFIX/lib/libnvshmem.a
libnvshmem.a is a deprecated library and not used. libnvshmem_device.a is what will be used by our users. I don't think the extra space is worth it. I would prefer to not change the recipe right now, and 
We have a bitcode library (libnvshmem_device.bc) coming in 2.1. I believe it's something Billy has planned for an additional layer to come later.

2025-02-05 17:59 UTC, carterbox requested changes

2025-02-05 17:59 UTC, carterbox commented on recipes/nvshmem/meta.yaml
> +{% set version = "3.1.7" %}
Why a separate recipe for this metapackage? Are there plans to add additional packages to the nvshmem umbrella?

2025-02-05 17:59 UTC, carterbox commented on recipes/libnvshmem/meta.yaml
> +outputs:
```suggestion
build:
  number: 0
  skip: true  # [not (linux64 or aarch64)]
  skip: true  # [cuda_compiler_version in (None, "None") or (aarch64 and (cuda_compiler_version or "").startswith("11"))]

requirements:
  build:
    - cf-nvidia-tools 1  # [linux]

outputs:
```

2025-02-05 17:59 UTC, carterbox commented on recipes/libnvshmem/build-libnvshmem.sh
> +mkdir -p $PREFIX/lib/cmake/nvshmem/
```suggestion
set -e

check-glibc bin/* lib/*

mkdir -p $PREFIX/lib/cmake/nvshmem/
```
https://github.com/conda-forge/cf-nvidia-tools-feedstock/tree/main/recipe

2025-02-05 17:59 UTC, carterbox commented on recipes/libnvshmem/build-libnvshmem.sh
> +#!/bin/bash
Rename this file build.sh

2025-02-05 17:59 UTC, carterbox commented on recipes/libnvshmem/meta.yaml
> +        cp -rv lib $PREFIX/
```suggestion
```

2025-02-05 17:59 UTC, carterbox commented on recipes/libnvshmem/meta.yaml
> +    script_interpreter: /bin/bash
```suggestion
```

2025-02-05 17:59 UTC, carterbox commented on recipes/libnvshmem/meta.yaml
> +        cp -rv lib/libnvshmem_device.a $PREFIX/lib/
```suggestion
```

2025-02-05 17:59 UTC, carterbox commented on recipes/libnvshmem/meta.yaml
> +      - {{ pin_subpackage("libnvshmem" ~ soname, max_pin="x") }}
```suggestion
      run_exports:
        - {{ pin_subpackage("libnvshmem" ~ soname, max_pin=None) }}
```
I think this needs to be indented one level?

Also, the max_pin should be None if the project actually uses the soname to indicate ABI compatability.

2025-02-05 17:59 UTC, carterbox commented on recipes/nvshmem/meta.yaml
> +{% set version = "3.1.7" %}
Technically, this package is redundant because you will get the same deps from installing libnvshmem-static.

2025-02-05 18:06 UTC, carterbox commented on recipes/libnvshmem/meta.yaml
> +        - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
Enhanced CUDA compatibility is not implemented correctly for this output. You need to ignore exports from the CUDA compiler.

2025-02-05 18:08 UTC, carterbox commented on recipes/libnvshmem/meta.yaml
> +        - cuda-version {{ cuda_compiler_version }}
Please check that cuda_compiler_version is defined when you haven't used the compiler package in the build requirements.

2025-02-11 18:19 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/libnvshmem/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/libnvshmem/meta.yaml**:

 * ❌ This recipe is using a compiler, which now requires adding a build dependence on `{{ stdlib("c") }}` as well. Note that this rule applies to each output of the recipe using a compiler. For further details, please see https://github.com/conda-forge/conda-forge.github.io/issues/2102.

For **recipes/libnvshmem/meta.yaml**:

 * ℹ️ The recipe is not parsable by parser `conda-souschef (grayskull)`. This parser is not currently used by conda-forge, but may be in the future. We are collecting information to see which recipes are compatible with grayskull.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/13269709230](https://github.com/conda-forge/conda-forge-webservices/actions/runs/13269709230). Examine the logs at this URL for more detail.</sub>

2025-02-11 19:34 UTC, billysuh7 commented on recipes/libnvshmem/meta.yaml
> +outputs:
Done. Thanks!

2025-02-11 19:35 UTC, billysuh7 commented on recipes/libnvshmem/build-libnvshmem.sh
> +mkdir -p $PREFIX/lib/cmake/nvshmem/
Done. Thanks!

2025-02-11 19:39 UTC, billysuh7 commented on recipes/libnvshmem/meta.yaml
> +        cp -rv lib $PREFIX/
I removed `run_exports`: section only, but I still need the `script:` section for this particular package

2025-02-11 19:40 UTC, billysuh7 commented on recipes/libnvshmem/meta.yaml
> +    script_interpreter: /bin/bash
Please see my earlier comment on this

2025-02-11 19:41 UTC, billysuh7 commented on recipes/libnvshmem/meta.yaml
> +        cp -rv lib/libnvshmem_device.a $PREFIX/lib/
I am keeping this section for the same reason, but modified the pattern to add all static libs in order for cmake test to pass. Otherwise I'd get 

```
CMake Error at /home/conda/staged-recipes/build_artifacts/libnvshmem-split_1739198615629/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/cmake/nvshmem/NVSHMEMTargets.cmake:190 (message):
    The imported target "nvshmem::nvshmem" references the file
  
       "/home/conda/staged-recipes/build_artifacts/libnvshmem-split_1739198615629/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/libnvshmem.a"
  
    but this file does not exist. 
```

2025-02-11 19:43 UTC, billysuh7 commented on recipes/libnvshmem/meta.yaml
> +        - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
Thank you for the headsup! Hopefully fixed now. The `cuda-cudart` dependency is no longer constrained to any version, leaving that decision up to `cuda-version`.

2025-02-11 19:43 UTC, billysuh7 commented on recipes/libnvshmem/meta.yaml
> +        - cuda-version {{ cuda_compiler_version }}
Done

2025-02-11 19:43 UTC, billysuh7 commented on recipes/libnvshmem/meta.yaml
> +        - test -L $PREFIX/lib/nvshmem_transport_ucx.so
Done

2025-02-11 19:48 UTC, billysuh7 commented on recipes/libnvshmem/meta.yaml
> +      - {{ pin_subpackage("libnvshmem" ~ soname, max_pin="x") }}
Fixed indentation and set `max_pin` to `None`. But I wonder how we can enforce ABI compatibility strictly ? Are leaving the responsibility to the end user to understand what they are doing based on the `soname` ?

2025-02-11 20:15 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/libnvshmem/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/libnvshmem/meta.yaml**:

 * ℹ️ The recipe is not parsable by parser `conda-souschef (grayskull)`. This parser is not currently used by conda-forge, but may be in the future. We are collecting information to see which recipes are compatible with grayskull.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/13271675037](https://github.com/conda-forge/conda-forge-webservices/actions/runs/13271675037). Examine the logs at this URL for more detail.</sub>

2025-02-11 23:39 UTC, carterbox requested changes

2025-02-11 23:39 UTC, carterbox commented on recipes/libnvshmem/build-libnvshmem.sh
> +#!/bin/bash
Typically, I use a global `build.sh` to copy everything to $PREFIX, then use `files:` in each output to select which files go to each output. Here you are using `build: script:` in each output to move the files for each output separately. This is allowed, but unexpected. It's also irregular because two outputs are using scripts defined in the meta.yaml and one is using a separate bash script.

https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#specifying-files-to-include-in-output

2025-02-11 23:39 UTC, carterbox commented on recipes/libnvshmem/meta.yaml
> +      - lib/nvshmem_transport*.so.*
```suggestion
      script: |
        mkdir -p $PREFIX/lib  # maybe two lines 
        cp -v lib/*.so.* $PREFIX/lib/
```
This is redundant. You should be able to do this in one or two line(s).

2025-02-11 23:39 UTC, carterbox commented on recipes/libnvshmem/meta.yaml
> +      - lib/libnvshmem*.a
```suggestion
      script: |
        cp -rv lib/libnvshmem*.a $PREFIX/lib/
```
See other comment about possibly needing to make $PREFIX/lib before you try to copy into it.

2025-02-11 23:39 UTC, carterbox commented on recipes/libnvshmem/build-libnvshmem.sh
> +cp -rv lib/nvshmem_transport*.so $PREFIX/lib
```suggestion
cp -rv lib/*.so $PREFIX/lib
```
There should only be shared libraries that we want to install in the source tar, right?

2025-02-11 23:39 UTC, carterbox commented on recipes/libnvshmem/build-libnvshmem.sh
> +$BUILD_PREFIX/bin/check-glibc bin/* lib/* bin/examples/* bin/perftest/device/coll/* bin/perftest/device/pt-to-pt/* bin/perftest/host/coll/* bin/perftest/host/init/* bin/perftest/host/pt-to-pt/*
"$BUILD_PREFIX/bin/check-glibc" If you need to full path for this tool to work it's because you're using this script in an unintended way. I suggest moving this call to check-glibc into `build.sh` and moving the dependency on `cf-nvidia-tools` to the top-level requirements.

The install steps can stay in this script.

2025-02-11 23:57 UTC, carterbox commented on recipes/libnvshmem/meta.yaml
> +      - {{ pin_subpackage("libnvshmem" ~ soname, max_pin="x") }}
If we are building libnvshmem version 1.2.3 then this template would be de-templated to something like:

```
- libnvshmem1 >=1.2.3
```

The `soname` is already a promise of ABI compatibility because of the way that unix searches for shared libraries. Any library named `foo.so.4` is assumed to be backward compatible with any earlier `foo.so.4`. Therefore, any library looking for libnvshmem5 can run with the latest version of whatever libnvshmem5 is available. This is why there is no upper bound.

The `libnvshmem3` package is not intended to be installed directly by humans. All downstream users should be installing `libnvshmem-dev`. If you think end users of this package want to be able to install the shared libraries directly without any of the headers or config, we can add a non-versioned `libnvshmem` output.

2025-02-12 00:08 UTC, carterbox commented on recipes/libnvshmem/meta.yaml
> +  - name: libnvshmem{{ soname }}
```suggestion
  - name: libnvshmem
    requirements:
      run:
        - {{ pin_subpackage("libnvshmem" ~ soname, max_pin=None) }}

  - name: libnvshmem{{ soname }}
```
If you want a non-ABI-versioned metapackage. part 1 of 2.

2025-02-12 00:08 UTC, carterbox commented on recipes/libnvshmem/meta.yaml
> +        - {{ pin_subpackage("libnvshmem" ~ soname, max_pin=None) }}
```suggestion
      run_exports:
        - {{ pin_subpackage("libnvshmem", max_pin=None) }}
        - {{ pin_subpackage("libnvshmem" ~ soname, max_pin=None) }}
```
If you want a non-ABI-versioned metapackage. part 2 of 2.

2025-02-13 04:45 UTC, billysuh7 commented on recipes/libnvshmem/meta.yaml
> +      - {{ pin_subpackage("libnvshmem" ~ soname, max_pin="x") }}
Thanks for the explanation. This helps!

2025-02-13 04:46 UTC, billysuh7 commented on recipes/libnvshmem/meta.yaml
> +      - lib/nvshmem_transport*.so.*
I've decided to have global `build.sh` as you suggested so this has been taken out

2025-02-13 04:48 UTC, billysuh7 commented on recipes/libnvshmem/build-libnvshmem.sh
> +#!/bin/bash
I will go with global `build.sh` after experimenting with both ways, global vs per-output install to `$PREFIX`. Thanks!

2025-02-13 04:49 UTC, billysuh7 commented on recipes/libnvshmem/meta.yaml
> +      - lib/libnvshmem*.a
This will be replaced with global `build.sh`

2025-02-13 04:50 UTC, billysuh7 commented on recipes/libnvshmem/build-libnvshmem.sh
> +cp -rv lib/nvshmem_transport*.so $PREFIX/lib
Yes - and I will have global `build.sh `with greatly simplified file patterns to copy

2025-02-13 04:51 UTC, billysuh7 commented on recipes/libnvshmem/meta.yaml
> +  - name: libnvshmem{{ soname }}
I won't bother with this after your explanation of how OS searches for ABI libs.

2025-02-13 04:51 UTC, billysuh7 commented on recipes/libnvshmem/meta.yaml
> +        - {{ pin_subpackage("libnvshmem" ~ soname, max_pin=None) }}
I won't bother with this after your explanation of how OS searches for ABI libs.

2025-02-13 21:16 UTC, merged