Add R package qgg
conda-forge/staged-recipes pull request #28661
Opened 2024-12-20 07:43 UTC by psoerensen

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-12-20 07:44 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/qgg/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/qgg/meta.yaml**:

 * ❌ The recipe could do with some maintainers listed in the `extra/recipe-maintainers` section.
 * ❌ The recipe must have a `build/number` section.
 * ❌ This recipe is using a compiler, which now requires adding a build dependence on `{{ stdlib("c") }}` as well. Note that this rule applies to each output of the recipe using a compiler. For further details, please see https://github.com/conda-forge/conda-forge.github.io/issues/2102.

For **recipes/qgg/meta.yaml**:

 * ℹ️ License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12427543521](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12427543521). Examine the logs at this URL for more detail.</sub>

2024-12-20 19:46 UTC, danielnachun commented
Thanks for this submission.  Can you try to generate this recipe using `conda skeleton cran qgg`?  This will create a recipe that is compliant with what we need for Conda-Forge.  There's some comments we'll need to clean up afterward but the skeleton will cover most of what is needed.

2024-12-21 15:12 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-qgg/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/r-qgg/meta.yaml**:

 * ℹ️ Jinja2 variable references are suggested to take a ``{{<one space><variable name><one space>}}`` form. See lines [58].


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12446265901](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12446265901). Examine the logs at this URL for more detail.</sub>

2024-12-21 15:29 UTC, psoerensen commented
Hi Daniel, I have updated the recipe using "conda skeleton cran qgg".
Please let me know if there are other things I should change. Kind regards
Peter

On Fri, Dec 20, 2024 at 8:46 PM Daniel Nachun ***@***.***>
wrote:

> Thanks for this submission. Can you try to generate this recipe using conda
> skeleton cran qgg? This will create a recipe that is compliant with what
> we need for Conda-Forge. There's some comments we'll need to clean up
> afterward but the skeleton will cover most of what is needed.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/conda-forge/staged-recipes/pull/28661#issuecomment-2557625545>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEEK34D3PTKEYN64XCI5FSL2GRX2XAVCNFSM6AAAAABT6SYUEOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNJXGYZDKNJUGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-21 17:56 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-qgg/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/r-qgg/meta.yaml**:

 * ❌ You're setting a requirement on sysroot_linux-<arch> directly; this should now be done by adding a build dependence on `{{ stdlib("c") }}`, and overriding `c_stdlib_version` in `recipe/conda_build_config.yaml` for the respective platform as necessary. For further details, please see https://github.com/conda-forge/conda-forge.github.io/issues/2102.

For **recipes/r-qgg/meta.yaml**:

 * ℹ️ Jinja2 variable references are suggested to take a ``{{<one space><variable name><one space>}}`` form. See lines [69].


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12447283049](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12447283049). Examine the logs at this URL for more detail.</sub>

2024-12-21 18:03 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-qgg/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/r-qgg/meta.yaml**:

 * ℹ️ Jinja2 variable references are suggested to take a ``{{<one space><variable name><one space>}}`` form. See lines [68].


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12447320203](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12447320203). Examine the logs at this URL for more detail.</sub>

2024-12-21 19:35 UTC, danielnachun requested changes
I've made some suggestions. Mostly to clean up some cruft from the recipe generator, as well as a fix for Windows.  Let's see after this the Windows build passes and then we should be good to go.

2024-12-21 19:35 UTC, danielnachun commented on recipes/r-qgg/meta.yaml
> +    - {{ stdlib('c') }}
```suggestion
```
This is only needed in the `build` requirements

2024-12-21 19:35 UTC, danielnachun commented on recipes/r-qgg/meta.yaml
> +    - {{native}}gcc-libs         # [win]
```suggestion
```
This no longer needed - `conda skeleton cran` is a little outdated now but deleting this should allow your Windows build to progress, hopefully fixing it.

2024-12-21 19:35 UTC, danielnachun commented on recipes/r-qgg/meta.yaml
> +    - {{ stdlib('c') }}
```suggestion
```
This is only needed in `build` requirements.

2024-12-21 19:35 UTC, danielnachun commented on recipes/r-qgg/meta.yaml
> +    # You can put additional test commands to be run here.
```suggestion
```
Most of these comments are just helpers that can be deleted now - I'll make a suggestion for that ones that should be deleted.

2024-12-21 19:35 UTC, danielnachun commented on recipes/r-qgg/meta.yaml
> +    # Put any additional test requirements here.
```suggestion
```

2024-12-21 19:35 UTC, danielnachun commented on recipes/r-qgg/meta.yaml
> +    - {{ stdlib("c") }}
```suggestion
    - {{ stdlib("c") }}
    - {{ stdlib("m2w64_c") }}
```
We need `m2w64_c` for Windows here.

2024-12-21 19:35 UTC, danielnachun commented on recipes/r-qgg/meta.yaml
> +  # If this is a new build for the same version, increment the build number.
```suggestion
```
`merge_build_host` should no longer be needed on Windows

2024-12-21 19:35 UTC, danielnachun commented on recipes/r-qgg/meta.yaml
> +{% set native = 'm2w64-' if win else '' %}
```suggestion
```
This is no longer needed

2024-12-21 19:35 UTC, danielnachun commented on recipes/r-qgg/meta.yaml
> +  license_family: GPL3
```suggestion
```
This is no longer needed.

2024-12-21 19:35 UTC, danielnachun commented on recipes/r-qgg/build.sh
> +# https://github.com/jeroen/autobrew/issues/3
```suggestion
```

2024-12-21 19:35 UTC, danielnachun commented on recipes/r-qgg/build.sh
> +# for a list of environment variables that are set during the build process.
```suggestion
```

2024-12-21 19:35 UTC, danielnachun commented on recipes/r-qgg/meta.yaml
> +  # no skip
```suggestion
```

2024-12-21 19:35 UTC, danielnachun commented on recipes/r-qgg/meta.yaml
> +  # This is required to make R link correctly on Linux.
```suggestion
```

2024-12-21 20:54 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-qgg/meta.yaml```) and found it was in an excellent condition.

2024-12-21 21:27 UTC, psoerensen commented
Not sure if I have done the right thing - still issues with the builds

2024-12-22 07:31 UTC, danielnachun commented on recipes/r-qgg/meta.yaml
> +    - libgfortran
```suggestion
    - libgfortran
```
I think this is no longer needed either, and is one of the reasons for some of the failures

2024-12-22 07:31 UTC, danielnachun commented on recipes/r-qgg/meta.yaml
> +    - {{ stdlib("m2w64_c") }}
```suggestion
    - {{ stdlib("c") }}  # [not win]
    - {{ stdlib("m2w64_c") }}  #[win]
```
I forgot the selectors here, sorry about that.

2024-12-22 07:31 UTC, danielnachun commented on recipes/r-qgg/meta.yaml
> +    - libgfortran
```suggestion
```
See above that this shouldn't be needed.

2024-12-22 07:31 UTC, danielnachun commented on recipes/r-qgg/meta.yaml
> +    - libopenblas
This may also be unneeded, but let's see what happens after you fix the other issues first.

2024-12-22 08:14 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-qgg/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/r-qgg/meta.yaml**:

 * ❌ Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [46]


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12452571339](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12452571339). Examine the logs at this URL for more detail.</sub>

2024-12-22 08:57 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-qgg/meta.yaml```) and found it was in an excellent condition.

2024-12-22 16:26 UTC, psoerensen commented
I made additional changes with a bit of "trial and error" and search in other recipes. Check passes, but I am not sure if things are OK.

2024-12-22 18:08 UTC, danielnachun reviewed
The recipe is in great shape - I've just suggested a few small cleanups.  Generally for R recipes we try to let `r-base` and the `compiler` packages handle all the dependencies which are not R packages.  As long as the build passes after this cleanup, we should be all set!

2024-12-22 18:08 UTC, danielnachun commented on recipes/r-qgg/meta.yaml
> +    - libopenblas
```suggestion
```
This should also be brought in through `r-base`, so we can remove it here.

2024-12-22 18:08 UTC, danielnachun commented on recipes/r-qgg/meta.yaml
> +    - m2w64-gcc-libgfortran  # [win]
```suggestion
```
This should be added automatically by `{{ compiler('m2w4_fortran') }}` - let's remove it and see what happens.

2024-12-22 18:08 UTC, danielnachun commented on recipes/r-qgg/meta.yaml
> +    - libopenblas
```suggestion
```
This should be unneeded - see above comment.

2024-12-22 18:08 UTC, danielnachun commented on recipes/r-qgg/meta.yaml
> +
```suggestion
```
Although `conda-build` reports these as unneeded, they are definitely necessary.  The output is unfortunately a bit confusing.

2024-12-22 18:46 UTC, psoerensen commented
I made the suggested changes. However check fails now. I had added these arguments in order to get them to pass. Please let me know if you have alternative suggestions to get it to pass.

2024-12-22 19:53 UTC, danielnachun commented
Let's put back what you had - there are some issues this may be uncovering relating to run exports, but these need to be fixed in other packages, not here.  Once that's done we'll be all set here.

2024-12-22 20:57 UTC, psoerensen commented
Added back and checks pass again. Looking forward to understand what is happening. Thanks for the help!

2024-12-22 23:32 UTC, danielnachun commented
Great work @psoerensen!  @conda-forge/staged-recipes @conda-forge/help-r This is ready for review.

2024-12-23 07:06 UTC, psoerensen commented
@conda-forge/help-r @conda-forge/help-c-cpp @conda-forge/help-cdts

This recipe contains an R package (`qgg`) that includes both C++ and Fortran code. Please review. Thank you!

2024-12-23 14:07 UTC, mfansler requested changes
Thanks for submitting this! ❤️ 

There are a few things to tidy up before merging.

@danielnachun thanks for helping with this. A couple notes:
  - `conda_r_skeleton_helper` is the canonical way to generate recipes for CRAN packages;
  - until R migration is closed out, `staged-recipes` Windows builds are pre-UCRT and therefore might still need the `native` variable, build-host merge, etc.. Often easiest is just to recommend skipping on Windows and postpone troubleshooting until the UCRT migration hits the feedstock.

2024-12-23 14:09 UTC, mfansler commented on recipes/r-qgg/meta.yaml
> +  license: GPL-3.0-or-later
@psoerensen just noticed your the author 🤦  So if you want the v3+ here, feel free to ignore this suggestion.

2024-12-23 14:36 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-qgg/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/r-qgg/meta.yaml**:

 * ℹ️ The recipe is not parsable by parser `conda-forge-tick (the bot)`. Your recipe  may not receive automatic updates and/or may not be compatible with conda-forge's infrastructure. Please check the logs for more information and ensure your recipe can be parsed.
 * ℹ️ The recipe is not parsable by parser `conda-souschef (grayskull)`. This parser is not currently used by conda-forge, but may be in the future. We are collecting information to see which recipes are compatible with grayskull.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12468456002](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12468456002). Examine the logs at this URL for more detail.</sub>

2024-12-23 14:37 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-qgg/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/r-qgg/meta.yaml**:

 * ❌ There are 1 too many lines.  There should be one empty line at the end of the file.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12468461125](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12468461125). Examine the logs at this URL for more detail.</sub>

2024-12-23 15:49 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-qgg/meta.yaml```) and found it was in an excellent condition.

2024-12-23 15:50 UTC, mfansler approved these changes
Looks good!

2024-12-23 16:15 UTC, merged