add conda_r_skeleton_helper recipe for r-qs2
conda-forge/staged-recipes pull request #28664
Opened 2024-12-20 11:19 UTC by brendanf

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-12-20 11:37 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/r-qs2/meta.yaml```) and found it was in an excellent condition.

2025-01-16 10:34 UTC, mfansler requested changes
Thanks for submitting this! ❤️ 

Couple suggestions to move this forward.

2025-01-16 10:34 UTC, mfansler commented on recipes/r-qs2/meta.yaml
> +    - '*/Rlapack.dll'  # [win]
I believe you can whitelist libtbb because it gets picked up via a non-standard path (i.e., vendored by r-rcppparallel):

```suggestion
    - '*/Rlapack.dll'  # [win]
    - '*/libtbb.*'
```

2025-01-16 10:34 UTC, mfansler commented on recipes/r-qs2/meta.yaml
> +  missing_dso_whitelist:
Maybe just skip Windows for now, unless you really want it compiled for R 4.1 (the only Win variant supported on `staged-recipes`). Once in feedstock, the migrator will swing by and try adding Windows back for 4.3 and 4.4.

```suggestion
  skip: true  # [win]
  missing_dso_whitelist:
```

2025-01-16 10:35 UTC, mfansler commented on recipes/r-qs2/meta.yaml
> +    - '*/Rlapack.dll'  # [win]
Also, I'm not sure why the Linux version doesn't shows that it detects TBB, but then doesn't include a `-ltbb` flag when linking. Maybe that's an issue with upstream?

2025-01-16 10:59 UTC, brendanf commented
Thanks @mfansler

Regarding `-ltbb`, apparently RcppParallel always includes it in `tbbLdFlags()` (and thus `LdFlags()` and `RcppParallelLibs()`) [on OSx, but not linux](https://github.com/RcppCore/RcppParallel/blob/965e1988ec122ad24da6f0e15f7e292ae77cd316/R/tbb.R#L109-L114).

2025-01-16 14:11 UTC, mfansler approved these changes
LGTM - thanks again!

2025-01-16 14:11 UTC, merged