Add ndcurves
conda-forge/staged-recipes pull request #28663
Opened 2024-12-20 10:45 UTC by jorisv

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-12-20 10:47 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/ndcurves/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/ndcurves/meta.yaml**:

 * ❌ license_file entry is missing, but is required.

For **recipes/ndcurves/meta.yaml**:

 * ℹ️ The recipe is not parsable by parser `conda-souschef (grayskull)`. This parser is not currently used by conda-forge, but may be in the future. We are collecting information to see which recipes are compatible with grayskull.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12430039890](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12430039890). Examine the logs at this URL for more detail.</sub>

2024-12-20 10:49 UTC, ManifoldFR commented
I agree to be a maintainer of this package

2024-12-20 15:47 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/ndcurves/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/ndcurves/meta.yaml**:

 * ℹ️ The recipe is not parsable by parser `conda-souschef (grayskull)`. This parser is not currently used by conda-forge, but may be in the future. We are collecting information to see which recipes are compatible with grayskull.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12434323711](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12434323711). Examine the logs at this URL for more detail.</sub>

2024-12-20 21:14 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/ndcurves/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/ndcurves/meta.yaml**:

 * ❌ license_file entry is missing, but is required.

For **recipes/ndcurves/meta.yaml**:

 * ℹ️ The recipe is not parsable by parser `conda-souschef (grayskull)`. This parser is not currently used by conda-forge, but may be in the future. We are collecting information to see which recipes are compatible with grayskull.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12438552471](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12438552471). Examine the logs at this URL for more detail.</sub>

2024-12-31 14:26 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/ndcurves/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/ndcurves/meta.yaml**:

 * ℹ️ The recipe is not parsable by parser `conda-souschef (grayskull)`. This parser is not currently used by conda-forge, but may be in the future. We are collecting information to see which recipes are compatible with grayskull.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12560659788](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12560659788). Examine the logs at this URL for more detail.</sub>

2025-01-01 20:47 UTC, jorisv commented
@conda-forge/staged-recipes @conda-forge/help-c-cpp This recipe is ready for review.

2025-01-08 11:12 UTC, jorisv commented
@conda-forge/staged-recipes @conda-forge/help-c-cpp we are still ready !

2025-01-11 13:44 UTC, xhochy requested changes

2025-01-11 13:44 UTC, xhochy commented on recipes/ndcurves/meta.yaml
> +        - clang  # [win]
Please add a conda_build_config.yaml with c_compiler: - clang
```suggestion
```

2025-01-11 13:44 UTC, xhochy commented on recipes/ndcurves/meta.yaml
> +        - pinocchio
These should not need to be here 
```suggestion
```

2025-01-13 12:37 UTC, jorisv commented
@xhochy Thank's for the review. I have applied it.

2025-01-23 09:43 UTC, xhochy approved these changes

2025-01-23 09:43 UTC, merged