Add AdaptiveCpp
conda-forge/staged-recipes pull request #28679
Opened 2024-12-22 01:53 UTC by jeongseok-meta

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-12-22 01:54 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/AdaptiveCpp/meta.yaml```) and found it was in an excellent condition.

2024-12-22 08:49 UTC, jeongseok-meta commented
@conda-forge/help-c-cpp, ready for review!

2025-01-06 03:33 UTC, jeongseok-meta commented
@conda-forge/help-c-cpp Could this PR receive some attention? Thank you!

2025-01-11 17:18 UTC, carterbox requested changes

2025-01-11 17:18 UTC, carterbox commented on recipes/AdaptiveCpp/meta.yaml
> +    - llvm >=14,<19
conda has detected unused run dependencies. Could you please supress unused exports?

```
WARNING (adaptivecpp): run-exports library package conda-forge/linux-64::spirv-tools==2024.3=h84d6215_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (adaptivecpp): dso library package conda-forge/linux-64::libboost==1.84.0=h6c02f8c_7 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (adaptivecpp): run-exports library package conda-forge/linux-64::llvm==18.1.8=h1c4df35_2 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (adaptivecpp): run-exports library package conda-forge/linux-64::llvm-openmp==18.1.8=hf5423f3_1 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
```

Possibly you may only need libboost-headers instead of libboost-devel.

2025-01-11 17:18 UTC, carterbox commented on recipes/AdaptiveCpp/meta.yaml
> +    - if not exist %PREFIX%\\Library\\lib\\cmake\\AdaptiveCpp\\adaptivecpp-config.cmake exit 1  # [win]
Please also check for a library, a header, and that the CLI tools run.

2025-01-11 17:18 UTC, carterbox commented on recipes/AdaptiveCpp/meta.yaml
> +    - if not exist %PREFIX%\\Library\\lib\\cmake\\AdaptiveCpp\\adaptivecpp-config.cmake exit 1  # [win]
I suggest that you try to compile a simple test program with these configs in order to check that the paths in these cmake files are correct.

Alternatively, you can manually look to see that they don't contain hardcoded paths to the BUILD_PREFIX. Only paths to the placeholder prefix are valid because those will be replaced at install time with the end user's environment path.

2025-01-11 18:15 UTC, jeongseok-meta commented on recipes/AdaptiveCpp/bld.bat
> +  -DWITH_CUDA_BACKEND=OFF ^
Yes, but could we add backends, including CUDA, OpenCL, and OpenMP, after creating the feedstock for faster iteration if it's acceptable?

2025-01-11 18:45 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint --conda-forge .` from the recipe directory. You can also examine the [workflow logs](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12726730168) for more detail.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12726730168](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12726730168). Examine the logs at this URL for more detail.</sub>

2025-01-11 18:48 UTC, jeongseok-meta commented on recipes/AdaptiveCpp/meta.yaml
> +    - llvm >=14,<19
Only adding `libboost-headers` fails due to missing components:

```
2025-01-11T18:33:56.7315453Z -- Could NOT find Boost (missing: context fiber) (found version "1.84.0")
2025-01-11T18:33:56.7320574Z CMake Error at CMakeLists.txt:104 (message):
2025-01-11T18:33:56.7321619Z   Please provide the path to the root directory of the boost installation
2025-01-11T18:33:56.7322444Z   using the -DBOOST_ROOT option
```

Let me add `libboost` as well to see if it can resolve it.

2025-01-11 19:13 UTC, jeongseok-meta commented on recipes/AdaptiveCpp/meta.yaml
> +    - llvm >=14,<19
It appears that `libboost-devel` is indeed required, as it needs to link to `context` and `fiber`. To suppress the warning, I will add `libboost-devel` to `ignore_run_exports`.

2025-01-11 19:23 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/AdaptiveCpp/meta.yaml```) and found it was in an excellent condition.

2025-01-11 20:36 UTC, carterbox commented on recipes/AdaptiveCpp/meta.yaml
> +    - llvm >=14,<19
I'm not familiar with boost. How is that these modules are linked, but not needed at runtime?

2025-01-11 20:37 UTC, carterbox commented on recipes/AdaptiveCpp/bld.bat
> +  -DWITH_CUDA_BACKEND=OFF ^
Yes. That's acceptable.

2025-01-11 20:47 UTC, carterbox requested changes

2025-01-11 20:47 UTC, carterbox commented on recipes/AdaptiveCpp/meta.yaml
> +    - "%PREFIX%\\Library\\bin\\acpp-info.exe"  # [win]
```suggestion
    - acpp-info  # [not win]
    - if not exist %PREFIX%\\Library\\include\\AdaptiveCpp\\SYCL\\sycl.hpp exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\AdaptiveCpp\\adaptivecpp-config.cmake exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\acpp-common.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\acpp-common.dll exit 1  # [win]
    - acpp-info.exe  # [win]
```
If these CLIs are installed correctly, they should be on the path and they shouldn't need to be accessed using the full name.

2025-01-11 20:47 UTC, carterbox commented on recipes/AdaptiveCpp/meta.yaml
> +    - llvm >=14,<19
Also, there's still warnings about spriv and llvm packages.

2025-01-11 20:49 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint --conda-forge .` from the recipe directory. You can also examine the [workflow logs](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12727489976) for more detail.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12727489976](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12727489976). Examine the logs at this URL for more detail.</sub>

2025-01-11 21:01 UTC, jeongseok-meta commented
Hi @carterbox, thank you so much for taking the time to review!

I'm also not super familiar with how the boost conda package is built, but this approach works for my case. Including boost, could we possibly address the export warnings after the feedstock repo is created for faster iterations, including OSX tests? If this is okay with you, I'd greatly appreciate it. To be honest, the export warnings are a bit fuzzy to me and take too much time to iterate.

2025-01-11 21:02 UTC, jeongseok-meta commented on recipes/AdaptiveCpp/meta.yaml
> +    - "%PREFIX%\\Library\\bin\\acpp-info.exe"  # [win]
Good to know, thanks!

2025-01-11 21:04 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/AdaptiveCpp/meta.yaml```) and found it was in an excellent condition.

2025-01-11 21:21 UTC, jeongseok-meta commented
@conda-forge/help-c-cpp, ready for review!

2025-01-13 18:50 UTC, merged