Adding faster-coco-eval
conda-forge/staged-recipes pull request #28684
Opened 2024-12-23 13:11 UTC by MiXaiLL76

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-12-23 13:13 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/faster-coco-eval/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/faster-coco-eval/meta.yaml**:

 * ❌ This recipe is using a compiler, which now requires adding a build dependence on `{{ stdlib("c") }}` as well. Note that this rule applies to each output of the recipe using a compiler. For further details, please see https://github.com/conda-forge/conda-forge.github.io/issues/2102.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12467379037](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12467379037). Examine the logs at this URL for more detail.</sub>

2024-12-23 13:45 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/faster-coco-eval/meta.yaml```) and found it was in an excellent condition.

2025-01-10 09:58 UTC, MiXaiLL76 commented
@conda-forge-admin, please ping conda-forge/help-python-c

2025-01-11 13:22 UTC, xhochy requested changes

2025-01-11 13:22 UTC, xhochy commented on recipes/faster-coco-eval/meta.yaml
> +    - oldest-supported-numpy  # [py<39]
```suggestion
    - numpy
```

2025-01-11 13:22 UTC, xhochy commented on recipes/faster-coco-eval/meta.yaml
> +    - {{ pin_compatible('numpy') }}
```suggestion
```

2025-01-23 10:19 UTC, xhochy approved these changes

2025-01-23 10:19 UTC, merged