Adding package recipe for `Chartlets`
conda-forge/staged-recipes pull request #28713
Opened 2024-12-27 15:27 UTC by b-yogesh

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [x] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-12-27 15:29 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/chartlets/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/chartlets/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `run` section of the recipe, you should usually use `python >={{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12517793027](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12517793027). Examine the logs at this URL for more detail.</sub>

2024-12-27 15:32 UTC, forman requested changes

2024-12-27 15:32 UTC, forman commented on recipes/chartlets/meta.yaml
> +    - chartlets.py/LICENSE
Not needed.

2024-12-27 15:32 UTC, forman commented on recipes/chartlets/meta.yaml
> +    - altair
`altair` is not required.
Please check `environment.yml`, only include required packages.

2024-12-27 15:34 UTC, forman commented
I confirm that I am willing to be listed as a maintainer for this recipe.

2024-12-27 15:34 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/chartlets/meta.yaml```) and found it was in an excellent condition.

2024-12-30 09:38 UTC, b-yogesh commented
Hi @conda-forge/help-python,

This recipe has passed all checks and linting. Is there anything else I need to do to proceed? 
Thank you for your help!

2025-01-03 13:22 UTC, ocefpaf commented on recipes/chartlets/meta.yaml
> +    - chartlets.py/LICENSE
Why? Are those the same? Or is that the license from a vendored Software? Can you please clarify?

2025-01-03 15:33 UTC, b-yogesh commented on recipes/chartlets/meta.yaml
> +    - chartlets.py/LICENSE
Thank you for your reply @ocefpaf 
Both are the same MIT licenses. The reason we have two is because we have a mono-repo containing two packages with their own MIT licenses.
Regarding the comment above, we have only removed the `license_family` tag.

Please let us know if there are any changes to be made.

2025-01-07 09:15 UTC, merged