Adding chafa package
conda-forge/staged-recipes pull request #28721
Opened 2024-12-29 12:52 UTC by peterjc

Extracted from stage-recipes pull request #26240 by @pavelzw which combined this with a recipe for fastfetch (see discussion there). If this looks good we can bump from v1.40.0 to the current v1.40.5 before/after merging.

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-12-29 12:53 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/chafa/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/chafa/meta.yaml**:

 * ❌ This recipe is using a compiler, which now requires adding a build dependence on `{{ stdlib("c") }}` as well. Note that this rule applies to each output of the recipe using a compiler. For further details, please see https://github.com/conda-forge/conda-forge.github.io/issues/2102.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12535557447](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12535557447). Examine the logs at this URL for more detail.</sub>

2024-12-29 12:58 UTC, pavelzw commented on recipes/chafa/meta.yaml
> +    # - {{ stdlib('c') }}
```suggestion
    - {{ stdlib('c') }}
```

2024-12-29 14:25 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/chafa/meta.yaml```) and found it was in an excellent condition.

2024-12-29 15:05 UTC, peterjc commented
Linux 64 failed:

```
configure: WARNING: unrecognized options: --disable-debug
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports the include directive... yes (GNU style)
checking for x86_64-conda-linux-gnu-gcc... $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc accepts -g... yes
checking for $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc option to enable C11 features... none needed
checking whether $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc understands -c and -o together... yes
checking dependency style of $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc... none
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for wchar.h... yes
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether _XOPEN_SOURCE should be defined... no
checking whether build environment is sane... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for an ANSI C-conforming const... yes
checking for x86_64-conda-linux-gnu-gcc... (cached) $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc
checking whether the compiler supports GNU C... (cached) yes
checking whether $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc accepts -g... (cached) yes
checking for $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc option to enable C11 features... (cached) none needed
checking whether $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc understands -c and -o together... (cached) yes
checking dependency style of $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc... (cached) none
checking how to run the C preprocessor... $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cpp
checking for x86_64-conda-linux-gnu-ar... $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ar
checking the archiver ($BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ar) interface... ar
checking build system type... x86_64-conda-linux-gnu
checking host system type... x86_64-conda-linux-gnu
checking how to print strings... printf
checking pkg-config is at least version 0.9.0... yes
checking for GLIB... yes
checking for FREETYPE... no
configure: error: You need freetype2-devel (or libfreetype6-dev on Debian) to build command-line tools, or pass --without-tools to build without.
```

The windows failure is simpler - there is no batch file so probably we need to skip Windows initially?

```
WARNING: No files or script found for output chafa
number of files: 0
```

2025-01-22 18:52 UTC, hpjansson commented
Hi, Chafa's `configure.ac` does this:

`PKG_CHECK_MODULES(FREETYPE, [freetype2 >= 2.0.0],,` (...)

It looks for `freetype2.pc` in the pkg-config search path. It won't build without. You need to have the development release of FreeType installed - it provides the `.pc` file. You can verify it on the command line by running `pkg-config --path freetype2`.

FreeType is pretty low in the stack, so maybe conda-forge already has it. I did a search and found [commits](1e33dd163d76e7f18a337985ec195c55b462732e), but GH claims the file can't be viewed. Not sure why.

If FreeType can't be provided, I may be able to turn it into an optional dependency, but it's kind of a last resort, since your build would then be missing functionality that's available in the Chafa CLI elsewhere.

Let me know if there's more I can do to help. Thanks for packaging Chafa!

2025-01-22 21:32 UTC, peterjc commented
A quirk of how conda-forge works means this repository https://github.com/conda-forge/staged-recipes/ only contains new potential packages - once accepted they each get their own repository.

I believe we'd using conda-forge's ``freetype`` package https://github.com/conda-forge/freetype-feedstock (and possibly the ``freetype-py`` package https://github.com/conda-forge/freetype-py-feedstock too?).

That's already listed as a host and run requirement though... but we can look for the ``freetype2.pc`` file next, thanks!

2025-01-22 22:39 UTC, hpjansson commented
Ok, sounds good. Chafa only needs the C library, so you should be fine with just `freetype`.

2025-01-22 23:34 UTC, peterjc commented
I wonder if this is breaking due to https://github.com/conda-forge/freetype-feedstock/issues/57 ? There's an open pull request which looks to fix that but as part of much more ambitious work...

2025-01-22 23:53 UTC, hpjansson commented
Chafa doesn't use `freetype-config`, though -- it uses the first `pkg-config` it can find in your path. I don't know why the wrong one is being found (should be the same as `which pkg-config` would find). Maybe you can work around it by doing one of the following before running `configure`:

* Ensuring `PATH` is set so the `bin` dir containing the correct instance of `pkg-config` is searched first.
* Setting the `PKG_CONFIG` env var to the path of Conda's `pkg-config`.

or

* Setting the `PKG_CONFIG_PATH` env var to the path where Conda's `freetype2.pc` file can be found.

`./configure --help` lists these and other env vars and options that can affect the build.

2025-01-23 00:08 UTC, hpjansson commented
Hmm, actually it may be finding the right `pkg-config` after all. Looking at the pipeline, it says:

`checking for x86_64-conda-linux-gnu-pkg-config... $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-pkg-config`

Maybe `config.log` will have more details, if you can extract it after the failed configure run.

2025-02-27 00:55 UTC, eunos-1128 commented
Is there any progress?

2025-02-27 09:53 UTC, peterjc commented
The last attempt was a month ago so the CI logs have gone. I'll rebase this now so you can take a look at the failure @eunos-1128 and hopefully you can spot something I missed.

2025-02-27 09:55 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/chafa/meta.yaml```) and found it was in an excellent condition.

2025-02-27 10:22 UTC, peterjc commented
I think the key part of the failing log is:

```
...
checking pkg-config is at least version 0.9.0... yes
checking for GLIB... yes
checking for FREETYPE... no
configure: error: You need freetype2-devel (or libfreetype6-dev on Debian) to build command-line tools, or pass --without-tools to build without.
```

i.e. The same as quoted earlier. We have declared a dependency on ``freetype2`` which I think means either the build script needs more help to find the header files, or that package isn't exporting all the headers chafa needs.

Quoting @hpjansson from earlier, one of his suggestions was doing this before ``./configure`` is run:

> Setting the `PKG_CONFIG_PATH` env var to the path where Conda's `freetype2.pc` file can be found.

I don't know where `freetype2.pc` should be with conda-forge...

2025-02-27 10:31 UTC, eunos-1128 commented
@peterjc 

How about adding the [freetype](https://anaconda.org/anaconda/freetype) package from conda-forge to the build section?

2025-02-27 14:39 UTC, hpjansson commented
Looks like it's finding GLib, which is also done by `pkg-config` invocation. So both `pkg-config` and the `glib-2.0.pc` file are being found. `freetype2.pc` should be in the same directory as `glib-2.0.pc` (typically `/usr/lib64/pkgconfig/` on vanilla Linux).

It's interesting that this seems to only affect the linux_64 build. Are there other packages that use `freetype2.pc`?

2025-02-27 16:05 UTC, eunos-1128 commented
@peterjc 

I've submitted a PR below in which `PKG_CONFIG_PATH` is fixed and zlib and some other packaged are added.

It seems zlib is required on build. Even if `PKG_CONFIG_PATH` is fixed, it fails without zlib.

https://github.com/peterjc/staged-recipes/pull/2

2025-02-27 17:24 UTC, eunos-1128 commented
@hpjansson 

> Looks like it's finding GLib, which is also done by pkg-config invocation. So both pkg-config and the glib-2.0.pc file are being found. freetype2.pc should be in the same directory as glib-2.0.pc (typically /usr/lib64/pkgconfig/ on vanilla Linux).
>
> It's interesting that this seems to only affect the linux_64 build. Are there other packages that use freetype2.pc?

macOS has the zlib library built into the system, so zlib is usually available “by default”, but minimal Linux installations and build environments (e.g. containers) may not include development headers (zlib-devel or libz-dev) The following is an example of a case where the development header (zlib-devel or libz-dev) is not included

I believe that is the cause of the error.

2025-02-27 17:35 UTC, hpjansson commented
> @hpjansson
> 
> macOS has the zlib library built into the system, so zlib is usually available “by default”, but minimal Linux installations and build environments (e.g. containers) may not include development headers (zlib-devel or libz-dev).
> 
> I believe that is the cause of the error.

I see. Chafa doesn't have a direct dependency on zlib, but some of our dependencies do. I think it's their responsibility to indicate the correct link flags in .pc files. I took a look at the `freetype2.pc` files in conda-forge, and it looks like the main difference between the osx and linux ones is that while the osx one has this:

```
Requires.private:
Libs.private: -lpng16 -lz
```

the linux one has this:

```
Requires.private: zlib, libpng
Libs.private: 
```

2025-02-27 17:51 UTC, eunos-1128 commented
@hpjansson 

I found that [Homebrew's chafa formula](https://github.com/Homebrew/homebrew-core/blob/f5e8c5cd0b52d6e1f49a3f215acd894bf048d0c0/Formula/c/chafa.rb) have some packages missing in this PR, so added them as dependencies.

What do you think about them?

```ruby
  depends_on "pkgconf" => :build
  depends_on "cairo"
  depends_on "freetype"
  depends_on "glib"
  depends_on "jpeg-turbo"
  depends_on "jpeg-xl"
  depends_on "libavif"
  depends_on "librsvg"
  depends_on "libtiff"
  depends_on "webp"

  on_macos do
    depends_on "gdk-pixbuf"
    depends_on "gettext"
  end
```

2025-02-27 18:37 UTC, hpjansson commented
Cairo, GDK-Pixbuf and gettext are superfluous. We don't use any of them directly - the former two are dependencies of librsvg, and gettext gets pulled in by GLib. Apart from that, the list looks good :+1:

2025-02-28 10:27 UTC, eunos-1128 commented
@peterjc 

Now ready for review?

2025-02-28 10:48 UTC, pavelzw commented on recipes/chafa/meta.yaml
> +    - pavelzw
@eunos-1128 @peterjc would you like to be maintainers as well for this package?

2025-02-28 11:17 UTC, peterjc commented on recipes/chafa/meta.yaml
> +    - pavelzw
I'm willing, but a bit out of my comfort zone here (Python packaging is safer ground).

2025-02-28 11:30 UTC, eunos-1128 commented on recipes/chafa/meta.yaml
> +    - pavelzw
I'm fine either way:)

2025-03-05 10:48 UTC, xhochy requested changes

2025-03-05 10:48 UTC, xhochy commented on recipes/chafa/build.sh
> +export PKG_CONFIG_PATH="${BUILD_PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH:-}"
Why is this needed? You should not be pulling anything from $BUILD_PREFIX here.

2025-03-05 10:48 UTC, xhochy commented on recipes/chafa/meta.yaml
> +    - gettext  # [osx]
```suggestion
    - libintl-devel  # [osx]
```

2025-03-05 10:48 UTC, xhochy commented on recipes/chafa/meta.yaml
> +    - gettext  # [osx]
These should probably all be pulled in by their respective `run_exports`
```suggestion
```

2025-03-05 10:57 UTC, peterjc commented on recipes/chafa/build.sh
> +export PKG_CONFIG_PATH="${BUILD_PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH:-}"
@eunos-1128 you added this line - were you seeing issues with pkgconfig?

2025-03-06 15:53 UTC, eunos-1128 commented on recipes/chafa/build.sh
> +export PKG_CONFIG_PATH="${BUILD_PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH:-}"
@peterjc 

I added the line according to https://github.com/conda-forge/staged-recipes/pull/28721#issuecomment-2608503329

> Setting the PKG_CONFIG_PATH env var to the path where Conda's freetype2.pc file can be found.

As I tried conda-build again without the line, however, I found it not required.

Please delete the line.

2025-03-06 19:32 UTC, peterjc commented
@xhochy I think this addressed your requests, thank you.

2025-03-07 18:39 UTC, xhochy approved these changes

2025-03-07 18:39 UTC, merged