Add py-trees recipe
conda-forge/staged-recipes pull request #28727
Opened 2024-12-30 21:24 UTC by naveedhd

Checklist
- [ ] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [ ] Source is from official source.
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [ ] Build number is 0.
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-12-30 21:26 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/py-trees/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipes/py-trees/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - For the `run` section of the recipe, you should usually use `python >={{ python_min }}` for the `python` entry.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12552099061](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12552099061). Examine the logs at this URL for more detail.</sub>

2024-12-30 21:27 UTC, naveedhd commented
@conda-forge/help-python

2024-12-30 21:38 UTC, naveedhd commented
@conda-forge-admin, please add noarch: python

2025-01-06 19:19 UTC, synapticarbors requested changes

2025-01-06 19:19 UTC, synapticarbors commented on recipes/py-trees/meta.yaml
> +    - python >={{ python_min }},<{{ python_max }}
```suggestion
    - python {{ python_min }}
```

`host` should only pin against the min python version

2025-01-06 19:19 UTC, synapticarbors commented on recipes/py-trees/meta.yaml
> +    - pip
`requires` should include `python {{ python_min }}`

2025-01-06 20:37 UTC, naveedhd commented on recipes/py-trees/meta.yaml
> +    - pip
added.

2025-01-06 20:38 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/py-trees/meta.yaml```) and found it was in an excellent condition.

2025-04-21 04:52 UTC, shermansiu commented on recipes/py-trees/meta.yaml
> +{% set python_min = "3.8" %}
Why are we manually setting python_min and python_max? They should be set by default.

2025-04-21 04:52 UTC, shermansiu commented on recipes/py-trees/meta.yaml
> +{% set python_min = "3.8" %}
Python 3.8 is already EOL.

2025-11-14 08:21 UTC, traversaro commented
See @shermansiu feedback.

2025-11-24 20:01 UTC, naveedhd commented on recipes/py-trees/meta.yaml
> +{% set python_min = "3.8" %}
removed these. Please check.

2025-11-24 20:01 UTC, naveedhd commented
> See @shermansiu feedback.

I have address @shermansiu feedback. Please take a look.

2025-11-27 08:48 UTC, shermansiu requested changes

2025-11-27 08:48 UTC, shermansiu commented on recipes/py-trees/meta.yaml
> +    - python >={{ python_min }},<{{ python_max }}
```suggestion
    - python >={{ python_min }}
```
`python_max` is undefined - just follow the linter's suggestions

2025-11-27 20:31 UTC, shermansiu commented on recipes/py-trees/meta.yaml
> +    - python >={{ python_min }},<{{ python_max }}
@naveedhd

2025-11-27 20:40 UTC, naveedhd commented on recipes/py-trees/meta.yaml
> +    - python >={{ python_min }},<{{ python_max }}
thanks @shermansiu. Removed.

2025-11-28 03:58 UTC, shermansiu requested changes

2025-11-28 03:58 UTC, shermansiu commented on recipes/py-trees/meta.yaml
> +  sha256: 8a2024ca6cb966c3c571d91e2d60c90cc562c4d237a0af8ab7a7c27c2cff0795
```suggestion
  sha256: cd8738a80e7422aec2b133270b6aa92e3e83926ded2ba9b3614028dba99cdb41
```
Update the SHA256 hash when bumping the version @naveedhd

2025-12-01 02:38 UTC, shermansiu approved these changes
LGTM!

2025-12-01 02:39 UTC, shermansiu commented
@conda-forge/help-python Ready for review!

2025-12-05 07:29 UTC, shermansiu requested changes

2025-12-05 07:29 UTC, shermansiu commented on recipes/py-trees/meta.yaml
> +  summary: pythonic implementation of behaviour trees
```suggestion
  summary: Python implementation of behaviour trees
```
@naveedhd Minor nitpick for a discrepancy between the official repo description and the one here.

2025-12-05 07:31 UTC, shermansiu commented on recipes/py-trees/meta.yaml
> +  summary: pythonic implementation of behaviour trees
"Python implementation" means that the implementation is written in Python. "Pythonic" means that the implementation's code adheres to the Python coding style that is commonly accepted by the community. They have different meanings.

2026-07-09 22:58 UTC, sea-bass commented
@naveedhd -- I'm currently maintaining PyTrees and we're gearing up for a next release that removes the poetry dependency, plus I'd like to use the new recipe format if that's okay.

Happy to have you finish up this PR after you implement the minor comment, if you'd be willing to add me to the list of maintainers in the feedback. Alternatively, we can replace it with a PR of my own once we do the new release, and I would likewise keep you as a conda maintainer if you're interested?

2026-07-10 13:54 UTC, naveedhd commented
> @naveedhd -- I'm currently maintaining PyTrees and we're gearing up for a next release that removes the poetry dependency, plus I'd like to use the new recipe format if that's okay.

@sea-bass thanks for maintaining py-trees and taking this up. I was unfortunately not able to follow this up.

> Alternatively, we can replace it with a PR of my own once we do the new release, and I would likewise keep you as a conda maintainer if you're interested?

That would be great as I have lost the context mostly. I will close this PR and let you make a release if needed.

2026-07-10 13:54 UTC, closed without merging