Add YAPSS to conda-forge
conda-forge/staged-recipes pull request #28720
Opened 2024-12-29 04:33 UTC by stevenrhall

Checklist
- [x] Title of this PR is meaningful: e.g. "Adding my_nifty_package", not "updated meta.yaml".
- [x] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/5eddbd7fc9d1502169089da06c3688d9759be978/recipes/example/meta.yaml#L64-L73) for an example).
- [x] Source is from official source.
- [x] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).
- [x] If static libraries are linked in, the license of the static library is packaged.
- [x] Package does not ship static libraries. If static libraries are needed, [follow CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).
- [x] Build number is 0.
- [x] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details).
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.
- [ ] When in trouble, please check our [knowledge base documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html) before pinging a team.

2024-12-29 04:36 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipes/yapss/meta.yaml```) and found some lint.

Here's what I've got...


For **recipes/yapss/meta.yaml**:

 * ❌ The home item is expected in the about section.
 * ❌ The license item is expected in the about section.
 * ❌ The summary item is expected in the about section.
 * ❌ There are too few lines.  There should be one empty line at the end of the file.
 * ❌ ``requirements: host: python>=3.9,<3.14`` must contain a space between the name and the pin, i.e. ``python >=3.9,<3.14``
 * ❌ ``requirements: run: python>=3.9,<3.14`` must contain a space between the name and the pin, i.e. ``python >=3.9,<3.14``
 * ❌ ``requirements: run: casadi>=3.6.0`` must contain a space between the name and the pin, i.e. ``casadi >=3.6.0``

For **recipes/yapss/meta.yaml**:

 * ℹ️ Recipes should usually depend on `matplotlib-base` as opposed to `matplotlib` so that runtime environments do not require large packages like `qt`.
 * ℹ️ PyPI default URL is now pypi.org, and not pypi.io. You may want to update the default source url.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12532502136](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12532502136). Examine the logs at this URL for more detail.</sub>

2024-12-29 04:47 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/yapss/meta.yaml```) and found it was in an excellent condition.

2024-12-29 05:43 UTC, stevenrhall commented
@conda-forge/help-python ready for review. I'm willing to be a maintainer.

2025-01-07 14:18 UTC, stevenrhall commented
@conda-forge-admin, please ping team

2025-01-08 14:40 UTC, stevenrhall commented
@conda-forge/help-python, ready for review.

2025-01-11 13:33 UTC, xhochy requested changes
Please squash the commits and force-push. Otherwise this will bloat the git repository.

2025-01-11 13:33 UTC, xhochy commented on recipes/yapss/meta.yaml
> +{% set sha256 = "ef084862f31dddd2c16e53ff60014768a64fb9e7266d75af5477dd3f1f44e405" %}
Don't use this indirection
```suggestion
```

2025-01-11 13:33 UTC, xhochy commented on recipes/yapss/meta.yaml
> +    - python >=3.9,<3.14
Please have a look at the linter
```suggestion
    - python {{ python_min }}
```

2025-01-11 13:33 UTC, xhochy commented on recipes/yapss/meta.yaml
> +        - black[jupyter] >=24.0.0,<25.0.0
Brackets have no effect in conda 
```suggestion
        - black >=24.0.0,<25.0.0
```

2025-01-11 21:41 UTC, stevenrhall commented on recipes/yapss/meta.yaml
> +    - python >=3.9,<3.14
Done, on all instances.

2025-01-11 21:41 UTC, stevenrhall commented on recipes/yapss/meta.yaml
> +        - black[jupyter] >=24.0.0,<25.0.0
Done. I added the [jupyter] dependencies separately.

2025-01-11 21:42 UTC, stevenrhall commented on recipes/yapss/meta.yaml
> +{% set sha256 = "ef084862f31dddd2c16e53ff60014768a64fb9e7266d75af5477dd3f1f44e405" %}
Done.

2025-01-20 13:19 UTC, xhochy requested changes

2025-01-20 13:19 UTC, xhochy commented on recipes/yapss/meta.yaml
> +    - python {{ python_min }}
```suggestion
    - python >={{ python_min }}
```

2025-01-20 13:19 UTC, xhochy commented on recipes/yapss/meta.yaml
> +        - python {{ python_min }}
```suggestion
        - python >={{ python_min }}
```

2025-01-20 13:19 UTC, xhochy commented on recipes/yapss/meta.yaml
> +        - pytest
```suggestion
        - pytest
        - python {{ python_min }}
```

2025-01-20 13:19 UTC, xhochy commented on recipes/yapss/meta.yaml
> +        - cyipopt
```suggestion
        - python >={{ python_min }}
        - {{ pin_subpackage('yapss', exact=True) }}
```

2025-01-20 13:19 UTC, xhochy commented on recipes/yapss/meta.yaml
> +      requires:
```suggestion
      requires:
        - python {{ python_min }}
```

2025-01-20 14:05 UTC, stevenrhall commented on recipes/yapss/meta.yaml
> +      requires:
Done.

2025-01-20 14:08 UTC, stevenrhall commented on recipes/yapss/meta.yaml
> +        - cyipopt
This is not quite right I think? Your suggestion has two separate python dependencies. I've change it to this:

```
        # yapss dependencies
        - python >={{ python_min }}
        - {{ pin_subpackage('yapss', exact=True) }}
        - numpy
        - casadi >=3.6.0
        - scipy
        - mpmath
        - matplotlib-base
        - cyipopt
```

2025-01-20 14:08 UTC, stevenrhall commented on recipes/yapss/meta.yaml
> +        - pytest
Done.

2025-01-20 14:10 UTC, stevenrhall commented on recipes/yapss/meta.yaml
> +    - python {{ python_min }}
Done.

2025-01-23 09:36 UTC, xhochy commented on recipes/yapss/meta.yaml
> +        - cyipopt
> Your suggestion has two separate python dependencies. 

But they are the same, right? We want python listed explicitly as it changes a bit in the handling of the dependencies of conda-build.

2025-01-23 15:10 UTC, stevenrhall commented on recipes/yapss/meta.yaml
> +        - cyipopt
Sorry, I misread the diff, and you're right of course. I've now corrected.

2025-01-23 15:10 UTC, stevenrhall commented
Thanks for you help @xhochy. Should be ready now.

2025-01-23 15:24 UTC, xhochy approved these changes

2025-01-23 15:24 UTC, merged